- package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk
- package/batocera/emulators/wine/wine-lutris/wine-lutris.mk
- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
> Fix Build for Wine

- package/batocera/core/batocera-configgen/configgen/configgen/settings/batoceraSettings.py
> Delete batoceraSettings.py (master)

- board/batocera/fsoverlay/etc/init.d/S26system
- package/batocera/core/batocera-system/batocera.conf
- package/batocera/utils/rpigpioswitch/Config.in
- package/batocera/utils/rpigpioswitch/S72gpioinput
- package/batocera/utils/rpigpioswitch/S92switch
- package/batocera/utils/rpigpioswitch/rpi-gpio-init.py
- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
- package/batocera/utils/rpigpioswitch/rpigpioswitch.mk
Moved all GPIO to RPi family now
Modernized S26system statement and removed rb_ residues
Removed WittyPi (WiringPi is not available anymore)
> GPIO rework to init.d

- board/batocera/scripts/post-image-script.sh
- board/batocera/x86/create-boot-script.sh
- board/batocera/x86/genimage-boot.cfg
- board/batocera/x86/genimage.cfg
> fix x86* boot

- package/batocera/alllinuxfirmwares/alllinuxfirmwares.mk
> remove some unused firmwares

- board/batocera/scripts/post-image-script.sh
- board/batocera/x86/genimage-boot.cfg
> x86 to 3.5G

- package/batocera/core/batocera-system/Config.in
> Add XFS support

- package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.hash
- package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.mk
> bump vkd3d-proton

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
add rumble, mouse ir and motion control support for Dualshock controllers in dolphin
tested with 2 DS4 controllers
> motion control,  rumble and mouse ir support for dualshock in dolphin

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> keep yml order in xml

- board/batocera/odroidxu4/create-boot-script.sh
- board/batocera/odroidxu4/genimage.cfg
- board/batocera/scripts/post-image-script.sh
- package/batocera/boot/uboot-odroid-xu4/uboot-odroid-xu4.mk
> fix xu4 boot

- board/batocera/raspberrypi/rpi/create-boot-script.sh
- board/batocera/raspberrypi/rpi3/create-boot-script.sh
- board/batocera/raspberrypi/rpi4/create-boot-script.sh
> fix rpi boot

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> cfeatures descriptions

- package/batocera/core/batocera-scripts/batocera-scripts.mk
- package/batocera/core/batocera-scripts/scripts/batocera-screenshot.drm
- package/batocera/core/batocera-scripts/scripts/batocera-screenshot.tvservice
- package/batocera/core/batocera-scripts/scripts/batocera-screenshot.xorg
> batocera-screenshot

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
not fan of how it is complex now in the code... next complexity i should rewrite with sub functions
> cfeatures: systems in cores

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
have test on lr/flycast no issue :D
> Add m3u on Flycast

- package/batocera/core/batocera-scripts/scripts/batocera-systems
> Update PS3 firmware

- board/batocera/raspberrypi/rpi4/create-boot-script.sh
- package/batocera/core/batocera-scripts/scripts/batocera-upgrade
> rpi4 64 bit switch

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> fix missing videomode when no cfeatures

- package/batocera/core/batocera-splash/S29splashscreencontrol
Attempt to migrate to dash
Need to check on Pi platform
> dash: Migrate S29splashscreencontrol

- package/batocera/core/batocera-system/Config.in
> disable not compiling RTL8821AU on x86

- board/batocera/rockchip/patches/mupen64plus-video-rice/updates-wip.patch
> fix rockchip mupen patch

- package/batocera/emulators/mame/mame.mk
> fix mame py dep

- package/batocera/core/batocera-scripts/scripts/batocera-store
Works like the theme and upgrade downloaders now
User keeps informed about size and progress
@lbrpdx Your turn now ;)
Output is kinda 
```
[15.07MiB] - Quake >>>10
[15.07MiB] - Quake >>>17
[15.07MiB] - Quake >>>27
[15.07MiB] - Quake >>>37
[15.07MiB] - Quake >>>44
[15.07MiB] - Quake >>>55
[15.07MiB] - Quake >>>64
[15.07MiB] - Quake >>>74
[15.07MiB] - Quake >>>82
[15.07MiB] - Quake >>>92
27.50MiB to extract.... >>>70
warning: ports-quake-shareware-1.0.0-4 is up to date -- reinstalling
27.50MiB to extract.... >>>70
Quake Installed ... >>>100
```
> update: batocera-store - Download badge in ES

- board/batocera/fsoverlay/etc/init.d/S10wifi
- board/batocera/fsoverlay/etc/init.d/S11share
- board/batocera/fsoverlay/etc/init.d/S26system
- board/batocera/fsoverlay/etc/init.d/S31sixad
- board/batocera/fsoverlay/etc/init.d/S35securepasswd
- board/batocera/fsoverlay/etc/init.d/S50triggerhappy
- board/batocera/fsoverlay/etc/init.d/S61cec
- board/batocera/fsoverlay/etc/init.d/S91smb
- board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc
- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-odroidga
- package/batocera/core/batocera-audio/alsa/batocera-audio-rockpro64
- package/batocera/core/batocera-audio/alsa/batocera-audio-vim3
- package/batocera/core/batocera-bluetooth/S32bluetooth.template
- package/batocera/core/batocera-scripts/scripts/batocera-config
- package/batocera/core/batocera-scripts/scripts/batocera-hybrid-nvidia
- package/batocera/core/batocera-scripts/scripts/batocera-install
- package/batocera/core/batocera-scripts/scripts/batocera-kodilauncher
- package/batocera/core/batocera-scripts/scripts/batocera-upgrade
- package/batocera/core/batocera-scripts/scripts/batocera-wifi
- package/batocera/core/batocera-splash/S29splashscreencontrol
- package/batocera/emulationstation/batocera-emulationstation/S31emulationstation
- package/batocera/utils/batocera-wine/batocera-wine
- package/batocera/utils/gpicase/batocera-gpicase-install
- package/batocera/utils/roshambo-case/S14roshambo
- package/batocera/utils/rpigpioswitch/S72gpioinput
- package/batocera/utils/rpigpioswitch/S92switch
- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
Migrates all callers to the new settings binaries.
> Migrate to the new batocera-settings-(get|set)

- package/batocera/core/batocera-splash/S03splash-image
- package/batocera/core/batocera-splash/batocera-splash.mk
> ogos: splash and es resolution

- board/batocera/rockchip/odroidgoa/patches/retroarch/001-fix-resolution.patch
> goa,ra: remove hard coded resolution

- board/batocera/rockchip/odroidgoa/patches/sdl2/board-SDL2-rotation.patch
> fix goa2 sdl2 rotation

- board/batocera/fsoverlay/etc/init.d/S65values4boot
Simplify the script using the new settings binaries
> S65values4boot: Use batocera-settings-(get|set)

- package/batocera/gpu/vulkan/glslang/glslang.mk
- package/batocera/gpu/vulkan/vulkan-headers/vulkan-headers.hash
- package/batocera/gpu/vulkan/vulkan-headers/vulkan-headers.mk
- package/batocera/gpu/vulkan/vulkan-loader/vulkan-loader.hash
- package/batocera/gpu/vulkan/vulkan-loader/vulkan-loader.mk
- package/batocera/gpu/vulkan/vulkan-tools/vulkan-tools.hash
- package/batocera/gpu/vulkan/vulkan-tools/vulkan-tools.mk
> Bump Vulkan + GLSLANG

- package/batocera/utils/batocera-wine/batocera-wine
not really a fixe but is better
> nano fixe :D

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml
> fix goa n64 resolution

- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation-joysticks-indexes.patch
> fix pad in es (done in sdl/retroarch/dolphin, but i forgot es)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> fix: disable bios at startup pcsx

- package/batocera/emulators/retroarch/libretro/libretro-retro8/001-sound_fix.patch
Tested on OGA and RPi4 (otherwise horrendous sound making it unusable)
> Fix sound on latest retro8

- package/batocera/core/batocera-scripts/batocera-scripts.mk
> Fix retroachievements script removal

- board/batocera/fsoverlay/etc/samba/smb.conf
> allow to connect to old nas

- board/batocera/x86/fsoverlay/usr/share/applications/defaults.list
- package/batocera/utils/l3afpad/l3afpad.mk
> fix l3afpad

- package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
Many controllers in es_input.cfg have the same ID for "hotkey" as for another button (usually "select").
This is not allowed by SDL2 and confuses games.
We generally want to prefer "select" ("back") over "hotkey" ("guide") for game mappings.
Detects and works around duplicate "hotkey" ID during SDL GameController config generation.
> Fix SDL2 controller with duplicate "hotkey" ID

- scripts/linux/runQemu.sh
> qemu: joysticks and usb disk

- batocera-Changelog
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/libretro/libretro-freechaf/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-freechaf/libretro-freechaf.mk
> Fairchild Channel-F emulator

- Config.in
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/redream/redreamGenerator.py
- package/batocera/core/batocera-configgen/configgen/setup.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/redream/Config.in
- package/batocera/emulators/redream/redream.hash
- package/batocera/emulators/redream/redream.mk
> add redream

- package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml
> fixe redream

- package/batocera/emulators/redream/redream.mk
> fix download link

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
Name already used in themes, and better overall consistency with the other systems.
> Renamed "channel-f" to "channelf"

- board/batocera/patches/solarus/001-dirs.patch
- board/batocera/patches/solarus/002-pad.patch
- board/batocera/patches/solarus/003-padnum.patch
- package/batocera/core/batocera-configgen/configgen/configgen/generators/solarus/solarusGenerator.py
> solarus configgen

- package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/redream/redreamGenerator.py
- package/batocera/emulators/redream/dreamcast.redream.keys
- package/batocera/emulators/redream/redream.mk
> redream configgen

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> link cemu to wine lutris

- package/batocera/core/batocera-configgen/configgen/configgen/generators/solarus/solarusGenerator.py
- package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> solarus: joystick choice

- package/batocera/core/batocera-configgen/configgen/configgen/generators/hatari/hatariGenerator.py
- package/batocera/emulators/hatari/001-path.patch
> fix hatari bios

- package/batocera/core/batocera-audio/alsa/batocera-audio
> fix audio script

- package/batocera/emulators/redream/redream.hash
- package/batocera/emulators/redream/redream.mk
for not break master need to update redream.
redream use fast update system.
> bump redream

- board/batocera/fsoverlay/etc/init.d/S65values4boot
- package/batocera/core/batocera-audio/S01audio
- package/batocera/core/batocera-scripts/scripts/batocera-save-overlay
This fix prevents batocera from corrupting files on the boot partition.
> fix: mount boot partition

- package/batocera/core/batocera-configgen/configgen/configgen/generators/easyrpg/easyrpgGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/easyrpg/easyrpg-player/001-screenshot.patch
- package/batocera/emulators/easyrpg/easyrpg-player/002-logs.patch
- package/batocera/emulators/easyrpg/easyrpg-player/003-padnumber.patch
- package/batocera/emulators/easyrpg/easyrpg-player/004-padbuttons.patch
- package/batocera/emulators/easyrpg/easyrpg-player/easyrpg-player.mk
- package/batocera/emulators/easyrpg/easyrpg-player/easyrpg.easyrpg.keys
> easyrpg-configgen

- package/batocera/core/batocera-scripts/scripts/batocera-systems
For fix this issue : https://discord.com/channels/357518249883205632/524321176068161554/798555719150075944
> Add GBA bios detection

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Options t make it working better and help users
> ES options for MelonDS

- package/batocera/core/batocera-scripts/scripts/batocera-install
- package/batocera/core/batocera-scripts/scripts/batocera-mount
- package/batocera/core/batocera-scripts/scripts/batocera-overclock
- package/batocera/core/batocera-scripts/scripts/batocera-padsinfo
- package/batocera/core/batocera-scripts/scripts/batocera-part
- package/batocera/core/batocera-scripts/scripts/batocera-screenshot.drm
- package/batocera/core/batocera-scripts/scripts/batocera-screenshot.tvservice
- package/batocera/core/batocera-scripts/scripts/batocera-screenshot.xorg
switch to dash
Review ? 
@tcamargo & @crcerror
> Swith to sh

- package/batocera/core/batocera-configgen/configgen/configgen/generators/easyrpg/easyrpgGenerator.py
- package/batocera/emulators/easyrpg/easyrpg-player/easyrpg.easyrpg.keys
> update easyrpg mapping

- board/batocera/scripts/doWineWow64-32package.sh
> fix lutris link

- package/batocera/emulators/easyrpg/easyrpg-player/easyrpg.easyrpg.keys
> easyrpg configgen addons

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> Fix a MelonDS ES option bug

- package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborGenerator.py
> fix openbor core choice

- board/batocera/scripts/doWineWow64-32package.sh
> Fix Missing Libs

- package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/emulators/openbor/openbor6330/002-fixkeys.patch
- package/batocera/emulators/openbor/openbor6412/002-fixkeys.patch
- package/batocera/emulators/openbor/openbor6510/002-fixkeys.patch
> fix openbor multi

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
- package/batocera/emulators/supermodel/001-folder-directory.patch
- package/batocera/emulators/supermodel/Supermodel.ini
- package/batocera/emulators/supermodel/supermodel.mk
Base controllers config off our template
> Fixed PR Sega Model 3 - copy NVRAM files to rw directory on /userdata.

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
- package/batocera/emulators/supermodel/001-folder-directory.patch
> fix supermodel nvram

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
- package/batocera/emulators/supermodel/001-folder-directory.patch
> nvram contains saved data, not really config as far as i understand

- package/batocera/emulators/supermodel/002-updatetemplate.patch
> supermodel template patching

- package/batocera/core/batocera-scripts/scripts/batocera-record
- package/batocera/core/batocera-scripts/scripts/batocera-screenshot.xorg
@nadenislamarre review
Now user have 3 : batocera-record -default -fast -compress
For make better video record.
But is running -default without args
> Improve Batocera-Record

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
> fix dolphin vulkan

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
++ inject state_slot value into retroarch
> Configgen : add support for -state_slot and -autosave command line arguments

- scripts/linux/buildstats.sh
> fix stat link

- board/batocera/raspberrypi/rpi3/boot/config.txt
- board/batocera/raspberrypi/rpi3/fsoverlay/etc/init.d/S03checkbootconfig
- board/batocera/raspberrypi/rpi4/boot/config.txt
- board/batocera/raspberrypi/rpi4/fsoverlay/etc/init.d/S03checkbootconfig
Sound is only coming through the headphone
> rpi-audio: vc4-kms-v3d

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
> fix super model axis

- Makefile
When you have both python2 and python3 on your build box.
> Tiny fix for make xxx-webserver

- Config.in
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/libretro/libretro-fmsx/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-fmsx/libretro-fmsx.mk
@rtissera review
Compilation OK on x86_64
Work on ARM too need patch
> Add lr-fmsx

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fix the Supermodel.log file
Add the option for enabling cross hairs per player
Add the option to enable force feedback for compatible controllers
> Log fix & more Sega Model3 options

- package/batocera/gpu/batocera-nvidia-driver/nvidia-driver.mk
> fix nvidia32 vulkan

- package/batocera/emulators/retroarch/libretro/libretro-bluemsx/libretro-bluemsx.mk
> fix bios msx

- package/batocera/gpu/mali-g31-gbm/Config.in
- package/batocera/gpu/mali-g31-gbm/mali-g31-gbm.mk
The new version provides a meson build and we automatically gain support for aarch64
> mali-g31-gbm: Bump version

- package/batocera/core/batocera-configgen/configgen/configgen/generators/lightspark/lightsparkGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ruffle/ruffleGenerator.py
> fix: remove unusefull generateSdlGameControllerConfig

- package/batocera/core/batocera-configgen/configgen/configgen/generators/wine/wineGenerator.py
- package/batocera/utils/batocera-wine/batocera-wine
> wine windows system agnostic (for mugen, cemu, ...)

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Test OGA 1.0 OK
Test OGA 1.1 OK
Test RK2020 OK
> add controller for OGA on new kernel

- package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulators/pcsx2/004-pads-order.patch
- package/batocera/emulators/pcsx2/ps2.pcsx2.keys
- package/batocera/emulators/pcsx2_avx2/004-pads-order.patch
> fix pcsx2 pads order

- package/batocera/core/batocera-scripts/scripts/batocera-systems
- Add the CDTV bios for PUAE CDTV. Works perfectly
- Modify NEOGEO bios file by adding UNIBIOS 4.0
- Modify NEOCD bios file by adding UNIBIOS 3.3
> BIOS Updates

- board/batocera/raspberrypi/rpi3/boot/config.txt
- board/batocera/raspberrypi/rpi3/fsoverlay/etc/init.d/S03checkbootconfig
- board/batocera/raspberrypi/rpi4/boot/config.txt
- board/batocera/raspberrypi/rpi4/fsoverlay/etc/init.d/S03checkbootconfig
Using fkms until the audio is corrected with the use of kms
> rpi: reversing the use of kms

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> Add OGS pad to new OGA aarch64 build

- package/batocera/emulators/retroarch/retroarch/014-cheevos-sounds.patch
> cheevos retroarch sound directory

- package/batocera/core/batocera-scripts/scripts/batocera-padsinfo
- package/batocera/utils/jstest2/005-infopath.patch
> infopads sdl id

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> tsugaru extensions

- batocera-Changelog
- package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject
Script update
New index file format (new name for compatibility)
New systems supported (libretro cores)
Take bezels by systems from TheBezelProjet Github
> theBezelProject update

- package/batocera/emulators/retroarch/libretro/libretro-mame/0003-arcade64-0228.patch
Same behiavor as it is in MAME standalone.
> lr-mame arcade64 patch (remove "useless" / "not working" stuff) 

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulators/pcsx2/006-multitap.patch
- package/batocera/emulators/pcsx2_avx2/006-multitap.patch
> pcsx2 multitap

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/batocera-report-system.py
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> fix es library system

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> don't force pcsx2 multitap, some games don't like it

- package/batocera/emulators/ruffle/ruffle.mk
> Bump Ruffle (v30)

- package/batocera/emulators/supermodel/002-updatetemplate.patch
> Fix patch for Start Wars Trilogy, simplified patch too

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/Generator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/lightspark/lightsparkGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ruffle/ruffleGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/wine/wineGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
- package/batocera/utils/batocera-wine/batocera-wine
> mouse for configgen

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
> fix supermodel3 when 1 axis only

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
> fix duckstation multiplayer

- package/batocera/utils/batocera-wine/batocera-wine
Help for compatibility on NTFS
Secure ESYNC option
Add Reg Option for import reg in games.
Add DXVK Async for more FPS / stability in games.
Tested before PR all is OK
> Fix and Options for Wine (v30)

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> chd for puae

- package/batocera/emulators/lightspark/lightspark.mk
> Bump LightSpark (v30)

- board/batocera/fsoverlay/etc/init.d/S11share
- package/batocera/core/batocera-system/Config.in
Improve speed of compression
Improve speed of FS with compression
Actually batocera use zlib compression is not very good.
Build x86_64 OK
Build RPI4 OK
> Compress with ZSTD (30)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Add 2 new Amiga CD32/TV options
Needed to make many games working better
> Add 3 new Amiga 500 1200 options

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mugen/mugenGenerator.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/utils/batocera-wine/batocera-wine.mk
- package/batocera/utils/batocera-wine/mugen.keys
> mugen initial configgen

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
> duckstation remove exit confirmation

- board/batocera/fsoverlay/etc/init.d/S08connman
- package/batocera/core/batocera-scripts/scripts/batocera-wifi
> wifi minor fixes

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- Add all important options in ES
- Fix .dos directories support for Pure
- Add zip support for pure and block it for others
> PURE DOSBOX settings

- package/batocera/emulationstation/batocera-es-system/es_features.yml
To prevent a bad error message in ES
Already validated with @f.caruso
> Add missed cheevros option to Virtuallboy in ES

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
We must use the same as other core, not the specific .pc and .dos directories command line.
> Multiple option updates + Bugfix

- board/batocera/raspberrypi/rpi4/boot/config.txt
provides more detailed option explanations too
> outline more video options available to Pi 4 users in config.txt

- package/batocera/emulators/drastic/drastic.hash
- package/batocera/emulators/drastic/drastic.mk
no merge now wait to finish build
OGA compilation OK
> better install

- package/batocera/core/batocera-splash/S03splash-mpv
- package/batocera/core/batocera-splash/batocera-splash.mk
> Fix splash playback on rockpro64

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
@nadenislamarre you can review ?
> Fix PS3 Issue (v31)

- board/batocera/x86/fsoverlay/etc/X11/xorg.conf.d/amdgpu.conf
- package/batocera/core/batocera-scripts/batocera-scripts.mk
> fix tearing on AMD Ryzen APU's

- batocera-Changelog
- board/batocera/amlogic/odroidn2/fsoverlay/etc/init.d/S02overclock
- board/batocera/raspberrypi/rpi/boot/config.txt
- board/batocera/raspberrypi/rpi3/boot/config.txt
- board/batocera/raspberrypi/rpi4/boot/config.txt
- package/batocera/core/batocera-scripts/scripts/batocera-overclock
> provide more overclocking options for the rpi4

- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml
> fix oga stretch on n64

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidn2.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- Add SNES player 3 for SLigtgun 2 player games
- Add NES player 2 for lightgun 2 player games and Arkanoid game
- Update Megadrive controllers for Lightgun
- Fix a Nestopia nospritelimit mistake
- Fix PSX CPU default to not crash the options
- Change the Amiga500 switch to use A600 for hard drive games
> Some libretro fix and controllers update

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
> check in case the yaml is empty (happened)

- package/batocera/emulators/xemu/xemu.hash
- package/batocera/emulators/xemu/xemu.mk
> clean qcow fil

- package/batocera/core/batocera-configgen/configgen/configgen/generators/devilutionx/devilutionxGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/devilutionx/devilutionx.hash
- package/batocera/emulators/devilutionx/devilutionx.mk
Bumps to a version with Hellfire support and adds support in the launcher.
Hellfire support is still in development but largely complete.
> DevilutionX Hellfire

- package/batocera/core/batocera-audio/S01audio
- package/batocera/core/batocera-audio/alsa/asoundrc-dmix+softvol
- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-odroidga
softvol is back, through "asym" alsa module
Addressing @glebm's comment
softvol
> Fix audio on OGA/RPi4/x86_64 (video thumbnails)

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
Add wiki links when they contain more info too
> Update arcade _info.txt which have been obsolete for a while

- package/batocera/core/batocera-scripts/scripts/batocera-info
> disk format

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> Xbox Option

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> add missing decoration feature in mame

- board/batocera/patches/sdl2/sdl2_disable_hidapi.patch
- board/batocera/patches/sdl2/sdl2_input_p003_extra_functions.patch
> disable hidapi and fix for sdl2

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
> fix some other python3

- batocera-Changelog
I think is more clear for users.
> More Clear changelog

- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/rendering-defaults.yml
> fixe spaces

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
> fix mame bezel

- package/batocera/emulators/xemu/xemu.hash
fix missing hash
and change md5 to sha256
> Fix Xemu Hash

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinSYSCONF.py
- package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py
- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
> fix some python 3 issues

- Dockerfile
This reverts commit 1a4922df60d5beaa45c71a2a0f41646731afa055.
> Revert "Merge pull request #3449 from liberodark/docker"

- package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/kodi/kodiConfig.py
> kodi to udev (partially working)

- board/batocera/patches/kodi/0010-remove-anoying-messages.patch
- board/batocera/patches/kodi/0011-guide-to-exit.patch
> remove some kodi messages

- package/batocera/core/batocera-configgen/configgen/configgen/generators/kodi/kodiConfig.py
> kodi back to linux old api driver

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py
> some more python3 fixes

- package/batocera/core/batocera-scripts/Config.in
- package/batocera/core/batocera-system/Config.in
> try to clean some py deps

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
Wait merge pr of rtissera before to merge
> Add CHD on PS2

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
DuckStation have adding PBP
PicoDrive have adding CHD > 1.98
> Add CHD/PBP Support in ES

- package/batocera/core/batocera-scripts/Config.in
> fix bluetooth agent deps

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> remove es_system path/extension/command if no extension

- board/batocera/fsoverlay/etc/usbmount/usbmount.conf
> fix btrfs mounts in /media

- package/batocera/utils/pacman/Config.in
- package/batocera/utils/pacman/batocera-pacman-batoexec
> fix batoexec with httplib2

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
Still some emulator issues on https://github.com/batocera-linux/batocera.linux/issues/3469 but at least we go past configgen
> Fix configgen Py3 for ppsspp and mupen64

- board/batocera/fsoverlay/etc/init.d/S04populate
> fix /var/tmp (flatpak)

- package/batocera/emulators/rpcs3/Config.in
- package/batocera/emulators/rpcs3/rpcs3.mk
> rpcs3 faudio dependency

- package/batocera/core/batocera-audio/alsa/asoundrc-dmix+softvol
> Fix stuttering / staturating sound on some PC configs

- package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
> fix python3 evmapy

- package/batocera/utils/batocera-wine/batocera-wine
Little clean up
Add MSI redist install fully silent ex case : in old games you can need to install nvidia physx.
Secure install for users (after install exe or import reg folder is moved in .bak)
> improve batocera-wine #2

- package/batocera/emulators/cemu/cemu/cemu.mk
> gameProfiles for cemu

- package/batocera/core/batocera-scripts/scripts/batocera-info
- package/batocera/core/batocera-scripts/scripts/batocera-part
> fix batocera-info partition

- Makefile
> makefile HOME and SHELL dir

- package/batocera/utils/rpigpioswitch/rpi-pin356-power.py
- package/batocera/utils/rpigpioswitch/rpi-pin56-power.py
- package/batocera/utils/rpigpioswitch/rpi-retroflag-AdvancedSafeShutdown.py
just some small changes in synthax
> fix: py3 fixes for power switches only

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-cemu
- package/batocera/emulators/cemu/cemu/cemu.mk
> Fix & Clean Cemu

- package/batocera/core/batocera-system/batocera-boot.conf
> batocera-boot.conf disable splash

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> Improve + Fixes Cemu

- package/batocera/emulators/mame/mame.mk
- package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
> mame, let my server breath please

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py
> fix ra notifications

- package/batocera/emulators/duckstation/006-drm-resolution.patch
> duckstation drm resolution

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
Now copy folder and file one by one + control file for not copy anytime
> Fix Green Screen Issue

- package/batocera/emulators/retroarch/retroarch/014-cheevos-sounds.patch
> fix retroarch cheevos patch

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
> fix es logs

- board/batocera/amlogic/odroidc4/genimage.cfg
- board/batocera/amlogic/s912/genimage.cfg
> fix amlogic boogs

- package/batocera/core/batocera-configgen/configgen/configgen/generators/easyrpg/easyrpgGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- Add Mupen64 MK2 options in ES
- Add Mupen64 RICE options in ES
- Update EasyRPG options
> N64 Standalone & EasyRPG Standalone Configs

- package/batocera/emulators/dolphin-emu/dolphin-emu.mk
> fix dolphin wiimotes : rollback to the previous version

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flatpak/flatpakGenerator.py
- package/batocera/utils/flatpak/batocera-flatpak-update
> flatpak under user batocera

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> flatpak in port group

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> VK for Cemu + Fix

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- Remove the old Gambatte "Colorization" option
Replace it by a new one in es_features
- Add a new GBC "Color Correction" option
- Upgrade the python
> ES Options Cleanup 1

- batocera-Changelog
- package/batocera/emulators/devilutionx/devilutionx.hash
- package/batocera/emulators/devilutionx/devilutionx.mk
https://github.com/diasurgical/devilutionX/releases/tag/1.2.1
> Bump DevilutionX (Diablo+Hellfire) to 1.2.1

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
> RetroAchievements for Duckstation (standalone)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> retroarch: don't force ozone

- package/batocera/core/batocera-configgen/configgen/configgen/generators/solarus/solarusGenerator.py
> fix solarus when it is a dir

- Makefile
make x86_64-source
https://buildroot.org/downloads/manual/manual.html#_offline_builds
> adding make source to makefile

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
> fix flycast inputs (py3)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Tested and working really fast on my Ryzen 3
Very impressive
Important for some games with big graphical glitch in OpenGL
Thanks @yomax69fly for the report
> Add PCSX2 Software Backend

- package/batocera/core/batocera-scripts/scripts/batocera-resolution.xorg
> max-widthxheight resolution mode for xorg

- package/batocera/core/batocera-configgen/configs/configgen-defaults-libretech-h5.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-miqi.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc2.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc4.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-pc.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-zero2.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3399.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rock960.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s812.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s905gen3.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s922x.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-tinkerboard.yml
> n64 maximum resolution for drm boards

- package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/citra/3ds.keys
- package/batocera/emulators/citra/citra.mk
- Add mouse support for tactile screen
- Options available from ES
- Auto use system language
- Add a key file for Mouse configuration and Hotkeys functions
> Final Citra Standalone configuration

- board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc
> fix es max resolution on xorg

- board/batocera/raspberrypi/rpi4/boot/config.txt
> update gpu_mem_1024 for rpi4

- board/batocera/rockchip/patches/ffmpeg/ffmpeg-99.1007-rkmppdec-enable-mpeg2.patch
> fix ffmpeg oga patch

- board/batocera/patches/libdrm/001-modeslist.patch
- package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm
> don't allow universal planes to get same ids in drm everywhere

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
> fix mupen64 resolution on drm

- package/batocera/emulators/amiberry/amiberry.mk
If i understand fine this PR i have miss this character for Line Return.
https://github.com/batocera-linux/batocera.linux/pull/3741/commits/2be946c03a70e6fe4d7ff9824916ee8a71235a40
> Amiberry a little fix

- package/batocera/utils/flatpak/batocera-flatpak-update
> flatpak permissions on binaries

- board/batocera/patches/sdl2/sdl2_fix_udev_device_get_subsystem_segfault.patch
> fix sdl2 pad crash

- board/batocera/amlogic/linux_patches/linux-battery-quircks.patch
- board/batocera/amlogic/linux_patches_5_8_18/linux-battery-quircks.patch
- board/batocera/libretech-h5/linux_patches/linux-battery-quircks.patch
- board/batocera/odroidxu4/linux_patches/linux-battery-quircks.patch
- board/batocera/orangepi-pc/linux_patches/linux-battery-quircks.patch
- board/batocera/orangepi-zero2/linux_patches/linux-battery-quircks.patch
- board/batocera/raspberrypi/rpi/linux_patches/linux-battery-quircks.patch
- board/batocera/raspberrypi/rpi3/linux_patches/linux-battery-quircks.patch
- board/batocera/raspberrypi/rpi4/linux_patches/linux-battery-quircks.patch
- board/batocera/rockchip/odroidgoa/linux_patches/linux-battery-quircks.patch
- board/batocera/rockchip/rk3288/miqi/linux_patches/linux-battery-quircks.patch
- board/batocera/rockchip/rk3399/linux_patches/linux-battery-quircks.patch
- board/batocera/s812/linux_patches/linux-battery-quircks.patch
- board/batocera/x86/linux_patches/linux-battery-quircks.patch
Sorry, this one will break some boards.
but i don't know by heart which one are in which kernel version.
Quite easy to fix (and ask me to fix if needed)
> 8bitdo battery quirks

- package/batocera/boot/uboot-odroid-goa/uboot-odroid-goa.mk
Should fix reboot when charging.
**I have removed kernel update from this PR** because it didn't boot. I will send a fixed PR for kernel upgrade separately.
> ogoa: update uboot (PR edited)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
> fix flycast hats

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/dolphin-emu/006-nicerlaunch.patch
> dolphin profiles + fix game list + force show toolbar + hide gamelist when launching a game

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Adding Custom textures for duckstation
See the wiki for further details
Have to be in saves\duckstation\textures\SLUS-00923 for exemple
> Duckstation - Custom texture

- package/batocera/emulators/ppsspp/006-sdl_window_fullscreen_drm.patch
> drm fullscreen doesn't like desktop fullscreen when changing resolution

- package/batocera/utils/evmapy/008-ready-flag.patch
- package/batocera/utils/evmapy/Config.in
- package/batocera/utils/evmapy/batocera-evmapy
> fix evmapy not yet started for duckstation

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
> fix dolphin internal resolution

- board/batocera/fsoverlay/usr/share/batocera/datainit/system/.kodi/userdata/advancedsettings.xml
> don't enable kodi web server by default anymore

- package/batocera/emulators/ruffle/ruffle.mk
That revert on old commit new commits make several compile errors.
> Fix Ruffle

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/Generator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/fpinball/fpinballGenerator.py
> fix fpinball libraries

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- Fix this issue : https://github.com/batocera-linux/batocera.linux/issues/3794
- Add controller type choice
> Vice64 controller fix

- batocera-Changelog
Add previous merged operation from myself
> Changelog - Previous Merged Operation

- package/batocera/core/batocera-scripts/scripts/batocera-config
> fix rpi4 upgrade check

- Config.in
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/libretro/libretro-watara/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-watara/libretro-watara.mk
Build x86_64 OK
Build RPI4 OK
Work OK
> Add Watara

- package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fix this bug
https://github.com/batocera-linux/batocera.linux/issues/3790
> Pcsx-Rearmed and Citre config fix

- package/batocera/emulators/duckstation/004-savestate-pathandnames.patch
> Duckstation - Fixing bad path for savestates

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/duckstation/psx.duckstation.keys
More Options to Duckstation :
Region Changing
Force 60hz timings
Preparing Quickmenu Hotkey for further next version of Duckstation
Edit Hotkey for QuickMenu
> Duckstation - Region/60Hz/QuickMenu

- package/batocera/emulators/ruffle/ruffle.mk
Build OK
Merge this pr https://github.com/batocera-linux/buildroot/pull/190 before merge
> Bump Ruffle (v32)

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> rename watara to supervision

- package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/cemu/cemu/wiiu.keys
- Remove cemu "vars" from batoceraFiles.py
- Updates the cemu "vars" with good Path
- Update the configs files with these new vars
- Remove the Wiimote option in ES and replace by Controller Combination
Better to play some games like New Super Mario Wii U where we must all use Pro Controller to have Shake option
- Add the Rumble option
> Cemu config update

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Adding Options in ES for Supervision
> Watara SuperVision Config

- package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
> fix evmapy r2 l2 as axis

- package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
> fix: evmapy with combo and axis

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- Add all good options for this core
> Odyssey 2 ES Options

- package/batocera/emulators/duckstation/007-maxbuttons.patch
- package/batocera/emulators/duckstation/psx.duckstation.keys
> fix duckstation 15 buttons pads

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix ra notification

- package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
> Duckstation Cheevros update

- package/batocera/emulators/moonlight-embedded/002-include-drm_fourcc.patch
> fix moonlight include error fourcc

- board/batocera/patches/kodi/0012-kodi-gbm-buffers.patch
> fix kodi out of memory

- package/batocera/core/batocera-configgen/configs/configgen-defaults-libretech-h5.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-miqi.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc2.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc4.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-pc.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-zero2.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3399.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rock960.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s812.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s905gen3.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s922x.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-tinkerboard.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
> clean configgen defaults

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cgenius/cgeniusGenerator.py
fix the binary name.
However, cgenius seems to be untested / unfinished at all ? should i revert for later ?!
> fix cgenius bin

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
- Use the Retroachievement name of the player if available
> Update PPSSPP Player name

- package/batocera/core/batocera-system/Config.in
> disable cgenius

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
This is a little fix for cemu.
- Fix incorrect Game Path
- Fix Missing MLC Path
> Fix Homedir

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
add posssibility to skip xbox boot animation on boot
> xemu-skipbootanim

- package/batocera/emulators/flycast/005-udev.patch
- package/batocera/emulators/flycast/flycast.mk
> fix flycast udev dep

- package/batocera/core/batocera-scripts/batocera-scripts.mk
- package/batocera/core/batocera-scripts/scripts/batocera-timezone
Watch out for the corresponding PR in ES.
> Timezone script (with auto detection)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-cemu
> Fix Cemu Path Storage

- package/batocera/core/batocera-audio/alsa/batocera-audio
Advanced to https://github.com/batocera-linux/batocera.linux/pull/3920
This script is better way better coded and can be extended more easily
> fix: ALSA audio fix for Pi family

- package/batocera/core/batocera-system/Config.in
> remove moonlight for miqi

- package/batocera/core/batocera-system/Config.in
> disable tsugaru on x86 (fails to compile)

- batocera-Changelog
- package/batocera/emulators/cemu/cemu/cemu.hash
- package/batocera/emulators/cemu/cemu/cemu.mk
Changelog: https://cemu.info/changelog/cemu_1_22_12.txt
> Bump Cemu to 1.22.12c

- package/batocera/core/batocera-system/Config.in
> [tools] added ncdu ( NCurses Disk Usage )

- package/batocera/core/batocera-configgen/configgen/configgen/generators/drastic/drasticGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/drastic/nds.drastic.keys
> Drastic Fix

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix ra framerate/audio

- Makefile
To open the kernel configuration editor.
Example:
make rpi3-kernel
> makefile: added linux-menuconfig

- board/batocera/patches/kodi/0013-disable-wayland-list-output-segfault.patch
- package/batocera/core/batocera-configgen/configgen/configgen/generators/kodi/kodiConfig.py
- package/batocera/core/batocera-scripts/scripts/batocera-kodi
> fix kodi system crash and fix joystick config

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
> log info for bt

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
* Force mouse
* Added Gun keys
* Added mouse keys (don't know if can be tested but values are there now)
* added possibility to customize mouse (have to be discussed later)
Tested and Ok for @foclabroc
PS : Only vulkan shows the aiming, it's currently a duckstation bug
> Duckstation - Gun and Mouse Fixes

- batocera-Changelog
- package/batocera/emulators/cemu/cemu/cemu.hash
- package/batocera/emulators/cemu/cemu/cemu.mk
Changelog: http://cemu.info/changelog/cemu_1_22_13.txt
> Bump Cemu to 1.22.13b

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulators/retroarch/retroarch/017-forces-video_refresh_rate-to-monitor.patch
> fix ra video refresh rate

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/retroarch/libretro/libretro-pcsx/libretro-pcsx.mk
- Bump to the last build with new multitap code simplification
- Update es_feature and configuen with new option code
https://github.com/libretro/pcsx_rearmed/pull/513
> PCSX Multitap option update

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> Cemu Fix FullScreen (v31)

- board/batocera/raspberrypi/rpi/boot/cmdline.txt
- board/batocera/raspberrypi/rpi3/boot/cmdline.txt
- board/batocera/raspberrypi/rpi4/boot/cmdline.txt
Removed fixes are no longer needed, they limit USB ports fixing an issue reported in 2012.
> rpi: update cmdline.txt

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
> fix duckstation dpad by default

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
> fix mame input when no axis

- package/batocera/core/batocera-scripts/scripts/batocera-support
> system report agent log

- package/batocera/core/batocera-system/Config.in
> rpi4: deactivated librero-melonds

- package/batocera/utils/winbtrfs/winbtrfs.hash
- package/batocera/utils/winbtrfs/winbtrfs.mk
- Fixed bug preventing new directories from appearing in listings
- Fixed Release version of driver still not working on XP
> Bump WinBTRFS (v32)

- package/batocera/core/batocera-scripts/scripts/batocera-upgrade
Improved (means simplified to PR https://github.com/batocera-linux/batocera.linux/pull/4003)
Added badge: DL-size info: x of y MB to download ...
Added badge: MD5 calculation, please wait ...
Added badge: Valid/Non valid checksum
Added badge: Extraction in progress
Added badge: Backing up files...
All is working with progress bar
Moreover
* Removed lots of clutter and unused variables
* Tried to make the script as simple as possible
* Removed the SSH version check (I never was satisfied with this mess)
* Back to the roots, simple and effcient
> update: batocera-update improved messages in ES -v2

- package/batocera/core/batocera-scripts/scripts/batocera-es-theme
resolved conflicts with https://github.com/batocera-linux/batocera.linux/pull/4115
> fix: batocera-es-theme downloader

- package/batocera/core/batocera-system/Config.in
> rpi4: disabled libretro-mednafen_psx

- board/batocera/rockchip/gameforce/fsoverlay/etc/init.d/S32colorbuttonled
- package/batocera/core/batocera-scripts/scripts/batocera-gameforce
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
Stores the status in a file so it can be retrieved at startup and GameForce starts in user settings.
> gameforce: PowerLed and ButtonColorLed

- package/batocera/emulators/wine/wine-mono-proton/wine-mono-proton.mk
- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
This release is minor update of proton for little fix on 6.3-2
> Bump Proton (v32)

- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
> Bump Proton (Again)

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/libretro/libretro-vice/libretro-vice.mk
> disable not working vice cores

- package/batocera/core/batocera-scripts/scripts/batocera-config
> fix update message when no version is available

- Config.in
- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/ecwolf/001-crosscompile.patch
- package/batocera/emulators/ecwolf/Config.in
- package/batocera/emulators/ecwolf/ecwolf.mk
- package/batocera/emulators/retroarch/libretro/libretro-ecwolf/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-ecwolf/libretro-ecwolf.mk
Build OK x86_64
Im adding too first support of ecwolf standalone
> Add lr-ecwolf & ecwolf

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-gameforce.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix psx for gameforce

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> fix swan option check

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
System folder moved from save to system/config
> duckstation: system folder

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/ecwolf/ecwolf.mk
- package/batocera/emulators/ecwolf/port.ecwolf.keys
- package/batocera/emulators/redream/redream.mk
This PR :
- Fix duplicated entry in redream
- Improve ECWolf install
- Add padtokey for quit game
- .ecwolf is only for standalone
Standalone ETA :
- Gamepad work
- Sound work
Issue : 
- ARG not effect ?
- Define config file
- Define save folder
Games tested : 
Spear of Destiny
Wolfenstein 3D
@nadenislamarre you can review please ?
> Improve ECWolf

- package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife
> update: batocera-es-swissknife -- reset all RA cores

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
Missing import :(
New game tested :
Super 3-D Noah's Ark Work
> Fix Configgen ECWolf

- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
> cleanup: rpi_gpioswitch

- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
This reverts commit 3ac6c90732700712d8695e8c0394a66129b53e9d.
reverts while it breaks the compilation.
> Revert "Bump Proton #1"

- package/batocera/core/batocera-system/Config.in
- package/batocera/emulators/ecwolf/ecwolf.mk
> ecwolf fix

- package/batocera/utils/rpigpioswitch/S92switch
- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
Should be easier to maintain now
Correct parameter set is only checked one time now
Some code cleanup
> cleanup: RPi powerswitch scripts

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
The automatic collection for lightgun games was introduced in Batocera 31.
> Killed "lightgun" as a system (replaced by an auto collection now)

- package/batocera/emulators/wine/wine-proton-wow64_32/proton.patch
- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/proton.patch
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
Build OK
Fix this issue : https://github.com/batocera-linux/batocera.linux/issues/4152
> Bump Proton

- board/batocera/users.txt
- package/batocera/core/batocera-audio/S02audio
- package/batocera/core/batocera-configgen/configgen/configgen/generators/flatpak/flatpakGenerator.py
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
> fix some flatpak issues

- board/batocera/amlogic/s905/odroidc2/genimage.cfg
- board/batocera/amlogic/s905/tvbox/genimage.cfg
- board/batocera/amlogic/s905gen3/odroidc4/genimage.cfg
- board/batocera/amlogic/s905gen3/tvbox/genimage.cfg
- board/batocera/amlogic/s912/genimage.cfg
- board/batocera/amlogic/s922x/odroidn2/genimage.cfg
- board/batocera/amlogic/s922x/vim3/genimage.cfg
- board/batocera/cha/genimage.cfg
- board/batocera/odroidxu4/genimage.cfg
- board/batocera/orangepi-pc/genimage.cfg
- board/batocera/orangepi-zero2/genimage.cfg
- board/batocera/raspberrypi/rpi/genimage.cfg
- board/batocera/raspberrypi/rpi3/genimage.cfg
- board/batocera/raspberrypi/rpi4/genimage.cfg
- board/batocera/rockchip/gameforce/genimage.cfg
- board/batocera/rockchip/odroidgoa/genimage.cfg
- board/batocera/rockchip/rk3288/miqi/genimage.cfg
- board/batocera/rockchip/rk3288/tinkerboard/genimage.cfg
- board/batocera/rockchip/rk3399/rock960/genimage.cfg
- board/batocera/rockchip/rk3399/rockpro64/genimage.cfg
- board/batocera/s812/genimage.cfg
- board/batocera/tritium-h5/genimage.cfg
All SBC changed first partition size
All SBC 4GB -> 3GB
~~CHA 2GB -> 3GB~~
> Resize FAT32 partition from all SBC to 3GB

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flatpak/flatpakGenerator.py
> fix flatpak permissions

- board/batocera/patches/pulseaudio-utils/001-rawoption.patch
- package/batocera/core/batocera-audio/Config.in
- package/batocera/core/batocera-audio/S30audioconfig
- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
> pw better names

- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
> fix audio in es list

- board/batocera/patches/libfuse/001-allow-empty.patch
> allow exfat to mount non empty device by default

- package/batocera/core/batocera-system/Config.in
> Restore mame for x86

- board/batocera/fsoverlay/etc/init.d/S12populateshare
> fix machine id

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
> Fix MAME bezel overlays aspect ratio

- package/batocera/utils/batocera-steam/batocera-steam-update
> steam : filter gams

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
this is required on rpi3 to get decent perfs on ra
> rpi3 enable video threaded

- package/batocera/core/batocera-desktopapps/scripts/batocera-config-ppsspp
> fix ppsspp config

- package/batocera/utils/batocera-steam/batocera-steam-update
> only one es call to update es

- package/batocera/core/batocera-splash/Ssystem-splash
- package/batocera/core/batocera-splash/batocera-splash.mk
This is a forced bootlogo in early boot stage
After this the user-splash is loaded
@nadenislamarre @lbrpdx Please review before merge
https://streamable.com/yao2da
pr 4303+4302
> add: BOOTLOGO for all platforms

- package/batocera/core/batocera-desktopapps/scripts/batocera-config-ppsspp
> ppsspp name

- package/batocera/core/batocera-audio/Saudio
- package/batocera/core/batocera-splash/Ssplashscreencontrol
S06audio waits till PA-cmds works proper
S30splashscreencontrol: fixed race condition with sleep timer (deamon service would be better)
> fix: audio on splash + ES

- package/batocera/core/batocera-splash/Ssplashscreencontrol
> more time to start the video

- package/batocera/emulators/retroarch/retroarch/retroarch.mk
> Bump retroarch 1.9.7

- package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk
- package/batocera/emulators/wine/wine-lutris/wine-lutris.mk
> Bump Lutris

- package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk
- package/batocera/emulators/wine/wine-lutris/wine-lutris.mk
- package/batocera/emulators/wine/wine-mono-lutris/wine-mono-lutris.mk
> Bump Lutris + Mono

- package/batocera/emulators/ruffle/ruffle.mk
> Bump Ruffle

- package/batocera/emulators/daphne/daphne.mk
> Bump Daphne

- package/batocera/core/batocera-configgen/configgen/configgen/generators/devilutionx/devilutionxGenerator.py
As noticed on #4348 (the second part of the ticket, this doesn't address the controller issue)
> Fix config path for DevilutionX

- package/batocera/utils/flatpak/batocera-flatpak-update
> flatpak icons

- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- package/batocera/emulationstation/batocera-emulationstation/batocera-preupdate-gamelists-hook
- package/batocera/utils/flatpak/flatpak.mk
> call script before reloading es game lists

- package/batocera/utils/batocera-steam/batocera-steam-update
- package/batocera/utils/flatpak/batocera-flatpak-update
> fix return code to clean es log

- package/batocera/core/batocera-desktopapps/scripts/filemanagerlauncher
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> Fix 'F4' when terminal not set up intially

- package/batocera/utils/bauh/003-suggestion-default-limit.patch
> bauh default suggestion limit size

- package/batocera/utils/bauh/004-nvidia.patch
> fix bauh on nvidia

- board/batocera/fsoverlay/etc/init.d/S00bootcustom
Early in the boot run /boot/boot-custom.sh start
Late in the shutdown run /boot/boot-custom.sh stop
The script is run synchronously.
This should provide ability to do many customizations, including ability to solve #4316 with a script.
> Run early startup/late shutdown script from /boot

- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> fix es rotation when restarting es

- package/batocera/emulators/cemu/cemu-hook/cemu-hook.hash
- package/batocera/emulators/cemu/cemu-hook/cemu-hook.mk
https://cemuhook.sshnuke.net/#Changelog
> Fix cemuhook for cemu 1.25.1

- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> fix es auto rotate

- Config.in
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/libretro/libretro-emuscv/001-fix-hardcoded-pathes.patch
- package/batocera/emulators/retroarch/libretro/libretro-emuscv/002-disable-watermark.patch
- package/batocera/emulators/retroarch/libretro/libretro-emuscv/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-emuscv/libretro-emuscv.mk
Build OK
Thanks @nadenislamarre
> Add Super Cassette Vision

- package/batocera/utils/flatpak/batocera-flatpak-update
> fix flatpak rights

- package/batocera/utils/bauh/004-nvidia.patch
> fix bauh env check

- board/batocera/amlogic/linux_patches/0001-Add-Odroid-N2-plus.patch
> fix n2 plus frequencies

- package/batocera/core/batocera-splash/Ssystem-splash
> splash enlarge for 4K

- board/batocera/scripts/doWineWow64-32package.sh
Fix sound & crash on Future Pinball
Add libpulse
> Fix doWineWow64-32package.sh

- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
- package/batocera/core/batocera-system/batocera.conf
- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys.conf
- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys_Anbernic_RG351P.conf
- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys_Hardkernel_ODROID_GO2.conf
- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys_Hardkernel_ODROID_GO3.conf
- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys_gameforce.conf
- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys_odroidgoadvance.conf
x86_64 OK
OGA In Progress
OGS In Progress
> Fix PW Sound

- package/batocera/core/batocera-scripts/scripts/batocera-overclock
Also tidies up the config.txt file with an [Overclock] heading.
> Adds higher overclock for the Compute Module 4

- package/batocera/utils/rpigpioswitch/S92switch
- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
which set config.txt parameters
> Fix avoiding to reboot twice with certain Raspberry Pi cases 

- package/batocera/emulators/lightspark/lightspark.mk
> Bump LightSpark

- package/batocera/kodi/kodi19-resource-language-de_de/kodi_resource_language_de_de.mk
- package/batocera/kodi/kodi19-resource-language-el_gr/kodi_resource_language_el_gr.mk
- package/batocera/kodi/kodi19-resource-language-es_es/kodi_resource_language_es_es.mk
- package/batocera/kodi/kodi19-resource-language-eu_es/kodi_resource_language_eu_es.mk
- package/batocera/kodi/kodi19-resource-language-fr_fr/kodi_resource_language_fr_fr.mk
- package/batocera/kodi/kodi19-resource-language-it_it/kodi_resource_language_it_it.mk
- package/batocera/kodi/kodi19-resource-language-pt_br/kodi_resource_language_pt_br.mk
- package/batocera/kodi/kodi19-resource-language-sv_se/kodi_resource_language_sv_se.mk
- package/batocera/kodi/kodi19-resource-language-tr_tr/kodi_resource_language_tr_tr.mk
- package/batocera/kodi/kodi19-resource-language-zh_cn/kodi_resource_language_zh_cn.mk
> Bump Kodi Lang

- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3399
> fix bt audio syntaxe

- package/batocera/emulators/ruffle/ruffle.mk
> Fix for #4422

- package/batocera/utils/batocera-wine/batocera-wine
> Improve Prefix for Lutris & Proton

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-cemu
> fix cemu first time config

- package/batocera/utils/winetricks/winetricks.mk
> Bump Winetricks

- package/batocera/core/batocera-system/Config.in
@jdorigao - removed comments to allow build.
> Fixes commit - fc53d9d to allow builds

- README.md
A little more complete README page :)
> New README page

- package/batocera/core/batocera-audio/batocera-audio.mk
- package/batocera/core/batocera-audio/client-rt.conf
> fix pw (and slow behavior)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/roms/model2/_readme.txt
- package/batocera/emulators/model2emu/model2.mk
Including:
1. Widescreen scripts
2. HD Texture pack for Daytona USA
3. Per game controller inputs
4. Per game NVDATA
5. More control over graphics features of the emulator
> Provides more options and enhancements for Sega Model 2 emulator

- package/batocera/utils/xow/xow.mk
Trying to get the wireless dongle working
@not43s - can you test this?
> update xow for xbox one controllers

- board/batocera/scripts/doWineWow64-32package.sh
- board/batocera/scripts/doWinepackage.sh
- package/batocera/utils/batocera-wine/batocera-wine
This reverts commit d1177f96340656b802544de339a7c8475aa2bd42, reversing
changes made to 8b51e19ef009941a42d48a060f943c569a39c921.
> Revert "Merge pull request #4501 from liberodark/wowpw"

- package/batocera/core/batocera-audio/batocera-audio.mk
> fix pw client rt suffit

- board/batocera/amlogic/linux_patches/0106-arm64-dts-meson-sm1-add-initial-device-trees-for-A95.patch
- board/batocera/amlogic/linux_patches/0115-arm64-dts-meson-add-initial-device-tree-for-Bananapi.patch
- board/batocera/amlogic/s905gen3/tvbox/create-boot-script.sh
- configs/batocera-s905gen3_defconfig
Change to Chewitt's latest patch. LAN is working now, tested by pedrobarbosa (forum member).
> s905gen3: fix A95X F3 tvbox lan

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fixes #4484 (thanks @Fishaphrodite for the detailed report)
> Fix PPSSPP VSyncInterval setting (True by default, perf boost)

- package/batocera/emulators/retroarch/libretro/libretro-duckstation/libretro-duckstation.mk
> fix lr duck

- board/batocera/patches/libretro-dosbox-pure/0001-Exit-DOSBox-Pure-when-game-close.patch
Needs regression testing.
Fixes #4486
Similar to #4552 and #4553
> Exit DOSBox Pure when game exits

- board/batocera/patches/libretro-tyrquake/0001-Exit-TyrQuake-when-game-close.patch
Needs regression testing.
Similar to #4487 and #4552
> Exit TyrQuake when game exits

- board/batocera/patches/libretro-prboom/0001-Exit-PrBoom-when-game-close.patch
Needs regression testing.
Similar to #4487 and #4553
> Exit PrBoom when game exits

- board/batocera/patches/pipewire/001-multiple-module-dir.patch
- board/batocera/scripts/doWineWow64-32package.sh
- package/batocera/core/batocera-audio/batocera-audio.mk
- package/batocera/core/batocera-configgen/configgen/configgen/generators/fpinball/fpinballGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-fpinball
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-model2emu
- package/batocera/utils/batocera-wine/batocera-wine
> fix pipewire wine

- board/batocera/patches/pulseaudio-utils/002-rawprofileoption.patch
- package/batocera/core/batocera-audio/S27audioconfig
- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
> audio profiles

- package/batocera/emulators/retroarch/libretro/libretro-mame/0003-arcade64-0228.patch
- package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
> fix lr mame (revert version)

- package/batocera/emulationstation/batocera-es-system/es_features.yml
to specify that it works on 32-bit only
> added label to enhanced res

- package/batocera/core/batocera-system/Config.in
> beetle psx for rpi

- package/batocera/core/batocera-audio/S27audioconfig
I'm pretty sure this was not intentional and it fixed my audio issue. Thanks.
> Fix typo that causes audio issue

- package/batocera/core/batocera-system/Config.in
@nadenislamarre this is probably a better fix for missing OpenVPN
Fixes #4613 
This is probably a better version of #4610
> fix: openvpn package for all boards

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/kodi/kodiConfig.py
> fix pads : use realName instead of configName

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Addresses https://github.com/batocera-linux/batocera-emulationstation/issues/960#issuecomment-930289875
> Fix cheevos for MelonDS

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds scaling render multiplier options and adds "Widescreen" to scale mode.
This has been tested by @ Modhack on the discord server, based on their changes here: https://versed-text-ead.notion.site/XBOX-Xemu-5b6ec41a3b95447994b2ab2286170da2
> Xemu: More scaling options

- package/batocera/emulators/wine/faudio/faudio.mk
> Bump faudio

- package/batocera/core/batocera-splash/batocera-splash.mk
> fix splash mk

- package/batocera/utils/flatpak/flatpak.mk
Build : OK
*Improve Steam support
> Bump Flatpak

- package/batocera/emulators/lightspark/lightspark.mk
- package/batocera/emulators/ruffle/ruffle.mk
> Bump Flash

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
This is the first part of a feature that needs some team synchronization -- looking at you @Hew-ux ;) 
Right now, this feature can still useful for streamers who want to add their own logo tattooed on top of a bezel.
You can configure this through `batocera.conf` with:
```
global.bezel.tattoo=1
global.bezel.tattoo_corner=NW
global.bezel.tattoo_file=/userdata/system/my_logo.png
gbc.bezel.tattoo_file=/userdata/system/batocera-logo-transparent.png
snes.bezel.tattoo=0
```
> Add the ability to "tattoo" a .png onto a libretro bezel

- board/batocera/rockchip/odroidgoa/patches/sdl2/board-SDL2-rotation.patch
> fix sdl2 goa rotation

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
Made the default controls for GameCube controls the actual defaults Dolphin uses.
> Fixed GC default controls

- package/batocera/emulators/citra/citra.mk
> Bump Citra

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> Add Xbox Series

- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/utils/flatpak/flatpak.mk
- package/batocera/utils/flatpak/steam.keys
> Add Pad2key for Steam

- package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk
> Bump DosboxPure

- package/batocera/emulators/retroarch/libretro/libretro-pcsx2/libretro-pcsx2.mk
> Bump libretro-pcsx2

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> joycon config

- batocera-Changelog
Adds suggestions from @liberodark and @jdorigao to the changelog.
> Add ppsspp changes to changelog

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
easyrpg Work but need to change save folder to go in /userdata/saves/easyrpg
WiiU Not Work need to set file in configgen.
Scumvm work
> Add More System with squashfs

- Config.in
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/libretro/libretro-gong/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-gong/libretro-gong.mk
> Add Gong LR

- Config.in
- package/batocera/core/batocera-system/Config.in
- package/batocera/utils/rclone/Config.in
- package/batocera/utils/rclone/rclone.mk
- package/batocera/utils/syncthing/Config.in
- package/batocera/utils/syncthing/syncthing.mk
Build : OK
Need service 
Run Sync : 
`/usr/bin/syncthing serve --no-browser --logfile=default`
Run UI : 
`/usr/bin/syncthing -browser-only` via xdg
`/usr/bin/syncthing --gui-address http://0.0.0.0:8384` via cli
Service : 
`/usr/bin/syncthing serve --no-browser --no-restart --logflags=0`
UI Access :
`http://batocera_ip:8384/`
Fix https://github.com/batocera-linux/batocera.linux/issues/4906
> Add Syncthing & Rclone

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
> fix squashfs options and single file option

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> squashfs for xbox

- package/batocera/emulationstation/batocera-es-system/batocera-report-system.py
> explode boards in archs

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
> fix squashfs evmapy

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> wiiu controller option for gamecube

- package/batocera/core/batocera-bluetooth/Config.in
> fix sixaxis

- package/batocera/emulationstation/batocera-es-system/es_features.yml
This reverts commit 3f1ea83da434276cbb9be23c5d927f3570143bc7.
> Revert "rk3326: option to vulkan removed (does not work)"

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
> let it possible to blacklist some bt devices

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi2.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> menu threaded video no ES

- package/batocera/emulators/wine/wine-mono-proton/wine-mono-proton.mk
> Bump Wine Mono Proton

- package/batocera/network/rtl8192eu/rtl8192eu.mk
> Fix rtl8192eu

- package/batocera/utils/batocera-wine/batocera-wine
Work : OK
Disable Nvapi for now
> Wine Fix Regression

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> Add 'Incremental SaveState' option

- package/batocera/core/batocera-system/Config.in
> bump and add some rtl for kernel 5.15

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Relates to https://github.com/batocera-linux/batocera.linux/issues/4851 
Options and description agreed with DirtBagXon (Hypseus Singe developer) and successfully tested.
> Adding options for Daphne and Singe games

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-model2emu
- package/batocera/emulationstation/batocera-es-system/roms/model2/_readme.txt
Fixes - crash with new version of Lutris
Fixes - controller issues as per #4426
> convert model2 emulator to use proton

- package/batocera/libraries/catch2/catch2.mk
> Bump catch2

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinSYSCONF.py
makes it uniform with the options available to dolphin generator (why there is duplicate code in different files and conflicting comments I will not question)
> add full ratio to dolphin SYSCONF

- package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk
- package/batocera/emulators/wine/wine-lutris/wine-lutris.mk
- package/batocera/emulators/wine/wine-mono-lutris/wine-mono-lutris.mk
- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
> Bump Lutris + Mono + Proton

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> gamename on hud

- board/batocera/fsoverlay/etc/init.d/S11share
That permit to mount RAID.
(Not work on boot for btrfs-raid but work on ssh)
> Fix Mont Raid

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
awaiting testing to confirm that this doesn't cause any issues
> turn on "auto disc change" in dolphin by default

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/melonds/melondsGenerator.py
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/emulators/melonds/001-default-config.patch
- package/batocera/emulators/melonds/melonds.mk
now supports dsi
note: requires updated firmware files
> bump melonds

- board/batocera/rockchip/rk3326/odroidgoa/patches/sdl2/Fix-black-screen-after-retroarch.patch
Fixes #5005
https://discourse.libsdl.org/t/handle-leak-in-sdl-kmsdrmmouse-c/33750
> odroidgoa: fix black screen after retroarch

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/Generator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml
- package/batocera/core/batocera-system/batocera.conf
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/utils/mangohud/0001-stb_image.patch
- package/batocera/utils/mangohud/0002-loadTextures.patch
- package/batocera/utils/mangohud/0003-rgba.patch
- package/batocera/utils/mangohud/0004-image.patch
> bezels on hud

- package/batocera/core/batocera-desktopapps/scripts/batocera-config-pcsx2
> fix f1 pcsx2

- package/batocera/core/batocera-audio/S27audioconfig
> set audio volume at boot when card cannot be set

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> hud everywhere

- package/batocera/core/batocera-configgen/Config.in
- package/batocera/core/batocera-system/Config.in
> fix configgen hud dep

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
> fix pcsx2 hud

- package/batocera/emulators/ppsspp/004-fix-ppssppramclean.patch
> clean ppsspp .ram

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> disable hud for openbor -- too many troubles depending on games

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-gameforce.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3326.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpizero2.yml
This reverts commit b98484133ac60ec83f25c8cad6586319bc8957a1.
> Revert ""game aspect ratio = auto" detects aspect ratio"

- package/batocera/emulators/ppsspp/004-fix-ppssppramclean.patch
> backport the ppsspp fix

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> reintroduce not so unusefull tags

- batocera-Changelog
> add pcsx2-fix and change tabs to spaces

- package/batocera/kodi/kodi19-resource-language-de_de/kodi_resource_language_de_de.mk
- package/batocera/kodi/kodi19-resource-language-el_gr/kodi_resource_language_el_gr.mk
- package/batocera/kodi/kodi19-resource-language-es_es/kodi_resource_language_es_es.mk
- package/batocera/kodi/kodi19-resource-language-eu_es/kodi_resource_language_eu_es.mk
- package/batocera/kodi/kodi19-resource-language-fr_fr/kodi_resource_language_fr_fr.mk
- package/batocera/kodi/kodi19-resource-language-it_it/kodi_resource_language_it_it.mk
- package/batocera/kodi/kodi19-resource-language-pt_br/kodi_resource_language_pt_br.mk
- package/batocera/kodi/kodi19-resource-language-sv_se/kodi_resource_language_sv_se.mk
- package/batocera/kodi/kodi19-resource-language-tr_tr/kodi_resource_language_tr_tr.mk
- package/batocera/kodi/kodi19-resource-language-zh_cn/kodi_resource_language_zh_cn.mk
> Update Kodi Lang

- package/batocera/utils-host/xa/xa.mk
version 2.3.11 is not available for download
> xa: version bump (2.3.12)

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> decoration menu

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk
- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> generate .h option file for es

- package/batocera/emulators/dolphin-emu/001-padorder.patch
- package/batocera/emulators/dolphin-emu/dolphin-emu.mk
This reverts commit bcbcbbc01d6fca26f188e66ce81677cf39e228ed.
> Revert "bump: dolphin-emu to 5.0-15478"

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> fix options xml

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
> fix pcsx2 internal resolution

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Continuation of https://github.com/batocera-linux/batocera.linux/pull/5206.
> es_features.yml spelling, grammar and corrections part 2

- board/batocera/scripts/post-image-script.sh
generate sha256 sums for images and boot.tar.xz
for #5214
> generate sha256 sums for images and boot.tar.xz

- package/batocera/emulators/retroarch/libretro/libretro-pcsx2/libretro-pcsx2.mk
> Bump PCSX2-LR

- Makefile
Added DOCKER variable which defaults to docker. This allows easy usage
of other container runtimes.
Example command line using rootless podman:
DOCKER=podman DOCKER_OPTS="--userns keep-id" make rk3399-build
or in batocera.mk:
DOCKER      := podman
DOCKER_OPTS := --userns keep-id
Note: examples above were executed in Manjaro Linux. podman required
catatonit package to be installed (for --init to work). And, of course,
you have run `make build-docker-image` first with variables above.
> Makefile: make docker executable configurable with conditional variable

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
This reverts commit 0564271b61f12b21020bc6d0253be00e0bca5b52, reversing
changes made to 29a2f9da53e821286a0a220c4f178908fff4a9d9.
> Revert "Merge pull request #5239 from NostalgicDavid/keymaps"

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk
- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
- package/batocera/emulationstation/batocera-es-system/locales/batocera-es-system.pot
- package/batocera/emulationstation/batocera-es-system/locales/fr/batocera-es-system.po
> game options translation (need .po integration for final compilation)

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk
- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
- package/batocera/emulationstation/batocera-es-system/locales/batocera-es-system.pot
- package/batocera/emulationstation/batocera-es-system/locales/blacklisted-words.txt
- package/batocera/emulationstation/batocera-es-system/locales/fr/batocera-es-system.po
> blacklist words for options translations

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
- package/batocera/emulationstation/batocera-es-system/locales/batocera-es-system.pot
- package/batocera/emulationstation/batocera-es-system/locales/fr/batocera-es-system.po
> comment on game options

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
I tried the config here and everything worked the way I expected it to  - except that the ab/xy buttons seemed to be mapped incorrectly. This fixes that. Thanks.
> Fix Steam Controller Buttons

- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/locales/fr/batocera-es-system.po
> move some options to es_features

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
> bt by types

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
> Fix MongoHUD

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3326.yml
Also, tested only on libretro as I don't have MAME standalone and HUD on OGS. 
This needs testing on other architectures, and in particular PC x86_64 with 4k/ultrawide screens as I suspect there are still bugs left in the current code.
> Fix bezels on OGS (and others, but requires more testing)

- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/wine/dxvk-nvapi/dxvk-nvapi.hash
- package/batocera/emulators/wine/dxvk-nvapi/dxvk-nvapi.mk
- package/batocera/utils/batocera-wine/batocera-wine
Set NVAPI ON same as Proton.
Next need a wiki for active DLSS
`echo dxgi.nvapiHack = False > /userdata/system/wine/dxvk/dxvk.conf`
In ES Set ON HIDE NVIDIA GPU
> Bump Nvapi

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> fix game settings

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
> fix bt agent

- board/batocera/patches/xapp_xrandr/xapp_xrandr-001-listResolutions.patch
- package/batocera/core/batocera-scripts/scripts/batocera-resolution.xorg
> xorg : resolution + rate

- package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
> simplifyessyspy

- package/batocera/utils/pacman/batocera-makepkg
Removed an option that creates confusion.
> Simplified batocera-makepkg

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Controllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
- package/batocera/emulators/rpcs3/006-no-firmware-confirmation.patch
> rpcs3 : fix pads, install firmware automatically

- package/batocera/emulators/retroarch/libretro/libretro-vice/libretro-vice.mk
bump libretro-vice and re-enable VFS after it has been fixed in lr-vice
> bump: libretro-vice

- package/batocera/emulators/scummvm/000-configure.patch
- package/batocera/emulators/scummvm/scummvm.mk
Newer commits are not compiling to rockchip.
> scummvm: rockchip

- batocera-Changelog
these changes have already been merged
> add xorg rate and rpi3/4 default emulator changes to changelog

- board/batocera/odroidxu4/patches/sdl2/sdl2_GBM_BO_USE_LINEAR.patch
- board/batocera/patches/sdl2/sdl2_add_video_mali_gles2.patch
- board/batocera/patches/sdl2/sdl2_older_gbm.patch
> fix mali by mrfixit

- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
and make it easier to comprehend, less unnecessary variables
> optimise bezels.py a bit + fix tattoo corner option

- board/batocera/fsoverlay/etc/init.d/S03urandom
- board/batocera/scripts/post-build-script.sh
buildroot urandom-scripts use /var/lib/ and run late
This saves and restores urandom. I tested.
@nadenislamarre
> Save and restore /dev/urandom seed

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/scummvm/scummvmGenerator.py
Hey @iconoclusterdotexe could you please test this and tell me if it fixes #5032 ?
> Tentative fix for SDL joypad on scummVM and flycast

- board/batocera/odroidxu4/fsoverlay/etc/asound.conf
> fix xu4 audio

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
It needs to have its d-pad assigned to the left analog stick otherwise it acts as if though up/left is always held down.
> add retrobit saturn controller

- board/batocera/patches/libdrm/001-modeslist.patch
> fix rpi4 black screen

- package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py
As requested on a comment #5357
> Add SDL joypad config for amiberry

- package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- Added selectable Auto Height mode (AUTO = FALSE)
- Added selectable Line Mode (AUTO = DOUBLE)
- Added Remove Interlace Artifacts option = (AUTO = OFF)
- Added Video Resolution option = (AUTO = HiRes)
- Added Scaling Method option = (AUTO = AUTO lol)
> Amiberry settings to ES [Part 1]

- package/batocera/core/batocera-drminfo/batocera-drminfo.c
> hide drm disconnected output

- board/batocera/rockchip/rk3326/patches/sdl2/board-SDL2-rotation.patch
> fix rk sdl rotation

- package/batocera/core/batocera-scripts/scripts/batocera-wifi
Merging it, as there's a bunch of issues that I'd like to see if they're properly fixed by this PR:
- #5327 
- #4540
> Fix wifi enable/disable issue (OGA/OGS mainly)

- package/batocera/emulators/retroarch/shaders/hsm-shaders/hsm-shaders.mk
> Bump Mega Bezels

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fix batocera-es-system build. Broken in  #5346 @TVsIan @lbrpdx
> Fix build (es_features.yml)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fix Emulation Station settings for vice_x64sc
Add Emulation Station settings for vice_x128, vice_xplus4, vice_xvic, vice_xpet
Need add keymaps for vice_x128, vice_xplus4, vice_xvic, vice_xpet in seperate pull request
Need help for keymaps
> libretro-vice ES settings

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/Generator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
> ingameratio rom

- package/batocera/core/batocera-configgen/configgen/configgen/generators/devilutionx/devilutionxGenerator.py
Fix https://github.com/batocera-linux/batocera.linux/issues/5383
> Fix DevilutionX

- package/batocera/utils/switchres/switchres.mk
> fix switchres

- package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm
> fix drm modes

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Controllers.py
> fix rpcs3 configgen

- package/batocera/emulators/rpcs3/Config.in
- package/batocera/emulators/rpcs3/rpcs3.mk
Build OK
Work : OK
Need to merge : https://github.com/batocera-linux/buildroot/pull/292
> Bump RPCS3

- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
> es specialisation to batoceta

- package/batocera/utils/xow/xow-daemon
> fix xow daemon

- package/batocera/utils/syncthing/syncthing.mk
> Bump syncthing

- package/batocera/core/batocera-system/Config.in
- package/batocera/utils/rclone/rclone.mk
> Bump rclone

- package/batocera/utils/ryzenadj/ryzenadj.mk
> Bump ryzenadj

- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
please don't revert
controllers don't work properly with model2emu under lutris
- crashes & controller order issues
until this is resolved, we need to use proton
> convert model2 to use proton - again

- package/batocera/emulators/openmsx/001-user-dir.patch
> Update openmsx patch

- package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
> fix evmapy when bad pad configuration with 2 same axis configured

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
Add OpenMSX on MSX+ & MSX Turbo
> Add MSX+ & MSX Turbo

- package/batocera/core/batocera-system/Config.in
> Fix rclone for x86_64

- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/retroarch/libretro/libretro-fmsx/libretro-fmsx.mk
Build : OK
Add Cheevos : https://github.com/libretro/fmsx-libretro/commit/aa59e437a5dd8a1106ec0ebe315ca0053198c368 
@lbrpdx can you check that ?
Thank you
> Bump libretro-fmsx

- package/batocera/emulationstation/batocera-es-system/es_features.yml
noticed that the other latency settings were recently added here, so I've put the extra VRR setting I've just added recently to ES here as well: https://github.com/batocera-linux/batocera-emulationstation/pull/1111
> add variable refresh rate to es_features

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
> Fix Mame Configgen

- package/batocera/emulators/pcsx2-avx2/005-states.patch
- package/batocera/emulators/pcsx2/005-states.patch
> save pcsx2 savestate

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
> fix pcsx2 fps

- package/batocera/emulators/retroarch/libretro/libretro-swanstation/libretro-swanstation.mk
> Bump Swanstation

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py
> fix mame arrows at first boot

- package/batocera/emulators/cemu/cemu/cemu.hash
- package/batocera/emulators/cemu/cemu/cemu.mk
> Bump Cemu v33

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Also fixed the indentation of the PiDMG controls.
> Add jammasd controls

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
> rename default bezels while it is a reserved word for configgen

- package/batocera/core/batocera-scripts/scripts/batocera-info
> show max number of core

- board/batocera/patches/fbv/001-xyz-rotate.patch
> xyz fbv rotate

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
As requested by @iconoclusterdotexe in #5357
> Add SDL env variable for controller

- batocera-Changelog
If this isn't done I don't think anyone will ever know it exists.
> add smartmontools to changelog

- package/batocera/emulators/rpcs3/007-fix-screenshot-directory.patch
fixes - https://github.com/batocera-linux/batocera.linux/issues/5412
> RPCS3 screenshot folder fix

- package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
This needs to be merged into master + v33
> Fix bezels for screensaver (for Batocera 33)

- package/batocera/emulators/ppsspp/001-batocera-path.patch
fixes save location for ppsspp standalone as per ... https://github.com/batocera-linux/batocera.linux/issues/5365
> Fix ppsspp save folder

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Surprised this wasn't already here actually. v34
> add pdp faceoff switch controller to es_input.cfg

- Config.in
- package/batocera/core/batocera-system/Config.in
- package/batocera/network/rtl8812au/Config.in
- package/batocera/network/rtl8812au/rtl8812au.mk
Fixes https://github.com/batocera-linux/batocera.linux/issues/5542
yes for v33
> fix rtl8812 wifi on S922x

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-flycast
- package/batocera/emulators/flycast/atomiswave.flycast.keys
- package/batocera/emulators/flycast/dreamcast.flycast.keys
- package/batocera/emulators/flycast/flycast.mk
- package/batocera/emulators/flycast/naomi.flycast.keys
fixes https://github.com/batocera-linux/batocera.linux/issues/5545
issues identified from 5545
* directory not created correctly on fresh install when not running dreamcast first
* flycast not finding bios files
* naomi & atomiswave controllers not mapped correctly
* fixed flycast exit (which aligns to v1.2 upgrade in v34)
* fix vulkan not working
fixes https://github.com/batocera-linux/batocera.linux/issues/5550
yes for v33
> fix flycast bios location

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> Update xbox wireless v33

- package/batocera/emulationstation/batocera-es-system/es_features.yml
these options were added here seemingly before the corrections were submitted to ES. Also made some improvements to the HUD option labels.
> bring over spelling/grammer improvements from ES

- package/batocera/emulators/redream/redream.hash
- package/batocera/emulators/redream/redream.mk
> Bump Redream v34

- package/batocera/emulators/mame/mame.mk
> Bump Mame (v34)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/demul/demulGenerator.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/demul/gaelco.demul.keys
- package/batocera/emulators/demul/hikaru.demul.keys
multiple fixes for gaelco roms when using demul
> gaelco updates for demul (v34)

- board/batocera/x86/linux_patches/01-fsync1_via_futex_waitv.patch
- board/batocera/x86/linux_patches/02-winesync.patch
Build OK
Checkup Non Breaking > https://github.com/batocera-linux/batocera.linux/pull/5534/files
> Bump Kernel 5.16 patch

- board/batocera/amlogic/s905/odroidc2/boot/extlinux.conf
- board/batocera/amlogic/s905/tvbox/boot/uEnv.txt
- board/batocera/amlogic/s905gen2/boot/extlinux.conf
- board/batocera/amlogic/s905gen3/odroidc4/boot/extlinux.conf
- board/batocera/amlogic/s905gen3/tvbox-gen3/boot/uEnv.txt
- board/batocera/amlogic/s912/boot/extlinux.conf
- board/batocera/amlogic/s922x/gtking/boot/extlinux.conf
- board/batocera/amlogic/s922x/gtkingpro/boot/extlinux.conf
- board/batocera/amlogic/s922x/odroidn2/boot/extlinux.conf
- board/batocera/amlogic/s922x/vim3/boot/extlinux.conf
- board/batocera/odroidxu4/boot/extlinux.conf
- board/batocera/rockchip/rk3288/miqi/boot/extlinux.conf
- board/batocera/rockchip/rk3288/tinkerboard/boot/extlinux.conf
- board/batocera/s812/boot/uEnv.txt
- board/batocera/tritium-h5/boot/extlinux.conf
> remove video=

- batocera-Changelog
- package/batocera/emulators/duckstation/duckstation.mk
> bump duckstation

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
- package/batocera/utils/mangohud/0002-loadTextures.patch
- package/batocera/utils/mangohud/0003-rgba.patch
- package/batocera/utils/mangohud/0007-drm-novk.patch
- package/batocera/utils/mangohud/mangohud.mk
no working correctly with mali+solarus, mali+mupen
working with rpi4+solarus
but not yet working with rpi4+retroarch+vk (just do nothing, not crashing)
> mangohud for drm

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
also fixes the bezels so they actually show now when using 4:3
> fix PCSX2 ratio

- package/batocera/emulators/pcsx2-avx2/pcsx2-avx2.mk
- package/batocera/emulators/pcsx2/003-path.patch
- package/batocera/emulators/pcsx2/pcsx2.mk
> update pcsx2 to v1.7.2364

- package/batocera/emulationstation/batocera-es-system/es_features.yml
add several options to "advanced options" to make it clearer to user on what's the general changed options.
The idea is that option rarely modified go here.
Don't hesitate to modify. it was a first pass.
It should work, but i'm unable to compile now, but i wanted to merge however so that if people add options, he does the same. (blame me if that doesn't compile, it should be ok)
> put some options to advanced options

- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
fixes a crash when the user does not have this key set
> fix bezel resize value

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes https://github.com/batocera-linux/batocera.linux/issues/5599
> fix xbox controllers on duckstation

- package/batocera/libraries/appstream-glib/Config.in
- package/batocera/libraries/appstream-glib/appstream-glib.mk
we are in control of this package - no need to keep comments as this isn't from BR source
also mk file was labeled wrong
> tidy-up appstream package

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> fixes build

- package/batocera/gpu/vulkan/vulkan-loader/vulkan-loader.hash
- package/batocera/gpu/vulkan/vulkan-loader/vulkan-loader.mk
- package/batocera/gpu/vulkan/vulkan-tools/001-fix-vkcube.patch
- package/batocera/gpu/vulkan/vulkan-tools/vulkan-tools.hash
- package/batocera/gpu/vulkan/vulkan-tools/vulkan-tools.mk
> bump vulkan libraries etc to 1.3.206

- package/batocera/emulators/ruffle/Config.in
- package/batocera/emulators/ruffle/ruffle.mk
fixes ruffle so it now builds with latest BuildRoot
bumped also
> bump & fix ruffle build for latest BR

- board/batocera/rockchip/rg552/fsoverlay/etc/init.d/S33checkhdmi
- board/batocera/rockchip/rg552/fsoverlay/usr/bin/batocera-check-hdmi
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rg552.yml
- package/batocera/core/batocera-scripts/batocera-scripts.mk
- package/batocera/core/batocera-scripts/scripts/batocera-resolution-post-rg552
- package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulators/retroarch/retroarch/retroarch.mk
> rg552 hdmi

- board/batocera/rockchip/rg552/fsoverlay/usr/bin/batocera-check-hdmi
> simplify the hdmi checker

- package/batocera/core/batocera-splash/scripts/Ssplash-mpv.template
> flag to remove video subtitle

- board/batocera/patches/sdl2/sdl2_x11modes.c_2.0.20_to_2.0.14.patch
requires sdl2 buildroot bump too
> bump sdl2 patches for 2.0.20

- board/batocera/amlogic/s922x/patches/mesa3d/001-mesa-panfrost-duckstation.patch
- board/batocera/amlogic/s922x/patches/mesa3d/002-mesa-pnafrost-ppsspp.patch
fixes - https://github.com/batocera-linux/batocera.linux/issues/5617
duckstation corrupted graphics
> patch panfrost for duckstation graphics fixes

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
creates a compliant xml file per controller detected
- uses XInput api type
- add more rumble options
- add wii u classic controller option
> cemu v1.26+ now uses xml for controller settings

- package/batocera/emulators/retroarch/retroarch/008-drm-libgo-resolution.patch
> resolution on drm libgo

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-duckstation
- package/batocera/emulators/duckstation/duckstation.mk
fix controller error when set to auto
use the nogui binary to avoid the gui showing (will use gui in F1->apps)
also fixes english translation error
removes a lot of code separation too
> multiple duckstation fixes

- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> clean es reboot

- package/batocera/utils/l3afpad/l3afpad.mk
> fix l3afpad cross compilation

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Surprised this wasn't already in actually. It should just be using the regular 360 controls.
> add 8bitdo X-input Xbox 360 config to es_input

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- change hard-coded python path
> fix libretro mame not working with some systems

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
It's a whack-ass 8 button arcade stick that's actually very nice. No home button unfortunately.
> add nygcan ps3 arcade-style controller and PS4 usb gen 1 config

- package/batocera/emulators/dolphin-triforce/dolphin-triforce.mk
- package/batocera/emulators/dolphin-triforce/triforce.dolphin_triforce.keys
More information: https://discord.com/channels/357518249883205632/524321176068161554/951608501170491412
> fix evmapy for triforce (again)

- package/batocera/core/batocera-system/Config.in
> disable some rtl until updated upstream for new kernel

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Adding custom palettes as an option for the Game Boy colorization.
> Custom palettes added to GB options

- package/batocera/core/batocera-system/Config.in
- package/batocera/network/rtl8192eu/rtl8192eu.mk
builds ok, needs end-user testing
> rtl8192eu builds with 5.17 kernel

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
Adding /userdata/systems/config/mame to the ini path to duplicate the functionality on other OSes.
> MAME INI Path Addition

- configs/batocera-rpi1_defconfig
- configs/batocera-rpi2_defconfig
- configs/batocera-rpi3_defconfig
- configs/batocera-rpi4_defconfig
- configs/batocera-rpizero2_defconfig
v5.15.28
- rpi firmware in buildroot repo
> bump rpi kernel

- package/batocera/alllinuxfirmwares/alllinuxfirmwares.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/5786
> create symbolic links for realtek firmware

- package/batocera/core/batocera-system/Config.in
helps fix dodgy usb wifi devices
> adds usb_modeswitch

- package/batocera/utils/switchres/000-fix-makefile.patch
- package/batocera/utils/switchres/switchres.mk
> bump switchres

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
> fix flycast controller configs

- package/batocera/emulators/retroarch/retroarch-assets/retroarch-assets.mk
- package/batocera/emulators/retroarch/retroarch/000-input_sort_devices.patch
- package/batocera/emulators/retroarch/retroarch/Config.in
- package/batocera/emulators/retroarch/retroarch/retroarch.mk
- package/batocera/emulators/retroarch/shaders/glsl-shaders/glsl-shaders.mk
- package/batocera/emulators/retroarch/shaders/slang-shaders/slang-shaders.mk
- bump shaders too
- compiles & runs ok across x86 & rpi4
- tested a few cores, no issues
> bump retroarch to 1.10.1

- package/batocera/emulators/melonds/001-default-config.patch
- package/batocera/emulators/melonds/melonds.mk
> fix standalone melonds

- package/batocera/gpu/vulkan/glslang/Config.in
- package/batocera/gpu/vulkan/vulkan-loader/Config.in
- package/batocera/gpu/vulkan/vulkan-tools/Config.in
fixes build spam & tidies up the dependency chain
> fix build dependencies

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/moonlight/moonlightConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Added all available AV Decoder options available in Moonlight Embedded.
Fixed formatting issue in changelog from original PR.
> Moonlight Config Fixes

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
> init bt list

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
too much copy & paste - my bad
> fix flycast gen on clean install

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
- also set volume to 100% by default
> fixes openal error in rpcs3

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
> pidof not working when called from es

- package/batocera/utils/evsieve/001-persistmodeexit.patch
> evsieve persist mode exit

- package/batocera/emulators/dolphin-emu/dolphin-emu.mk
- package/batocera/emulators/dolphin-emu/gamecube.dolphin-emu.keys
- package/batocera/emulators/dolphin-emu/wii.dolphin-emu.keys
sometimes dolphin stays around in the background
- now we kill it for good.
> bump & fix dolphin not closing

- package/batocera/utils/evsieve/evsieve-merge-devices
- package/batocera/utils/evsieve/evsieve.mk
> evsieve-merge-devices

- package/batocera/utils/evsieve/evsieve-merge-devices
> evsieve-merge-devices by names

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Expanding on achievements that are available for the lr-flycast core. My first PR so if I haven't done something right I apologise.
> Add RetroAchievements for Atomiswave and Naomi (lr-flycast)

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
adds logitech f30
adds 8bitdo pro 2
fixes nvidia shield
alignments & consistency
> es_input additions & tweaks

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/5919
> fixes multi-player in flycast standalone

- package/batocera/core/batocera-system/batocera.conf
- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
- package/batocera/utils/rpigpioswitch/rpigpioswitch.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/5368
> add PiStation LCD case support

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
> fix ra check about info

- package/batocera/core/batocera-system/Config.in
> disable drv on rg552

- package/batocera/emulationstation/batocera-es-system/locales/fr/batocera-es-system.po
> update fr translations

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/redream/redreamGenerator.py
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/redream/Config.in
- package/batocera/emulators/redream/dreamcast.redream.keys
- package/batocera/emulators/redream/redream.hash
- package/batocera/emulators/redream/redream.mk
- controllers now defined by batocera
- ab, xy now correct
- hotkey exits redream
> bump redream & add rpi4 64bit support!

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-ppsspp
- package/batocera/emulators/ppsspp/001-batocera-path.patch
- package/batocera/emulators/ppsspp/ppsspp.mk
QT wasn't working with Vulkan
SDL works just fine
> bump ppsspp & fix vulkan

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-flycast
- package/batocera/emulators/flycast/flycast.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/5945
> bump flycast & fix vulkan

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3128.yml
> change default emulators. at least for megadrive, it is really better

- package/batocera/emulators/supermodel/supermodel.hash
- package/batocera/emulators/supermodel/supermodel.mk
> Bump Supermodel

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
Disable HUD for core with issue or not need.
> Disable HUD

- board/batocera/fsoverlay/etc/init.d/S11share
> more mounting options for partitions at boot

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> hide game name popup at ra startup

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix ra cache

- package/batocera/emulationstation/batocera-emulationstation/Config.in
> es video dep

- package/batocera/emulators/pcsx2-avx2/008-statenameasromfilename.patch
- package/batocera/emulators/pcsx2/008-statenameasromfilename.patch
> pcsx2 : saves as rom name.slot

- package/batocera/emulators/pcsx2-avx2/pcsx2-avx2.mk
- package/batocera/emulators/pcsx2/pcsx2.mk
> bump pcsx2

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
> max 720p for rpi3

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py
> configgen state_filename option

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
> fix supermodel ini comments

- package/batocera/emulators/rpcs3/rpcs3.mk
- fixes seg fault on exit of Shadow of the Colosus
> bump rpcs3 to 0.0.21-13449

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> add guitar hero 5 ps3 controller to es_input.cfg

- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/5996
> remove model2 option that doesn't work

- package/batocera/emulators/mame/mame.mk
Temporary Rollback mame for fix shader.
Is better to keep shader and skip v242.
Build OK
> Rollback Mame

- board/batocera/fsoverlay/etc/modprobe.d/rtw88.conf
- fixes wifi on Atari VCS sometimes not connecting
- improves wifi performance
> fixes rtw88 devices from going into low power states

- package/batocera/emulationstation/batocera-es-system/es_features.yml
thanks Maioni for discovering this
> add Ê to PORTUGUÊS in AI translation target language

- package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/daphne/daphne.mk
New version v2.8.2a supports two new features:
- -nocrosshair  for supporting games (e.g. the five ActionMax games)
- -texturestream for video performance improvements on SBCs using SDL2 => 2.0.16
> Daphne: corrected ratio and rotation, added joystick sensitivity, bump to v2.8.2a

- package/batocera/emulationstation/batocera-es-system/es_features.yml
- removes tabs for spaces causing yml compilation errors
- revert PORTUGUÊS causing other translation engine errors too. (needs investigation).
> fixes es_systems

- package/batocera/ports/sdlpop/001-datapath.patch
- package/batocera/ports/sdlpop/002-padnum.patch
- package/batocera/ports/sdlpop/sdlpop.mk
- SDL2 updates
- numerous game bugs
> bumps SDLPoP

- package/batocera/core/batocera-system/Config.in
Build OK
Drafting until this is properly tested.
> add Kodi VFS RAR plugin

- package/batocera/core/batocera-configgen/configgen/configgen/generators/redream/redreamGenerator.py
- package/batocera/emulators/redream/dreamcast.redream.keys
- package/batocera/emulators/redream/redream.mk
> change some redream mappings

- batocera-Changelog
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/flycast/flycast.mk
- package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
- Version 1.3 updates
- Adds initial support for Naomi2 roms
> bump flycast emulators

- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/6051
> add cheevos to libretro-pce

- package/batocera/emulators/retroarch/libretro/libretro-play/libretro-play.mk
> Bump Play LR

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fixes https://github.com/batocera-linux/batocera.linux/issues/4650
> add framebuffer read setting for mupen64 glide64mk2

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Now it actually describes what it does. https://github.com/DirtBagXon/hypseus-singe#singe-joystick-mouse-support
> amend singe_joystick_range label

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
This was initially meant to be included in a prior PR but that was closed.
> update triforce _info.txt

- board/batocera/fsoverlay/etc/init.d/S11share
> fix network mounting

- package/batocera/emulators/cemu/cemu-hook/cemu-hook.hash
- package/batocera/emulators/cemu/cemu-hook/cemu-hook.mk
> Bump Cemu Hook

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> Add cheevos to flycast in ES

- package/batocera/emulationstation/batocera-es-system/es_features.yml
https://retroachievements.org/viewtopic.php?t=15835
As of Retroarch 1.10.1
> Caprice32 supports retroachievements

- package/batocera/core/batocera-configgen/configgen/configgen/generators/scummvm/scummvmGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/6100
> fix scummvm launching with no joystick

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mugen/mugenGenerator.py
Tested with 2 Mugen games that crashed configgen before.
> Fix configgen for mugen

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix double integerscale

- package/batocera/core/batocera-system/Config.in
> evsieve wants rust that seems to not like arm32 on aarch64

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> Fix Amstrad gx4000 configgen

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> Fix bezels on RG552

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3326.yml
> clean rg552 bezels
