batocera-linux/batocera.linux

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> fix wiiu squashfs

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> fixwiiurpx2

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/emulators/retroarch/retroarch/013-remapcommon.patch
> ra remap common

- package/batocera/core/batocera-configgen/configs/configgen-defaults-s922x.yml
> fix duckstation crash on s922x (however perf are not very good)

- package/batocera/core/batocera-system/Config.in
> disable flycast standalone on s922

- package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/sdlpop/sdlpopGenerator.py
- package/batocera/ports/sdlpop/sdlpop.mk
> fix sdlpop config file locations

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> fix cemu wux

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
- package/batocera/ports/ecwolf/Config.in
- package/batocera/ports/ecwolf/ecwolf.mk
- ecwolf now starts fullscreen
- ecwolf now accepts the resolution set in ES
> bump ecwolf & fix

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix zx spectrum phys keyboard

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> nib for c64

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dosbox/dosboxGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dosboxstaging/dosboxstagingGenerator.py
Fix for #6113 @Redemp please confirm.
> Fix resolution change for dosbox and dosbox-staging

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
> Fix bezel resizing for 16:10 aspect ratios and others

- board/batocera/fsoverlay/etc/modprobe.d/bluetooth.conf
fix - https://github.com/batocera-linux/batocera.linux/issues/6163
> disable btusb autosuspend

- package/batocera/emulators/retroarch/retroarch/001-avoid_xim.patch
> fix ra physical keyboard

- board/batocera/fsoverlay/etc/init.d/S12populateshare
> Fix S12populateshare

- package/batocera/emulators/flycast/flycast.mk
- package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
- fix gles on rpi4
- fix some (not all) naomi2 issues (#6160)
- fix Nightmare in the dark graphical issues
> flycast fixes

- board/batocera/fsoverlay/etc/default/rngd
> rngd : eat less cpu at boot

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Last Fix for HUD/Bezel that fixe crash issue when HUD is actived
> Fixe HUD/Bezel Part 3 v34

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/flycast/atomiswave.flycast.keys
- package/batocera/emulators/flycast/dreamcast.flycast.keys
- package/batocera/emulators/flycast/naomi.flycast.keys
- package/batocera/emulators/flycast/naomi2.flycast.keys
- option previously wasn't available
- allow hiding of bezels too
> add rumble to flycast

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
adds the xbox one s controller
> xbox one-s config

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
- fixes positive pole required for full trigger when axis
- reduced time to start by only writing config for required 'system'
> flycast controller updates

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> gun options

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> duckstation osd messages

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/mame/dats/gameinit.dat
- package/batocera/emulators/mame/mame.mk
This enables the Data plugin as an option (off by default).
When enabled, there's an extra menu option inside MAME for "External DAT View." Depending on the game, this can show game history, special moves or other commands, and initialization instructions (such as service menus, calibrations, etc).
Currently not included for lr-mame, as it requires changing the directory to the MAME directory before launch for the data paths to be detected properly. It may be added later when I can work out the correct paths.
This does include the data files, which should be updated after MAME bumps (old files will still work, but they may be missing newer info). Sources are listed on the plugin's page (https://docs.mamedev.org/plugins/data.html) and will be added into the changelog when I update it.
> Add Data Plugin to Standalone MAME

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rg552.yml
> hud on psp on rg552 not working

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> nestopia guns

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> nes crosshair gun options

- package/batocera/emulators/rpcs3/rpcs3.mk
Build : OK
Big FPS improvement
> Bump rpcs3 (v35)

- board/batocera/amlogic/linux_patches/wii-ir-revert-x.patch
- board/batocera/cha/linux_patches/wii-ir-revert-x.patch
- board/batocera/odroidxu4/linux_patches/wii-ir-revert-x.patch
- board/batocera/orangepi-pc/linux_patches/wii-ir-revert-x.patch
- board/batocera/orangepi-zero2/linux_patches/wii-ir-revert-x.patch
- board/batocera/raspberrypi/linux_patches/wii-ir-revert-x.patch
- board/batocera/rockchip/rk3128/linux_patches/wii-ir-revert-x.patch
- board/batocera/rockchip/rk3288/linux_patches/wii-ir-revert-x.patch
- board/batocera/rockchip/rk3326/linux_patches/wii-ir-revert-x.patch
- board/batocera/rockchip/rk3399/linux_patches/wii-ir-revert-x.patch
- board/batocera/s812/linux_patches/wii-ir-revert-x.patch
- board/batocera/tritium-h5/linux_patches/wii-ir-revert-x.patch
- board/batocera/x86/linux_patches/wii-ir-revert-x.patch
> invert wii ir x for guns

- package/batocera/controllers/wiimotes-rules/99-wiimote.rules
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-joystick-status
- package/batocera/controllers/wiimotes-rules/wiimotes-rules.mk
> vdolphin bar cleaning

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> gun master system

- Config.in
- package/batocera/controllers/aimtrak-guns/99-Aimtrak_ATRAK.rules
- package/batocera/controllers/dolphinbar-guns/99-dolphinbar.rules
- package/batocera/controllers/guncon/99-guncon.rules
- package/batocera/controllers/guncon/Config.in
- package/batocera/controllers/guncon/guncon.mk
- package/batocera/controllers/sinden-guns/99-sinden.rules
- package/batocera/controllers/wiimotes-rules/99-wiimote.rules
- package/batocera/core/batocera-system/Config.in
> guncon and add to gun udev rules

- board/batocera/fsoverlay/etc/init.d/rcS
> boot time logger

- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-add
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-remap
> command to remap wiimote to joystick / gun and vice and versa

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
Under user request from LauLau on the Discord.
> Add videopac+ system

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Added a few new controllers and updated a couple of others for the new axis mapping. Also fixed some 8BitDo controllers that were using select as the hotkey instead of the home button.
> Updated es_input

- Config.in
- package/batocera/controllers/aimtrak-guns/99-Aimtrak_ATRAK.rules
- package/batocera/controllers/batocera-gun-calibrator/99-gun-calibrator.rules
- package/batocera/controllers/batocera-gun-calibrator/Config.in
- package/batocera/controllers/batocera-gun-calibrator/batocera-gun-calibrator
- package/batocera/controllers/batocera-gun-calibrator/batocera-gun-calibrator.mk
- package/batocera/controllers/dolphinbar-guns/99-dolphinbar.rules
- package/batocera/controllers/gun4ir-guns/99-gun4ir.rules
- package/batocera/controllers/guncon/99-guncon.rules
- package/batocera/controllers/guncon/Config.in
- package/batocera/controllers/sinden-guns/99-sinden.rules
- package/batocera/controllers/wiimotes-rules/99-wiimote.rules
- package/batocera/controllers/wiimotes-rules/Config.in
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-add
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-joystick-status
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- package/batocera/emulationstation/es-theme-carbon/es-theme-carbon.mk
> guncalibrator

- package/batocera/core/batocera-system/Config.in
these packages try to force evsieve to compile, which does not compile for rpizero2
> fix rpizero2 compilation by disabling guns

- package/batocera/controllers/batocera-gun-calibrator/99-gun-calibrator.rules
- package/batocera/controllers/batocera-gun-calibrator/batocera-gun-calibrator
- package/batocera/controllers/wiimotes-rules/99-wiimote.rules
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-add
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulators/retroarch/retroarch/015-mousebuttons.patch
> gun multi buttons + ra config

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
also makes it so syntax highlighting doesn't freak out because of the colons
> cleanup msx1 info instructions

- package/batocera/emulators/scummvm/000-configure.patch
- package/batocera/emulators/scummvm/scummvm.mk
> Bump Scummvm v35

- package/batocera/emulationstation/batocera-es-system/es_features.yml
This is the complement PR to https://github.com/batocera-linux/batocera-emulationstation/pull/1158 , refer to that for more details.
Fixes https://github.com/batocera-linux/batocera.linux/issues/4669
> Clarity and label improvements

- package/batocera/alllinuxfirmwares/alllinuxfirmwares.mk
Uninstalling video firmware for SBC and creating symlinks based on the WHENCE file
> update: alllinuxfirmwares

- package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
- package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
- package/batocera/core/batocera-configgen/configgen/configgen/GeneratorImporter.py
- package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
> configgen optim 1

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
1) touch /var/run/emulatorlauncher.perf
2) start a game
3) gprof2dot.py -f pstats /var/run/emulatorlauncher.prof -o emulatorlauncher.dot # wget https://raw.githubusercontent.com/jrfonseca/gprof2dot/master/gprof2dot.py
4) dot -Tpng emulatorlauncher.dot -o emulatorlauncher.png
> emulationlauncher profiler

- package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
> emulationlaunch optim2

- package/batocera/gpu/rockchip-rga/001-meson.patch
> fix rockchip rga array meson error

- package/batocera/emulators/retroarch/libretro/libretro-uae4arm/libretro-uae4arm.mk
> fix libretro-uae4arm for aarch64 non rpi

- Config.in
- package/batocera/core/batocera-system/Config.in
- package/batocera/core/swapit/Config.in
- package/batocera/core/swapit/S40swapit
- package/batocera/core/swapit/swapit.mk
> swap on boards

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/locales/batocera-es-system.pot
- package/batocera/emulationstation/batocera-es-system/locales/cs_CZ/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/en_GB/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/es/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/fr/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/ja_JP/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/nl/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/pl/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/pt_BR/batocera-es-system.po
- package/batocera/emulationstation/batocera-es-system/locales/ru_RU/batocera-es-system.po
> Bezels caching, HUD corner selector, tattoo image browser fix

- board/batocera/scripts/doWineWow64-32package.sh
Build OK
Fix bad icd files loaded.
> Fix ICD VK files

- board/batocera/scripts/post-image-script.sh
> fix target rockship (_TARGET, _ANY should be reserved in fact)

- package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
> fix videomode max check

- package/batocera/core/batocera-configgen/configgen/configgen/generators/drastic/drasticGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
and corrects a label description about the 3d screen mode.
> add frameskip options for drastic standalone

- package/batocera/controllers/xpadneo/001-remove-guide-functions.patch
- package/batocera/controllers/xpadneo/Config.in
- package/batocera/controllers/xpadneo/xpadneo.mk
required for xbox one s & xbox x & s gamepads
> add xpadneo

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> fix nes crosshair when force

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix lr-mame guns

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> lr-mame: use_guns option

- package/batocera/core/batocera-system/Config.in
- package/batocera/utils/btop/Config.in
- package/batocera/utils/btop/btop.mk
Allows for btop to be built on all platforms.
Draft because this needs way more testing on more platforms.
> build btop for all platforms

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
@dmanlfc re-created pull request
> Supermodel hat joystick support

- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix bezels for the model2

- package/batocera/controllers/sinden-guns/99-sinden.rules
- package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
> sinden borders support

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
> sinden borders part 2

- package/batocera/controllers/batocera-gun-calibrator/batocera-gun-calibrator
> fix wii gun calibrator for xorg

- package/batocera/controllers/aimtrak-guns/99-Aimtrak_ATRAK.rules
> disable aimtrak batocera calibration

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix tatoo when hud+nobezel

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
> disable hud for daphne

- board/batocera/scripts/doWineWow64-32package.sh
- board/batocera/scripts/doWinepackage.sh
- Cleanup unused code
- Fix ld thank to @nadenislamarre
> Cleanup wine-wow64

- Config.in
- package/batocera/core/batocera-system/Config.in
- package/batocera/network/qualcomm/pd-mapper/Config.in
- package/batocera/network/qualcomm/pd-mapper/pd-mapper.mk
- package/batocera/network/qualcomm/qrtr/Config.in
- package/batocera/network/qualcomm/qrtr/qrtr.mk
- package/batocera/network/qualcomm/rmtfs/Config.in
- package/batocera/network/qualcomm/rmtfs/rmtfs.mk
- package/batocera/network/qualcomm/tqftpserv/Config.in
- package/batocera/network/qualcomm/tqftpserv/tqftpserv.mk
> add odin wifi deps for baseband

- package/batocera/core/batocera-system/Config.in
This reverts commit d92c276be6322a19ff29d989ae61e9560d2a33c5.
> Revert "xow: small correction"

- package/batocera/core/batocera-configgen/data/special/lynx.csv
Delimiter was off in this one csv file, corrected it.
> Fix for Lynx Rotation Detection

- package/batocera/core/batocera-system/batocera.conf
> add country code wifi setting in batocera.conf

- package/batocera/gpu/batocera-nvidia/batocera-nvidia
- package/batocera/gpu/batocera-nvidia/batocera-nvidia.mk
> nvidia: handle modules names

- Config.in
- package/batocera/controllers/aelightgun/99-aelightgun.rules
- package/batocera/controllers/aelightgun/Config.in
- package/batocera/controllers/aelightgun/aelightgun.mk
- package/batocera/controllers/aelightgun/virtual-aelightgun-add
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-add
> ae lightgun support

- package/batocera/core/batocera-system/Config.in
- package/batocera/utils/mangohud/mangohud.mk
Vulkan is being installed on platforms that do not support
> fix wayland and vulkan dependency

- board/batocera/fsoverlay/etc/init.d/S04populate
- package/batocera/gpu/batocera-nvidia-driver/batocera-nvidia-driver.mk
- package/batocera/gpu/batocera-nvidia-legacy-driver/batocera-nvidia-legacy-driver.mk
- package/batocera/gpu/batocera-nvidia/batocera-nvidia
- package/batocera/gpu/batocera-nvidia/batocera-nvidia.mk
- package/batocera/gpu/batocera-nvidia340-legacy-driver/batocera-nvidia340-legacy-driver.mk
- package/batocera/gpu/batocera-nvidia390-legacy-driver/batocera-nvidia390-legacy-driver.mk
fixes blackscreen on non-nvidia systems
doesn't spam modules.dep with all the versions
> tidy up nvidia some more

- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> es: added --output to rotation

- Config.in
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-dolphin/Config.in
- package/batocera/emulators/retroarch/libretro/libretro-dolphin/libretro-dolphin.mk
- scripts/linux/checkPackagesUpdates.sh
> add libretro-dolphin

- board/batocera/scripts/doWineWow64-32package.sh
> fixwow32 link

- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
This reverts commit 30c7e4f68a2ba0953681b7e8e8163c903b5094a0.
> Revert "Fix audio mute toggle (keyboard key for sound)"

- package/batocera/utils/mangohud/mangohud.mk
> fix mangohud dep

- batocera-Changelog
- package/batocera/core/batocera-configgen/configs/configgen-defaults-s922x.yml
> s922x dolphin lr

- package/batocera/gpu/vulkan/glslang/Config.in
> clean glslang

- board/batocera/amlogic/s922x/patches/libretro-dolphin/001-openglmessage.patch
> remove s922x warn message on lr-dolphin

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py
> fix mupen axis when axis are buttons

- package/batocera/emulators/wine/wine-mono-proton/wine-mono-proton.mk
- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
> Revert Proton

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds core options to xrick (screen cropping & cheats) by request.
> xrick Options

- package/batocera/controllers/aelightgun/virtual-aelightgun-add
- package/batocera/controllers/aimtrak-guns/aimtrak-add
- package/batocera/controllers/sinden-guns/99-sinden.rules
- package/batocera/controllers/sinden-guns/Config.in
- package/batocera/controllers/sinden-guns/LightgunMono.exe.config.template
- package/batocera/controllers/sinden-guns/licence.txt
- package/batocera/controllers/sinden-guns/sinden-guns.mk
- package/batocera/controllers/sinden-guns/virtual-sindenlightgun-add
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-add
> sinden gun

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
Allows for the user to play patches from ES.
> add json to dolphin

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceGenerator.py
> more guns support

- package/batocera/core/batocera-desktopapps/scripts/batocera-config-duckstation
We don't have QT library installed on SBC
> sbc-xorg: batocera-config-duckstation

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix guns sega

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> Add .wua format for WiiU

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py
No user configuration is required.
This probably could be coded in a better way (such as using an actual Python module to grab the network interface name), but this is consistent for me.
Needs some testing on various different network setups. I really only have one.
Might need to program in some extra safety checks to make sure only appropriate names get passed through, but I want to see if it "just works" on different network setups.
> Enable Xemu local netplay

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/retroarch/libretro/libretro-puae/libretro-puae.mk
- package/batocera/emulators/retroarch/libretro/libretro-puae2021/libretro-puae2021.mk
* fix settings renamed in libretro-vice
* bump: libretro-puae
* bump: libretro-puae2021
* fix settings renamed in libretro-puae
> Fix libretro-vice settings and bump libretro-puae

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
> sinden mame borders

- package/batocera/controllers/sinden-guns/virtual-sindenlightgun-add
> fix multiple sinden guns

- package/batocera/controllers/batocera-gun-calibrator/batocera-gun-calibrator
- package/batocera/controllers/wiimotes-rules/99-wiimote.rules
> switch calibration button on home for wiimote

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
fixes https://github.com/batocera-linux/batocera.linux/issues/6555
> add 7z as incompatible format for drastic

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
hot new controller that literally no one is going to use
> add present for mocute-056 in default mode

- package/batocera/emulators/pcsx2/003-path.patch
fixes - https://github.com/batocera-linux/batocera.linux/issues/6566
> rename the log file

- package/batocera/controllers/xpad-noone/001-add-additional-xbox360.patch
add more compatible controllers
some power-off / standby updates
fix - https://github.com/batocera-linux/batocera.linux/issues/6568
> update xpad-noone patch

- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> rotation after setresolution seems to cause issues (at least win600)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
> adsticks mame configuration for guns

- package/batocera/controllers/batocera-gun-calibrator/batocera-gun-calibrator
> fix relaod in mame

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- clone lr-puae settings for lr-puae2021
- remove surplus spaces in libretroOptions.py
> configgen: lr-puae2021 settings

- Config.in
- batocera-Changelog
- board/batocera/fsoverlay/etc/init.d/S97joycond
- package/batocera/controllers/joycond/Config.in
- package/batocera/controllers/joycond/joycond.mk
- package/batocera/core/batocera-system/Config.in
provides the ability to use nintendo joycons
- merges them together as a virtual 'pro' controller
*** WiP ***
> add joycond userspace driver

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix rumble gain

- package/batocera/core/batocera-system/Config.in
Reverts batocera-linux/batocera.linux#6682
> Revert "hid-nx: Compiling only for x86_64 so far"

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> Force aspect ratio when told so (even with a defined bezel/viewport)

- package/batocera/controllers/joycond/Config.in
> joycond dep

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> X68000 fix HDF files loading and random crashes

- package/batocera/emulationstation/batocera-es-system/es_features.yml
and updates some new options to be clearer and easier to understand.
> Description updates to es_features

- package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/6705
> fix daphne

- batocera-Changelog
> add recently merged changes to changelog

- package/batocera/emulators/retroarch/libretro/libretro-pcsx/libretro-pcsx.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/6735
> bump lr-pcsx_rearmed

- batocera-Changelog
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> supermodel tweaks

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
reflects currently available commands
> update batocera-bluetooth help

- package/batocera/core/batocera-system/Config.in
> linuxconsoletools

- package/batocera/emulators/retroarch/libretro/libretro-beetle-saturn/libretro-beetle-saturn.mk
fixes multi-tap causing crash when enabled
> bump lr-beetle-saturn

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/6788
> mupen64-feature

- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys.conf
> print screen

- package/batocera/emulators/pcsx2-avx2/008-statename.patch
- package/batocera/emulators/pcsx2/008-statename.patch
> fix ps2 state name

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> fix saturn gun

- package/batocera/emulators/dolphin-emu/001-padorder.patch
- package/batocera/emulators/retroarch/retroarch/014_input_sort_devices.patch
> fix pad orders crashes

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> superscope reverse

- package/batocera/controllers/sinden-guns/LightgunMono.exe.config.template
- package/batocera/controllers/sinden-guns/virtual-sindenlightgun-add
> fix sinden alt mapping causing bad up action

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
> rpi4 vulkan defaults

- package/batocera/controllers/sinden-guns/sinden-guns.hash
- package/batocera/controllers/sinden-guns/sinden-guns.mk
> update sinden software

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
> fix dolphin controllers multiplayer

- package/batocera/emulators/mame/005-lightgun-udev-driver.patch
> fix mame precision - limited to 4/3 games for the moment

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/6889
> enable the option to turn off hw hacks

- board/batocera/fsoverlay/etc/samba/smb.conf
One line edit to fix https://github.com/batocera-linux/batocera.linux/issues/6726 regression introduced with v35 beta.
> fix NAS access

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
already checked if it shares a guid with OG switch controller, it does not.
> add retrofighters brawlergen Switch mode to es_input.cfg

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/6892
> fix mame controller is no button defined

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/6874
> fixes dreamcast controller config not being written

- board/batocera/fsoverlay/etc/init.d/S27brightness
> Preserve brightness across reboot

- package/batocera/emulators/duckstation/008-user-dir.patch
fixes - https://github.com/batocera-linux/batocera.linux/issues/6934
> fix duckstation directory

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/6923
> add duckstation sbi option to fix some roms

- board/batocera/fsoverlay/etc/init.d/S04populate
- board/batocera/x86/fsoverlay/etc/init.d/S05nvidia
- package/batocera/gpu/batocera-nvidia/batocera-nvidia
fixes - https://github.com/batocera-linux/batocera.linux/issues/6944
fixes - https://github.com/batocera-linux/batocera.linux/issues/6943
> more robust nvidia device lookup

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3326.yml
Glcore on rk3326 needs to be fixed games work fine but Retroarch does not show notifications and menu.
> rk3326: Setting opengl as default

- package/batocera/core/batocera-triggerhappy/conf/multimedia_keys.conf
- package/batocera/core/batocera-triggerhappy/conf/rg552/multimedia_keys.conf
- package/batocera/core/batocera-triggerhappy/conf/rk3128/multimedia_keys_Game_Simulator_Board.conf
- package/batocera/core/batocera-triggerhappy/conf/rk3326/multimedia_keys_Anbernic_RG351P.conf
- package/batocera/core/batocera-triggerhappy/conf/rk3326/multimedia_keys_Golden_GameForce.conf
- package/batocera/core/batocera-triggerhappy/conf/rk3326/multimedia_keys_Hardkernel_ODROID_GO2.conf
- package/batocera/core/batocera-triggerhappy/conf/rk3326/multimedia_keys_Hardkernel_ODROID_GO3.conf
> fix osd_cat missing lan

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
> fix bezels for none

- package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
i must do tests before merging.
> daphne manymouse as option

- package/batocera/core/batocera-configgen/configgen/configgen/generators/scummvm/scummvmGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
this is necessary to save synth firmware/roms
fixes - #6967 (testing)
> allow a scummvm extras directory in userdata

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
- package/batocera/emulators/mame/005-lightgun-udev-driver.patch
> fix mame lightgun udev driver when screen is not yet opened

- board/batocera/fsoverlay/etc/init.d/S11share
hopefully to avoid situations like https://github.com/batocera-linux/batocera.linux/pull/6989 in the future
> update comments in S11share

- package/batocera/utils/roshambo-case/roshambo-case.mk
looking at - https://github.com/batocera-linux/batocera.linux/issues/6951
> update Rock64-R64.GPIO for python3

- package/batocera/core/batocera-scripts/scripts/batocera-resolution.xorg
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> rotation_by_output

- package/batocera/utils/batocera-wine/batocera-wine
Made & tested the suggested modification.
> Wine autorun.cmd line break fix v2

- board/batocera/patches/sdl2/002-drm-conn.patch
- board/batocera/patches/sdl2/sdl2_input_evdev_at_first_unrelease_button.patch
- board/batocera/patches/sdl2/sdl2_input_p005_limit_ABS_max.patch
- board/batocera/patches/sdl2/sdl2_older_gbm.patch
- board/batocera/patches/sdl2/sdl2_x11modes.c_2.0.20_to_2.0.14.patch
> sdl 2.24.0

- package/batocera/emulators/dosbox/004-sdl2X.patch
> fix dosbox sdl 2.X new numbers

- package/batocera/ports/devilutionx/001-sdl2main.patch
> devilutionx sdl2main

- package/batocera/ports/eduke32/003-fixrpath.patch
> fix eduke32 rpath

- board/batocera/patches/glibc/002-glibc-iconv-modules-extra.patch
This reverts commit 1cacd5f7df6dfaba6a62115f008240e73bc60c1a.
> Revert "revert patch, not needed for glibc 2.33"

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> steam controller config

- package/batocera/core/batocera-audio/S27audioconfig
> setaudio set the sink, so, it must be done after the profile

- package/batocera/core/batocera-scripts/scripts/batocera-info
- package/batocera/core/batocera-scripts/scripts/batocera-support
> update support/info scripts

- package/batocera/core/batocera-settings/batocera-settings-get-master
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> fix auto for settings

- package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm
- package/batocera/core/batocera-splash/scripts/Ssplash-mpv.template
- package/batocera/core/batocera-splash/scripts/Ssystem-splash
> fix some rotation for splash

- board/batocera/patches/xapp_xrandr/xapp_xrandr-001-listResolutions.patch
- package/batocera/core/batocera-scripts/rules/80-switch-screen.rules
- package/batocera/core/batocera-scripts/scripts/batocera-switch-screen-checker
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> display output stimuli

- package/batocera/core/batocera-scripts/scripts/batocera-shutdown
> allow to override the suspend mode by board

- package/batocera/core/batocera-scripts/scripts/batocera-switch-screen-checker
> don't allow switch resquests until es is booted

- package/batocera/emulators/retroarch/shaders/slang-shaders/slang-shaders.mk
> Bump slang shaders

- package/batocera/core/batocera-system/batocera-system.mk
> list modules that doesn't like suspend mode

- package/batocera/core/batocera-scripts/scripts/batocera-es-theme
+ fix of a typo where temp .zip files did not get deleted
> Themes: support for Github main default branch

- batocera-Changelog
- package/batocera/emulators/amiberry/000-amiberry-path.patch
- package/batocera/emulators/amiberry/amiberry.mk
https://github.com/BlitterStudio/amiberry/releases/tag/v5.4
> amiberry: bump to v5.4

- board/batocera/x86/boot/syslinux.cfg
> reduce syslinux timeout

- batocera-Changelog
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
fixes https://github.com/batocera-linux/batocera.linux/issues/7217
> share saves between kronos and beetle

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> we got 64-bit upscaling on pcsx-rearmed bb

- board/batocera/x86/linux_patches/14-hid-steam-Add-basic-support-for-Steam-Deck-controlle.patch
- board/batocera/x86/linux_patches/15-hid-steam-Add-basic-support-for-Steam-Deck-controlle-rumble.patch
- package/batocera/core/batocera-system/sysconfigs/x86_64/batocera.conf.Jupiter
> steam controllers and audio

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> disbale hud & notification option for cemu

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
- package/batocera/emulators/cemu/004-fix-linux-overlay.patch
> fix cemu linux overlay

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
suffix cannot be applied to target cemu params.
> cemu suffix fix

- package/batocera/core/batocera-system/Config.in
> add vulkan for S905 boards

- package/batocera/gpu/batocera-nvidia/batocera-nvidia
fixes - https://github.com/batocera-linux/batocera.linux/issues/7279
> fix nvidia 390 black screen

- package/batocera/emulators/cemu/005-force-no-menubar.patch
> cemu force no menubar (cosmetic)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
> cemu force no menubar

- package/batocera/emulators/cemu/get-audio-device
> cemu default sink

- package/batocera/core/batocera-audio/Saudio
- package/batocera/core/batocera-audio/batocera-audio.mk
- package/batocera/core/batocera-audio/ucm2/conf.d/acp5x/acp5x.conf
> load ucm2 files

- board/batocera/fsoverlay/etc/init.d/S11share
> manage mini packages for bins

- package/batocera/core/batocera-configgen/configgen/configgen/generators/kodi/kodiConfig.py
> kodi: switch to udev driver

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
> fix dolphin configgen

- board/batocera/patches/kodi-peripheral-joystick/001-realvendprodid.patch
- package/batocera/core/batocera-configgen/configgen/configgen/generators/kodi/kodiConfig.py
> yet another kodi joystick bugfix : use real vpids

- package/batocera/core/batocera-triggerhappy/conf/x86_64/multimedia_keys_Jupiter.conf
> steam deck headphones : first step. can probably be better

- package/batocera/core/batocera-scripts/scripts/batocera-switch-screen-checker
> don't switch when es is not idle

- package/batocera/emulators/mupen64plus/mupen64plus-video-glide64mk2/001-hide-framebuffer-message.patch
> hide mupen64 framebuffer message

- package/batocera/core/batocera-scripts/scripts/batocera-info
> hide some messages in batocera-info

- package/batocera/emulators/retroarch/retroarch/018-disable-autoconfig-to-remove-messages.patch
> remove autoconfig in ra

- package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml
> hud_support is a boolean

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> add use_guns to daphne options

- package/batocera/gpu/batocera-nvidia-driver/batocera-nvidia-driver.mk
> fix vulkan loading time

- package/batocera/controllers/guncon/99-guncon.rules
- package/batocera/controllers/guncon/guncon-add
- package/batocera/controllers/guncon/guncon.mk
> guncon buttons

- package/batocera/controllers/guncon/guncon-add
Made I mistake in the button mapping. Now fixed.
> Fix swapped A-B button.

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
> update bt lists

- package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceControllers.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/7413
> fixes vice controller config with less buttons than normal

- package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
> Bump bezels

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
apparently it's exactly the same syntax as yabansanshiro, how nice
> add controller type to beetle saturn

- package/batocera/controllers/sinden-guns/virtual-sindenlightgun-add
- package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/dolphin-emu/008-guns.patch
> guns for wii

- board/batocera/rockchip/rg552/patches/sdl2/0002-config-Link-to-rga.patch
- board/batocera/rockchip/rk3128/patches/sdl2/0002-config-Link-to-rga.patch
- board/batocera/rockchip/rk3326/patches/sdl2/0002-config-Link-to-rga.patch
> rga: Add `-lrga` to sdl2-config and sdl2.pc

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
> force sinden border more often

- package/batocera/emulators/mame/mame.mk
- package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
Otherwise, it tries to spawn 17 workers even on a 4 core machine.
> Limit MAME_JOBS by BR2_JLEVEL

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> Fix o2em (Odyssey2) bezels

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
- package/batocera/emulators/rpcs3/013-gun-support.patch
> ps3 gun support (multiplayers)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
> fix rpcs3 no gui

- package/batocera/emulators/pcsx2-avx2/pcsx2-avx2.mk
- package/batocera/emulators/pcsx2/pcsx2.mk
- no shared libs (requires cleanbuild)
> bump & refactor pcsx2

- batocera-Changelog.md
- package/batocera/emulators/retroarch/libretro/libretro-yabasanshiro/libretro-yabasanshiro.mk
> bump lr-yabasanshiro

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.drm
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> fix rotation

- board/batocera/patches/kodi-peripheral-joystick/002-axis.patch
> fix kodi udev axis

- package/batocera/utils/batocera-wine/batocera-wine
That help to improve games supports on wine.
> Add fonts in Wine

- package/batocera/emulators/retroarch/retroarch/019-draw_splash_screen.patch
https://github.com/libretro/RetroArch/issues/14408
> wl-retroarch: Fixed strange checkered window when running RA in Wayland

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
> fix window size when resolution changes

- board/batocera/fsoverlay/etc/init.d/S27brightness
> minimal brightness

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix gun options

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.basic
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.drm
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.tvservice
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.wayland
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
> minor rotation cleaning

- package/batocera/emulators/dolphin-emu/012-ereaderuntranslatedname.patch
> dolphin ereader untranslated window name

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.wayland
This reverts commit 1d362df1415877f2be5dcfe7b7536904fb1e82a6.
> Revert "fix wayland resolution - sort highest"

- board/batocera/allwinner/h3/cha/patches/sdl2/sdl2_have_rle.patch
> disable sdl2 rle for cha

- board/batocera/x86/linux_patches/17-Add-DS4-to-HID-Playstation.patch
fix DualShock4 bluetooth memory corruption bug.
> fix DualShock4 bluetooth CRC endian issue.

- package/batocera/firmwares/sound-open-firmware/sound-open-firmware.mk
add support for ADL-N production platform
cherry pick topology updates for Intel Raptor Lake (RPL), Alder Lake (ADL) and Ice Lake (ICL) platforms.
> bump sof for updated sound support

- package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- Also removed long obsolete argument from daphne arguments
Untested but copying existing code format. Feel free to correct as required.....
> Add new Singe overlay options for hypseus v2.10.1

- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
> fix hud, mainly for daphne

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
- package/batocera/emulators/xenia-canary/xenia-canary.mk
- package/batocera/emulators/xenia/xenia.mk
also fixes:
- slow boot
- error on clean install
> set some xenia compatibility options

- board/batocera/patches/kodi-peripheral-joystick/002-axis.patch
> fix kodi axis

- board/batocera/patches/lirc-tools/001-compile.patch
> fix lirc tools

- board/batocera/scripts/doWineWow64-32package.sh
- fixes libglvnd for /lib32
- adds new haswel+ vulkan layers
- more verbose output when building in certain cases
@nadenislamarre - wow64 will need an update
> include complete libglvnd libraries - wow64

- package/batocera/core/batocera-desktopapps/apps/xterm.desktop
> fix font size

- package/batocera/emulators/retroarch/libretro/libretro-arduous/001-bootsizewarning.patch
> fix error libretro-arduous boot size uninitialized

- board/batocera/amlogic/s922x/patches/rtl8192eu/sha256_2.patch
> try to fix rtl8192eu for s922x (untested)

- package/batocera/controllers/gun4ir-guns/99-gun4ir.rules
- package/batocera/controllers/gun4ir-guns/gun4ir-guns.mk
- package/batocera/controllers/gun4ir-guns/virtual-gun4ir-add
> gun4ir, all buttons, merge devices

- package/batocera/core/batocera-desktopapps/apps/xterm.desktop
same format as ssh: 
[root@BATOCERA /userdata/system]#
> add prompt to xterm

- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/7825
> fix model2emu subdir issue

- configs/batocera-rk3326.board
- configs/batocera-rk3399.board
- package/batocera/core/batocera-configgen/configgen/configgen/generators/devilutionx/devilutionxGenerator.py
- package/batocera/ports/devilutionx/devilutionx.hash
- package/batocera/ports/devilutionx/devilutionx.mk
Also creates the config and save directories in the generator.
> DevilutionX: Update to 1.4.1 and enable networking

- package/batocera/emulators/bigpemu/bigpemu.hash
- package/batocera/emulators/bigpemu/bigpemu.mk
> fixes audio & graphics issues

- package/batocera/core/batocera-drminfo/batocera-drminfo-no-1366x768.c
- package/batocera/core/batocera-drminfo/batocera-drminfo.mk
> batocera-drminfo-no-1366x768

- package/batocera/emulators/wine/wine-proton/001-liblm.patch
> fix -lm missing, ceil error, wine-proton

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> force borders on ra if needed

- board/batocera/patches/kodi-peripheral-joystick/003-buttons.patch
> fix kodi buttons count

- batocera-Changelog.md
Just a small note in the changelog
> small update to changelog (light guns)

- package/batocera/core/batocera-audio/alsa/batocera-audio
- package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
> some audio issue when parsing pactl output not in english

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Make consistent capitalisation of prompts.
Make prompts more consistent overall.
Remove redundant descriptions.
Improve clarity.
Tense correction.
> minor amendments to es_features

- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
- package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
> fixes wanted devices ; by removing old filtering

- package/batocera/emulators/vita3k/001-base-path.patch
- package/batocera/emulators/vita3k/003-drop-xdg-desktop-portals.patch
- package/batocera/emulators/vita3k/vita3k.mk
- fixes graphics in a couple of games
> vita3k vulkan fixes

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- Add Texture Filtering option
> fix spelling etc

- package/batocera/core/batocera-scripts/scripts/batocera-info
Fix regression of #7922
@dmanlfc can you please look into this?
> batocera-info: fix model display

- board/batocera/patches/sdl2/sdl2_disable_joystickShouldIgnoreEvent.patch
> fix joystick disabled if 'keyboard' has no focus

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> fix esinput

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.drm
> fix rpi4 resolution 1360x768

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix mame 2003 plus guns

- package/batocera/controllers/guncon/guncon.mk
Cleaned up the script.
Fixed saving the calibration values.
Opps  :man_facepalming:
> GunCon2 Calibration save fix

- package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
> Flycast standalone: fix service buttons L3/R3

- board/batocera/fsoverlay/etc/init.d/S11share
Using **sharewait** value when **sharedevice=NETWORK**
> MAXTRY in NETWORK mode

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> Fix wrong platform for scraping c20

- package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/7980
> fix cemu async

- package/batocera/display/sway/sway.hash
- package/batocera/display/sway/sway.mk
https://github.com/swaywm/sway/releases/tag/1.8.1
> sway: bump to 1.8.1

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Xbox Nacon Revolution X
Xbox SteelSeries Stratus Duo
Xbox Thrustmaster eSwap X Pro Controller
> Add New Controllers #2

- board/batocera/fsoverlay/etc/init.d/S02resize
useful for very large drives
updated with more logging too
> fix partition resize to take more of the available disk space

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fixes - https://github.com/batocera-linux/batocera.linux/issues/8268
> fix typo & recommendation.

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
addresses - https://github.com/batocera-linux/batocera.linux/issues/8266
> enable setting the xbla license

- package/batocera/core/batocera-configgen/configgen/configgen/generators/fpinball/fpinballGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
resolves - https://github.com/batocera-linux/batocera.linux/issues/8275
> allow users to set their own controller config

- package/batocera/core/batocera-scripts/scripts/batocera-systems
addresses - https://github.com/batocera-linux/batocera.linux/issues/8254
> update ps3 bios requirements

- package/batocera/core/batocera-configgen/configgen/configgen/generators/scummvm/scummvmGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/8316
> allow scummvm to change resolution

- Config.in
- batocera-Changelog.md
- package/batocera/toolchain/llvm-project/batocera-llvm-cmake/batocera-llvm-cmake.hash
- package/batocera/toolchain/llvm-project/batocera-llvm-cmake/batocera-llvm-cmake.mk
- package/batocera/toolchain/llvm-project/batocera-llvm-project.mk
- package/batocera/toolchain/llvm-project/batocera-llvm/Config.in
- package/batocera/toolchain/llvm-project/batocera-llvm/batocera-llvm.hash
- package/batocera/toolchain/llvm-project/batocera-llvm/batocera-llvm.mk
update to llvm 15 for amd rdna3 gpu support
*** Testing ***
> bring llvm package under batocera control

- batocera-Changelog.md
- package/batocera/emulators/xenia-canary/xenia-canary.mk
- package/batocera/emulators/xenia/xenia.mk
improved game compatibility :-)
> bump xenia versions

- package/batocera/core/batocera-splash/scripts/Ssplash-mpv.template
fixes - https://github.com/batocera-linux/batocera.linux/issues/8008
> fixes splash on the wrong display in multi-monitor environments

- package/batocera/emulators/mame/mame.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/8356
> add neogeo.mame.keys

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/8213
> fixes fuse machine

- board/batocera/rockchip/rk3588/patches/mpv/0004-change_video_zplane_pos_to_1.patch
- board/batocera/rockchip/rk3588/patches/mpv/0005-stop_setting_zpos.patch
recent version bump broke the rk3588 patches for mpv.
> rk3588 / fix mpv patch

- scripts/linux/patch_age.sh
Example use:
scripts/linux/patch_age.sh "kodi*" | sort -n
> scripts / Checks the age of patches within a package or packages

- Dockerfile
- Makefile
This reverts commit 8b68f1e09ee914ba3fa61e1de65e5a30843d9712.
> Revert "Merge pull request #8079 from xEtherealx/osxsupport"

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/xenia/xenia.mk
> bump xenia & add headless option

- package/batocera/utils/alsa-ucm-conf/alsa-ucm-conf.mk
Update required for RK3326 (RK817)
> alsa-ucm-conf: Bump to Mar 20, 2023 Build

- board/batocera/fsoverlay/etc/init.d/S02resize
- fixes busybox changes affecting resize
> refactor partition probe

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix mednafen_psx settings

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix lr-swanstation configs

- package/batocera/core/README.md
> minor addition to batocera/core/README.md

- package/batocera/core/batocera-configgen/configgen/configgen/generators/openmsx/openmsxGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/openmsx/colecovision.openmsx.keys
- package/batocera/emulators/openmsx/openmsx.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/8488
> add openmsx for colecovision

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/8494
> fix swanstation to cfg file

- board/batocera/patches/xapp_xrandr/xapp_xrandr-002-getRotation.patch
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
- package/batocera/emulators/mame/mame.mk
- package/batocera/emulators/mame/rotation_fix.sh
Thanks to @Redemp for the initial idea behind this fix.
> Better fix for MAME exit on SteamDeck (maybe other rotated screens too)

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> Fix Videopac+ G7400 scraping

- package/batocera/emulators/retroarch/libretro/libretro-mgba/libretro-mgba.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/8531
> fix lr-mGBA no audio

- board/batocera/rockchip/rk3399/linux_patches/linux-0001-drivers-add_rg552_singleadcjoy.patch
This reverts commit 47a9c64d360242e2f6dac458b01a8171780ad7fc.
> Revert "fix: drivers add rg552 singleadcjoy"

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py
> fix mame exception

- package/batocera/emulators/retroarch/retroarch/021-disable-gamemode.patch
- removes confusing error message
> disable gamemode

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/emulationstation/batocera-es-system/es_features.yml
addresses - https://github.com/batocera-linux/batocera.linux/issues/8624
> add more melonds options

- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
#v2.4 - removed code duplicates @lala
> rpi_gpioswitch tidy up

- package/batocera/core/batocera-configgen/configgen/configgen/generators/openmsx/openmsxGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> use new .openmsx extension to allow rom / disk stacking

- package/batocera/utils/batocera-test/src/batocera-test
Adds support for multiple games per system via gamesToTest.yml file
> batocera-test: multiple games per system

- package/batocera/core/batocera-configgen/configgen/configgen/generators/redream/redreamGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
This reverts commit 2d31b8cee87d02da2ce0e8a1e0497be9a4e4b7e9.
hardcoding pads is completly forbidden. it is not the correct fix, for sure.
> Revert "use hidapi for easier controller configs"

- board/batocera/x86/fsoverlay/etc/init.d/S05nvidia
- package/batocera/emulationstation/batocera-emulationstation/xorg/xinitrc
- package/batocera/gpu/batocera-nvidia/batocera-nvidia
last thing i was working on...
hopefully provides more info why some drivers aren't loading...
> improve nvidia logging

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/pcsx2/Config.in
- package/batocera/emulators/pcsx2/pcsx2.mk
- package/batocera/emulators/pcsx2/ps2.pcsx2.keys
- hide gui on start
- add hotkeys
> adjust resolution options

- board/batocera/fsoverlay/etc/init.d/S02resize
- board/batocera/x86/genimage.cfg
- No more sgdisk / gparted errors
- fix x86_64 gpt partitioning
- less math :-)
> update the resize methodology again!

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/core/batocera-desktopapps/scripts/batocera-config-duckstation
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/duckstation/psx.duckstation.keys
Start of the update duckstation config
*** Controllers need fixing ***
> update config for qt

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/8447
> default monsters

- package/batocera/core/batocera-scripts/scripts/batocera-systems
resolves - https://github.com/batocera-linux/batocera.linux/issues/8754
> add msx machine roms

- package/batocera/controllers/xpadneo/001-remove-guide-functions.patch
fixes - https://github.com/batocera-linux/batocera.linux/issues/8710
> fixes xpadneo

- batocera-Changelog.md
- package/batocera/emulators/wine/vkd3d-proton/Config.in
- package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.hash
- package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.mk
> bmp vkd3d_proton to v2.9

- batocera-Changelog.md
- package/batocera/emulators/ppsspp/ppsspp.mk
- package/batocera/emulators/retroarch/libretro/libretro-ppsspp/libretro-ppsspp.mk
> you down with ppsspp ?

- package/batocera/emulators/daphne/daphne.mk
No user changes here, but some recent overlay switching fixes which could result in segfault.
> Hotfix for Hypseus

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> Removing duplicate

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/8890
> improve adam system rom configuration

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.wayland
fixes - https://github.com/batocera-linux/batocera.linux/issues/8866
and - https://github.com/batocera-linux/batocera.linux/issues/8892
> fix wayland setMode

- package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/8870
> fix pcsx2 multitap

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/8884
> fix lr-mame with ti99

- package/batocera/emulators/xemu/xemu.hash
- package/batocera/emulators/xemu/xemu.mk
> Bump xemu to 0.7.90 

- package/batocera/emulators/rpcs3/000-rpcs3-v0.0.28-hotfix.patch
Applying https://github.com/RPCS3/rpcs3/pull/13945
> RPCS3 hotfix (regressions) for 0.0.28 alpha (thanks @Johnnylemonhead)

- package/batocera/controllers/guncon/guncon-add
Working together with @Tovarichtch 
Input device name: "GunCon2-Gun"
Trigger = BTN_LEFT
A =   BTN_MIDDLE
B =  BTN_1
C =  BTN_RIGHT
Start =BTN_3
Select = BTN_2
D-Pad Up = BTN_5
D-Pad Down = BTN_6
D-Pad Left = BTN_7
D-Pad Right =  BTN_8
> Update guncon2 virtual gun mapping

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
fixes - https://github.com/batocera-linux/batocera.linux/issues/8920
> fix c64 vice keyboard option config error

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- bezels appearing when full, stretch, 16:9 etc
- add memory option
- fix config file settings
> fix xemu options

- package/batocera/core/batocera-scripts/scripts/batocera-upgrade
> Fix upgrade progress bar

- package/batocera/utils/batocera-wine/batocera-wine
fixes - https://github.com/batocera-linux/batocera.linux/issues/8953
> fix wine with squashfs, more aggressive umounts & directory removals

- team.js
we miss a lot of people here,
if people would give here values here.
this is to generate : https://batocera.org/team/
> team people

- package/batocera/core/batocera-system/Config.in
> Fix build following rk3568 and h3 PR

- board/batocera/rockchip/rk3568/linux_patches/rk3566-roc-cc-dts-fix-usb.patch
Mainline DTS is wrong :(
The patch needs to be upstreamed to Linux kernel
> Fix Firefly Station M2 USB

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
closes - https://github.com/batocera-linux/batocera.linux/issues/9013
> add yabasanshiro system language option

- package/batocera/emulators/retroarch/shaders/batocera-shaders/batocera-shaders.mk
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/curvature/rendering-defaults-mali-400.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/curvature/rendering-defaults-mali-450.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/curvature/rendering-defaults-mali-t720.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/curvature/rendering-defaults-vc4.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/curvature/rendering-defaults-vc5.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/scanlines/rendering-defaults-mali-400.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/scanlines/rendering-defaults-mali-450.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/scanlines/rendering-defaults-mali-t720.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/scanlines/rendering-defaults-vc4.yml
- package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/scanlines/rendering-defaults-vc5.yml
Documented GPU for each SoC / chipset.
Linked Mali-400, Mali-450, Mali-T720, VideoCore 4, VideoCore 5 to low-end settings.
> Refactor batocera-shaders using GPU names for future fine tweaking

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
adjust xorg for user resolution setting:
- add more checks for refresh rate & apply accordingly
- tidy xorg script formatting
- add more logging for troubleshooting
> remove previous 60hz xorg restriction

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
- remove 60hz again for CRT users
> take resolution defaults unless set

- package/batocera/core/batocera-configgen/configgen/configgen/generators/hatari/hatariGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
closes - https://github.com/batocera-linux/batocera.linux/issues/8979
> allow hd rom type for hitari standalone

- board/batocera/allwinner/linux_patches/1001-H616-Full-Support-WIP.patch
- board/batocera/allwinner/linux_patches/1002-H616-thermal-fix.patch
- board/batocera/allwinner/linux_patches/1003-opz2-leds-fix.patch
- package/batocera/boot/uboot-multiboard/common-h616/allwinner-h616-THS-workaround.patch
Also removes orangepi changes preventing A/V out working (WIP right now).
> Fix H616 thermal issues (uboot+dtsi) and opz2 leds

- package/batocera/core/batocera-scripts/scripts/batocera-systems
fixes - https://github.com/batocera-linux/batocera.linux/issues/9191
> add bios required for Supr'A'can

- package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
- package/batocera/emulators/wine/wine-proton/wine-proton.mk
@nadenislamarre remember to rebuild wow64
> proton bump

- package/batocera/emulators/retroarch/retroarch/024-achievementcall.patch
> ra cheevos script

- package/batocera/controllers/xpadneo/xpadneo.mk
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
- adjust es_input.cfg accordingly
> bump xpad neo for sdl 2.28

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/9310
> fix swanstation controller config

- package/batocera/emulators/dosbox-x/004-arrach-MT32.patch
> fixes mt32 support for arm64 devices

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Add SPU block size and power saving CPU pre-emptions settings to ES
> ES settings for rpcs3 update

- package/batocera/firmwares/alllinuxfirmwares/alllinuxfirmwares.mk
- urgent amd zenbleed microcode update
- fix amd gpu flickering on some gpus
- intel bt ax device updates
- numerous other firmware update
> bump firmware

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- player1 hotkey now brings up the quick menu
> changed analog mode to hotkey+l2

- package/batocera/core/batocera-configgen/configgen/configgen/generators/thextech/thextechGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> TheXTech: add options, fix saves location

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Combined Controller Type with Controller Pak settings into submenus for each controller for better ES menu organization.
> Organize N64 libretro es_features.yml

- package/batocera/core/batocera-scripts/scripts/batocera-info
- package/batocera/gpu/vulkan/vulkan-tools/S55vulkaninfo
- package/batocera/gpu/vulkan/vulkan-tools/vulkan-tools.mk
- adjust info to a more logical flow
> bring back vulkan info

- package/batocera/core/batocera-configgen/configgen/configgen/generators/gzdoom/gzdoomGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/ports/gzdoom/0001-Fix-file-paths.patch
- package/batocera/ports/gzdoom/gzdoom.hash
- package/batocera/ports/gzdoom/gzdoom.mk
* add vulkan api option
* fix rpi4 not setting ES
* fix bezels showing when 16x9
* vulkan is not always better...
> gzdoom updates

- batocera-Changelog.md
- package/batocera/emulators/bigpemu/bigpemu.mk
> bigpemu to v107

- batocera-Changelog.md
- package/batocera/emulators/duckstation/duckstation.mk
> bump duckstation to Aug 4, 2023 build

- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/9483
> fix model2emu ratio, default 4:3

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> more model 2 enhancements

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- Skylanders Portal
- Infinity Base
> add hotkeys for dolphin usb device support

- package/batocera/core/batocera-configgen/configgen/configgen/generators/hurrican/hurricanGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/tyrian/tyrianGenerator.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/ports/tyrian/002-paths.patch
- package/batocera/ports/tyrian/tyrian.keys
- package/batocera/ports/tyrian/tyrian.mk
> Tyrian: compatibility with the Content Downloader package

- package/batocera/core/batocera-configgen/configgen/configgen/generators/vpinball/vpinballGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/vpinball/002-default-path.patch
- package/batocera/emulators/vpinball/vpinball.keys
- package/batocera/emulators/vpinball/vpinball.mk
- nicer vpinball exit
- updated info on paths etc
> - get pinmame roms working

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
I don't know since when it's working _for few games_ but it's working. Singleplayer only. Tested with my gun.
> Fixing light gun controls on lr-swanstation

- batocera-Changelog.md
- package/batocera/core/batocera-scripts/scripts/batocera-info
- package/batocera/core/batocera-system/batocera-boot.conf
- package/batocera/emulationstation/batocera-emulationstation/xorg/xinitrc
- batocera-info to show the 2nd GPU varsion too.
> automatically detect two gpu's & set environment variables accordingly.

- package/batocera/emulators/openmsx/002-filepool.patch
fixes - https://github.com/batocera-linux/batocera.linux/issues/8996
> set where the bios files should be

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
fixes - https://github.com/batocera-linux/batocera.linux/issues/8990
> enable gamecube boot logo

- package/batocera/core/batocera-scripts/scripts/batocera-services
- package/batocera/core/batocera-scripts/scripts/batocera-version
Add "u" indicator to "batocera-version --extra" if custom user services are enabled
> Add custom user services indicator

- package/batocera/utils/batocera-steam/batocera-steam
That allow controller support by default in this mode.
> Run steam in Big Picture mode.

- board/batocera/x86/linux_patches/0001-ALSA-cs35l41-Use-mbox-command-to-enable-speaker-outp.patch
- board/batocera/x86/linux_patches/0002-ALSA-cs35l41-Poll-for-Power-Up-Down-rather-than-wait.patch
- board/batocera/x86/linux_patches/0003-ALSA-hda-cs35l41-Check-mailbox-status-of-pause-comma.patch
- board/batocera/x86/linux_patches/0004-ALSA-hda-cs35l41-Ensure-we-correctly-re-sync-regmap-.patch
- board/batocera/x86/linux_patches/0005-ALSA-hda-cs35l41-Ensure-we-pass-up-any-errors-during.patch
- board/batocera/x86/linux_patches/0006-ALSA-hda-cs35l41-Move-Play-and-Pause-into-separate-f.patch
- board/batocera/x86/linux_patches/0007-ALSA-hda-hda_component-Add-pre-and-post-playback-hoo.patch
- board/batocera/x86/linux_patches/0008-ALSA-hda-cs35l41-Use-pre-and-post-playback-hooks.patch
- board/batocera/x86/linux_patches/0009-ALSA-hda-cs35l41-Rework-System-Suspend-to-ensure-cor.patch
- board/batocera/x86/linux_patches/0010-ALSA-hda-cs35l41-Add-device_link-between-HDA-and-cs3.patch
- board/batocera/x86/linux_patches/0011-ALSA-hda-cs35l41-Ensure-amp-is-only-unmuted-during-p.patch
> add cs35l41 patches

- package/batocera/utils/flatpak/steam.keys
Tested work
Fix [9665](https://github.com/batocera-linux/batocera.linux/issues/9665)
Wait for user test
> Steam Fix Game Exit

- package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.hash
- package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.mk
> Bump VKD3D

- package/batocera/core/batocera-configgen/configs/configgen-defaults-h3.yml
Superseed PR https://github.com/batocera-linux/batocera.linux/pull/7096
> Disable HUD support N64 on Allwinner H3 hardware (including CHA)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/citra/citra.mk
- adds vulkan option
- adds async shader compilation
- tidy some ES options
> fix citra segfault

- package/batocera/core/batocera-configgen/configgen/configgen/utils/gunsUtils.py
> fix namco2x6 precalibration

- package/batocera/emulators/vita3k/003-drop-xdg-desktop-portals.patch
- package/batocera/emulators/vita3k/vita3k.mk
> fix vulkan with vita3k

- board/batocera/scripts/post-image-script.sh
Per @Ntemis request 
Tag @nadenislamarre for review
> Alter post-image-script to always include subtarget in image names 

- package/batocera/emulators/ppsspp/psp.ppsspp.keys
Fix for #9974 (tested on OGA + regression testing on x86_64)
> Fix ppsspp quit on OGA

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix cemu info on button combo for switching screens

- board/batocera/x86/linux_patches/24-ayn-loki-zero-headset-fix.patch
@nadenislamarre ok for v38 too
> fix ayn loki zero headphone jack volume

- package/batocera/firmwares/firmware-radxa-rkwifibt/firmware-radxa-rkwifibt.mk
> fix firmware dir

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Added Feature to turn off onscreen display messages for dolphin-emu.
> Added Feature to turn off onscreen display message for dolphin-emu

- package/batocera/core/batocera-configgen/configgen/configgen/generators/raze/razeGenerator.py
- arm = gl_es=true
- x86 = gl_es=false
> fix opengl options in raze

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py
> fix aspect_ratio_index

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fixed bug that prevented setting from working. Also edited values.
> bugfix-rpcs3-cpupreemptivecountsetting

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- helps with lower-end systems sometimes
> add audio driver options

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Fix #10144
@dmanlfc can you double check and merge if OK? It's basically half a revert of #10045
> Fix #10144

- package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
- package/batocera/emulationstation/batocera-es-system/batocera-report-system.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
1. Removed duplicate entries in yml files
2. Moved same_cdi to configgen x86 since it's only built for that
3. Fixed condition for `requireAnyOf`
> Minor fixes for configgen and systems generation

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Revert tyrian portion of #10153 - superseded by #10178
> Revert tyrian bezel features

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Also fixed typo in duckstation
> Fix typo in es_features for mupenplus-next

- package/batocera/core/batocera-scripts/batocera-scripts.mk
- package/batocera/core/batocera-scripts/scripts/batocera-get-nvidia-list
- package/batocera/gpu/batocera-nvidia/batocera-nvidia
@nadenislamarre please check you're happy with this.
updating the list file for nvidia users will be helpful for driver compatibility between versions.
> get the updated nvidia production.list file

- board/batocera/rockchip/rk3399/fsoverlay/etc/init.d/S95touchscreen
Added a sleep when more roms are loaded + fixed indent
> RG552 touch screen

- package/batocera/gpu/batocera-amd/S05amd-check
- remove dual card which is handled by xinitrc now
> tidy amdgpu code detection

- board/batocera/x86/fsoverlay/etc/init.d/S05nvidia
- board/batocera/x86/fsoverlay/etc/init.d/S30checkprime
- board/batocera/x86/fsoverlay/etc/init.d/S92nvdownload
- package/batocera/core/batocera-scripts/scripts/batocera-get-nvidia-list
- package/batocera/emulationstation/batocera-emulationstation/xorg/xinitrc
- package/batocera/gpu/batocera-nvidia-lists/batocera-nvidia-lists.mk
- package/batocera/gpu/batocera-nvidia/batocera-nvidia
- package/batocera/gpu/batocera-nvidia/batocera-nvidia.mk
- fix nvidia.log on first boot
- reduce card name where we can
- update nidia lists
> - try to speed up nv card detection

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> scummvm - fix tv2x filter

- package/batocera/firmwares/alllinuxfirmwares/alllinuxfirmwares.mk
> link to newer firmware

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-scripts/scripts/batocera-systems
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- add fast boot option for lr-pcsx2
> simplify ps2 bios requirements

- package/batocera/utils/batocera-wine/batocera-wine
Fix the use of libs depending on the wine folder used
> Minor Fix batocera-wine

- board/batocera/x86/fsoverlay/etc/init.d/S30checkprime
- package/batocera/gpu/batocera-amd/S05amd-check
should fix - https://github.com/batocera-linux/batocera.linux/issues/10461
> expand detected card types

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Updated descriptions and values in es_features.
Updated/Fixed logic handling both sensitivity and deadzone more accurately.
Fixes issue with how the ES sensitivity settings would be inversed from expected behavior.
(lower sensitivity ES settings resulted in more responsive joystick movements and vice versa)
Behavior now correctly matches user expectations.
> Mupen64Plus-Deadzone-Sensitivity-Update

- batocera-Changelog.md
- package/batocera/core/batocera-scripts/scripts/batocera-powermode
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Add powermode settings to changelog. Fixed typo in es_features + better description of setting(specified that it effects in-game power profile/usage). Code cleanup-removed obsolete unused variable passed to handle_powermode function that no longer needed it.
> Power Mode add changelog / es features typo fix and better description

- package/batocera/emulators/vpinball/vpinball.mk
- package/batocera/libraries/libpinmame/libpinmame.mk
Updates for vpinball and libpinmame to fix broken mech support
> bump vpinball and libpinmame

- package/batocera/core/batocera-configgen/scripts/powermode_launch_hooks.sh
- package/batocera/core/batocera-system/sysconfigs/bcm2711/batocera.conf.Raspberry_Pi_4_Model_B_Rev_1_4
- package/batocera/core/batocera-system/sysconfigs/bcm2837/batocera.conf.Raspberry_Pi_3_Model_B_Plus_Rev_1_3
- use user settings if power mode not set
> run performance by default

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/core/batocera-configgen/configs/configgen-defaults-bcm2712.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/dolphin-emu/dolphin-emu.mk
> bump dolphin-emu to 5.0-20619

- package/batocera/controllers/fusion-lightguns/fusion-lightguns-add
Per request by the maker
(waiting for confirmation before OK to merge)
> Update Fusion Lightgun mapping

- package/batocera/controllers/aelightgun/virtual-aelightgun-add
Please stop using this lightgun
(Missing `UP` and `DOWN` buttons)
> Fix AE Lightgun mapping

- .github/ISSUE_TEMPLATE/bug_report.yml
- Language clarity
- Replace expired Discord invite link
> Fix issue template

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/support_request.yml
Provide dummy templates to minimize the number of users following the "Don't see your issue here? Open a blank issue" link
> Add dummy github issue templates

- board/batocera/fsoverlay/etc/init.d/S11share
> Support CONFIGS@ mount point in S11share

- board/batocera/fsoverlay/etc/init.d/S08connman
> Support open wifi network without passphrase

- package/batocera/core/batocera-scripts/scripts/batocera-upgrade
> Provide warning if upgrade changes board

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Adding controller mapping for Asus Gamepad TV500BG Wireless (Bluetooth) Gaming Controller
> Add Asus Gamepad TV500BG

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
START = (SHARE) button
SELECT = (OPTIONS) button
+L3 & R3
Physical L2 & R2 buttons are unmapped.
> update G29 wheel mapping

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Based on real world data, useful for experienced users
> Add more wheel values to ES

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> revert xenia back to lutris until proton issues resolved:

- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> add logitech driving force steering wheel

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
> Scrape ScummVM from "scummvm" platform instead of "pc"

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> Update mapping for gamepad on ps7000

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> Add padtokeyboard feature to lr-mame

- package/batocera/emulators/vpinball/vpinball.mk
- package/batocera/libraries/libdmdutil/libdmdutil.mk
- package/batocera/libraries/libpinmame/libpinmame.mk
This PR updates pinmame, libdmdutil, and vpinball.
libdmdutil has some important updates that improve Pixelcade communication.
> vpinball: update pinmame and libdmdutil deps

- batocera-Changelog.md
> remove duplicate

- batocera-Changelog.md
Because nobody will know otherwise
> tiny update

- package/batocera/core/batocera-configgen/configgen/configgen/generators/vpinball/vpinballGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
continuation of #10887 (closed while trying to resolve conflicting files :-( )
*Configgen is on by default
*integrated logging from dmanlfc when duplicates are present in the VPinballX.ini
Ready to merge imo
> vpinball configgen v7

- batocera-Changelog.md
- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> add g923 ps4/pc wheel

- batocera-Changelog.md
- package/batocera/emulators/pcsx2/ps2.pcsx2.keys
Patch from @zognic in Discord ES request
> Add hotkey+south padtokey for pcsx2 OSD menu

- .github/ISSUE_TEMPLATE/bug_report.yml
- Add wiki link for creating a support file
- Tweak the version placeholder
- GPU "dedicated" -> "discrete"
- Add "Other" as a GPU brand option
> Tweak GitHub issue template

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
> fix gc wheel

- batocera-Changelog.md
- configs/batocera-board.common
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- package/batocera/emulationstation/batocera-es-system/locales/vi_VN/batocera-es-system.po
@nadenislamarre I'll let you merge if this looks good.
> Add Vietnamese language

- package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds es feature so user can control if vsync is off or on.
Default is on.
> XEMU - Add ES Feature Vsync

- board/batocera/amlogic/s905/lepotato/genimage.cfg
- board/batocera/amlogic/s905/odroidc2/genimage.cfg
- board/batocera/amlogic/s905/p201/genimage.cfg
- board/batocera/amlogic/s905/vim/genimage.cfg
- board/batocera/amlogic/s905gen2/khadas-vim2/genimage.cfg
- board/batocera/amlogic/s905gen2/radxa-zero/genimage.cfg
- board/batocera/amlogic/s905gen3/khadas-vim3l/genimage.cfg
- board/batocera/amlogic/s905gen3/odroidc4/genimage.cfg
- board/batocera/amlogic/s922x/gtking/genimage.cfg
- board/batocera/amlogic/s922x/gtkingpro/genimage.cfg
- board/batocera/amlogic/s922x/odroidn2/genimage.cfg
- board/batocera/amlogic/s922x/odroidn2plus/genimage.cfg
- board/batocera/amlogic/s922x/ogu/genimage.cfg
- board/batocera/amlogic/s922x/vim3/genimage.cfg
- board/batocera/amlogic/s922x/zero2/genimage.cfg
This reverts commit 4c7dd134dcb129fb1b05720d309e790497a611e7.
> Revert "Latest 2023/4 mainline U-boot change the way bootloader functions on amlogic socs"

- package/batocera/core/batocera-configgen/configgen/configgen/utils/wheelsUtils.py
(temporary fix for v39)
trying to fix dc shifter
trying to fix saturn mapping
> fix some wheel mapping

- batocera-Changelog.md
- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> add G27 Racing Wheel support

- board/batocera/rockchip/rk3588/fsoverlay/etc/init.d/S10rk3588
- package/batocera/firmwares/firmware-radxa-rkwifibt/firmware-radxa-rkwifibt.mk
fixes - https://github.com/batocera-linux/batocera.linux/issues/10939
testing...
> fixes Khadas Edge 2 Bluetooth

- package/batocera/emulators/redream/redream.hash
- package/batocera/emulators/redream/redream.mk
Copied from  #11053 / #11064, but without switchres (that needs a different PR)
> Fix redream (from #11053 / #11064)

- package/batocera/core/batocera-system/Config.in
Database dependency BR2_PACKAGE_KODI_MYSQL
> kodi: clean duplicate dependency

- package/batocera/controllers/aelightgun/virtual-aelightgun-add
- package/batocera/controllers/aimtrak-guns/aimtrak-add
- package/batocera/controllers/gun4ir-guns/virtual-gun4ir-add
- package/batocera/controllers/guncon/guncon-add
- package/batocera/controllers/sinden-guns/virtual-sindenlightgun-add
- package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-add
Just to want it more clear for the future.
Has a tiny fix (need to test) for GunCon2 mapping to avoid duplication (middle, right and 1). @Redemp
> Clean up lightguns mapping

- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/utils/batocera-wine/batocera-wine
- my OCD kicked in, refactored too
> allow a custom wine runner in /userdata/system/wine/custom

- Makefile
You can get statistics on the cache (its size, number of hits, misses, etc.)
> Makefile: added -ccache-stats option

- batocera-Changelog.md
- package/batocera/controllers/guncon3/guncon3-add
> update GunCon3 mapping

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinSYSCONF.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds es setting to change dolphin position for sensor bar.
> Dolphin Sensor Bar ES Setting

- batocera-Changelog.md
- board/batocera/fsoverlay/etc/init.d/S12populateshare
> Fix Kodi settings lost on upgrades

- board/batocera/scripts/post-image-script.sh
- also shorten then name when possible
> fix build label with tr change

- board/batocera/amlogic/s922x/ogu/boot/boot.ini
- board/batocera/amlogic/s922x/ogu/boot/extlinux.conf
- board/batocera/amlogic/s922x/ogu/build-uboot.sh
- board/batocera/amlogic/s922x/ogu/create-boot-script.sh
- board/batocera/amlogic/s922x/patches/uboot-ogu/uboot-000-ODROID-GOU-modify-lcd-logic-to-accomodate-kernel-6.x.patch
- board/batocera/amlogic/s922x/patches/uboot-ogu/uboot-001-fix-export-toolchain.patch
- board/batocera/amlogic/s922x/patches/uboot-ogu/uboot-002-odroidgo4-boot-sdcard-emmc.patch
- board/batocera/amlogic/s922x/patches/uboot-ogu/uboot-003-fix-name-dtb.patch
> gou: add uboot hardkernel

- package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/daphne/001-git-fix.patch
- package/batocera/emulators/daphne/003-SDL-fix.patch
- package/batocera/emulators/daphne/Config.in
- package/batocera/emulators/daphne/daphne.daphne.keys
- package/batocera/emulators/daphne/daphne.mk
- positioning with Wayland
- determine the video size & scale accordingly
- fix forced 4:3
- add bezels including sinden
> fix daphne:

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> libretro-Flycast offscreen reload button

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> add mesen lightgun support + changelog

- batocera-Changelog.md
- package/batocera/emulators/ruffle/ruffle.mk
> bump ruffle to 2024-03-28

- package/batocera/utils/batocera-wine/batocera-wine
i.e. ENV=MESA_EXTENSION_MAX_YEAR=2002
> allow adding environment variable to wine `autorun.cmd`

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/flatpak/flatpakGenerator.py
- package/batocera/utils/flatpak/flatpak.keys
- package/batocera/utils/flatpak/flatpak.mk
- package/batocera/utils/flatpak/steam.keys
- add evmapy keys file to exit flatpak
> fix flatpak running from Ports

- board/batocera/fsoverlay/etc/init.d/rcS
> fix bootlog timestamp

- package/batocera/libraries/libzedmd/libzedmd.mk
reconnect to ZeDMD if connection gets lost
> libzedmd v0.7.1

- batocera-Changelog.md
- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Might need https://github.com/scarburato/t150_driver to gain more features on this steering wheel. FFB is partially working (from feedback).
> add T150RS steering wheel support

- board/batocera/x86/fsoverlay/etc/init.d/S93amdtdp
- package/batocera/core/batocera-configgen/scripts/tdp_hooks.sh
- package/batocera/core/batocera-scripts/scripts/batocera-amd-tdp
- add logging
- allow up to 95 degrees
> update TDP setting logic

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- Block pad config if guns and `use_guns` are detected
- Adapt new mapping to recent upstream fix
- Add third player for 3 guns game
> fix lr-mame lightgun controls

- package/batocera/kodi/kodi20-resource-language-de_de/kodi20_resource_language_de_de.mk
- package/batocera/kodi/kodi20-resource-language-el_gr/kodi20_resource_language_el_gr.mk
- package/batocera/kodi/kodi20-resource-language-es_es/kodi20_resource_language_es_es.mk
- package/batocera/kodi/kodi20-resource-language-eu_es/kodi20_resource_language_eu_es.mk
- package/batocera/kodi/kodi20-resource-language-fr_fr/kodi20_resource_language_fr_fr.mk
- package/batocera/kodi/kodi20-resource-language-it_it/kodi20_resource_language_it_it.mk
- package/batocera/kodi/kodi20-resource-language-pt_br/kodi20_resource_language_pt_br.mk
- package/batocera/kodi/kodi20-resource-language-sv_se/kodi20_resource_language_sv_se.mk
- package/batocera/kodi/kodi20-resource-language-tr_tr/kodi20_resource_language_tr_tr.mk
- package/batocera/kodi/kodi20-resource-language-zh_cn/kodi20_resource_language_zh_cn.mk
- package/batocera/utils-host/xa/xa.mk
This PR fix some urls with http instead https also the xa version to 2.4.1, this were affecting rk3399 compilation
comments welcomed
> rk3399 compilations fix

- batocera-Changelog.md
- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> Add support for SV200 steering wheel

- package/batocera/core/batocera-splash/batocera-splash.mk
- package/batocera/core/batocera-splash/scripts/Ssplash-mpv
- mpv defaults to the first GPU card
- we now check which one to use
> fix splash not showing in certain conditions

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
Correct typo and add a better Singe example - i.e. Not ActionMax
> Update Daphne supported games

- package/batocera/core/batocera-configgen/configgen/configgen/generators/bigpemu/bigpemuGenerator.py
- fix widescreen
- yes modhack, we can change button configs later. let's get stock tested first...
> add bigpemu controller config

- batocera-Changelog.md
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/cemu/004-force-no-menubar.patch
- package/batocera/emulators/cemu/cemu.mk
- now supports wuhb extensions
> cemu to v2.0-82

- package/batocera/emulationstation/batocera-es-system/es_features.yml
- put into Power Options section
> make tdp a slider

- board/batocera/x86/fsoverlay/etc/init.d/S80leds
- package/batocera/core/batocera-scripts/scripts/batocera-led-effects
- package/batocera/core/batocera-system/batocera.conf
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- package/batocera/leds/ayn-platform/ayn-platform.mk
- move to standard values for future x86 handhelds
- ayn-platform is now RGB
> supported x86 handhelds can now use LED sliders to change colours in ES

- package/batocera/core/batocera-configgen/configgen/configgen/generators/scummvm/scummvmGenerator.py
- package/batocera/emulators/scummvm/scummvm.mk
- add mpeg, helps with other game cut scenes
- fix scummvm logging
> fix monkey island

- package/batocera/core/batocera-configgen/configgen/configgen/generators/vita3k/vita3kGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> disable vulkan for now

- board/batocera/x86/fsoverlay/etc/pm/sleep.d/99resume_wifi
- board/batocera/x86/fsoverlay/etc/pm/sleep.d/99tweak_controller
- package/batocera/core/batocera-scripts/scripts/batocera-amd-tdp
- package/batocera/core/batocera-splash/scripts/Ssystem-splash
- Add TDP values for the SteamDeck's
> update names due to preference for product name

- batocera-Changelog.md
- package/batocera/emulators/ppsspp/ppsspp.mk
- package/batocera/emulators/retroarch/libretro/libretro-ppsspp/libretro-ppsspp.mk
> revert ppsspp's to v1.17.1

- board/batocera/x86/boot/grub.cfg
- board/batocera/x86/boot/syslinux.cfg
> remove mitigations off flag causing sd-oled not to boot

- package/batocera/emulators/cemu/Config.in
- package/batocera/emulators/cemu/cemu.mk
- package/batocera/libraries/wxwidgets/wxwidgets.mk
> cemu to v2.0-83

- package/batocera/core/batocera-configgen/configgen/configgen/generators/hypseus_singe/hypseusSingeGenerator.py
- package/batocera/emulators/hypseus-singe/006-render-sinden-last.patch
- package/batocera/emulators/hypseus-singe/hypseus-singe.mk
- reduces the number of bezels
> render sinden last for controllable borders

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- set analog mode switching = hotkey
> set wizard to false

- package/batocera/core/batocera-configgen/configgen/configgen/generators/hypseus_singe/hypseusSingeGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- fix scanlines
- tidy options
> add bezel toggle option

- board/batocera/x86/patches/mesa3d/001-revert-radeonsi-shader-changes.patch
> fix amd shader pipeline again

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> pre-cache only works with vulkan

- batocera-Changelog.md
- package/batocera/emulators/pcsx2/pcsx2.mk
> pcsx2 to v1.7.5864

- package/batocera/emulationstation/batocera-es-system/es_features.yml
Fix submenu order in es features for wheels and lightguns
> fix wheels and lightguns es features order

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
hey my bad for not knowing `mameGenerator.py` code is duplicated in `libretroMAMEConfig.py`
I copied the coco autoload (#11706) code verbatim into libretroMAMEConfig and tested it with my entire coco configuration in the latest v40-dev.
I’m purposely not updating the Changelog as my request is to merge this into v40 if it’s not too late 🙏 (no biggie if it has to wait for v41)
I noticed immediately an apple2gs fix #8964 is only in lr-mame (not standalone MAME).  When the time is ripe, I’d like to be involved in the refactoring of the standalone MAME and lr-mame generators so they share the same code base (eg. enhanced autoload behavior) (and more fundamentally, separating MESS code by system so `libretroMAMEGenerator` is a subclass of `MAMEGenerator` (perhaps) or `cocoGenerator` is a …
> propagate coco autoload behavior from standalone MAME to lr-mame

- Config.in
- package/batocera/gpu/vulkan/vulkan-volk/Config.in
- package/batocera/gpu/vulkan/vulkan-volk/vulkan-volk.mk
> add vulkan-volk for vulkan-tools

- package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
- package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- expand boolean possible inputs
> make switch values look better in the gui

- batocera-Changelog.md
- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Everything was tested and it works.
Hotkey mapped on R3.
> add logitech driving force pro wheel support

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> add region and bios settings lr-flycast

- configs/batocera-board.common
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> Fix duplicate localized names.

- board/batocera/rockchip/rk3568/anbernic-rgxx3/fsoverlay/etc/udev/rules.d/99-adc-keys.rules
> remove second phantom controller - adc-keys

- board/batocera/fsoverlay/etc/init.d/S02resize
- don't remove the trigger unless successful
- throw an error if necessary
- refactored a bit too
> fix resize not fully working sometimes

- package/batocera/emulators/flycast/atomiswave.flycast.keys
- package/batocera/emulators/flycast/dreamcast.flycast.keys
- package/batocera/emulators/flycast/flycast.mk
- package/batocera/emulators/flycast/naomi.flycast.keys
- package/batocera/emulators/flycast/naomi2.flycast.keys
> fix flycast navigation

- package/batocera/core/batocera-scripts/scripts/batocera-info
- package/batocera/utils/batocera-battery-checker/batocera-battery-checker
update and optimized some of the code in batocare-info and batocera-battery-checker relating to getting battery percentage and remaining time.
> battery-update

- package/batocera/emulationstation/batocera-es-system/es_features.yml
https://github.com/batocera-linux/batocera.linux/pull/11926#issuecomment-2176920813
> rm orphaned comment in #11926 (from #11806)

- batocera-Changelog.md
- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
OK
Must be on 3-axis mode :
(Force button is the bottom red button, centered)
> add Ferrari GT Rumble Force Wheel support

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Pedals were malfunctioning. From feedback.
> fix t150rs pedals

- package/batocera/emulationstation/batocera-es-system/es_features.yml
I don't know how to english, sometimes.
> typo in hypseus singe ES adv settings (crosshair)

- package/batocera/core/batocera-configgen/configgen/configgen/generators/bigpemu/bigpemuGenerator.py
- package/batocera/core/batocera-resolution/scripts/recorder/batocera-record.xorg
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
fix refresh rate value
ensure bigpemu config converts floating point to an integer
> fix batocera record for user selection of encoder

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
This adds squashfs support to Snes-MSU1 and Satellaview
> Added squashfs to Snes-MSU1 and Satellaview (Thanks thwonp)

- package/batocera/emulators/moonlight-embedded/Config.in
- package/batocera/emulators/moonlight-embedded/batocera-moonlight
- package/batocera/emulators/moonlight-embedded/moonlight-embedded.mk
Accessing irtimmer/moonlight-embedded will now redirect to moonlight-stream/moonlight-embedded
> update moonlight-embedded git url

- Config.in
- package/batocera/controllers/nso-n64/Config.in
- package/batocera/controllers/nso-n64/nso-n64.mk
> add nso controller script to config

- batocera-Changelog.md
- package/batocera/emulators/pcsx2/007-center-notifications.patch
- package/batocera/emulators/pcsx2/pcsx2.mk
- sync SDL2 bump required for pcsx2
> bump pcsx2 & center notifications

- package/batocera/core/batocera-configgen/configgen/configgen/generators/hypseus_singe/hypseusSingeGenerator.py
> fix cliffhanger bezel

- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
Same hardware, different name.
> add revision of G920 steering wheel

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.basic
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.drm
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.tvservice
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.wayland-sway
- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
add 
display.reflection=x
display.reflection=y
display.reflection=xy
display.reflection=normal
in batocera.conf to change the reflexion
> xorg-reflection

- package/batocera/emulators/dolphin-emu/wii.dolphin.keys
- package/batocera/emulators/duckstation/psx.duckstation.keys
- package/batocera/emulators/flycast/atomiswave.flycast.keys
- package/batocera/emulators/flycast/dreamcast.flycast.keys
- package/batocera/emulators/flycast/naomi.flycast.keys
- package/batocera/emulators/mame/mame.mame.keys
- package/batocera/emulators/model2emu/model2.model2emu.keys
- package/batocera/emulators/pcsx2/ps2.pcsx2.keys
- package/batocera/emulators/retroarch/retroarch/libretro.keys
- package/batocera/emulators/rpcs3/evmapy.keys
- package/batocera/emulators/supermodel/model3.supermodel.keys
- package/batocera/emulators/vice/c128.vice.keys
- package/batocera/emulators/vice/c64.vice.keys
> fix light gun evmapy exit

- package/batocera/core/batocera-scripts/scripts/batocera-services
The two main changes:
1. Improve help text by including the `status` parameter and referencing the [newly updated docs](https://wiki.batocera.org/launch_a_script#services).
2. Unify formatting, make file layout consistent, remove dead code.
> Improve batocera-services

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
See ES part here:
https://github.com/batocera-linux/batocera-emulationstation/commit/8a29da53345b5a0918194bae9656dd8e491cf5f8
> Add custom relay server to libretro

- Makefile
There are currently two issues with the build on macOS I have addressed:
1. POSIX `find` does not have the `-printf` operator. Installing `findutils` from Homebrew puts GNU `find` on the user's path as `gfind`. I've added logic to check for `gfind` on macOS and produce an error if it doesn't exist.
2. macOS uses [Open Directory](https://en.wikipedia.org/wiki/Apple_Open_Directory) to store information about users rather than `/etc/passwd`. This means that `$HOME` is set to `/` in the container and the build of `host-ccache` fails when it tries to run `mkdir -p $HOME/.buildroot-ccache` and can't create `//.buildroot-ccache`. To work around this issue, I've changed the invocation of `docker run` to set `$HOME` in the container to match the host.
> fix Makefile for macOS

- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix wrong crosshair value duckstation

- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
Tested and confirmed working. New model of G920 (PID c262)
> add g920 revision

- package/batocera/controllers/wheels/hid-t150/001-hid-t150-fix-dangling-else.patch
On some custom kernel build, hid-t150 package will fail on -Wdangling-else
> hid-t150: fix dangling-else build error

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Disable bezels for mrboom proper aspect ratio, fixes #10484
> Disable bezels for mrboom proper aspect ratio, fixes #10484

- Makefile
I did a couple of things here:
* Fixed the docker build to only pull the docker image when needed
* Renamed some variables with more readable names
* Consolidated `$(DOCKER_CMD) $(MAKE_CMD)` to `$(MAKE_BUILDROOT)`
* Moved the echo suppression to the calling recipe
* Used buildroot's environment variables for download and ccache instead of overriding the user's settings
> clean up `Makefile` and fix docker build

- package/batocera/emulationstation/batocera-emulationstation/wayland/sway/sway-launch
i need to understand better before merging.
> rpi5 sway dri issue

- board/batocera/amlogic/a3gen2/linux_patches/005-fix-gcc13.patch
- board/batocera/amlogic/a3gen2/linux_patches/006-fix-mmc-sd-sdio.patch
Fix Werror
Fix slow eMMC, intermittent wlan and sd
> VIM4: gcc-13 fixes

- package/batocera/core/batocera-configgen/configgen/configgen/GeneratorImporter.py
- package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/Generator.py
- package/batocera/core/batocera-configgen/configgen/configgen/types.py
- package/batocera/core/batocera-configgen/configgen/pyproject.toml
> add typing for `Generator`

- package/batocera/utils/hotkeygen/hotkeygen.py
Issues addressed:
* No need to use `global gcontext` (or forgetting to do so) for the daemon
* Simplified arguments to action and events handlers
* Class uses `dataclass` with slots to reduce memory consumption
* Simplified `InputDevice` lookup when an event happens by keeping a map of file descriptors -> `InputDevice`:
```
event = self.input_devices[self.nodes_by_fd[fd]].read_one()
vs.
event = self.input_devices_by_fd[fd].read_one()
```
> refactor hotkeygen daemon functions into self-contained class

- package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Controllers.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Add rumble toggle for controllers.
Reorganized es settings for controls following same structure as recent dolphin reorganization.
> rpcs3 add rumble toggle / organize controls

- package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/evmapy.py
- package/batocera/core/batocera-configgen/configgen/configgen/utils/hotkeygen.py
This changes the `evmapy` class into a context manager that handles stopping itself internally. This also adds a context manager for setting and resetting the hotkeygen context that functions similarly.
> improve configgen evmapy and hotkeygen invocations

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Add missing dsp es setting for flycast libretro core. Also fixed typo.
> Add dsp es setting to flycast libretro core

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
Just cleaning up the code a bit
> n64-limitedhotkeys-cleanup

- package/batocera/core/batocera-configgen/configgen/configgen/generators/bigpemu/bigpemuGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
Tested and working.
Scripts modules improve games QOL (e.g.: analog controls, mouse look and no FPS cap in Alien vs Predator).
Screen filter was requested by a user for a more blurry effect.
> add scripts modules and screen filter bigpemu

- Config.in
- board/batocera/fsoverlay/etc/init.d/S11share
- board/batocera/fsoverlay/etc/init.d/S65values4boot
- package/batocera/core/batocera-system/Config.in
- package/batocera/utils/clevis/0001-bypass-required-program-checks.patch
- package/batocera/utils/clevis/Config.in
- package/batocera/utils/clevis/clevis.mk
https://discord.com/channels/357518249883205632/1292908716122964121/1292908716122964121
> Support LUKS for partition and disk encryption

- Config.in
- batocera-Changelog.md
- package/batocera/core/batocera-system/Config.in
- package/batocera/utils/fake-hwclock/Config.in
- package/batocera/utils/fake-hwclock/fake-hwclock.mk
Add fake-hwclock to save/restore system clock on machines without working RTC hardware
> Add fake-hwclock

- getPoFromWebsite.sh
Check environment variable BR2_BATOCERA_GETPOFROMWEBSITE and skip download of new po files if the value is n
> Make fetching po from website optional

- package/batocera/controllers/pads/keyboardtopads/99-keyboardtopads.rules
- package/batocera/controllers/pads/keyboardtopads/inputs/XGamingXArcade.vaa55.p0101.yml
- package/batocera/controllers/pads/keyboardtopads/keyboardToPads.py
Use your Tankstick in keyboard mode.
> Add X-Arcade Tankstick config to keyboardtopads

- getPoFromWebsite.sh
Reverts batocera-linux/batocera.linux#12802
> Revert "Make fetching po from website optional"

- package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.wayland-sway
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
- package/batocera/emulationstation/batocera-emulationstation/wayland/sway/config
- package/batocera/emulationstation/batocera-emulationstation/wayland/sway/sway-launch
- tidied some code
- fixed some config errors
> sway will now use the specified output for the primary video

- board/batocera/fsoverlay/etc/init.d/S08connman
- avoids random ip address all the time
> create the retroidpocket mac address off the serial number

- package/batocera/core/batocera-scripts/scripts/qcom-fan
@lbrpdx it works well under stress & keeps the noise down.
> adjust fan curve

- package/batocera/cases/pironman/005-fix-disk-details.patch
- now displays the percentage of /userdata
> fix pironman disk display

- package/batocera/ports/cgenius/003-fix-pad-order.patch
- package/batocera/ports/cgenius/cgenius.cgenius.keys
- add the quicksave & quickload mappings
> fix commander genius pad order

- batocera-Changelog.md
- package/batocera/emulators/hypseus-singe/singe.hypseus-singe.keys
My exit functionality wasn't there... for some reason.
...+ some changes in the log
> hypseus singe evmapy fix for guns

- package/batocera/core/batocera-configgen/configgen/configgen/generators/bigpemu/bigpemuGenerator.py
- package/batocera/emulators/bigpemu/jaguar.bigpemu.keys
- package/batocera/emulators/bigpemu/jaguarcd.bigpemu.keys
-add state loading & saving + screenshots
> fix bigpemu config location

- Config.in
- package/batocera/audio/wm8960-audio-hat/001-fix-for-bato.patch
- package/batocera/audio/wm8960-audio-hat/Config.in
- package/batocera/audio/wm8960-audio-hat/S12wm8960
- package/batocera/audio/wm8960-audio-hat/wm8960-audio-hat.mk
- package/batocera/core/batocera-system/Config.in
- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
- package/batocera/utils/rpigpioswitch/rpigpioswitch.mk
- fix Powerboard hat config
- handle the config better (needs a complete rewrite)
> fix missing WM8960 driver for compatible rpi's

- package/batocera/emulationstation/batocera-emulationstation/es_savestates.cfg
> add remaining compatible savestates emulators

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix old fbneo crosshair issue

- package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix - model 3 should use right trigger as accelerate

- batocera-Changelog.md
Just correcting here and there
> typos on changelog

- batocera-Changelog.md
> typo changelog

- batocera-Changelog.md
- package/batocera/emulationstation/batocera-emulationstation/xorg/xinitrc
> fix nvidia decoding with hybrid laptops

- package/batocera/core/batocera-scripts/scripts/batocera-usbmount
fix issue with potential of having race condition with sequential numbering
> fix batocera-usbmount [V41 or V42?]

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> gambette core: add game-specific palette option

- package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> enable DuckStation cheat list

- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Working out of the box, no driver added
Waiting for feedback...
> add g923 (xbox) steering wheel

- board/batocera/amlogic/a3gen2/patches/fbv/001-fbv-fix-black-screen.patch
Fixes build errors due to updated fbv
> vim4: Redo fbv patch for v42

- package/batocera/ports/catacombgl/catacomb.keys
> add missing CatacombGL control

- board/batocera/x86/fsoverlay/etc/X11/xorg.conf.d/20-amdgpu.conf
> add variable refresh rate support for modern amdgpu's

- package/batocera/gpu/batocera-nvidia/batocera-nvidia
Fix the link to the Nvidia 470 Legacy driver dynamic library.
> Fix nvidia470-legacy-driver

- package/batocera/core/batocera-configgen/configgen/configgen/generators/lindbergh/lindberghGenerator.py
lindberghGenerator.py revisited
> some guns improvements

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
**TESTED AND WORKING LIST ONLY**
There are many different games with different revisions, but I've trimmed them down to what's most compatible.
I've merged variants of each games, except initial D 4 & 5 series. Each revision has its own eeprom that is incompatible in between.
Hope this can be fixed with a card rw skip check in the future by upstraem devs.
> add and fix more lindbergh games info

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
It works, tested on 15 zipped games.
> add .zip support for libretro-virtualjaguar

- package/batocera/audio/zmusic/zmusic.mk
- zmusic: add dependency on fluidsynth
- bump buildroot for wayland-protocol deps
> Add some dependencies

- package/batocera/controllers/pads/hid-nx/0002-improved-player-led.patch
Backport #commit https://github.com/torvalds/linux/commit/928276075f169d36f34e751ea5c81dd24d3a6823 and #commit https://github.com/torvalds/linux/commit/5307de63d71d0b2303a8c645493a36021bedd800
> hid-nx: improve player led

- board/batocera/rockchip/rk3326/dts/rk3326-rg351v-linux.dts
- board/batocera/rockchip/rk3326/linux_patches/0010-rg351pv-battery.patch
- board/batocera/rockchip/rk3326/rk3326/boot/boot.ini
- board/batocera/rockchip/rk3326/rk3326/create-boot-script.sh
- configs/batocera-rk3326.board
- package/batocera/boot/uboot-odroid-goa/007-hwrev-rg351v.patch
- package/batocera/core/batocera-system/sysconfigs/rk3326/batocera.conf.Anbernic_RG351V
- package/batocera/core/batocera-triggerhappy/conf/rk3326/multimedia_keys_AnbernicRG351V.conf
Getting the RG351V back in the game
> RG351V initial PR

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
first merge https://github.com/batocera-linux/batocera-emulationstation/pull/1827
> (snes9x) add m.a.c.s. rifle support

- package/batocera/core/batocera-configgen/configgen/configgen/generators/lindbergh/lindberghGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/lindbergh-loader/lindbergh-loader.mk
> update lindbergh for the latest updates

- package/batocera/controllers/guns/retroshooter-guns/retroshooter-guns-add
> fix retroshooter

- package/batocera/kodi/kodi21-resource-language-de_de/kodi21_resource_language_de_de.mk
- package/batocera/kodi/kodi21-resource-language-es_es/kodi21_resource_language_es_es.mk
- package/batocera/kodi/kodi21-resource-language-fr_fr/kodi21_resource_language_fr_fr.mk
- package/batocera/kodi/kodi21-resource-language-pt_br/kodi21_resource_language_pt_br.mk
- package/batocera/kodi/kodi21-resource-language-zh_cn/kodi21_resource_language_zh_cn.mk
The older ones are already deleted on the servers and could not be downloaded
> Kodi language packs update

- package/batocera/utils/batocera-wine/batocera-wine
fix bug from my original PR  for .pc extension
https://github.com/batocera-linux/batocera.linux/pull/13194
> batocera-wine: fix SAVEDIR && SAVEFILES for .pc extension

- package/batocera/core/batocera-system/Config.in
and some clean up. Forgot to add the package.
> add XGunner package

- batocera-Changelog.md
- board/batocera/patches/clang/002-fix-toolchain-dir.patch
- package/batocera/emulators/rpcs3/014-gun-mapping.patch
- package/batocera/emulators/rpcs3/rpcs3.mk
> bump rpcs3 to 0.0.34-17438

- batocera-Changelog.md
- package/batocera/wine/dxvk-nvapi/dxvk-nvapi.hash
- package/batocera/wine/dxvk-nvapi/dxvk-nvapi.mk
- package/batocera/wine/dxvk/dxvk.mk
> dxvk to 2.5.3

- package/batocera/controllers/guns/xgunner-lightguns/Config.in
> fix xgunner

- batocera-Changelog.md
- package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Waiting for feedback...
Speedlink OK; Microsoft KO.
> add speedlink steering wheel (SL-6698)

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
> Fix G920 pedals

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
this was causing the bias x value to reset back to 0.
> remove orphan bias libretro

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
> Fix uncentered screen (bias) - LIBRETRO

- package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
This is the only device using shell scripts working for today. I'd say to remove the unused switches later - See the working one as example how to port.
> gpiod for shell, ONOFFSHIM working again

- package/batocera/emulationstation/batocera-es-system/es_systems.yml
We can use MSI-Packages as installers. I've managed to get this working
> Add MSI installers to Windows_installes

- package/batocera/ports/vkquake2/002-fix-quit.patch
- package/batocera/ports/vkquake2/quake2.keys
> add controller config for vkquake2

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
* Port the hard drive fix in #13058 (the first item) to MAME.
* unify one log message between libretroMAME and MAME
> port apple2 harddrive fix from libretroMAME to MAME

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Adds the input configuration for https://www.8bitdo.com/ultimate-2c-wireless-controller/
> Add joystick configuration for 8BitDo Ultimate 2C Wireless Controller

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
This USB controller supports afaict two players with 18 buttons each which differs in the device name and the usb model id.
P1:
```
P: /devices/pci0000:00/0000:00:08.3/0000:67:00.4/usb7/7-1/7-1.1/7-1.1.4/7-1.1.4.1/7-1.1.4.1:1.0/0003:0314:2201.0012/input/input32/event23
N: input/event23
S: input/by-id/usb-_MICREAL_USB_Controller1-event-joystick
S: input/by-path/pci-0000:67:00.4-usb-0:1.1.4.1:1.0-event-joystick
E: DEVLINKS=/dev/input/by-id/usb-_MICREAL_USB_Controller1-event-joystick /dev/input/by-path/pci-0000:67:00.4-usb-0:1.1.4.1:1.0-event-joystick
E: DEVNAME=/dev/input/event23
E: DEVPATH=/devices/pci0000:00/0000:00:08.3/0000:67:00.4/usb7/7-1/7-1.1/7-1.1.4/7-1.1.4.1/7-1.1.4.1:1.0/0003:0314:2201.0012/input/input32/event23
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: …
```
> Add joystick configuration for MICREAL USB Controllers

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
Same as https://github.com/batocera-linux/batocera.linux/pull/13662/ 
@lbrpdx Please merge
> ecwolf - spaces in filenames allowed

- package/batocera/utils/batocera-wine/batocera-wine
@nadenislamarre  or @dmanlfc Please review and merge if it's good.
I've added the `cp`-error control you suggested, thank you
- added requestFileSystem() as dev tool
- saveToUserdata some fixes and code cleanings
- better logging by using bash-builtin $FUNCNAME
- $FUNCNAME is used as array now
- some small bash-spelling fixes
> batocera-wine - error control, filesystem info

- package/batocera/emulators/lindbergh-loader/0001-evdev-add-technical-input-values.patch
- package/batocera/emulators/lindbergh-loader/0002-evdev-add-shake-special-event.patch
- package/batocera/emulators/lindbergh-loader/0003-evdev-add-abs-to-key-mapping.patch
- package/batocera/emulators/lindbergh-loader/lindbergh-loader.mk
- lindbergh build changes
- add back the evdev patches
> update to fix segfault

- package/batocera/core/batocera-scripts/scripts/batocera-amd-tdp
Values taken from:
- https://www.amd.com/en/products/processors/handhelds/ryzen-z-series/z1-series/z1-extreme.html
- https://www.amd.com/en/products/processors/handhelds/ryzen-z-series/z1-series/z1.html
- https://rog.asus.com/us/gaming-handhelds/rog-ally/rog-ally-2023/spec/
- https://rog.asus.com/us/gaming-handhelds/rog-ally/rog-ally-x-2024/spec/
> add ROG Ally TDP values

- package/batocera/ports/bstone/001-no-prompt-to-exit.patch
- package/batocera/ports/bstone/bstone.keys
- tweak some controller configs
> bstone don't prompt to exit

- package/batocera/core/batocera-configgen/configgen/configgen/generators/hypseus_singe/hypseusSingeGenerator.py
https://github.com/user-attachments/assets/ff4bb6e5-41c0-4aa9-946a-6f607750e8b8
> add formula for fast draw (hypseus singe)

- batocera-Changelog.md
> intel mediadriver to 25.1.4

- package/batocera/core/batocera-configgen/configgen/configgen/generators/mugen/mugenGenerator.py
commit https://github.com/batocera-linux/batocera.linux/commit/f533dbac35d148030bfae3fb0df2efa707dd26e3 is breaking again old mugen engine.
The key values are different in old mugen engine, and this is doing an assert on old mugen engine start.
This patch detect the engine version through [Video Win] section in mugen.cfg, and set correct key mapping.
Also, resolution of old mugen engine is 640x480, 4/3 only,  and if the resolution is higher or 16:9, the aspect ratio is not keeped and image is deformed. This patch is forcinf 640x480, keeping full screen with correct ratio
> mugen: fix generator for old mugen engine

- package/batocera/core/batocera-system/Config.in
- now supports opengl & vulkan
> enable dolphin on the rk3588

- board/batocera/fsoverlay/etc/profile.d/25-language.sh
- board/batocera/fsoverlay/etc/profile.d/26-keyboard.sh
- board/batocera/fsoverlay/etc/profile.d/50-system.sh
- package/batocera/core/batocera-scripts/scripts/batocera-save-overlay
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
- package/batocera/emulationstation/batocera-emulationstation/wayland/sway/config
- package/batocera/emulationstation/batocera-emulationstation/wayland/sway/sway-launch
set keyboard variables
remove from es-standalone
adjust sway keyboard to align to user choice
> set language variables earlier

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Adds a controller configuration for 8BitDo Ultimate 2 Wireless Controller (https://www.8bitdo.com/ultimate-2-wireless-controller/).
> Controller config for 8BitDo Ultimate 2 Wireless Controller

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dosboxstaging/dosboxstagingGenerator.py
- package/batocera/emulators/dosbox-staging/003-fix-config-path.patch
- package/batocera/emulators/dosbox-staging/dosbox-staging.mk
- fix config location
- fix custom config filename
> fix dosbox-staging build

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
> fix dolphin crosshair for light guns

- package/batocera/emulators/shadps4/shadps4.mk
> shadps4 0.8.0

- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
> Fix WonderSwan portrait/landscape rotation

- package/batocera/core/batocera-controller-overlays/batocera-controller-overlays.hash
- package/batocera/core/batocera-controller-overlays/batocera-controller-overlays.mk
> Added dice and fixed pico-8 controller overlays

- package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/hypseus_singe/hypseusSingeGenerator.py
> fix dolphin/hypseus configgen crosshair

- package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
Adds Integer scaling to EmulationStation Menu for PPSSPP
> Integer Scaling for PPSSPP

- board/batocera/qualcomm/sm8250/linux_patches/0019-drm-panel-panel-ddic-ch13726a-Add-dsi-init-comm.patch
Without this patch, stutter are happen in 240p Test Suite scrolling test.
> Fix micro stutter problem in RetroidPocket SM8250 platform

- batocera-Changelog.md
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/retroarch/libretro/libretro-ps2/libretro-ps2.mk
- fix fastboot option
- add rendering options
- fix lr aspect not hiding bezels
- fix graphics api
> libretro-ps2 to March 16 build

- package/batocera/wine/dxvk/dxvk.mk
- package/batocera/wine/wine-mono/wine-mono.mk
- package/batocera/wine/wine-tkg/wine-tkg.mk
ten, ten, tiger
dxvk 2.6.2
wine mono 10.1.0
> wine-tkg 10.10

- package/batocera/core/batocera-configgen/configs/configgen-defaults-bcm2712.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3588.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-sm8250.yml
- package/batocera/core/batocera-configgen/configs/configgen-defaults-sm8550.yml
- package/batocera/emulators/ymir/ymir.mk
> ymir 19th June

- batocera-Changelog.md
- package/batocera/emulators/hypseus-singe/hypseus-singe.hash
- package/batocera/emulators/hypseus-singe/hypseus-singe.mk
> update hyseus-singe to 2.11.5

- board/batocera/x86/fsoverlay/etc/init.d/S93amdtdp
- package/batocera/core/batocera-configgen/scripts/tdp_hooks.sh
- package/batocera/core/batocera-scripts/scripts/batocera-amd-tdp
- package/batocera/core/batocera-scripts/scripts/batocera-info
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/utils/ryzenadj/ryzenadj.mk
> update ryzenadj for strix point apu's

- package/batocera/kodi/kodi21-resource-language-de_de/kodi21_resource_language_de_de.mk
- package/batocera/kodi/kodi21-resource-language-el_gr/kodi21_resource_language_el_gr.mk
- package/batocera/kodi/kodi21-resource-language-es_es/kodi21_resource_language_es_es.mk
- package/batocera/kodi/kodi21-resource-language-eu_es/kodi21_resource_language_eu_es.mk
- package/batocera/kodi/kodi21-resource-language-fr_fr/kodi21_resource_language_fr_fr.mk
- package/batocera/kodi/kodi21-resource-language-it_it/kodi21_resource_language_it_it.mk
- package/batocera/kodi/kodi21-resource-language-pt_br/kodi21_resource_language_pt_br.mk
- package/batocera/kodi/kodi21-resource-language-sv_se/kodi21_resource_language_sv_se.mk
- package/batocera/kodi/kodi21-resource-language-tr_tr/kodi21_resource_language_tr_tr.mk
- package/batocera/kodi/kodi21-resource-language-zh_cn/kodi21_resource_language_zh_cn.mk
updates the kodi language pack urls
> fix kodi languages

- package/batocera/core/batocera-scripts/scripts/batocera-shutdown
- package/batocera/emulationstation/batocera-emulationstation/S31emulationstation
- package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
- clamp max frequency down on fake standby
- add suspend & resume functions for S31emulationstation
- check if a game is running before trying to fake standby
> more fake standby tweaks

- package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife
* uses new S31emulationstation switches for kodi
* return codes (usage for several scripts possible)
* uses hotkeygen --exit for standard exit
* uses timer to wait for exiting emulators, 5s is standard
* .... just optimized the whole code
history in https://github.com/batocera-linux/batocera.linux/pull/14180
---
Well tested so it should be suitable for v42
> optimized es-swissknife

- package/batocera/emulators/vpinball/batocera-vpx-scraper.py
- package/batocera/emulators/vpinball/vpinball.mk
Separate script, not part of ES, needs some testing before a tighter integration.
> `batocera-vpx-scraper` script for vpinball tables scraping

- package/batocera/core/batocera-scripts/batocera-scripts.mk
- package/batocera/core/batocera-scripts/scripts/batocera-xtract
inspired by an idea from *brunoeduardobrasil* by an discord-chat.
* expanded to a universal-extraction solution
*  adds function arhive files for deserted **Extract here / Extract to ...** context menus PCmanFM
* minimal code changes and no need for extra packages
* toolset itself is useable for every platform
* more to come...
> add: Archive extractor + PCmanFM integration

- package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
I got a couple of 8bitdo micros and to my surprise there was no configuration for it yet.
So this PR adds support for it.
[Product page](https://www.8bitdo.com/micro/)
> 8bitdo micro input config

- package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulators/amiberry/amiberry.mk
Fix Amiberry path and data init
Add UAE configuration as valid roms
Add more Keyboard Options
> Fix Amiberry Path and add more ES features

- package/batocera/looks/hypseus-singe-bezels/hypseus-singe-bezels.mk
1 game added (tierras)
https://github.com/batocera-linux/batocera-emulationstation/pull/1954
> bump hypseus bezel

- batocera-Changelog.md
- package/batocera/emulators/xemu/xemu.hash
- package/batocera/emulators/xemu/xemu.mk
- https://github.com/xemu-project/xemu/issues/2301
- vulkan rendering fixes
> xemu to v0.8.96. fixes opengl slowdown regression

- batocera-Changelog.md
libretro is always lowercase.
fixed bunch of core/emu/dep names.
added few changes/fixed not mentionned in changelog
> changelog preparation for v42 release

- package/batocera/core/batocera-configgen/configgen/configgen/generators/azahar/azaharGenerator.py
- package/batocera/emulationstation/batocera-es-system/es_features.yml
enabled by default, disable to launch some games (will crash if enabled) e.g.: Kirby games
> give workaround to help some 3ds game to launch

- batocera-Changelog.md
vpinball and Steam Deck LCD are blocking the release
> Update release date in changelog to October 2025
