package/batocera/emulationstation/batocera-es-system/es_systems.yml
Is not work for NeoGeo CD
Is only for old true rip support by NeoCD.
And LR have been remove the rom support from FBNeo : 
https://github.com/libretro/libretro-database/blob/master/metadat/redump/SNK%20-%20Neo%20Geo%20CD.dat
That make confusion for users this core not work anymore for Neo Geo CD now.
=> Remove FBNeo for NeoGeo CD

Config.in, board/batocera/fsoverlay/etc/udev/rules.d/99-wiimote.rules, package/batocera/controllers/wiimotes-rules/99-wiimote.rules, package/batocera/controllers/wiimotes-rules/Config.in, package/batocera/controllers/wiimotes-rules/virtual-wii-mouse-bar-add, package/batocera/controllers/wiimotes-rules/wiimotes-rules.mk, package/batocera/core/batocera-system/Config.in
no more dolphin bar required, only a ir, so only one dolphinbar plugged
on tv for example for all wii, or a standard wiibar or a candle
=>>>>>> needs controllers.wiimote.mode=gun in batocera.conf
=> virtual dolphin bar (called virtual-wii-mouse-bar)

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Added Mesen as a supported emulator for famicom disk system
=> Add Mesen to FDS

board/batocera/raspberrypi/boot/config_mesa3d.txt, board/batocera/raspberrypi/boot/config_vcore.txt
-pi4 is no longer needed in vc4-kms-v3d in RPI4
=> rpi: minor tweaks in config.txt

batocera-Changelog, package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Couple of small changes:
- Adds an option for the PPU mode (LLVM Recompiler, Dynamic Interpreter, Static Interpreter)
- Adds the Discard Vertex Cache option (Fixes flickering graphics in certain games like Scott Pilgrim & Bomberman Ultra)
There was also a placeholder for setting the aspect ratio. After looking at the option, it only supports 4:3 or 16:9. I added code to check the resolution, and if the screen is 16:10 (Steam Deck & some monitors) or wider, it will pick 16:9, otherwise it will pick 4:3. This can be overridden with the existing config options, it's only used if set to auto.
=> RPCS3 Additions

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
https://docs.retroachievements.org/Rich-Presence/
This setting has been available in Retroarch since middle of 2020
ES UI setting PR https://github.com/batocera-linux/batocera-emulationstation/pull/1181
=> add cheevos_richpresence

board/batocera/fsoverlay/etc/init.d/S08connman, package/batocera/core/batocera-scripts/scripts/batocera-wifi
Odroid Go Advance still has wifi enable/disable issue.
1. Sometimes wifi is still connected when wifi disabled and device rebooted.
2. Enabling and disabling wifi is not stable on Odroid Go Advance. Sometimes wifi actually works when disabled and not work when enabled.
This PR should always fix 1. issue and mostly fix 2. issue.
=> Better fix for wifi enable/disable

batocera-Changelog, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
* Adds a VSync option to standalone MAME. Due to the way MAME works, this may result in dropped frames, but fixes screen tearing.
* There is a second option, "synctorefresh," that runs the game at the screen's exact refresh rate. This is designed for screens with custom or arcade-specific refresh rates. It is currently not listed in the options as in most cases turning it on will result in the game running at nearly unthrottled speeds and being unplayable. I did leave the code in place to enable it if added to batocera.conf manually (mame.syncrefresh=1) for the edge cases where it may be useful, like CRT users. We don't have an easy way to enable this otherwise.
I can re-enable that option in es_settings.yml, but it would very likely result in support requests when it doesn't behave as …
=> Add MAME VSync

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
The default setting for this core is not to have this setting enabled.
Having this setting enabled by default causes visual glitches in certain games. Most notably, Sonic the Hedgehog's title screen and underwater sections.
Glitched title screen (when this setting is enabled):
How it's meant to look (when this setting is disabled):
=> change default no sprite limit to disabled in genesisplusgx

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
There was a typo loading the custom config setting, causing it to be overwritten on launch. This fixes it.
=> Fix lr-mame custom config

package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject
This PR adds an option of  `install all` to `batocera-es-thebezelproject` to install the bezels for the entire system by looping over all locally available systems (gleaned from the `list` command) and calling `install` for each.
For people like me with lots of systems, this is MUCH faster than iterating over each system one by one manually either on the commandline or in the UX. Additionally, since the `list` command shows `[I]` when **any** bezel is installed, this option makes it much easier to just make **one** script call to address when ROMs are added, removed, or renamed.
Personally, after a big ROM purge or addition, I just call `remove all` followed by `install all` to make sure there are no orphaned bezels.
Sample output:
```
29 local system(s) found.
[3ds] 31 ROMs found
[3ds] …
```
=> Adding support for installing all local systems to batocera-es-thebezelproject

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
It seems that there are situations where only one of these conditions are true. We should veer on the side of allowing the user to manually use RetroArch if they only set the shader set to none.
=> fix "none" shader set behaviour

package/batocera/emulationstation/batocera-es-system/es_systems.yml
proposal by DarkNior. Would be preferable to leave as a group not checked by default.
=> group atari800 + xegs as atari8bit

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
It's concerning that it's overwriting an already existing config, but that one was just plain wrong. Has something happened to cause Batocera to start interpreting controls from controllers in a different order? I've noticed other controllers also acting like they have different mappings (like the Xbox 360 controller config for the 8bitdo BT adapter).
If it were just a case of "controller is in a different input mode", then why wouldn't its GUID change? Was it just a coincidence that other controllers started playing up around the same time too?
The old config didn't have Z and C bound (in this case, I just bound them to L2 and R2) so maybe it's just a case of an old config that's been forgotten.
=> amend 8bitdo M30 gamepad input.cfg (please read desc!)

package/batocera/core/batocera-configgen/configgen/configgen/generators/sh/shGenerator.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
No use sh is linked to dash
Use bash for improve compatibility
Add Squashfs
Use run.sh for squashfs in some because you can have several "sh" files in the same game folder.
This allows you to launch the desired sh.
Have adding information in wiki : https://wiki.batocera.org/disk_image_compression#squashfs
=> Add Squash on Ports

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpizero2.yml
Fixes the slowdown issue reported by Vininess on the forum: https://forum.batocera.org/d/7679-raspberry-pi-zero-2w-ui-low-frame-lag
Considering the RPi Zero 2 is even weaker than the Rpi 3 which itself has 720p as its max default resolution, this seems like a no-brainer.
I am curious as to why the ratio is set to 4/3, and the "smooth" is set to off. Seems odd. No comment explaining?
=> add default res of 720p to rpizero2 as well

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Don't keep more than 10 adapted bezel files as they stack up in /tmp, which is tmpfs -- especially for SBCs with low RAM.
=> More bezel caching optimizations

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
This fixes three issues.
1) Eliminates the D-Pad Mode workaround by pulling the values for the D-Pad when setting directional controls. This needs to be tested on a controller where the D-Pad maps as buttons, like the DS3. It should work, but I don't have a controller that does that to test with. This also adjusts using the buttons as right stick (for playing twinstick games on a controller with no sticks) to make sure they map to the correct positions.
2) LR-MAME was inverting most of the buttons - a/b, x/y, l2/r2, and l3/r3 (strangely, not l/r) were flipped, causing the control schemes to be different from expected & standalone MAME. All the settings were adjusted to account for this, if the problem gets resolved, they can be changed back by copying & pasting from MAME's generator.
3) …
=> MAME D-Pad & LR-MAME Controls Fix

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
Fix for the generator when using a non-system MESS rom (LCD, Plug n' Play).
=> Fix lr-mame gen for non-system MESS

package/batocera/core/batocera-scripts/scripts/batocera-systems
Missing a couple of files - 2 prevent Apple II from launching in MESS, the 3rd (votrax.zip) is listed as required but doesn't throw an error if missing.
=> Add missing Apple II MESS BIOS Files to Script

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
By default the functions we were using are the same.
- video_font_size=32
- menu_widget_scale_auto=true
The menu_widget_scale_auto option scales notifications to smaller screens and that way we free it up for the user to customize
=> On-Screen Display Notifications

package/batocera/utils/od-commander/001-swap-ab-controls.patch
OD commander has A and B switched by default, this patch makes it so it uses the same layout as the rest of Batocera does.
=> OD commander patch a/b controls

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rg552.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3288.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3399.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-s922x.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-tritium-h5.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/mame/mame.mk, package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
This is mostly to speed up compiling - MAME and LR-MAME now only compile once each instead of the previous 3x each. It's a full build that includes all supported MAME machines, so arcade, MESS, and MAMEVirtual are all one binary (just like downloading a precompiled version).
The generators and ES system files have been updated to replace LR-MESS & LR-MAMEVirtual with just LR-MAME. I tested arcade, systemless non-arcade ROMs (plugnplay & lcdgames), and a couple of MESS systems in both emulators, and it appears to all be working fine.
=> Condense MAME/LR-MAME

package/batocera/emulators/cemu/cemu/cemu.hash, package/batocera/emulators/cemu/cemu/cemu.mk
1.27.1 could not mount games to launch them properly
=> rollback cemu to 1.26.2

board/batocera/raspberrypi/rpi2/boot/config.txt, board/batocera/raspberrypi/rpi3/boot/config.txt, board/batocera/raspberrypi/rpi4/boot/config.txt
```
cma-512                 CMA is 512MB (needs 1GB)
cma-448                 CMA is 448MB (needs 1GB)
cma-384                 CMA is 384MB (needs 1GB)
cma-320                 CMA is 320MB (needs 1GB)
cma-256                 CMA is 256MB (needs 1GB)
cma-192                 CMA is 192MB (needs 1GB)
cma-128                 CMA is 128MB
cma-96                  CMA is 96MB
cma-64                  CMA is 64MB
```
=> rpi-config: Removing gpu_mem and adding cma

package/batocera/emulators/amiberry/amiberry.mk
https://github.com/BlitterStudio/amiberry/releases/tag/v5.3
=> bump: Amiberry to v5.3

batocera-Changelog, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-configgen/data/mame/messSystems.csv, package/batocera/core/batocera-scripts/scripts/batocera-systems, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/mame/mame.mk
Another 8-bit computer system added by request. Seems to be a bit flaky in lr-mame at the moment, if that doesn't resolve itself in lr-mame updates it can be restricted to standalone-only.
Also a small fix due to the removed/merged lr-mess & lr-mamevirtual cores - if either of those are set in batocera.conf, the generator will load the correct lr-mame instead.
=> Add VTech Laser 310 (MAME)

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Almost all officially supported Raze games we had working with our command line launcher but one of the games had a major bug that I created a [ticket ](https://github.com/coelckers/Raze/issues/690)for over in the Raze GitHub. We got a reply but no solution.
Thanks to Modhack again though for discovering the correct way to get this game working.
=> Fix route66 instructions in raze info text

package/batocera/emulationstation/batocera-es-system/es_systems.yml
the website linked into the _info.txt file of the dos system doesn't seem legit
> "Is it free? Is it legal?
> 
> We allow you to download old games for free, but we do not take any responsibility for downloads considered illegal in your country. Please try to buy the game first: GOG.com, Steam, Amazon or eBay may be selling your game. We never ask for credit card number, PayPal or anything. "
Also has traces of having games like mario is missing, pretty sure that's nukable material.
If I'm wrong, feel free to dismiss this PR **after** explaining how I was wrong
=> Removing potential problematic link

package/batocera/emulationstation/batocera-es-system/locales/fr/batocera-es-system.po
The Integer Scaling option was translated as "Mise à l'échelle (pixel perfect)", leaving the most important word, aka Integer, out of the translation.
This fixes it, while also not being too long.
=> Fix integer scaling french batocera-es-system.po

board/batocera/x86/fsoverlay/etc/acpi/events/powerbtn, package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-brightness, package/batocera/core/batocera-scripts/scripts/batocera-shutdown, package/batocera/core/batocera-triggerhappy/conf/multimedia_keys.conf
Tested on Anbernic Win600 but should work on Aya Neo and OneXPlayer as well.
- the "Windows" button (i.e. the "Windows" keyboard key) will cycle through brightness as there's no dedicated hardware button
- you can select a power suspend mode adding `system.suspendmode=suspend` or `system.suspendmode=hybrid` in `batocera.conf`. Hybrid saves a little more energy than suspend (but takes longer). Full "hibernate" mode doesn't work right now. As these options are only working on x86_64 handheld PC, not on ARM-based OGA/OGS/RG552 yet, I think it's better not to add an entry in ES menus at this point. 
This PR addresses a part of #6679
=> Handheld PC: brightness and suspend mode

package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml
Fix #6681 (except no bezel, this requires to be added in configgen)
=> Samcoupe: fix missing advanced options, support for zip.

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
There was a report of directional controls not working in lr-mame on a Dragonrise encoder. It appears there are two issues:
1) The Dragonrise uses the analog stick axis for directions, and the MAME/LR-MAME controller handler wasn't built to handle controllers with analog but no d-pad.
Which wouldn't have been a problem, except:
2) lr-mame got changed to use a strange version of the virtual Retropad in config files instead of the actual button IDs like it used to. This would explain the recent button flip issues.
The end result was that lr-mame was looking for analog stick inputs (the real controller), but being passed d-pad inputs (the Retropad).
This fix will map the d-pad if there's no secondary input. There is a chance that other controllers may have other issues. If so, I can do a …
=> lr-mame Dragonrise Fix

package/batocera/emulationstation/batocera-es-system/es_features.yml
The functionality was altered by https://github.com/batocera-linux/batocera.linux/pull/6689, this adjusts the description accordingly.
In the future, it is intended for this setting to apply globally to all applicable emulators, but since not all emulators support all ratios, the description now mentions this.
=> update "GAME ASPECT RATIO" description

package/batocera/core/batocera-system/batocera.conf
* Add system.suspendmode
* Correct grammar/spelling in the comments
* Remove splash.screen.length option as it was removed from Batocera itself
* Moved display rotation option up (it's important)
* Remove (0,1) notation on boolean options, it's implied by the examples and not consistent anyway
* Remove unnecessary note about limitation with Odroid CEC (this should only be on the wiki, and this device has since been discontinued/is barely supported by Batocera anymore)
* Reverse polarity of SSH/Samba (they're enabled by default)
* Remove ## Please enable only one of the following: as it is contradictory to the default settings
* Add language code descriptions
* Made new lines consistent
* Camelcase all headers for consistency
* Add Other section
* Redid options for scraper preferences
* …
=> update explanations + add power button behaviour

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds an option to use Lightgun Button 2 to replicate an off-screen reload. This is a command line option provided by MAME. IT should work for lr-mame as well, but I'm currently having lightgun issues with it.
It's per game/system, intended to be used for game/controller combinations that don't play nice with shooting off-screen (ie Wiimote & Lethal Enforcers).
It may make sense to have Auto enable it based on game/controller, for now it's just off by default.
=> MAME Offscreen Reload

board/batocera/raspberrypi/rpi3/boot/config.txt, configs/batocera-rpi3_defconfig, package/batocera/core/batocera-scripts/scripts/batocera-overclock
It will be possible to use the image of rpi3 in rpiZero2.
=> rpiZero2: Adding bcm2710-rpi-zero-2 to rpi3 image

Config.in, batocera-Changelog, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-system/Config.in, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/retroarch/libretro/libretro-arduous/Config.in, package/batocera/emulators/retroarch/libretro/libretro-arduous/libretro-arduous.mk
Adds the Arduous core, which emulates the Arduboy - an open source, Arduino-based handheld. Currently enabled on all boards.
There are a lot of decent free games available, though currently none of the scrapers have data for the system. There is a repo of games at https://github.com/eried/ArduboyCollection - it includes screenshots and additional info, so it may be possible to write a script (internal or external) to parse that into a gamelist.xml.
Also fixes a minor issue with GP32 in es_systems (listed as Handheld instead of Portable).
=> Add lr-arduous (Arduboy)

.gitignore
This allows you to save folder view properties in Dolphin (KDE's default file manager) without fear!
=> add dolphin (the file explorer) .directory file to .gitignore

board/batocera/patches/glibc/002-glibc-iconv-modules-extra.patch
the patch basically copies all lines from extra to normal
if you find a better way to enable it...
(kodi uses zip, that uses utf8 or cp374, and while some kodi packagers uses windows. glibc tries to clean up deprecated software.)
=> include all extra glibc iconv modules

package/batocera/emulationstation/batocera-es-system/es_features.yml
Makes it consistent with the other similar "automatic game fixes" option. Also clarifies what the hacks in question are actually in relation to (the graphics instead of the games themselves).
=> Relabel new hw hacks pcsx2 feature

package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
A user on Discord was defaulting to OpenGL over GLCore on a GT1030. After having them check the output strings, it turned out the OpenGL version had two decimal points - it was returning 4.6.0 instead of the usual 4.6 - which Python couldn't translate into a float.
This change will check the string and drop the extra decimal if it exists. It was tested with both my AMD driver (which reports properly), and I fed it the string with the extra decimal, and it worked in both cases.
This is a bug fix that is safe for v35.
=> Fix GL Version Check [v35]

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/dos.keys, package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk
- Don't add rom name twice in the command line
- Workaround for https://github.com/schellingb/dosbox-pure/issues/343
- Add default pad2key
=> Fix various lr-dosbox-pure issues for 35

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
The ratio setting set in the global game configuration screen will now be respected by pcsx2.
Also fixes https://github.com/batocera-linux/batocera.linux/issues/6958
Makes way for the actual tv_mode setting which is to be implemented in the future.
Clean up the empty lines in the pcsx2generator too.
=> rename + unify the pcsx2 ratio settings

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Having this setting on (in actuality off, ie. to tell PCSX2 to not use the user-define hacks (which no one using all auto settings is going to be using anyway)) fixes a variety of issues within PS2 games.
With the current default (off), Burnout 3 has black skyboxes:
(the actual glitch is that the skybox texture does not get updated, so if the game is loaded once with HWhacks enabled it will become that skybox permanently until HWhacks are used again, so I cannot get a high-quality screenshot of this myself in Batocera)
By turning HWhacks on, skyboxes are fixed:
With the current default (off), God of War has glitch vertical bars rendered when using upscaling:
By turning HWhacks on, no vertical bars:
I'm sure there are many other cases where issues are fixed. While playing various other …
=> Switch automatic HW hacks for pcsx2 to on

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
Option was originally added in https://github.com/batocera-linux/batocera.linux/pull/6213, citing that swanstation was not functional with opengl. Swanstation is now able to run with opengl just fine. Opengl is also more performant than Vulkan is on the RPi 4. Testing the game Tomb Raider III, in "Lara's home" running around the corner and looking into the lobby there is sever slowdown with Vulkan. This is handled much better with OpenGL.
=> remove vulkan as default api for psx on rpi4

package/batocera/emulationstation/batocera-es-system/es_features.yml
This setting is not required for certain games, apparently off-screen reloading works with most devices. However, the wiimote is currently bugged, where this setting comes into play. Fixes up the labelling to remove this confusing "required" statement.
=> minor corrections to label for off-screen reload

package/batocera/utils/batocera-wine/batocera-wine
Adds a fix for autorun.cmd files that contain Windows-style line breaks (CR+LF instead of just LF).
It will make a temp copy of the autorun.cmd, run dos2unix on it to fix line breaks, and read the values from that copy. That prevents it from editing the user's files.
Tested by loading a game with the current Unix formatted file, editing the line breaks to Windows-style, then opening it again. Probably best to save this one for v36 for further testing just in case.
=> Batocera-Wine/Windows Line Breaks [v36]

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulators/xemu/001-fix-optionrom-makefile.patch, package/batocera/emulators/xemu/002-eeprom.patch, package/batocera/emulators/xemu/003-eeprom-path.patch, package/batocera/emulators/xemu/004-hide-menu.patch, package/batocera/emulators/xemu/xemu.hash, package/batocera/emulators/xemu/xemu.mk
Allows more games to run, notably midnight club 3.
Includes updates to the patches, configgen and es_features to accomodate for changes within the emulator. Notably, Xemu will now reject the config file if there are any options with empty values in them, something the old configgen for this system relied on. All of those instances had to be removed. Tested and working fine.
Also took liberty to add "Enable DSP audio" as a user editable option, instead of just hard-coding it to be off.
Networking should work out of box, but I won't be able to test for that for a while.
=> bump xemu to 0.7.67

package/batocera/gpu/batocera-nvidia/batocera-nvidia
This log is added to every time Batocera boots to `system/logs/batocera.log`:
This will result in a file that increases in size every time Batocera boots.
And the worst thing is that this is logged even when the log level is set to "error".
This PR is a quick solution to the issue, the file will at least be recreated every boot instead of appended to every time, but I intend on looking for a more permanent solution by querying the current log level setting the user has set in dev settings > log level.
=> fix batocera-nvidia log spam

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Allow the user to set per-game/per-system volume for RetroArch cores (also possibly to expand this in the future for other emulators).
Fixes https://github.com/batocera-linux/batocera.linux/issues/7072
=> Volume control per Libretro emulator core

package/batocera/emulators/vice/vice.mk
resid is to taxing for old devices, please enable fastsid also.
=> make vice usable on rpi1/rpizero

package/batocera/emulators/retroarch/libretro/libretro-fbneo/libretro-fbneo.mk
The `bios/fbneo` on a fresh install now includes a `light/` folder. According to its readme:
```
Those "light" dat files are meant for n3ds builds, which can't load a full FBNeo build due to memory limitations.
```
They should be removed, they do nothing for Batocera.
There may be a better way to do this "copy everything but exclude the light folder" but this is the one I know. Will draft for a while so others can think of better ideas.
=> exclude "light" folder from bios/fbneo

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Also changes the default zoom level to "MSX2" as the default "ON" seems to cut out important content of the game:
"ON":
"MSX2":
=> add zoom option for bluemsx

board/batocera/patches/mesa3d/0001-panfrost-fix-ES-and-RA-menu-FPS-drop.patch
Add a patch that reverts the change in mesa commit 673f812835be26500958c79cd6f10bd24f99a385 fixing emulationstation and RetroArch menu fps. Found the commit using git bisect on mesa git after finding out that mesa3d v21.3.7 works but any newer release doesn't.
Note that the original commit in mesa actually increased fps in some glmark2 test (based on the commit message). So it's possible that there's a performance drop elsewhere to be found after this patch.
This only changes panfrost so other mesa drivers aren't affected.
Commit in mesa Gitlab: https://gitlab.freedesktop.org/mesa/mesa/-/commit/673f812835be26500958c79cd6f10bd24f99a385
Tested with rk3399/rockpro64 target.
=> mesa3d/panfrost: fix emulationstation and RetroArch menu fps drop

package/batocera/core/batocera-system/Config.in
https://github.com/duganchen/dosbox/issues/33
=> dosbox: Need libGLEW

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds an "enable mouse" option to standalone MAME.
When off, analog devices (trackball, spinner, lightgun, etc) are mapped to the analog stick. Note that lightgun is not a good experience on a standard gamepad, but would work well with a flightstick or an Operation Wolf-type mounted gun cabinet (adstick).
When on, they are mapped to the mouse instead. In addtion, mouse buttons are mapped to MAME's buttons where available - 1-3 are buttons 1-3, 4 & 5 are coin/start, and 6+ are additional game buttons.
Lightguns being turned on will override both options, and use the lightgun for gun & adstick.
There is code and a commented out option for Multimouse, MAME on Linux only supports SDL for mouse input, which only returns one pointer. If the ManyMouse library can be integrated with MAME, or a …
=> MAME Mouse Option

batocera-Changelog, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
lr-mame was using the name of the cmd file (which was usually lr-mame.cmd) for save states. To fix this, the generated cmd file now uses the ROM file name, minus extension - ie launching pacman.zip produces pacman.cmd. This makes lr-mame save states with the proper name, so they'll work per-game and show up in the ES save states list.
Since the filename is no longer consistent, it now creates a subfolder in the temp folder, and deletes any existing cmd files in that folder before creating the new one. The files are small and it would take a lot of launches without a reboot to build up a problematic amount of files, but safer to remove them.
=> lr-MAME save state fix

Config.in, package/batocera/core/batocera-system/Config.in, package/batocera/libraries/python-hidapi/Config.in, package/batocera/libraries/python-hidapi/python-hidapi.mk
Adds the [hidapi](https://pypi.org/project/hidapi/) Python module to Batocera.
The hidapi library is already available in Batocera.  Including the Python interface allows game start/stop scripts to take advantage of it.  This is particularly useful for general-purpose, low-level interaction with certain game controllers, to either read their capabilities, or to write new configuration on the fly.
My particular use case relates to the [BlissBox 4-Play](https://bliss-box.net), which allows numerous original game controllers to connect via USB.  The BlissBox API allows me to query which kind of device is connected through it.  I use this information at game launch to modify input mappings and other emulator configurations.  I can also use the hid interface to update settings on the BlissBox …
=> Implement the hidapi interface for Python

board/batocera/x86/boot/syslinux.cfg
This allows the user to access the syslinux boot menu to select one of the boot modes. This can greatly assist in helping the user debug booting issues.
This however comes at the cost of actually having to wait for the timeout, hence the need to reduce the TIMEOUT value as well.
=> change MENU SHIFTKEY to MENU HIDDEN for syslinux

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
Fixes https://github.com/batocera-linux/batocera.linux/issues/7198
MAME2003Plus maps multiple physical controls per input - so "Button 1" for example maps to joystick button 1, lightgun button 1, and mouse button 1. As a result, if the default setting of mapping controllers to lightgun inputs is enabled, multiple buttons perform the same action, and some controls can't be mapped.
This is the same fix that was previously applied to lr-MAME - the core is added to an exception list that disables the Controller to Lightgun option unless it is specifically turned on.
=> MAME2003Plus Duplicate Control Fix

package/batocera/core/batocera-scripts/scripts/batocera-info
The purpose of this PR is explained in https://github.com/batocera-linux/batocera-emulationstation/pull/1311. This just implements the same basic logic in batocera-info to allow battery readings from separate fuel gauge and charger drivers. 
While working on this, I noticed an unrelated bash warning `command substitution: ignored null byte in input` so I fixed that while I was in there.
=> batocera-info: Support battery readings from standalone fuel gauge and charger

package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/utils/batocera-wine/batocera-wine
This adds an option to Wine to enable/disable raw input for HID devices. Some games have issues detecting non-xinput controllers if raw input is enabled (the default). It builds a .reg file when loading options, and applies it during launch.
In addition, while working on this, I found that .reg files were not being loaded from the regs folder - the folder would rename, but the keys would not apply. Testing using regedit inside the wine bottle showed that regedit was prefixing files loaded from the Linux filesystem with "\\?\unix", adding this to the regedit command in the script as //?/unix allowed it to load properly.
=> WINE registry file fix & raw input option

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
- normal : draw borders when required
- hidden : the border are not displayed (assume that there are provided by an other way like bezels)
- force  : force even if no gun requires it (or even no gun at all)
- gameonly : borders are not visible in es, just in game (for boards having a sinden gun alway plugged in)
=> sinden guns modes

package/batocera/core/batocera-scripts/scripts/batocera-systems
Is basically https://github.com/batocera-linux/batocera.linux/pull/7247 but without any of the functionality changes, just the updated BIOS info.
=> update bios for amiga and atari

package/batocera/core/batocera-scripts/scripts/batocera-systems
* BIOS checker will now read es_systems.cfg to look for installed systems & emulators.
* By default, it will only search BIOS files for installed emulators. There is a --noFilter option to skip reading es_systems.cfg and check all BIOS files.
* Systems and individual files can be tagged with an emulator and core. It can be tagged with just an emulator as well, it will check  the files if the emulator is installed with any cores. This is best for a case where the same BIOS files are needed for multiple cores, or standalone emulators with one core. In the event of shared BIOS, best practice would be to tag with the core available on the most boards.
Two systems were filled in for examples -
* Macintosh has every BIOS file tagged, since minivmac and mame use different files. This way, …
=> BIOS Checker Modifications

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
and clean up some blank spaces in the configgen too.
=> add gamecube controller types to dolphin options

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Changes to `es_systems.yml:`:
- Change a `comment_fr` to `comment_br` in `tyrquake`. I don't know either language but it certainly looks like a typo :)
- Trim trailing spaces
=> es_systems.yml: fix a typo and trim trailing spaces

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
Replaces https://github.com/batocera-linux/batocera.linux/pull/7182
New method: uses evdev to determine what is a mouse or gamepad based on available inputs. If a mouse and gamepad have the same physical ID (checks out on BT and USB), the input device of the controller is stored. If there's a mouse with no matching gamepad, a dummy value gets stored to keep proper indexing.
When Retroarch generates the controller config, if the system is NDS or 3DS (we assume other systems will want a real mouse, but others can be added), it will check to see if the current controller matches one of the input devices in the list. If so, it will set the mouse index to the index in the list.
=> Sony Touchpad Fix v2

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
Fix for #6957 .  Work around makes a symlink to a /tmp/ folder to work around a dosbox pure bug. Has some error checking
=> Workaround for Dosbox Pure folder issue

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py
Fix for MAME/LR-MAME "combo" keys (gamepad with keyboard alternative). This was affecting a couple of systems, like PDP-1.
=> MAME Combo Key Fix

Config.in, package/batocera/core/batocera-configgen/configgen/configgen/GeneratorImporter.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/ikemen/ikemenGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-scripts/scripts/batocera-ikemen, package/batocera/core/batocera-system/Config.in, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/ikemen/Config.in, package/batocera/emulators/ikemen/ikemen.keys, package/batocera/emulators/ikemen/ikemen.mk
Ikemen-Go is an extension to MUGEN, with more capacities (and it's an open-source re-implementation of IKEMEN in Golang). Very active in the fighting community. Installation of the games needs a little bit of work, but worth it.
It can theoretically run on a RPi4, but it needs some work to compile it at the moment. At least we have a first step here.
=> Add Ikemen-Go (only x86_64 at the moment)

Dockerfile
Use system cmake instead of compiling host-cmake
Ubuntu 22.04 has cmake 3.22.1, which is recent enough for everything
=> Dockerfile: Install cmake

package/batocera/emulators/retroarch/libretro/libretro-same-cdi/libretro-same-cdi.mk
`libretro-same-cdi` internally compiles `genie`, a host tool.
It previously used target compilation flags to compile it, so it failed to run.
Fixes this by compiling genie with the host flags first.
=> libretro-same-cdi: Fix build

package/batocera/utils/rclone/rclone.mk
Previous version no longer builds due to some dependencies having moved to new URLs.
=> Bump rclone

package/batocera/core/batocera-configgen/configgen/configgen/generators/xash3d_fwgs/xash3dFwgsGenerator.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/ports/xash3d/hlsdk-xash3d-dmc/hlsdk-xash3d-dmc.hash, package/batocera/ports/xash3d/hlsdk-xash3d-dmc/hlsdk-xash3d-dmc.mk, package/batocera/ports/xash3d/hlsdk-xash3d-opfor/hlsdk-xash3d-opfor.hash, package/batocera/ports/xash3d/hlsdk-xash3d-opfor/hlsdk-xash3d-opfor.mk, package/batocera/ports/xash3d/hlsdk-xash3d/hlsdk-xash3d.hash, package/batocera/ports/xash3d/hlsdk-xash3d/hlsdk-xash3d.mk, package/batocera/ports/xash3d/xash3d-fwgs/xash3d-fwgs.hash, package/batocera/ports/xash3d/xash3d-fwgs/xash3d-fwgs.mk
The new version includes multiple bugfixes
The `extras` package is now built as part of the release and included in the installation.
It is no longer available as a separate download.
This simplifies the installation process but increases the image size by 2.4 MiB.
=> Update xash3d to the latest release

package/batocera/ports/gzdoom/0002-Add-an-option-to-only-build-the-tools.patch, package/batocera/ports/gzdoom/0003-gdtoa-Fix-cross-compiling.patch, package/batocera/ports/gzdoom/Config.in, package/batocera/ports/gzdoom/Config.in.host, package/batocera/ports/gzdoom/arith.h, package/batocera/ports/gzdoom/gd_qnan.h, package/batocera/ports/gzdoom/gzdoom.mk
gzdoom compilation requires some host tools and generated headers. Build the host tools first, and provide generated headers.
The headers were generated on an x86_64 machine which is OK for now as gzdoom is currently set to `BR2_PACKAGE_BATOCERA_TARGET_X86_64_ANY`.
Support for other architectures can be added by generating the appropriate headers on the target machine:
```bash
cmake -S. -Bbuild && cmake --build build -j $(nproc) && find build/deps -iname '*.h'
```
I've sent the cross-compiling patches upstream:
1. https://github.com/ZDoom/gzdoom/pull/1794
2. https://github.com/ZDoom/gzdoom/pull/1795
This is similar to the fix for ecwolf at https://github.com/batocera-linux/batocera.linux/pull/7446
=> gzdoom: Fix build

package/batocera/core/batocera-scripts/scripts/batocera-switch-screen-checker
=> batocera-switch-screen-checker: Fix typo

package/batocera/core/batocera-settings/batocera-settings-get-master
1. Fixes warning:
/usr/bin/batocera-settings-get-master: line 16: warning: command substitution: ignored null byte in input
2. Fixes `board_name` fallback (the `-z` condition was reversed).
3. Removes bashisms, runs with `sh`, makes the style more consistent with other scripts.
=> batocera-settings-get-master: cleanup

package/batocera/emulators/dolphin-emu/010-disable-events-merging.patch
the dolphin-emu merges some linux events (to handle some pads like the ps4 controller). This is not compatible with simple autoconfiguration of emulators.
=> disable dolphin-emu pads auto merging

batocera-Changelog.md, configs/batocera-bcm2711.board, configs/batocera-bcm2835.board, configs/batocera-bcm2836.board, configs/batocera-bcm2837.board, configs/batocera-rpizero2.board
This reverts commit f60f07bb7d6380a5d29452e170fc1d1dd3158451.
=> Revert "bump: rpi-linux to 1.20221028 (5.15.74)"

package/batocera/core/batocera-scripts/scripts/batocera-systems
It appears that MAME now requires the ADB Modem BIOS for Mac emulation, I added it to batocera-systems.
=> MAME Macintosh BIOS Update

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
decreases input lag when set to lower numbers, at the cost of performance
=> add vsyncqueuesize setting to pcsx2

package/batocera/emulators/dolphin-emu/011-gba-path-fix.patch
Apparently, Dolphin ignores the GBA BIOS and Save path options - you can test it by opening Dolphin-config, changing them, then exiting and re-opening. It will update Dolphin.ini, but apparently never reads it and will always use the defaults.
I missed this during initial testing because I had files there from some early tests, so everything worked as expected.
This patch sets the defaults to Batocera's BIOS file (shared with GBA) and temporary save path (for symlinking existing saves). Tested after deleting /userdata/saves/dolphin-emu/GBA, and everything worked.
=> Dolphin GBA Path Fix

package/batocera/emulators/dolphin-emu/gamecube.dolphin.keys
Swap GBA & GC screens - useful for games that download demos & other software to the GBA. USes the same hotkey+r2 that Cemu does.
=> Dolphin GBA Screen Swap Hotkey

package/batocera/core/batocera-scripts/scripts/batocera-ratpoison, package/batocera/emulationstation/batocera-emulationstation/ratpoisonrc
batocera-ratpoison script and default keybind/ratpoison settings changes so that alt-tab will now show a window list for a couple of seconds when pressed. The list will be in the format `Window Number: Title (Process Name)` with the currently focused window indicated with a *.
In addition, `batocera-ratpoison message` can be used to display a pop-up message on screen via ratpoison, should we need to do so in any other scripts (warnings, errors, status messages, etc). The message should be in quotes - ie `batocera-ratpoison message "Hello, World!"`
=> Alt-Tab Enhancement & Message Functionality

package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
The e-Card file selection box was taking over the Dolphin frame as a white screen. This change will unmanage that particular window, allowing it to appear normally.
Note that the `set winname title` command shouldn't be 100% necessary since a previous PR makes that the default, but that will reset it should somebody change it, and make sure the correct window behavior happens.
=> e-Reader File Select Fix

package/batocera/emulationstation/batocera-es-system/es_features.yml
Tested on lr-flycast x86_64 and rg552
=> Fixed rumble value for disabling with latest RetroArch update

package/batocera/emulationstation/batocera-es-system/es_systems.yml
The Windows and Windows Installer systems are tagged as "pc" rather than "computer." This causes it to show up in the wrong place in the "sort by type" and recently added "sort by manufacturer and type" lists.
These were also the only two platforms with that tag, every other computer is tagged as "computer."
=> Fix Windows "hardware" Tag

package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
Add a text file containing the filename of the xbla file desired to be loaded. Name the text file "name of game.xbla" (edit: now .xbox360, check commit notes). ES will recognise and boot it in Xenia, very nice.
Might add the ability to define absolute paths later if I feel like it. Going to let it simmer for a bit in case there's any feedback first.
=> allow loading xbla digital titles from ES

package/batocera/controllers/guncon/guncon.mk
My repository has then the following changes
Substring:
Allow side buttons to quit the calibration app
Better screen resolution handling
Use the guncon DPAD to calibrate the cross-hair
homefefeld: 
smooth controls : holding down an arrow on the dpad to control the hair cross
Redemp (Rion):
Remove double button press when C is pressed.
guncon2_calibrate.sh (For Batocera)
Disable Trigger (So not to mess up the calibration by accident) Thank you Lbrpdx 
For v36
=> guncon2 driver and calibration

board/batocera/scripts/doWineWow64-32package.sh
This PR fix some games issue on wine Coromon is good example because is using some libs needed by wine.
Other example is Dreamlight Valley etc...
=> Fix Coromon

package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
it's too small. 1 to 3 are very thin border for Sinden Lightgun (it can go from 1 to 10). Current values of the camera are not good enough to track correctly the screen. 2 should be the bare minimum for thin, but I suggest 3. 6 for medium. 9 for big (auto). I've tried tweaking the camera, but 1 is too thin. Some games have very bright white lines and it messes with the tracking. Colors will be required to add afterwards for those specific scenes for some games with very dark or bright colors. Having a contrasted color will help further.
=> thickens white border for Sinden (Daphne)

package/batocera/controllers/sinden-guns/LightgunMono.exe.config.template
Default should be Exposure -7, Contrast 100, Brightness 50. ExposureAuto is very bad when light in gun games fluctuates. Sinden Lightgun community and testers recommend Exposure set to -7, Contrast to 120 and Brightness to 60 as a starting point. I've tested countless and it works best for thinner borders with high light. Camera is losing track with current values, sadly.
=> Tweaking Sinden Lightgun settings to recommended

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Some games require this to be set to "accurate" to avoid crashes.
"Relaxed xfloat" always being set to "true" is not an oversight. This is actually how selecting any option from the RPCS3 GUI functions, even "Accurate XFloat" will set "Relaxed xfloat" to "true". This is to stay true to what the GUI reports, as that's what user reports reflect upon when submitting information to the RPCS3 wiki.
Cleanup of whitespace.
=> Add SPU Xfloat setting to ES

package/batocera/core/batocera-configgen/configgen/configgen/generators/melonds/melondsGenerator.py
Fix  #7840 for MelonDS standalone on SteamDeck (and probably other joypads with non-Xbox360 SDL2 mapping)
=> Fix MelonDS touchscreen on SteamDeck

package/batocera/core/batocera-configgen/configgen/configgen/generators/sh/shGenerator.py
Most Linux ports are written in SDL, therefore it is extremely useful to export the (known working) controller mappings as it is done for other systems. This is invaluable for older binaries with their own copy of SDL and controller mappings, as they won't work out-of-the-box with new controllers and/or kernel drivers.
This does not have any impact on non-SDL ports.
=> Set SDL_GAMECONTROLLERCONFIG when launching ports

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py
Fixes the chicken-and-egg issue of opening up the RetroArch menu to allow the user to rebind their keyboard controls when only a keyboard is available.
Existing users will not have their config changed, they will still have Esc be their "immediately close RetroArch" button. But, new users or users who erase their RetroArch custom config will have to press Shift+Esc to exit. Considering the keyboard is not mapped consistently between emulators anyway, I don't see this as an issue. If it is, though, we could easily add in an evmapy keys profile to re-enable the exiting immediately upon pressing Esc functionality (in my opinion, having a single button exit the emulator is not a good practice in the first place, especially when saves are at stake).
=> allow shift+f1 to open RA quick menu on keyboard-only

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
Upstream changes to MAME2010 for lightgun support conflict with Batocera's controller to lightgun mapping, causing double inputs. This will add MAME2010 to the cores that will turn off that functionality by default (it can be turned on manually in ES options).
=> MAME2010 Double Input Fix

package/batocera/core/batocera-desktopapps/apps/xterm.desktop
UTF-8 is needed for special/extended characters (without it it's just jibberish), scrollbar increases ux/legibility (reviewing history)
=> xterm.desktop  >  add scrollbar & UTF-8 support

package/batocera/emulators/mame/mame.mk
GroovyMAME 0.251 - Switchres 2.002o
Update to upstream Switchres (fixes rotated desktop in X)
This fixes a long standing bug where Mame on a CRT monitor could not use the build in function to rotate the desktop ( in Emulation Station) without first rotating back to normal via a script before mame was launched.
=> Bump GroovyMame

package/batocera/utils/switchres/switchres.mk
There are a few noticeable changes since last bump.
- Correctly store desktop rotation in linux and sdl display backends.
- -g, --geometry <h_size>:<h_shift>:<v_shift>  Adjust geometry of generated modeline
- Increase h_size range maximum to 2.0
=> Bump switchres

Makefile
Example usage:
Count the number of packages to be built:
```
$ make rk3399-show-build-order | grep -v ' ' | grep -v \# | wc -l
642
```
=> Makefile enhancement to expose buildroot show-build-order

board/batocera/rockchip/rk3399/dts/rk3399-anbernic-rg552.dts
You need to give me proper credit of this DTS. I forked this from maccraft12 and spent nearly 100 hours getting it to boot on the 552 for JELOS. Its fine if you use but when you copied the patch from Jelos and made your changes you never thanked me or gave me credit. 
https://github.com/brooksytech/rk3399-kernel-5.19/blob/main/arch/arm64/boot/dts/rockchip/rk3399-rg552-linux.dts
https://github.com/brooksytech/rk3399-kernel-5.19
Thank you.
=> Fixing copyright of the RG552, I wrote this DTS.

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py, package/batocera/emulators/cemu/006-fix-keys-path.patch
Batocera documentation states [1] that the `keys.txt` file needs to go in the `/userdata/bios/cemu/` directory, however cemu looks for this file in the user data path [2], which batocera is then defining to be `/userdata/saves/wiiu`, through a custom patch [3].
This commit changes cemu to look for the keys file in `/userdata/bios/cemu/`, so it matches the documentation. This  makes it so that we do not need to do additional workarounds in the generators, to copy the keys from the bios directory to where cemu would look for it.
strace before the change:
```
[...]
newfstatat(AT_FDCWD, "/userdata/saves/wiiu/keys.txt", 0x7f31487f6d60, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/userdata/saves/wiiu", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[...]
openat(AT_FDCWD, …
```
=> emulators/cemu: fix path for keys.txt

package/batocera/core/batocera-desktopapps/scripts/filemanagerlauncher
We should only try to use a specific DISPLAY if the env var is not yet defined. In the file manager launcher, let's check first whether DISPLAY is not defined, before assuming it to be :0.0.
=> batocera-desktopapps: do not hardcode DISPLAY in file manager launcher

package/batocera/emulationstation/batocera-es-system/es_systems.yml
ZX Spectrum is missing support for .dsk images, which are disk images from the ZX Spectrum +3 and a few other third-party add-ons.
fuse-libretro 1.6.0 (and likely earlier versions) support these without any issues, but they aren't recognised by the EmulationStation configuration - loading them manually in RetroArch under Batocera works fine, so it looks like the file type was missed when it was added.
=> Add support for zxspectrum .dsk images

package/batocera/utils/jstest2/006-fix-gamecontrollerdb-path.patch
When running `batocera-padsinfo`, the following message always pops up: `"error: failed to read gamecontrollerdb.txt: Invalid RWops"`
It turns out it is trying to read `gamecontrollerdb.txt` that should be located at `/usr/share/sdl-jstest`; however that is a broken symlink pointing to `SDL_GameControllerDB/gamecontrollerdb.txt`.
After digging a little, it seems that when building `jstest2`, we do not copy the db file from the submodule we checked out. Let's fix this by adjusting the path.
=> utils/jstest2: fix path for gamecontrollerdb

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
Currently DOSBox-Pure gives an error when starting (and starts afterwards) if all these conditions are true
- ROM is in a folder;
- ROM name contains space;
- `ROM name.bat` exists.
This fix maintains maximum compatibility.
An alternative would be simplifying the code and always using the code currently in else statement (removing lines 218-222)
=> Fix DBP for folders with space in name

package/batocera/core/batocera-splash/scripts/Ssystem-splash
Display rotated splash image for ODROID-GO Advance.
Model detection taken from `batocera-info`.
=> odroidgoa: display rotated splash image

batocera-Changelog.md, package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
MAME was bumped through #7911 resulting in a discrepancy with lr-mame (and outdated changelog).
=> Realign lr-mame with mame standalone 0.251

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
This is a proposal to fix https://github.com/batocera-linux/batocera.linux/issues/5659
It looks like not all (loadiine) squashfs images have the same structure, e.g.
* Single rpx file: `mlc01/usr/title/00050000/10145c00/code/RedCarpet.rpx`
* Multiple rpx files:
* `mlc01/usr/title/00050000/10180600/code/Kinopio.rpx`
* `mlc01/usr/title/0005000e/10180600/code/Kinopio.rpx`
This commit selects the first rpx file in a `code` directory, no matter where the exact location in the squashfs image is.
=> fix(cemu): improve rpx location for squashfs

board/batocera/scripts/post-build-script.sh
Decrease CPU priority of rngd to decrease its impact on system performance.
On ODROID-GO Advance I noticed several CPU usage spikes of rngd. Haven't checked this on other systems.
This PR should decrease effect of such rngd CPU spikes to overall system performance.
=> Set niceness of rngd to 10

package/batocera/controllers/guncon/guncon.mk
Adding new functions from @psakhis fork. 
- calibrate -32768 to 32767
- Normalize in kernel
- micro calibration added
- Update calibration script for new functions 
- Button C + D-pad left/right -> decrease x-min -> apply if your gun is out on left of the screen
- Button C + D-pad up/down -> increase x-max -> apply if your gun is out on right of the screen
You need to do a first calibration only once 
Now calibration tool adjust real values to RX analog And emulators use ABS_X where position values are interpolated inside driver In other words, ABS_X min and max values are -32768,32767 always, and ABS_RX min and max are real gun values
=> GunCon 2 Driver Update

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
This is a fix for a bug introduced with https://github.com/batocera-linux/batocera.linux/pull/8052: path resolution fails when the path contains glob special characters (e.g. square brackes as in `Game Title [ABC]`)
=> fix(cemu): allow special chars in squashfs path

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> Add pad2key to macintosh, atom, bbc, electron

package/batocera/emulators/mame/mame.mame.keys
**This is a temporary fix** so that we can release B36. If you use ESC with standalone MAME on the SteamDeck, the right side of the screen stays on forever. With this hard kill, it seems to fix it.
=> Fix for B36 Steamdeck: exit for standalone MAME

package/batocera/emulators/rpcs3/013-gun-support.patch
Making SELECT pushable so that the game Child of Eden can be played with a gun. This is the only game from my tests that requires SELECT button to be pressed on the emulated PS Move. So, left d-pad on the gun will be SELECT.
=> fix RPCS3 select button

package/batocera/emulators/retroarch/libretro/libretro-o2em/libretro-o2em.mk
Commits made after this version introduced an audio bug which causes the pitch of the sound to be incorrect. Considering that all commits made after this are just "clean up code" and other house-cleaning, it's probably fine.
The issue has been reported to the original Github page of the core, when that gets fixed it will probably be safe to upgrade this to the current version once again.
=> revert lr-o2em to Nov 3, 2021 to fix audio problems

Makefile
That's how I reclaimed 48GB from my batocera build machine: removing old archive files and build sub-trees that are now superseded by newer versions.
This introduces the following commands:
- `make find-dl-dups`: show packages that are outdated, because a newer has been downloaded
- `make remove-dl-dups`: remove all these outdated packages from your `dl/` directory
- `make x86_64-find-build-dups`: show directories in the `x86_64/build/` tree that are outdated because a newer one has been created
- `make x86_64-remove-build-dups`: remove all these outdated directories
Of course `x86_64` is an example, you can use any supported arch.
=> Find/remove older files in `dl/` and `build/` directories

board/batocera/rockchip/rk3399/linux_patches/linux-0001-drivers-add_rg552_singleadcjoy.patch
Prevents a race condition, where singleadcjoy gets probed and starts initialising before the IIO channel is probed.
=> Propagate PROBE_DEFER in singleadcjoy

package/batocera/core/batocera-scripts/scripts/batocera-info
This PR extends the `batocera-info` script to read the temperature from `hwmon` in addition to the existing `thermal` node.
Depending on the system configuration, the directory `/sys/devices/virtual/thermal` may exist but not contain any `thermal_zone*` subdirectory. On such a system, the temperature is missing in batocera. I could observe this on a x86_64 system that has 4 `cooling_device*` nodes but no `thermal_zone*` node.
=> Read temperature from hwmon

package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg
Might work with other handheld PC, now that we're on 6.1.x kernel.
If you have a handheld PC, with the touch screen recognized, but working sideways (i.e, moving up is left or right), connect to SSH and give me the output of `DISPLAY=:0.0 xinput | grep pointer | tail -n +2`
=> Fix touchscreen OneXPlayer (original Kickstarter edition)

package/batocera/utils/batocera-wine/batocera-wine
while it remove/add virtually devices breaking pad2key there is an option in es to reenable it in case
=> disable proton hidraw

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> Fix Apple II extensions (now compatible with MAME)

package/batocera/emulators/daphne/daphne.mk
New **bezel** support +
https://github.com/DirtBagXon/hypseus-singe/releases/tag/v2.10.2
=> hypseus: Version bump to 2.10.2

package/batocera/controllers/joycond/001-fix-udev-path.patch
This PR grants read/write permission for Nintendo Switch Pro Controllers to group `input`.
This permission is required when a non-root user requires access to a Pro Controller.
In batocera, flatpak apps are run as user `batocera` which does not have root privileges but is in group `input`. Thus, flatpak apps that are started from batocera have no permission to use pro controllers. A lot of emulators and games are available as flatpak apps and would benefit from this extension.
The flatpak image of yuzu contains an input settings dialog where the change was and may be tested, even using motion controls. The flatpak image of citra may also be used for testing, also with motion control.
=> Allow flatpak emulators to use a Switch Pro Controller

board/batocera/amlogic/s905gen3/tvbox-gen3/create-boot-script.sh, configs/batocera-s905gen3.board
Tested with a v36 build on the target.
=> s905gen3: fix dts names

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
It won't work otherwise since Dolphin's default is for it to be disabled.
=> Enable Wii balance board with native controllers

package/batocera/core/batocera-scripts/scripts/batocera-info, package/batocera/core/batocera-scripts/scripts/batocera-padsinfo
This PR adds basic support to read the battery from controllers that do not provide their capacity as percentage but as discrete values (e.g. `Low`  or `Full`).
It depends on the controller whether the capacity is provided as percentage or as level. A _Nintendo Switch Pro Controller_ returned levels. This was observed using either kernel module _hid-nintendo_ or _hid-nx_.
This change is backwards-compatible. The existing scripts `batocera-info` and `batocera-padsinfo` have been extended. To avoid redundancy, a helper library `pad-support.sh` was introduced.
The implementation is targeted to be minimal-invasive: the [well-known levels](https://github.com/emilyst/hid-nx-dkms/blob/974d6c407296c47390d99f008933846c86f52bb9/hid-nx.c#L1533) are simply adapted to matching percentage values. This …
=> Add support for controller battery level

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Added RAM Size option for FM Towns (2MB default, 4MB available) and media type options for Acorn Electron.
=> MAME Additional Options

package/batocera/core/batocera-audio/alsa/batocera-audio
Fixes the issue where when `S27audioconfig` first starts, not all audio profiles are `"available=1"` during that time (e.g., the Nvidia HDMI audio profiles in my environment).  Doing `batocera-audio set-profile` during that time results in subsequently doing `setSystemVolume` on the default device (on-board audio) instead of the intended device (Nvidia HDMI), because `batocera-audio set-profile` never checks if the switch really did happen. 
The change adds additional checks in `batocera-audio set-profile` and `batocera-audio set` to see if the switch really did happen.  If not it returns 1 so that `S27audioconfig` would try again.
=> fix issue #8180 (system volume reverts to 40 at reboot)

board/batocera/fsoverlay/etc/samba/smb.conf
This patch adjusts the default configuration of samba to allow and enable following of symlinks outside the share directory.
This patch enhances the utility of samba sharing for people using symlinks to redirect parts of userdata to a larger disk.
Signed-off-by: Steve Hay <me@stevenhay.com>
=> samba / Enable samba to recognize and follow wide symlinks.

package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
Fix #8332 and saves download time and disk space when building Batocera.
=> Fix Odyssey2 bezels + general bezels clean-up

package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
- Also fixes a previous commandArray.append() commandArray.extend() mixup in https://github.com/batocera-linux/batocera.linux/commit/e2206bb03a117c7719fb90af1f910f5952af3c80
This will update a recent commit by @Tovarichtch (https://github.com/batocera-linux/batocera.linux/commit/1ffb85b405c6e64257b8ee3b09808fcafab4e3bd)
Border widths have been optimised for both SD and HD video resolutions.
=> Added Sinden border color options to daphne (singe) gun games

Dockerfile, Makefile
As titled; I haven't tested this on systems other than OSX, so it'd be great if someone could validate that this does work everywhere before merging.
=> Support OSX build and remove exposure of host system files to container

package/batocera/emulators/cemu/Config.in
A build without PCSX2 fails because cemu requires wxwidgets but does not declare this requirement.
=> fix(cemu): add missing dependency to wxwidgets

board/batocera/amlogic/s922x/odroidn2/boot/boot.ini, board/batocera/amlogic/s922x/odroidn2/create-boot-script.sh, board/batocera/amlogic/s922x/odroidn2plus/boot/boot.ini, board/batocera/amlogic/s922x/odroidn2plus/create-boot-script.sh
The N2 and N2-plus have a boot switch that loads a bootloader (Petitboot) from SPI NOR. This reintroduction of the boot.ini file enables Batocera to boot from Petitboot, which is helpful for people that want to run Batocera on an SD card while having another OS on emmc. (Boot order in the other position is emmc first)
- boot.ini adapted from previous version in batocera
- config.ini (from previous) not included, not needed
- create-boot-script aligned between the two boards
If someone has a straight-up N2 maybe they can test.
=> odroid-n2 and odroid-n2-plus / Added a boot.ini to support use of petitboot, an onboard kexec-based bootloader

package/batocera/emulationstation/batocera-es-system/es_systems.yml
For the six Sega CD titles that require a 32X
- Corpse Killer
- Fahrenheit
- Night Trap
- Slam City with Scotty Pippen
- Supreme Warrior
- Surgical Strike
=> sega32x: add extension chd

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
Fixed problem:
EmulationStation sanitize a game name (if include # or =)
but batocera-configgen cannot recognized the name
The way:
do the same sanitize rule in configggen
=> [Fix] settings name on configgen

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
Fixed problem:
libretro-pcsx2 can use m3u
but EmulationStation cannot reconize
The way:
- add settings to es-systems.yml
- but only libretro-pcsx2 can use
- add settings to libretroControllers.py to control by UI
=> [Add] m3u to libretro-pcsx2

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Fixed problem:
msxturbor can use m3u
but EmulationStation cannot recognize
The way:
add settings to es-systems.yml
=> [Add] m3u to msxturbor

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Fixed problem:
SMSPLUSGX cannot start
(is wrong path)
The way:
rename smsplusgx to smsplus on es_systems.yml
=> [Fix] SMSPLUSGX starting

board/batocera/fsoverlay/etc/openbox/rc.xml
This change exclusively enables flatpak Lutris to run in windowed mode, which it needs, because it uses a gtk-styled layout that has an add/"+" button on the window titlebar
The app is entirely unusable without this change
=> Update openbox/rc.xml to support flatpak Lutris

Makefile
Ability to run specified commands inside the Docker container.
E.g.:
```
make x86_64-shell CMD="echo This command is run inside the container"
```
This can be useful for scripts that run custom steps of a build (in my case I need to run `mkimage` inside the container as a part of script for building experimental kernel versions).
=> Ability to run specified commands inside Docker

package/batocera/emulators/rpcs3/rpcs3.mk
Demetris requested it.
Tested and it builds fine with GCC 12 on x86_64
=> Bump RPCS3 to v0.0.28 (build tested on x86_64)

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
@nadenislamarre for your review...
1. Added the option for alowing custom textures
2. Added the fog hack as an option from users request
3. We now symbolic link the file from `/usr/pcsx2/bin/resources/textures/....` accordingly
4. If the option is not enabled, we remove the symbolic link
Over to you...
=> allows fog hack as user select-able option

batocera-Changelog.md
Because the path changed again, from /userdata/saves/ps2 to /userdata/saves/ps2/pcsx2, worth noting
=> small note about pcsx-qt6 save folder

package/batocera/core/batocera-splash/scripts/Ssplash-mpv
Some boards miss splash video sound if ao is not set to sdl.
It is a safe move as this only changes the splash script used on x86 and boards (except rpi) and SDL is built everywhere.
=> Force mpv to use SDL for audio output

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
Cropping horizontal overscan leads to text being cut off in certain games (e.g. Castlevania). The default for both Nestopia and FCEUmm libretro cores is to only crop the vertical overscan.
=> configgen: Change default crop overscan for NES to vertical only

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
UI controls matched incorrectly:
down to up
right to left
=> fix mame ui control mappings

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
The newer builds of FCEUmm and Nestopia use integer values for cropping overscan rather than enabled/disabled
=> Fix crop overscan core settings for NES

board/batocera/patches/xapp_xinit/002-failure-diagnostics.patch
Show text diagnostics on the console instead of black screen, if xinit fails to start X from startx
There are several different failure modes which can result in Batocera booting, displaying the splash screen and video, and then leaving the user at a black screen.
Diagnosing these black screen problems, and providing assistance in the Discord channels or elsewhere is challenging.  Wrong outputs, bad/incompatible resolution settings, and Xorg failing or crashing all lead to a similar result.
This PR will make the last category behave distinctly from the others, and will provide more information in these Xorg failure scenarios.  Instead of being left on a black screen, the user will be switched to a text virtual terminal console, the Xorg log will be dumped onto that terminal, and the user …
=> Show text diagnostics on the console instead of black screen

package/batocera/libraries/libopenmpt/Config.in, package/batocera/libraries/libopenmpt/libopenmpt.mk
It used to work only because mpg123 is selected by other packages, but doing a build without emulators ALL_SYSTEMS and only Kodi brings a failure.
Fix that and broken help text.
=> Fixup libopenmpt requiring mpg123 and Config.in help text

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Edit for use with added audio buffer duration settings in es_features
=> Add RPCS3 ES settings for audio buffer duration

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
At the moment, the core is using its own controls & Batocera controls at the same time, which mixes up everything. Ex.: secondary button reloads offscreen and shoot grenade simultaneously. By removing the Batocera controls to only keep the start/coins buttons, it's working as intended. Tested on various gun games (ex.: le2) and analog stick gun games (ex.: term2, revx). This is only for mame078plus core.
=> fixing mame078plus light gun controls

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
For n64 style controllers with libreto n64 cores.
Automagically remaps inputs for users with n64 style controllers based on ES controller type setting. 
Does not break inputs for normal "retropads". Can mix and match! :)
Adds ES setting for P1 only that regenerates hotkey dictionary to only include exit_emulator. Needed for n64 controllers that don't have enough inputs for a dedicated hotkey. Without this users have to give up in-game input for a dedicated hotkey button.
Additional ES setting for A/B swap, so consistency is possible on a per controller basis between ES(with or without dev option to swap CONFIRM/CANCEL) and in-game inputs. 
(Default/Recommended mapping is "A" as SOUTH and "B" as EAST to keep consistency with other controllers/standard setups.)
N64 A/B Swap setting is …
=> N64 controller auto remap for libreto n64 cores

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
Fixed problem:
libretro-kronos can swap discs.
but cannot control by hotkey.
The way:
add to coreWithSwapSupport in batocera-configgen
=> libretro-kronos can swap discs by hotkey

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
SPU loop detection can improve performance on CPUs with low core/thread count. But may also result in broken timings in some games.
=> Add ES Setting RPCS3 SPU Loop Detection

Config.in, batocera-Changelog.md, package/batocera/core/batocera-configgen/batocera-configgen.mk, package/batocera/core/batocera-configgen/configgen/configgen/GeneratorImporter.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/thextech/thextechGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-system/Config.in, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/thextech/Config.in, package/batocera/emulators/thextech/thextech.keys, package/batocera/emulators/thextech/thextech.mk
To install TheXTech games, download game assets, and extract them into a folder `/userdata/roms/thextech/<yourgame>.smbx/`
For example, the default SMBX assets can be downloaded from https://wohlsoft.ru/projects/TheXTech/_downloads/thextech-smbx13-assets-full.7z and put into a directory `/userdata/roms/thextech/thextech-smbx13-assets-full.smbx/`
Then you can launch from ES.
PR compiled on x86_64, rk3399 and rk3568. Tested on x86_64.
=> Add TheXTech game engine (SMBX)

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulators/mupen64plus/mupen64plus-core/controllers/input.xml
Add Controller submenu to stand alone mupen emulator in ES
Controller Type for Retropads and N64 controllers, sensitivity, and deadzone options per controller.
Added new function that calculates per controller joystick sensitivity and deadzone. Deadzone is always calculated from peak value. If ES settings auto makes no change to values in xml(to allow for custom amount), however default behavior is to always calculate deadzone from 5% of peak value.
Prior behavior was to always have deadzone at 0, which is very odd and resulted in several controllers having joystick drift. Not good.
Also added additional n64 controllers to es_input.
=> Mupen controller type and additional controller settings

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Added controller type classic controller pro(this is the original code for what was classic controller / old cc = pro)
Changed type classic controller to mirror how retroarch classic controller type is mapped(swapped L+R with ZL/ZR).
Also removed submenu from dolphin-lightgun-hide-crosshair in es_features, I assume this was a mistake as it resulted in there being 2 "CONTROLLERS" sub menus in the Wii advanced system settings.
=> Dolphin ES settings for CC+CC Pro  control type

package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulators/daphne/daphne.mk
https://github.com/DirtBagXon/hypseus-singe/releases/tag/v2.11.1
New Daphne game, overlay restructure and removal of legacy Singe overlay functions.
See Changelog on link above for full list of changes, hopefully this catches the argument changes.
=> Bump hypseus to v2.11.1

board/batocera/fsoverlay/etc/connman/main.conf, board/batocera/fsoverlay/etc/init.d/S08connman
these changes open way to running docker/podman containers inside batocera (which in turn opens way to make bato a very viable always-on box)
1. starting connmand with -r prevents it from occupying dns port 53, which opens way for running eg containerised pihole; port 53 is currently used to run the default dnscache service (which seems unnecessary in batocera (?))
2. updated etc/connman/main.conf blacklist prevents connman from getting lost and jumping ship when a docker/podman instance with -p is started; without this bato/host will lose connectivity (unless containers are run with --network=host instead of -p)
=> make connman compatible with docker/podman

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
Libretro cores will currently fail to start if START is not mapped to a controller button, and will behave oddly if HOTKEY is not mapped to a controller button.
This patch fixes both bugs, allowing the use of single-button controllers with adapters such as the "hexagons.de Retro-Joystick" USB adapter.
=> Allow libretro cores to work with controllers having minimal mappings

package/batocera/core/batocera-configgen/configgen/configgen/generators/wine/wineGenerator.py
Default configuration of batocera.conf is system.language is unset.  This results in a crash of any WINE game in the current butterfly beta.
```
evmapy: no process found
2023-08-13 20:55:52,716 ERROR (emulatorlauncher:594):<module> configgen exception:
Traceback (most recent call last):
File "/usr/bin/emulatorlauncher", line 592, in <module>
exitcode = main(args, maxnbplayers)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/emulatorlauncher", line 99, in main
return start_rom(args, maxnbplayers, args.rom, args.rom)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/emulatorlauncher", line 260, in start_rom
cmd = generator.generate(system, rom, playersControllers, guns, gameResolution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Provide a default system language for WINE

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
Implements suggestion from @dmanlfc in #9544 .
=> Warn if CPU does not support SSE4.1 which is required by pcsx2

board/batocera/fsoverlay/etc/init.d/S99userservices
- Interpreter must be bash, sh (dash) does not have the variable substitution feature
- "/" and "." are not valid characters in a variable name, so strip down to a basename
=> Fix some bugs in the new /etc/init.d/S99userservices

package/batocera/core/batocera-scripts/scripts/batocera-services
- Ensure service name is valid before enabling service
- Warn if script name is invalid when listing services
- Correctly construct list of remaining services during disable
=> Validate service names, disable correct service

board/batocera/dropbear_localoptions.h, board/batocera/fsoverlay/etc/init.d/S12populateshare, board/batocera/scripts/post-build-script.sh
Savvy users will use the OpenSSH `ssh-copy-id` script on remote systems to install their SSH keys to the authorized_keys file on Batocera.  The behavior of that widely deployed script is to target /etc/dropbear/authorized_keys when the remote system is running dropbear.
Before this patch, /etc/dropbear was a symlink to /userdata/system/ssh so that system keys would be written to that location. User keys are stored in /userdata/system/.ssh along with the authorized_keys and known_hosts files.
This patch maintains the separation of user keys/data from system keys, while allowing ssh-copy-id to function properly.
=> Fix dropbear directory layout for ssh-copy-id, fixes #5540

package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone, package/batocera/emulationstation/batocera-emulationstation/xorg/xinitrc
dbus-launch is currently run from xinitrc, which causes two bugs:
- Trash can is not visible in pcmanfm on Wayland systems
- Trash can can not be viewed or emptied on X11 systems because HOME is not set in dbus-launch environment (#4644)
=> Fix pcmanfm trash can, fixes #4644

package/batocera/emulators/dolphin-emu/011-savestate-with-romname.patch
current dolphin savestates names have the internal game name.
not easy to handle them.
with this patch :
- the savestates have now the romname + .st<num>
- a screenshot is taken to have a .png file with it.
the drawback : you have to rename your saves...
=> dolphin savestate as rom name

board/batocera/x86/genimage.cfg
Improves disk performance and reduces wear.
Ref: https://www.thomas-krenn.com/en/wiki/Partition_Alignment_detailed_explanation
=> Align x86 partitions to 1M

package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.wayland
Convert mHz to Hz for correct human-readable units in wayland batocera-resolution listModes
Tested on bcm2711 Raspberry_Pi_4_Model_B_Rev_1_4
Old output:
```
max-1920x1080:maximum 1920x1080
max-640x480:maximum 640x480
1920x1080.60000:1920x1080 60000 Hz
1920x1080.59940:1920x1080 59940 Hz
1920x1080.50000:1920x1080 50000 Hz
1920x1080.30000:1920x1080 30000 Hz
1920x1080.29970:1920x1080 29970 Hz
1920x1080.24000:1920x1080 24000 Hz
1920x1080.23976:1920x1080 23976 Hz
1680x1050.59954:1680x1050 59954 Hz
1400x1050.59948:1400x1050 59948 Hz
1600x900.60000:1600x900 60000 Hz
1280x1024.75025:1280x1024 75025 Hz
1280x1024.60020:1280x1024 60020 Hz
1440x900.59901:1440x900 59901 Hz
1280x800.59910:1280x800 59910 Hz
1152x864.75000:1152x864 75000 Hz
1280x720.60000:1280x720 60000 Hz
1280x720.59940:1280x720 59940 Hz …
```
=> Scale refresh rates to Hz for Wayland mode list

batocera-Changelog.md, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/xenia-canary/xenia-canary.mk
Flag ZAR exentsion as incompatible with normal xenia as only xenia-canary supports ZAR files so far.
=> Bump xenia-canary, add ZAR support for xbox360 system

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulators/pcsx2/disable-pine-breaking-mangohud.patch
Even if not enabled, the PINE server is disabled causing an error when mangohud is enabled, and reseting the emulator to the bios. PINE seems to be a upnp server. The project url provided in pcsx2 seems to not work anymore.
=> disable (completly) PINE from pcsx2.

package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/utils/batocera-wine/batocera-wine
Now for enable DLSS we need to use DXVK 2.x & `NVAPI` ON.
Also NVAPI is part of DXVK so you need to enable `DXVK` ON
But you can disable NVAPI and is disable on prefix too that help some games on AMD GPU not support NVAPI.
=> Finish DLSS

package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/utils/batocera-wine/batocera-wine
Fix NVAPI to ENABLE_NVAPI for no create confusion when is disable/enable with ES.
All test is passed.
=> Fix NVAPI Enable

package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
As long times promised, I'll bring back modability back to the ecwolf core.
ecwolf offers lot of command line parameters like
```
--data {wl6, sod, wl1 extension}
--extravbls
--file (this is the resource for mods)
type ecwolf --help for more
```
I slightly changed the generator to differ between a directory (Wolfstein 3D.ecwolf) with the separated game files (sod, wl6, n3a) inside and a file (Wolfenstein 3D High Resolution and Music Pack.ecwolf)
A file example could be
**Wolfenstein 3D High Resolution and Music Pack.ecwolf**
```
./wolf3d_14 --data wl6 --file ../addons/HD/ECWolf_hdpack.pk3 ../addons/HD/ECWolf_hdmus_3DO.pk3
```
To explain
My wolf3d_14 works as basedir for the full version of Wolfenstein but does also contain Spear of Destiny therefore I've to set dataset to wl6 extension, …
=> ecwolf modable again

package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
I've restored usage of pk3-files, too!
Nevertheless I recommend the use of the .ecwolf method - this offers much more options for fine tuning your games brought by https://github.com/batocera-linux/batocera.linux/pull/9869
We have 3 methods now to launch Wolfenstein now:
1. Directory method: Create a directory with .ecwolf extension for example "Wolfenstein 3d.ecwolf" and then put the wl6 or wl1 data there and you are fine
2. .pk3-mod method: Inside this folder you can put pk3 files for example totenhaus.pk3, in ES you can directly start the mod with pk3 file
3. .ecwolf-file method: Create a file with .ecwolf extension and set aditional parameters there, first argument is intended to be a directory like `./wolf3d` where your Wolfenstein dataset is contained, followed by additional …
=> ecwolf fix for file pk3 extensions and savegame location

package/batocera/core/batocera-configgen/configgen/configgen/generators/ecwolf/ecwolfGenerator.py
1. Savegames are now saved to a directory according to the called file/dir ecwolf was started from
2. config file is not fully recreated per ecwolf-start now, that keeps highscore and some specfic settings alive. Resolution is still changed according ES settings, joypad is always enabled **(devs: take looks to line 43 and 55 if you plan to add more options to EmulationStation-ecwolf setup)**
3. Changes according PR https://github.com/batocera-linux/batocera.linux/pull/9869 and https://github.com/batocera-linux/batocera.linux/pull/9893 are still working
Start methods:
1. Directory .ecwolf with gameset included (as descriped to wiki)
2. File .ecwolf with one line of commands, first argument can work as relative path to point to Wolfenstein/Spear/Noahs gameset
3. File .pk3 - but pk3 files …
=> ecwolf fixes (Savegame location, config file)

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
Fixed problem:
libretro-beetle-pcfx can use m3u
but EmulationStation cannot recognize
The way:
- add settings to es-systems.yml
- add settings to libretroControllers.py to control by UI
=> [Add] m3u to pcfx

package/batocera/controllers/gun4ir-guns/99-gun4ir.rules
Name of hardware is correct (and tested), but unsure if the code is good. Just delete the `Pro` in the light gun name.
=> Add non-Pro GUN4IR light gun

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py
Change default value for the retroarch fps_update_interval value from 256 to 30.
Note that the value is in frames. FPS counter is updated every X frames.
Default of 256 results in on screen fps counter updating every 4.26 seconds based on a 60 Hz display.
Updated value of 30 would update on screen fps counter every 0.5 seconds based on a 60 Hz display.
The updated value is beneficial to those using systems that mangohud is not available for.
If hard coding an updated value is not desirable we could add a user selectable ES setting to allow a user to select from several choices. But I believe there is little benefit in adding yet another ES option and simply hard coding it to a newer value is much better.
=> Update value for retroarch fps counter interval to be more inline with mangohud

package/batocera/emulators/vpinball/vpinball.mk, package/batocera/libraries/libpinmame/libpinmame.mk
The latest versions include several bug fixes for VPinball and B2S Backglasses:
- Solenoid fixes
- Rotation fixes
- Animations
- LED Segments
- FlexDMD tween fixes
- B2S DMD displays
- DMD and B2S rendering only on changes
=> fix vpinball with pinmame and b2s backglasses

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg, package/batocera/emulationstation/batocera-es-system/es_features.yml
- ES - Move DS4 gyro and mouse controllers settings in Wii system
- ES - Add Controller 1-4 submenu and move GC Port controller type into new submenus, and add new GameCube controller type
- ES - Add alt input mapping settings for standard controller type per controller. (Rotate face buttons CW/CCW)
- ES - Add deadzone and joystick gate size settings per controller
- ES - Add Dolby Pro Logic II setting
+Dolphin+
New logic for controller type and various other controller settings on a per controller basis.
Changed default audio backend to Cubeb. ALSA(current default) is not compatible with DPLII+surround, moreover Cubeb is now the recommended default on Dolphin windows side.
If L1 is mapped on a controller GC games will now utilize either L1 or R1 as "Z". No more button that doesn't do …
=> Major Dolphin Configgen Update / Bug Fix

package/batocera/emulationstation/batocera-emulationstation/wayland/sway-launch
=> Allow sway to start with no keyboard or libinput devices, fixes #10098

board/batocera/riscv/linux-defconfig-fragment.config
On riscv, CONFIG_INPUT_UINPUT is set in kernel config fragment, but is dependent on CONFIG_INPUT_MISC which is not set.  Therefore the /dev/uinput device is missing, and libevdev_new() will always fail (ENOENT).
This patch enables the missing config option.
=> Enable uinput for riscv

board/batocera/fsoverlay/etc/init.d/S12populateshare
Added start/stop event
According to [Batoceras Wiki](https://wiki.batocera.org/launch_a_script#s12populatesharefirst_after_userdata_mount_last_before_userdata_gets_unmounted)
=> S12populateshare start/stop for user script

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
The new version, not the one from the 80s.
=> Atari VCS 2600 classic controller support (1st part)

package/batocera/core/batocera-configgen/scripts/call_achievements_hooks.sh, package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-led-effects
This can be extended to other PCs with addressable LEDs when we have access to them.
https://github.com/batocera-linux/batocera.linux/assets/21372356/0ca550bb-e9dc-4991-99a3-b65eeceef11d
=> Retroachievements: LED rainbow effet on Ayn Loki

package/batocera/core/batocera-scripts/scripts/batocera-services
Alphabetic characters in Bash variable names must be ASCII even in non-ASCII locales.
=> Fix service script name validation

package/batocera/core/batocera-scripts/scripts/batocera-info
Show UEFI boot mode and Secure Boot state in output of `batocera-info --full`
=> Show UEFI boot mode and Secure Boot state

board/batocera/fsoverlay/etc/init.d/S99userservices
PS: bash is such as bad - for proper reg expressions use LC_ALL=C
Avoid [[ $a =~ regex-expression ]]
tested and working with suggestion for users how to rename file (@n2qz as you wished, but please do the service-change on your own)
```
[root@BATOCERA /userdata/system/services]# /etc/init.d/S99userservices
User Service: SanitizerApp -> service is disabled [ok]
User Service: GrüßGott -> suggest rename sevice file to: 'GrGott' [ko]
User Service: underscore_test -> service is disabled [ok]
User Service: 1sttest -> suggest rename sevice file to: 'sttest' [ko]
User Service: 12345gh -> suggest rename sevice file to: 'gh' [ko]
User Service: 1234567.sh -> suggest rename sevice file to: 'sh' [ko]
System Service: ledspicer -> service is disabled [ok]
System Service: syncthing -> service is disabled …
```
=> S99userservices - finally

package/batocera/core/batocera-scripts/scripts/batocera-switch-screen-checker
Fix a mostly-harmless error message from the switch-screen-checker
```
[root@nardole /userdata/system]# /usr/bin/batocera-switch-screen-checker
/usr/bin/batocera-switch-screen-checker: line 6: /etc/profile.d/04-sway.sh: No such file or directory
```
=> Fix error message in script for hot switching of video outputs on x86_64

package/batocera/core/batocera-scripts/scripts/batocera-info
Capture stderr messages such as "This system doesn't support Secure Boot" when querying Secure Boot status
=> Capture stderr when fetching sb-state

package/batocera/firmwares/alllinuxfirmwares/alllinuxfirmwares.mk
- removed AX101 workaround in favor of the new dedicated firmware
=> update allinuxfirmwares to 20231030

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
This PR contains a refactoring of the generator for the cemu controller configuration.
It contains a pure refactoring without changes to the behavior, and it is tested.
Content:
* Use `join()` instead of string concatenation when building file paths
* Remove dependency on minidom
* Use functions to reduce code duplication
* Remove unused variable `addIndex`
(Looking at the history, I guess this could be something for @dmanlfc)
=> Refactor generator for cemu controller config

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Fixes issue originally reported in the ES repository https://github.com/batocera-linux/batocera-emulationstation/issues/1561
Scrape msx1, msx2, msx2+, msxturbor games from correct systems in screenscraper, instead of from "pc"
=> Fix msx* platform names to align with ES PlatformId.cpp, fixes #10365

package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
Fixes #10220 .  Tested on bcm2711 and rk3326 (rg351m).
=> Allow CUSTOMESOPTIONS to be set when not running xorg, fixes #10220

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/Generator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/cgenius/cgeniusGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/flatpak/flatpakGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/lightspark/lightsparkGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/ruffle/ruffleGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/sh/shGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/sonicretro/sonicretroGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/steam/steamGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/theforceengine/theforceengineGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/vita3k/vita3kGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/wine/wineGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
- Enable mouse for known versions of soniccd roms requiring
touchscreen navigation.  See wiki for details on this rom:
https://wiki.batocera.org/systems:sonicretro
- Add rom parameter to getMouseMode() method on Generator objects
(BREAKING API CHANGE)
=> Enable mouse cursor when required for soniccd

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
Justifier controller type (PSX) + crosshair (disabled by default) + correct mapping.
Only affecting default core (libretro:pcsx_rearmed). Use clean ROMs or force GunCon controller type. Nuvee patch is incompatible.
=> add justifier gun type as default for justifier gun games

package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-powermode, package/batocera/emulationstation/batocera-es-system/es_features.yml
Add new ES powermode setting. Both global and shared for every system. I basically just added it to any system with also a videomode which made the most sense to me.
Allows user control over cpu governor for a better and more dynamic system power/performance usage.
This would be greatly beneficial for handhelds, as well as mini pc's since users would be able to customize power profiles per system or globally to maintain any battery, electricity, or temp needs.
=> Powermode feature

package/batocera/core/batocera-scripts/scripts/batocera-powermode
Somehow I overlooked the removal of SYSTEM_NAME when I was cleaning up the original script before submitting the PR. Without the system_name event per system powermode settings were being ignored.
Also note that when I manually updated the script after susan moved it to usr/bin it was no longer receiving the proper events.
The script has to either go in a directory receiving applicable events, or if the script is to remain in usr/bin the events need to call that directory from the emulatorlauncher.py script. Otherwise it will be broken.
OR if someone can suggest a way to call the script to pass the needed values before a game launches and again when it closes that could be another option. Currently I just have it in the original location on my personal machine …
=> fix-powermode

package/batocera/emulators/retroarch/libretro/libretro-mame2003-plus/libretro-mame2003-plus.mk, package/batocera/emulators/retroarch/libretro/libretro-mame2010/libretro-mame2010.mk
Disk space in datainit is at a premium, as the fallback ramdisk has a total of 256M available.
Around 20% of this space is consumed by lr-mame 2003 and 2010 XML DAT files.  While these files are handy to have in the distribution, they are not directly used by the installed system.  A significant chunk of space can be saved by compressing them with gzip at the highest compression ratio.  Users can easily decompress them if needed for reference or to validate a romset.
=> Compress lr-mame xml DATs with gzip, fixes #8556

board/batocera/fsoverlay/etc/init.d/S11share
In abandoned PR #10296 the code to mount the ramdisk SHARE was refactored into a single function.
This PR retains only the refactoring, without changing the ramdisk size.
=> New function to mount ramdisk, to keep it DRY

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
This adds a flag in the advanced game options for atari800 to enable or disable the Atari BASIC ROM. BASIC is disabled by default in the atari800 emulator, so this is necessary for booting into BASIC disks or cartridges.
This adds two new translatable strings, and I included the automatic .po file changes in this commit.
=> Expose the atari800_internalbasic option

batocera-Changelog.md, package/batocera/utils-host/xa/xa.mk
Bump xa to 2.4.0 to fix build failure on clean system after source package was moved to archive directory.
Built and tested with vice for x86_64 and bcm2711.
=> Bump xa to 2.4.0

package/batocera/emulators/vpinball/vpinball.keys
Some tables (Indiana Jones TPA, Judge Dredd,...) allow the player to buy an extraball (or multiball session with Judge Dredd) for a credit. It's mapped to "2" key, but this will allow to fully control the pinball with a gamepad.
I also cleaned up the file a little bit (with the spaces).
=> update vpinball.keys to add buy extraball button

package/batocera/core/batocera-scripts/scripts/batocera-install
Fix some bugs in batocera-install:
- warning about stray backslash before quotes in "grep" regexp
- progress indication stopping around 31% of download
- image file being redownloaded when present and correct size
Fixes #6588
=> Fix some bugs in batocera-install

package/batocera/emulators/vpinball/vpinball.keys
A few pinball machines have a canon fired by a button at the bottom of the pinball. Examples: Ac/Dc, Terminator 2,...
It'll be convenient to have this mapped next to launch button on the gamepad.
=> Vpinball: Add Lockbar Fire Button

board/batocera/patches/efibootmgr/001-return-entry-if-found-before-end-of-list.patch
Patch to address a bug in the current version of efibootmgr, described at https://github.com/rhboot/efibootmgr/issues/186
=> Bug fix, efibootmgr cannot set boot entries active/inactive

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Depends on https://github.com/batocera-linux/batocera-emulationstation/pull/1593
=> Change cplus4 platform from c64 to cplus4

package/batocera/core/batocera-configgen/scripts/powermode_launch_hooks.sh
Updated code to make sure the system default governor is applied in the instance where it may get "stuck" as something other than system default and a game is launched with no powermode defined (auto).
=> Ensure cpu governor default if powermode not defined

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk
* Bump libretro-dosbox-pure to 0.9.8
* Remove workaround from #7351, because it was fixed in https://github.com/schellingb/dosbox-pure/commit/00495dd91dc4e471f6bff64befac211ee1ad0531 (related to https://github.com/schellingb/dosbox-pure/pull/382).
CC: @jdeath @lbrpdx
=> Bump libretro-dosbox-pure to 0.9.8 and remove workaround

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/emulators/retroarch/libretro/libretro-mame/004-batocera-ini.patch
- lr-mame no longer parses computer.ini, add and use our own batocera.ini to restore autoboot functionality
- Correct autoboot configgen for bbc micro, fixes #10402
=> Fix lr-mame autoboot

package/batocera/core/batocera-scripts/scripts/batocera-info
- Architecture is provided by $(uname -m)
=> batocera-scripts / batocera-info updated to report V_BOARD as board

package/batocera/core/batocera-scripts/scripts/batocera-upgrade
Use curl instead of wget when running on a terminal, to allow upgrade from of local files using "file://" url scheme
=> Allow upgrade from of local files using "file://" url scheme

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
es_features value "rpcs3_async_texture" did nothing in rpcs3Generator configgen.
Fixed it so now adjusts setting in rpcs3 config. Also changed description to notate this setting is compatible with Vulkan only.
=> rpcs3-fix-AsyncTexture

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
Added additional frame limit settings for a more granular control over fps. Particularly useful in games with a variable fps where using a specific frame limit can result in an overall more consistent frame rate.
Changed SPU cache to True. RPCS3 Devs removed this setting from the GUI because they found no use case for disabling it as it would always result in a performance loss due to a SPU module having to be recompiled at every game launch vs loading from cache. RPCS3 devs have enabled by default. Eventually will probably be best to just remove the line but I thought it best for now to change to True to account for updates where existing config file is present.
=> rpcs3-AdditionalFrameLimits-UpdateDepreciatedSetting

board/batocera/fsoverlay/etc/init.d/S11share
The workaround used in V38 to prevent use of the "ntfs" driver (which we no longer ship) isn't satisfactory, and has some side effects on mounting other filesystem types.
- Instead of using "mount -t nontfs", detect the filesystem type and mount using that type explicitly.
- For the ntfs case, replace it with ntfs-3g.
=> Replace the previous ntfs workaround

Makefile
Allow overriding webserver directory for a specific BOARD. Don't hide web server command, to provide information on what's being served.
Replaces and closes #8809
Example:
```
(bugfix/webserver-board)entropy@katarina:~/batocera.linux$ make riscv-webserver
Makefile:193: *** "Directory not found: /home/entropy/batocera.linux/output/riscv/images/batocera/images/riscv".  Stop.
(bugfix/webserver-board)entropy@katarina:~/batocera.linux$ make riscv-webserver BOARD=visionfive2
python3 -m http.server --directory /home/entropy/batocera.linux/output/riscv/images/batocera/images/visionfive2/
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```
=> Allow overriding webserver directory for a specific BOARD

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg, package/batocera/emulationstation/batocera-es-system/es_features.yml
Added ES settings for controller input mapping for genesisplusgx + picodrive libretro cores. (Could be added for genesisplusgx-wide core but there are NO es settings for this core currently so I assume it's mostly unused)
For use when using a megadrive style controller with 6 face buttons. Controllers can be mapped in ES with recommended mappings then select new ES setting to automap correct inputs in-game.
retropad = default PS/Xbox style controller
megadrive = any megadrive style controller with 6 face buttons.
Recommended mappings for megadrive style controller in ES:
A = SOUTH
B = EAST
C = R
X = WEST
Y = NORTH
Z = L
=> automap-inputs-genesisplusgx-picodrive

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py
General code cleanup and added ability to auto config based on controller guid/name, increasing plug-and-play-ability.
Currently only the official nintendo switch n64 controller and the 8bitdo n64 modkit are included but others can be added later. Note that any user using a controller that does NOT have a dedicated hotkey button should still use the es setting for limited hotkeys as controller type and at least currently should not have the controllers guid added to auto config.
=> N64 libretro + mupen code cleanup and added n64 controller auto config 

batocera-Changelog.md, board/batocera/fsoverlay/etc/init.d/S08connman, board/batocera/fsoverlay/etc/init.d/S26system, board/batocera/fsoverlay/etc/init.d/S65values4boot, package/batocera/core/batocera-system/Config.in
- save system.hostname to batocera-boot.conf
- set hostname before starting connman
- configure connman to send hostname (BR2_PACKAGE_CONNMAN_LOOPBACK)
- set default hostname for first boot
- allow for both static and dynamic hostname configuration
- fixes #7502
=> Send hostname in DHCP request, fixes #7502

board/batocera/fsoverlay/etc/init.d/S11share
- Only include devices which have both TYPE and UUID tags to skip garbage like /dev/loop*
- Sort devices for slightly more consistency and predictability
- Fixes #3455
=> Be more selective about ANYEXTERNAL devices, fixes #3455

board/batocera/fsoverlay/etc/bluetooth/input.conf, board/batocera/scripts/post-build-script.sh, package/batocera/core/batocera-bluetooth/S32bluetooth.template
Set `ClassicBondedOnly=false` only when `controllers.bluetooth.enabled`=1 and `controllers.ps3.enabled`=1.
`ClassicBondedOnly=true` (which is default starting BlueZ 5.71) fixes [CVE-2023-45866](https://ubuntu.com/security/CVE-2023-45866), but also breaks compatibility with PS3 (and possibly some legacy other) controllers. 
Hence when PS3 controller support is enabled (when `controllers.bluetooth.enabled`=1 and `controllers.ps3.enabled`=1) `ClassicBondedOnly` is set to `false`.
Additionally this PR fixes removal of the file `/etc/init.d/S40bluetoothd` (which unsuccessfully tries to do a subset of what `S32bluetooth` does).
=> Bluetooth: dynamically set ClassicBondedOnly

board/batocera/scripts/post-build-script.sh
In Batocera `/etc/iptables.conf` is on volatile file system, so there is not much use for saving iptables configuration to this file.
The best option is to put `iptables` commands in `/boot/boot-custom.sh` - then they will be invoked early in the startup, before any network services start.
=> Use /userdata/system/iptables.conf in S35iptables

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
puae have 2 missing video_standard options:
- PAL auto
- NTSC auto
(and "PAL auto" is the default in retroarch)
These auto formats, allow to switch to another video_standard if it's defined in romfile path. This is important to automatic correct aspect ratio.
for example:
with "PAL auto", for a game with romfile "mygame_NTSC.adf", It'll auto switch to NTSC.
=> libretro: puae: add missing video_standard options

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
Yabasanshiro core has the Saturn pad C and Z inputs reversed. This fix corrects the default retroarch mapping to be in line with both Kronos and Beetle cores.
Also of note is that the Yabasanshiro core is unmaintained so issue is unlikely to be fixed upstream.
=> Yabasanshiro-InputFix

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Add ES settings for libretro N64 cores. Note that because these are core options they are global for the core. Meaning they effect all controllers. ES descriptions states this so users are informed.
Unfortunately at this time there is no way to adjust deadzone/sensitivity per player controller.
If Retroarch or the core maintainers ever update to accommodate per player deadzone/sensitivity settings I will revisit this.
=> LibretroN64-Deadzone/Sensitivity

board/batocera/fsoverlay/etc/init.d/S11share, package/batocera/core/batocera-scripts/scripts/batocera-config
1. filter LVM partitions from "batocera-config storage list" as they aren't mountable
2. activate available logical volumes ~~that match a prefix~~ before mounting /userdata in S11share
These two changes are interrelated. Logical volumes need to be activated so that are visible to `lsblk` and can be presented in the ES system settings storage menu. Once the partitions are activated (TYPE="lvm") they need to be added to the output of `batocera-config storage list` and the partition the LVs reside on (FSTYPE="LVM2_member") should be excluded from the list.
I'm creating as a draft because I'd like comments on the decision to use a prefix to limit the LVs available to for mounting, as well as entertain any questions on the implementation. All feedback is welcome.
=> Allow LVM partitions to be used for storage

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Remove squashfs from mugen extensions, closes #6968
=> Remove squashfs from mugen extensions, closes #6968

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk, package/batocera/emulationstation/batocera-es-system/es_features.yml
Add es feature for libretro cores(n64 and sega systems) that enable 16:9 aspect ratio for games that natively supported widescreen. 
Needs https://github.com/batocera-linux/batocera-emulationstation/pull/1660 to be merged first so that gamesdb.xml is updated. Once it's merged I can bump es and then this PR will be ready to merge.
=> libretro-autowidescreen-n64-segasystems

batocera-Changelog.md, package/batocera/core/batocera-system/Config.in
Enable swap on rpi through rpi3 to improve suppport for low-memory variants e.g. Zero 2W
=> Enable swap on rpi through rpi3

package/batocera/core/batocera-configgen/configgen/configgen/generators/xemu/xemuConfig.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
I wanted to have the possibility to use/configure system link from the couch.
So, this adds the ability to turn the network on, in order to:
1.  configure internet access (via nat) (to import save games for eg)
2. or to configure System Link for local (or remote with a public server) play (via udp) with another xemu computer.
Default settings are:
- network turned off to avoid an error message if the computer is disconnected from the wifi (for example)
- if the remote and bind fields are empty, then the values present in /userdata/system/config/xemu/xemu.toml are left untouched. This allows manual editing of the config file.
It's just  little improvement because these settings are accessible only by pressing the hotkey to overlay the xemu config window, and navigation inside this window …
=> xemu configgen network part

package/batocera/core/batocera-configgen/configgen/configgen/generators/vpinball/vpinballGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Closing #10785 in favor this one (due to merge problems on my local branch (and too limited github skills...)), so that it's one commit only (will be cleaner).
This allows to set the new (and old also, as the current configgen is very limited) options of vpinball through the gui.
=> vpinball configgen improvements (v2)

package/batocera/core/batocera-configgen/configgen/configgen/generators/vpinball/vpinballGenerator.py
In the current situation, if there's no /userdata/system/configs/vpinball/VPinballX.ini, es launch crashes.
With this modification, if there's no configfile, it starts by copying from /usr/bin/vpinball/assets/Default VPinballX.ini to /userdata/system/configs/vpinball/VPinballX.ini
Thanks @Modhack for testing.
=> solves: vpinball configgen crashes if missing configfile

package/batocera/core/batocera-configgen/configgen/configgen/generators/xash3d_fwgs/gamepad.cfg, package/batocera/core/batocera-configgen/configgen/configgen/generators/xash3d_fwgs/xash3dFwgsGenerator.py, package/batocera/ports/xash3d/xash3d-fwgs/0001-Enable-VSync-by-default.patch
1. Enable vsync by default. Even an rk3326 can run Half-Life at 60 FPS, so on is a better default.
2. Set a default deadzone.
=> xash3d_fwgs improvements

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Cleans up duplicate M30 entry. Also maps according to new recommended default mapping in edition to using the following info from 8bitdo using the dpad as HAT and not a joystick.
```
LEFT + Select : set Dpad as left analogue stick.
Up + Select : reset Dpad.
Right + Select : set Dpad as right analogue stick.
Down + Select : Swap A/B and X/Y mapping (on Switch mode only).
*Press and hold any of the key combinations above for 5 seconds to map the buttons.
*LED will blink in red to indicate the success of each button mapping.
*You need to reset the buttons manually.
```
should resolve https://github.com/batocera-linux/batocera.linux/issues/10869
=> Update es_input.cfg - M30 cleanup

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
I want to go ahead and map the "left joystick" so out of the box the controller will work regardless if dpad is in HAT mode or left joystick mode. But it's recommended to use HAT mode for the dpad. Note this is only for when the controller is in x-input mode. When in d-input mode using dpad as left joystick does not work.
=> M30-add-leftjoystickmapping-xinputmodeonly

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Inputs are for both D-input and X-input modes. Note holding C-right and C-up for about 3 seconds switches between modes. This controller does not have a dedicated button for hotkey, or a select button so hotkey is mapped to L shoulder.
Recommended to use N64 ES setting controller type N64-Limited hotkeys with controller.
=> Add Tribute64 controller recommended input mappings

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Removed the old language selection behavior based on the batocera environment.
For example, if you want to play an Italian GC game, you have to set batocera to Italian.
Dolphin seems to only recognize the key=value `SelectedLanguage`,
and nothing else in Dolphin.ini for selecting the language.
Users can now select the desired Gamecube language in ES.
I only compiled `batocera-configgen` and `batocera-es-system`
Tested it on batocera butterfly and it works.
=> Dolphin standalone language selection from ES

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
The DS motion control option does not work on my PS5 controllers. evdev sees the controllers as 3 devices: Controller, Controller Motion Sensors, and Controller Trackpad. This pull request enables the Motion Sensors controller in the config to allow the DS controller's gyros to be used for the Wii.
Since the motion is on the gyro, I want the controllers to emulate the Nunchuk on Joystick 1.  This eliminates conflicts from joystick drift or accidental touch on the standard motion configuration.
This is my first pull request for Batocera... please let me know if I missed any steps in submitting this.
=> Dolphin Motion Controls Fix for DualSense Controllers

board/batocera/rockchip/rk3588/firefly-station-m3/boot/extlinux.conf, board/batocera/rockchip/rk3588/firefly-station-m3/create-boot-script.sh, board/batocera/rockchip/rk3588/firefly-station-m3/genimage.cfg, configs/batocera-rk3588.board, package/batocera/core/batocera-system/Config.in
Add ROC-RK3588S-PC board Support.
[https://en.t-firefly.com/product/industry/rocrk3588spc](url)
Station M3 Mini PC is a consumer device based on this board.
[https://www.stationpc.com/product/stationm3](url)
=> Add ROC-RK3588S-PC Support

package/batocera/emulationstation/batocera-es-system/es_systems.yml
This is a following of my first attempt to fix the current bad situation
Currently, for the steam platform scrapping returns very poor results.
Eg, for this game (https://store.steampowered.com/app/1342260/SAMURAI_SHODOWN/): the scrapper returns way too many results which are not relevant at all (example here are games exclusive to xbox360 or neo geo pocket), so it's a mess.
With this fix, for the same game, it gives correct results:
The initial discussion is here:
https://github.com/batocera-linux/batocera-emulationstation/pull/1679
I followed the advice of @fabricecaruso, but I did this only for steam as I can't test for windows games (https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_systems.yml#L2299).
=> improve steam scrapping results

package/batocera/libraries/libliftoff/libliftoff.hash, package/batocera/libraries/libliftoff/libliftoff.mk
Fix -Wsign-conversion on 32-bit
=> libliftoff: bump to 0.4.1

board/batocera/allwinner/h3/cha/boot/extlinux.conf
When browsing games, worse if moving fast, Emulation Station freezes for long periods and then the whole system will stop responding/crash.
=> [v39] Fix ES hanging and system crashing when browsing games lists

package/batocera/firmwares/alllinuxfirmwares/alllinuxfirmwares.mk
Bump linux-firmware to [20240220](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tag/?h=20240220).
=> Bump linux-firmware to 20240220

package/batocera/utils/batocera-wine/batocera-wine
fix sandbox function is overriding the global DIR variable,
breaking the play_pc(),  "drive_c/windows/system3/dx*.dll" symlink when dxvk is not enabled
fix https://github.com/batocera-linux/batocera.linux/issues/11060
=> batocera-wine: fix sandbox local DIR variable

board/batocera/fsoverlay/etc/init.d/S31sixad
Currently sixad is started if `controllers.ps3.driver` is set to `official` or `shanwan`, and `controllers.ps3.enabled` is set to `1`.
This happens even if `controllers.bluetooth.enabled` is set to `0`.
With this PR sixad is started if `controllers.ps3.driver` is set to `official` or `shanwan`, and `controllers.ps3.enabled` is set to `1`, **and `controllers.bluetooth.enabled` is set to `1`**.
@dmanlfc
=> Start sixad only if Bluetooth is enabled

board/batocera/fsoverlay/etc/init.d/S12populateshare
Submitted PR on behalf of another user:
cjom:
"Hi! I found a bug in /etc/init.d/S12populateshare but I can't do a PR because I can't find the package where it comes from (I had deleted my entire "dl" folder after building, to save some space...
The problem is in lines 111 and 118. This is supposed to copy newer files and folders after a system update, but when copying a folder over an existing folder it will create a new folder with the same name inside the older one. For example, instead of updating /userdata/bios it will create the new folder /userdata/bios/bios
Please change the lines 111 and 118 from: cp -rf "${IN}/${FILE}" "${OUT}/${FILE}"
to: cp -rf "${IN}/${FILE}" "$(dirname "${OUT}/${FILE}")"/
This will work as intended, either with files or folders."
I have experienced this bug …
=> CriticalFix-V39-duplicate-folders

package/batocera/utils/batocera-wine/batocera-wine
it could be usefull to use differents wine versions for specific games in case of regression.
simply but a specific version in /userdata/system/wine/<wineversion>
then use <system>.core=<winversion> ,  or windows["<gameid">].core=<winversion>
=> batocera-wine: allow custom wine_versions

package/batocera/utils/batocera-wine/batocera-wine
for example, wine-ge official build are using /lib64/wine
=> batocera-wine: allow to use custom wine build with /lib64/wine directory

package/batocera/emulators/vpinball/vpinball.mk, package/batocera/libraries/libaltsound/libaltsound.mk, package/batocera/libraries/libdmdutil/libdmdutil.mk, package/batocera/libraries/libpinmame/libpinmame.mk, package/batocera/libraries/libzedmd/libzedmd.mk
- new libdmdutil which makes multiple copies of the dmd buffer needed for in game dmd and external windows.
- new pinmame that supports pwm lights and modulated solenoids
- new vpx that's is based on 10.8.0 rc 1 with some memory leak fixes
- support for reordering external windows so pinmame and flex external windows are above b2s external windows.
can wait until v40.
=> [v40] vpinball: update libdmdutil, libpinmame, libaltsound, libzedmd, and vpinball

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Fixes invalid values error in the rpcs3 configgen for frame limits.
Frame limit only accepts specific values: Off, 30, 50, 59.94, and 60.
Second Frame Limit can accept any float/integer value, so the configgen checks if the setting equals accepted values for the primary frame limit first, if not than applies to the secondary frame limit.
Default/Auto frame limit value of "Auto" for primary and 0 for seconday.
=> V39-fix-rpcs3-configgen

package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
Add "enable" and "disable" commands to `batocera-bluetooth`.
They are required for https://github.com/batocera-linux/batocera-emulationstation/pull/1682
=> [v40] batocera-bluetooth: Add "enable" and "disable" commands

package/batocera/core/batocera-system/batocera.conf
In `batocera.conf` for `controllers.ps3.enabled` add comment:
`## PS3 controller support enables CVE-2023-45866 security vulnerability. Disable if not needed.`
Idea is to inform users who manually edit `batocera.conf` that they might want to disable `controllers.ps3.enabled` if they are not planning to use PS3 controllers. 
Maybe the text can be improved.
@lbrpdx What do you think about this?
=> In batocera.conf add CVE comment for controllers.ps3.enabled

package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
1-lightgun only
- Fixes controller type (`GunCon` instead of `NamcoGunCon` that doesn't exist) 
- Fixes gun mapping (`A`, `B`, `Trigger`)
- Add setting for crosshair in ES (`ON`, `OFF`)
=> fix DuckStation lightgun (v40)

package/batocera/core/batocera-system/batocera.conf
Mention that PS3 controller support might also be needed for some other controllers.
=> Minor improvement in batocera.conf comment

package/batocera/core/batocera-configgen/configgen/configgen/generators/vpinball/vpinballGenerator.py
the default config file changed from 
/usr/bin/vpinball/assets/Default VPinballX.ini
to
/usr/bin/vpinball/assets/Default_VPinballX.ini
=> Update vpinballGenerator.py to match new asset name

package/batocera/utils/ledspicer/001-userdata.patch, package/batocera/utils/ledspicer/ledspicer, package/batocera/utils/ledspicer/ledspicer.mk
Contains the following changes:
- Version bump to 0.6.0 (latest release)
- Patch the location of `colors.ini` to `/userdata/system/configs/ledspicer/colors.ini`, consistent with other config files in the original Batocera release of LEDSpicer (#10388)
- Set the default location of `ledspicer.conf` to `/userdata/system/configs/ledspicer/ledspicer.conf`, eliminating the need to manually specify the path to this config when invoking `ledspicerd` and `emitter`. (#10388)
=> LEDSpicer: Fix config locations & bump version

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
Since https://github.com/batocera-linux/batocera.linux/pull/11329 pcsx2 (butterfly) crashes on launch with the error:
```
File "/usr/lib/python3.11/site-packages/configgen/generators/pcsx2/pcsx2Generator.py", line 71, in generate
configureINI(pcsx2ConfigDir, pcsx2BiosDir, system, rom, playersControllers, metadata, guns, wheels, playingWithWheel)
File "/usr/lib/python3.11/site-packages/configgen/generators/pcsx2/pcsx2Generator.py", line 486, in configureINI
pcsx2INIConfig.set("USB2", "guncon2_cursor_path", "")
File "/usr/lib/python3.11/configparser.py", line 1220, in set
super().set(section, option, value)
File "/usr/lib/python3.11/configparser.py", line 918, in set
raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'USB2'
```
I'm not sure that setting it to …
=> fix broken pcsx2Generator.py

batocera-Changelog.md, package/batocera/core/batocera-udev-rules/rules/99-wheels.rules, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Gamepad mode only. It won't work in wheel mode (not supported by Linux kernel).
How to:
(Waiting for feedback...)
=> add T80 steering wheel support

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Checks es_settings for ES confirm/cancel inputs value and sets RA to match to keep input consistency automatically
=> Automatically set RA menu confirm/cancel inputs to match ES

package/batocera/emulators/retroarch/retroarch/023-change-dot-config-path-to-configs.patch
Batocera now uses "/userdata/system/configs" but RetroArch still creates "/userdata/system/.config/retroarch"
This was tested with RetroArch 1.18.0 in CHA build (allwinner H3).
=> RetroArch - change support folder from "~/.config/retroarch" to "~/configs/retroarch"

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
While trying to debug #11545, I turned on the newly implemented offscreen reload option in ES (#6704) and configgen craps out:
```
evmapy: no process found
2024-05-01 19:12:00,060 ERROR (emulatorlauncher:609):<module> configgen exception: 
Traceback (most recent call last):
File "/usr/bin/emulatorlauncher", line 607, in <module>
exitcode = main(args, maxnbplayers)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/emulatorlauncher", line 99, in main
return start_rom(args, maxnbplayers, args.rom, args.rom)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/emulatorlauncher", line 268, in start_rom
cmd = generator.generate(system, rom, playersControllers, metadata, guns, wheels, gameResolution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> fix typo in variable use in lightgun reload option

package/batocera/core/batocera-configgen/configgen/configgen/generators/vpinball/vpinballOptions.py
UI might be tricky in ES with the current menu, and I must be the only one with multiple audio outputs in my Batocera pincab right now, so if you want to use it:
- connect through SSH and run `/usr/bin/vpinball/VPinballX_GL -listsnd`
- select from the list you get the `<id>`s you want for your table audio output (ball sounds) and the one for your backglass (music and sound effects).
- add `vpinball.vpinball_sounddevice=<id>` (table) and  `vpinball.vpinball_sounddevicebg=<id>` (backglass) in your `batocera.conf`
=> VPinballX: add option for multiaudio (backglass + ball)

batocera-Changelog.md, package/batocera/core/batocera-bluetooth/S29namebluetooth, package/batocera/core/batocera-bluetooth/batocera-bluetooth.mk
- prevents multiple devices sharing the same generic Bluez name
- improves discovery / identification in 3rd-party apps
=> name the bluetooth adapter

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/mame/autoload/coco_cass_autoload.csv, package/batocera/emulators/mame/autoload/coco_flop_autoload.csv, package/batocera/emulators/mame/mame.mk
Color Computer (coco) .cas and .dsk files previously did not autoload like other systems (eg. apple2)
Drivers coco & coco3 as of MAME v0.261 have support for .dsk:
```
[root@BATOCERA]# /usr/bin/mame/mame -listmedia coco
SYSTEM           MEDIA NAME       (brief)    IMAGE FILE EXTENSIONS SUPPORTED
---------------- --------------------------- -------------------------------
coco             floppydisk1      (flop1)    .mfi  .dfi  .hfe  .mfm  .td0  .imd  .d77  .d88  .1dd  .cqm  .cqi  .dsk  .dmk  .sdf  .jvc  .vdk  .os9  
[root@BATOCERA]# /usr/bin/mame/mame -listmedia coco3
SYSTEM           MEDIA NAME       (brief)    IMAGE FILE EXTENSIONS SUPPORTED
---------------- --------------------------- -------------------------------
coco3             floppydisk1      (flop1)    .mfi  .dfi  .hfe  .mfm …
```
=> coco autoload .dsk and .cas support

package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation_legacy/duckstationLegacyGenerator.py
I wasn't aware we also have a "Duckstation Legacy" emulator for some boards.
=> Faster loading time when enabling RetroAchievements

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Reorganizing ES settings. Starting with Dolphin stand alone. This will be a long process so doing one system at a time.
Actually fixed an issue where rumble es setting was under wii system but it's actually global between wii+gamecube, so moved it under general dolphin and not in wii system.
Categorized ES settings into:
DISPLAY
RENDERING
EMULATION
AUDIO
CONTROLS
UI
Set global videomode and aspect ratio submenu "DISPLAY".
I also gave global wheels and lightgun es settings submenus and CONTROLS group. Used order 99/100 to ensure they are always at the bottom of the list. Pad profiles and rumble are used for gamecube and wii. And since controls seem to be a more complicated matter over other settings I thought it best to make CONTROLS a group so additional submenus can be used and organized …
=> reorganize-es-settings-dolphin

package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
Add Justifier controller type in DuckStation when a Justifier ROM game is detected from database; otherwise, set default gun type settings.
This is the end of nuvee patch. Forever.
=> DuckStation justifier gun type

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
I want to undo this change (and appreciate your willingness to merge it in quickly)
most critically, `-hashpath` isn’t even used in `libretroMAMEConfig` [more details](https://github.com/batocera-linux/batocera.linux/pull/11913#issuecomment-2153593152)
I am also seeing what I assume are legacy code references to `lr-mess` and commandArray is built completely differently [than in MAMEGenerator]
Sorry :(
Reverts batocera-linux/batocera.linux#11913
=> Revert "propagate coco autoload behavior from standalone MAME to lr-mame"

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
lr-mame inherits coco autoload behavior (#11706) with known issues:
1. lr-mame is sensitive to long filenames and/or filenames with spaces and symbols (workaround: create a symlink to original file with a shortened name removing all spaces and non-alphanumeric chars)
2. plugins not supported in lr-mame MESS - coco hiscore is only available in standalone MAME
3. Can’t access File Manager - swapping disks or changing cassettes (aka. flipping sides) is only available in standalone MAME
ok - that was a bit of an adventure discovering that standalone MAME and lr-mame are not 100% functionally equivalent (at least when it comes to MESS).
I got through all my coco test cases & made sure to boot non-MESS roms in lr-mame and MAME2010.
What doesn’t work in `lr-mame` is relatively minor (see below). …
=> propagate coco autoload behavior from standalone MAME to lr-mame

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
Manual texture sampling is a hack. So enabling setting should disable hack, while enabling setting should disable hack.
=> fix-dolphin-configgen

package/batocera/emulators/cemu/wiiu.keys
On Cemu the default shortcut listen CTRL+TAB
but the Batocera config targets ALT+TAB.
=> fix pad2key shortcut for switching TV/Gamepad screen on WiiU

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
Putting MAME BIOS files in `/userdata/bios/mame` is totally optional and available for those who wish to reduce the clutter in `roms/mame` and `/userdata/bios`
This commit only adds `/userdata/bios/mame` to the `-rompath` for **non-MESS** roms.
=> add support for MAME (standalone, lr-mame) BIOS files in bios/mame

package/batocera/core/batocera-udev-rules/rules/99-pedals.rules
Only required for hardcoded pedals which can't be rebinded in any tool. May change in the future.
First addition: **VEC Infinity 3 USB Digital Foot Control**
By default, this is for player 1 only. Center pedal is `C` key. Left pedal is `5` (for coins/select). Right pedal is `1` (for start).
=> initial database for hardcoded foot pedals

batocera-Changelog.md, package/batocera/core/batocera-udev-rules/rules/99-wheels.rules, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Waiting for feedback...
Must be set on `MODE 2` (gamepad).
This wheel has no FFB.
Xbox logo is HOTKEY.
=> add HORI Racing Wheel Overdrive support

package/batocera/emulationstation/batocera-es-system/es_systems.yml
3ds games can use a lot of space,  
citra emulator don't support compression format currently.
squashfs compression ratio is around 60% of original size
```
-rw-rw-r-- 1 root root 4.0G Jun 22 09:04 'Pokemon Ultra Moon.3ds'
-rw-r--r-- 1 root root 2.4G Jun 22 09:12 'Pokemon Ultra Moon.3ds.squashfs'
```
=> 3ds: add support for .squashfs

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
mrboom removed support for the `no monsters` option on 12th Jan - See https://github.com/Javanaise/mrboom-libretro/commit/553ddd34ac0199c0c549497d6a7558edb8bec462
=> mrboom no longer supports nomonster

package/batocera/core/batocera-configgen/configgen/configgen/generators/mugen/mugenGenerator.py
config rewrite for older mugen is broken since
https://github.com/batocera-linux/batocera.linux/commit/c97b6665669fc069c69954526b6d6839f74567b6
Width/Height are wrongly rewritten to GameWidth/GameHeight
newer version support both Width/Heigh  && newer GameWidth/GameHeight, so it was not breaking it
Older mugen support only Width= && Height=,  and crash at start with GameWidth/GameHeight, throwing a video config error.
=> fix mugen generator config rewrite

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Additional input configs for the following controllers. 
From the makers of the AVS,
[SNES RetroPort](https://www.retrousb.com/product/snes-retroport/25?cp=true&sa=false&sbp=false&q=false&category_id=XMUPJ4I27NZEHIOGMV3JUCBH), [NES RetroPort](https://www.retrousb.com/product/nes-retroport/24?cp=true&sa=false&sbp=false&q=false&category_id=XMUPJ4I27NZEHIOGMV3JUCBH) and [N64 RetroPort](https://www.retrousb.com/product/n64-retroport/34?cp=true&sa=false&sbp=false&q=false&category_id=XMUPJ4I27NZEHIOGMV3JUCBH)
The N64 controller was mapped to the recommended control layout here -> https://wiki.batocera.org/systems:n64#controls
The [May Flash F500 V2](https://www.mayflash.com/product/mayflash_arcade_stick_f500_v2.html) arcade stick in controller mode 
The [Sony Dualshock …
=> add controller support RetroUSB SNES/NES/N64, MayFlash F500 and PS3 Dualshock 3

package/batocera/emulators/hypseus-singe/singe.hypseus-singe.keys
Player 1 light gun and player 2 light gun. Useful for Hypseus Singe multigun versions of gun games (e.g.: Crime Patrol & Drug Wars).
=> add start/select on guns (Hypseus Singe)

batocera-Changelog.md, package/batocera/emulators/dolphin-emu/dolphin-emu.mk
There have been quite a lot of recent fixes in dolphin development version, including one that should help preventing DDOS of retroachievements.org, thus older versions with achievement support [will be blacklisted](https://retroachievements.org/viewtopic.php?t=27292)
Not sure if you're ok to use the dev version, and not sure about naming convention for those versions (:
_Also it seems RA notifications for Dolphin aren't shown in Batocera, a user reported on discord that they work (he unlocked achievements) but no notification is ever shown, but that might need a new issue. EDIT: It's actually because on-screen display messages were disabled for this system. Maybe enabling achievements should enable them?_
=> bump dolphin to 2407-76 (5.0 dev)

package/batocera/core/batocera-udev-rules/rules/99-steam-controller.rules
- fixes Steam locking access to the controller on exit
=> don't give Steam full access to the Nintendo Pro controller

package/batocera/emulators/dolphin-emu/wii.dolphin.keys, package/batocera/emulators/duckstation/psx.duckstation.keys, package/batocera/emulators/flycast/atomiswave.flycast.keys, package/batocera/emulators/flycast/dreamcast.flycast.keys, package/batocera/emulators/flycast/naomi.flycast.keys, package/batocera/emulators/mame/mame.mame.keys, package/batocera/emulators/model2emu/model2.model2emu.keys, package/batocera/emulators/pcsx2/ps2.pcsx2.keys, package/batocera/emulators/retroarch/retroarch/libretro.keys, package/batocera/emulators/rpcs3/evmapy.keys, package/batocera/emulators/supermodel/model3.supermodel.keys, package/batocera/emulators/vice/c64.vice.keys
This will add functionality to exit emulators with only the (first player) gun, making possible to play on Batocera without the need of a controller. To exit, hold `TRIGGER`, `ACTION` and `START` at the same time (left, right, middle mouse click).
Adding some mapping to Daphne standalone emulators too (coin, start).
=> Add exit function for light guns (v41)

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Add back in enhanced resolution es-settings. Previously removed due to "some games having glitches" but I think it's ok to add back in now. Testing with several games has not had any problems.
=> pcsx-rearmed-add-enhanced-resolution

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Removes unused rotate face buttons counter-clockwise and changes to simple switch toggle. Updated setting name and description for better clarity.
=> update-rotate-mappings-dolphin [V41]

package/batocera/core/batocera-configgen/scripts/powermode_launch_hooks.sh
The UI saves the game specific powermode to batocera.conf but is not applied by the powermode launcher hook
=> Apply game specific powermode

board/batocera/amlogic/a3gen2/patches/sdl2/sdl2-revert-drmModeAddFB2WithModifiers.patch
Until the current libmali blobs are updated to support the latest sdl2 kmsdrm mechanism, revert just this change
=> VIM4: Fix no UI due to sdl2

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py, package/batocera/core/batocera-configgen/configs/configgen-defaults-bcm2712.yml, package/batocera/emulationstation/batocera-es-system/es_features.yml
add forced border ratio for emulators that need 4:3 sinden borders
- i.e. Model3
=> enable borders on the rpi5 for model3

package/batocera/controllers/jammasd/jammASDSplit
I have noticed that the mapping with my jammASD USB card configured in Standard is wrong. I propose this fix
Please refer to the card datasheet available on the SmallCab website
Also, other buttons can be mapped (7 & 8 for player 1 & 2)
=> Fix jammASDSplit

package/batocera/controllers/jammasd/jammASDSplit
This fix should allow the players to use Buttons 7 & 8 if they are wired on the JammASD board. It will also create 2 placeholders to potentially use the combinations 'P1+Button1' or 'P1+Button2' and same with P2.
=> Adding placeholders for Buttons 7 & 8

package/batocera/controllers/nso-n64/99-nso-n64-joystick.rules, package/batocera/controllers/nso-n64/Config.in, package/batocera/controllers/nso-n64/nso-n64-calibration.sh, package/batocera/controllers/nso-n64/nso-n64.mk, package/batocera/core/batocera-system/Config.in
The default calibration data is incorrect for the NSO N64 controller. Known issue for several releases now. This aims to automatically calibrate to more correct values. I have 4 NSO N64 controllers, this is a universal issue and not related to any one specific controller.
Example of incorrect calibration:
Super Mario 64: Cannot jump out of water (down axis never reaches max value)
Star Fox 64: Unable to do loop (down axis never reaches max value)
After better calibration values are used issues resolve.
=> fix-nso-n64-calibration [V41]

batocera-Changelog.md, package/batocera/core/batocera-udev-rules/rules/99-wheels.rules, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Works out of the box, mapping is limited. Select (bottom left button) is also hotkey. Bottom right button is start. No dpad.
=> add support for SideWinder Precision Racing Wheel

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
Since batocera 40, the Cemu input controller API _Wiimote_ is supported. This PR adds support for Wiimotes in Cemu, including motion control.
For each batocera controller, its name is used to check if it is a real Wiimote (should be stable because it is baked into the kernel module). If so, additional info is requested via udev to check if extensions are connected. The Cemu XML config is then updated accordingly.
The code was successfully tested against batocera 40 using
1. a classic Wiimote (RVL-003)
2. a classic Wiimote (RVL-003) with Nunchuk
3. a Wiimote including MotionPlus (RVL-036)
The following tests have not been successful and are probably issues in Cemu:
- RVL-036 with any extension (Nunchuk, Classic Controller, Classic Controller Pro). Problem: the extension status in Cemu …
=> Cemu: add Wiimote support

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Just like mugen, it needs to write a file which is read-only on .squashfs format. Remove it.
=> remove .squashfs support for ikemen

package/batocera/emulationstation/batocera-es-system/es_systems.yml
xtech games directories are readonly (and saves are already done in /userdata/saves).
They can have a lot of small files (around 60000 for supermario X).
compression is around 25%
du -sh "Super Mario Bros X.smbx"
2.1G	Super Mario Bros X.smbx
du -sh "Super Mario Bros X.squashfs"
1.6G	Super Mario Bros X.squashfs
=> es_systems: thextech : add .squashfs support

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
In the following PR squashfs was added for Snes MSU1 and Satellaview: https://github.com/batocera-linux/batocera.linux/pull/12142
This PR also adds squashfs for MSU-MD.
=> Added squashfs for MSU-MD

package/batocera/emulationstation/batocera-es-system/es_systems.yml
American laser disc (platform 170 on screenscrapper) is missing from daphne and singe emulators.
=> singe scrapping also with alg

package/batocera/emulationstation/batocera-es-system/es_systems.yml
There's no namco2x6 platform in https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/PlatformId.cpp On screenscrapper, id are 147 for sega classics (Sega released some games on namco's 2x6 system) and 155 for namco classics. Not sure if we should keep "arcade" as a platform, so let's keep it for now, just in case.
=> Correct scrapping for namco2x6 platform

batocera-Changelog.md, package/batocera/core/batocera-scripts/scripts/batocera-systems, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> N64DD: add support for standalone .ndd (via lr-paralleln64)

package/batocera/emulators/pcsx2/013-fix-cross-compile.patch
Currently, the pcsx2 build decides the build flags to use based on the *host* architecture rather than the *target* architecture. This means building pcsx2 on aarch64 for x86_64 results in aarch64 build flags being used. The buildroot cmake package infrastructure sets `CMAKE_SYSTEM_PROCESSOR` to `BR2_ARCH` (as outlined in [cmake's docs](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html)), so using `CMAKE_SYSTEM_PROCESSOR` to determine build flags is the correct choice.
=> fix pcsx2 cross-compile

package/batocera/emulators/retroarch/libretro/libretro-bsnes-hd/libretro-bsnes-hd.mk
`libretro-bsnes-hd` ignores `CC` and `CXX`. When `platform` is set to `linux` without setting `compiler`, [it uses `g++`](https://github.com/DerKoun/bsnes-hd/blob/f46b6d6368ea93943a30b5d4e79e8ed51c2da5e8/nall/GNUmakefile#L70). This only works in the amd64 container because `/usr/bin/g++` produces x86_64 binaries (which could create problems, but doesn't in this case), but to support cross-compiling `compiler` needs to be overridden with `TARGET_CXX`.
=> fix libretro-bsnes-hd cross-compile

package/batocera/emulators/ruffle/ruffle.mk
In order to find the libraries in the staging and target directories, `cargo` needs to be told which `pkg-config` to use.
=> fix ruffle build

package/batocera/emulators/scummvm/scummvm.mk
The `configure` script for `scummvm` defaults to using `uname` to get the default value for the `--host` option. For cross-compiling, this means cflags and ldflags are set based on the host architecture rather than the target. Passing buildroot's `GNU_TARGET_NAME` (which is the target triple) corrects the problem. This also updates the value passed to `--with-sdl-prefix` to follow the documentation in the configure script.
=> fix scummvm build

package/batocera/gpu/nvidia-open-driver/nvidia-open-driver.mk, package/batocera/gpu/nvidia-proprietary-driver/nvidia-proprietary-driver.mk, package/batocera/gpu/nvidia340-legacy-driver/nvidia340-legacy-driver.mk, package/batocera/gpu/nvidia390-legacy-driver/nvidia390-legacy-driver.mk, package/batocera/gpu/nvidia470-legacy-driver/nvidia470-legacy-driver.mk
The scripts that are used to compile the nvidia drivers check for `xz` or `zstd` and if they aren't found, use extract a binary that is contained within the script and use it. This isn't a problem when building on an x86_64 machine since the binary is x86. However when cross-compiling, `xz` or `zstd` need to be available to run on the host and in the `PATH` for the scripts to find them.
=> ensure nvidia scripts use utilities in host directory

package/batocera/emulators/python-pyxel/python-pyxel.mk
The plain `pep517` setup type for a `python-package` doesn't set up the rust compiler for cross-compiling. Using `maturin` fixes the issue.
=> fix pyxel build

package/batocera/libraries/batocera-luajit/Config.in
`luajit` can be compiled on `aarch64` (including cross-compiling). This change affects the `solarus-engine` emulator.
=> fix batocera-luajit build

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds an option to use preemptive frames in Emulation Station since it was currently impossible to use them without editing the batocera.conf file and setting retroarch global overrides there. Already implemented previously in batocera downstream [Knulli PR](https://github.com/knulli-cfw/distribution/pull/50)
=> feat: Add preemptive frames as lag reduction option in ES

package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Hi,
I have mapping problem with a dualsense controller. (coin/start are mapping to analog stick click).
This patches serie is fixing it:
- sdl mapping is not currently enabled in wine. (It's enabled by default for windows system).
- use xinput instead dinput. (include update of game mapping  CFG/*.input. they are binary files)
- add force-feedback option 
I have tested all games, including lightgun with sinden && wheel games with a g25 controller
=> Model2 : add support for xinput && force-feedback

board/batocera/dropbear_localoptions.h
Reduce compile-time Dropbear default receive window to match new value from #12463 for increased compatibility.
The /etc/default/dropbear file will only affect the server at runtime, and this patch will set the default for both server and client utilities.
=> Reduce compile-time Dropbear default receive window 

package/batocera/emulators/ruffle/Config.in, package/batocera/emulators/ruffle/ruffle.mk
I ran into an issue doing a clean build where the dependencies weren't ready in the target when buildroot started compiling ruffle. I also updated the makefile to be closer to what `cargo-package` does to make sure the buildroot toolchain is being used.
=> improve ruffle build and add dependencies

Makefile
- changed two more references to complete batocera-linux/batocera.linux#12410
- if buiidroot/dl is a symlink (as it likely is in a direct build), put a trailing slash on find statement so it returns results
=> change 2 more find references in remove-*-dups targets & support symlinked dl dir

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Don't try to map an analog stick to a d-pad (i.e. 4x buttons).
=> Removed a buggy duplicate XArcade Tankstick mapping.

Makefile
The `%-upgrade` target was out-of-date.
1. Changed to correct path to boot.tar.xz
2. Output `lsblk` and list contents of partition (`ls`) and ask for confirmation. (only `y` is accepted)
3. Preserve `batocera-boot.conf` and `config.txt` (assumes this is an **upgrade** and these 2 files exist as extraction of these 2 files is intentionally suppressed)
4. label partition with `BATOCERA` (system will hang on boot in the event label got lost)
tested using last v41-dev build of bcm2836 to a micro SD with the following command:
```
make bcm2836-upgrade DEV=/dev/sdb
```
new build booted on Pi Zero 2W 🚀
=> fix & update `upgrade` target

package/batocera/core/batocera-configgen/configgen/configgen/utils/wheelsUtils.py
got into a situation where pad.dev was None
using format() ensures it is converted to a null string before being passed to print()
=> wheelsUtil.py: fix bug where wheelsUtils crashes if pad.dev happens to be None

batocera-Changelog.md, package/batocera/boot/batocera-shim-signed-efi-helpers-ia32/batocera-shim-signed-efi-helpers-ia32.hash, package/batocera/boot/batocera-shim-signed-efi-helpers-ia32/batocera-shim-signed-efi-helpers-ia32.mk, package/batocera/boot/batocera-shim-signed-efi-ia32/batocera-shim-signed-efi-ia32.hash, package/batocera/boot/batocera-shim-signed-efi-ia32/batocera-shim-signed-efi-ia32.mk
Bump ia32 EFI shim boot to latest version from Debian.
Replaces #12501
=> Bump ia32 EFI shim boot to latest

Makefile
thanks @bryanforbes for identifying which 2 variables need to be passed onto buildroot to make this work.
I had a chance to test this and needed to pass the variables directly on the make command line.
=> direct build: fix buildroot DL_DIR and CCACHE_DIR overrides

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
I mistakenly removed these imports because `generateCoreSettings()` is too complex for pyright to analyze. I checked all of the imports I removed in the relative import refactor and these were the only ones referenced in the file.
=> fix libretro generator after relative import refactor

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py
The following changes are incorporated:
* Use `dataclass` to define the shape of the object
* Use slots to keep the size of the objects as small as possible
* Updated the names of properties and methods to follow PEP-8 guidelines
* Added type hints
* Updated to allow passing either a string or a `pathlib.Path` for the path to the settings file
* Updated `write()` to use `Path.open()` as a context manager which always closes the file at the end of the `with` block
=> modernize `UnixSettings`

package/batocera/core/batocera-configgen/configgen/configgen/Command.py, package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py, package/batocera/core/batocera-configgen/configgen/configgen/README.md, package/batocera/core/batocera-configgen/configgen/configgen/batoceraPaths.py, package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py
I've refactored the core modules of configgen to use `pathlib.Path` instead of strings. There are a couple of advantages to using path objects over strings:
* No need to remember whether you need "/" at the beginning of the string you're concatenating
* Most `os.path` functions have equivalent methods on path objects
This is the first of several pull requests to refactor configgen to use path objects
=> use path objects in configgen core

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
In a squashfs volume with more than one file, a ".ROM" symlink may point to the ROM file that should be passed to the emulator.
Similar to https://github.com/batocera-linux/batocera.linux/pull/12142, this allows squashfs volumes to be used for snes-msu1 and other platforms where the emulator expects to be given a ROM file but will open additional files within the containing directory.
The advantage of this approach is that it makes squashfs volumes useful to platforms beyond snes-msu1, satellaview and msu-md without needing platform-specific code in configgen.  Or it may be beneficial where configgen makes incorrect assumptions about the location/name of the ROM file within a squashfs volume, or where the volume contains multiple ROM files.  It does, however, require that users include …
=> configgen: emulatorlauncher: Support ".ROM" symlink in squashfs volumes.

package/batocera/core/batocera-configgen/configgen/configgen/generators/corsixth/corsixthGenerator.py
Currently, it's writing `audio_music = [[{corsixthDataPath / 'MP3'}]]` to the config file. The string within the f-string needs to use single quotes.
=> fix f-string in corsixth generator

package/batocera/emulationstation/batocera-es-system/es_systems.yml
1. Updates the assets version number to v4, which is the correct assets version for v1.5.1+.
2. Adds links to the new Russian and Spanish voice packs.
3. `/userdata/roms/devilution` -> `/userdata/roms/devilutionx`, per:
https://github.com/batocera-linux/batocera.linux/blob/d3da6abdf56a835f49fe85e06dbfcf6ec6fa2dc3/package/batocera/core/batocera-configgen/configgen/configgen/generators/devilutionx/devilutionxGenerator.py#L22
=> es_systems.yml: Update DevilutionX instructions

package/batocera/core/batocera-configgen/configgen/configgen/input.py
Hats and keys don't have `code` set in `es_input.cfg`
=> change type of Input.code from `str` to `str | None`

package/batocera/core/batocera-scripts/scripts/batocera-power-mode
For both the [Intel](https://github.com/torvalds/linux/blob/94ede2a3e9135764736221c080ac7c0ad993dc2d/drivers/cpufreq/intel_pstate.c#L791-L792) and [AMD](https://github.com/torvalds/linux/blob/94ede2a3e9135764736221c080ac7c0ad993dc2d/drivers/cpufreq/amd-pstate.c#L305-L308) p-state drivers, the only option available for `energy_performance_preference` using the `performance` governor is `performance` and setting it to anything else will result in an error. In order to set `energy_performance_preference` to `balance_performance`, the governor needs to be set to a governor like `powersave`.
I have tested this on my ROG Ally.
=> set governor to `powersave` for fallback in "balanced" mode

board/batocera/rockchip/rk3588/fsoverlay/etc/inittab
- getty device name must not include /dev/ path
- use vt100 as a TERM baseline
- reorder parameters for consistency
=> Fix serial console on rockchip boards

board/batocera/rockchip/rk3588/nanopi-m6/boot/extlinux.conf, board/batocera/rockchip/rk3588/nanopi-m6/create-boot-script.sh
- Add boot menu of configuration options, each will be tried in order
- Move .dtb and .dtbo to /boot/dtbs/rockchip
- Use FDTDIR instead of FDT, to find dtb chosen by u-boot
=> Handle NanoPI M6 DSI display automatically at boot

package/batocera/core/batocera-configgen/configgen/configgen/generators/hypseus_singe/hypseusSingeGenerator.py
Do NOT merge until Hypseus Singe is updated to 2.11.3, Batocera Hypseus Singe repository bezel bumped ~~and multi-games zipped ROMs is added to configgen~~.
=> add captain power bezel to configgen (Hypseus Singe)

package/batocera/utils/fake-hwclock/0001-fix-load-force.patch, package/batocera/utils/fake-hwclock/fake-hwclock.mk
- Fix inverted logic in the script causing backwards time travel
- Ensure installation command returns success
=> Fix fake-hwclock bugs discovered in testing

batocera-Changelog.md, package/batocera/core/batocera-udev-rules/rules/99-wheels.rules, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
(PS version of the wheel)
Firmware must be updated to v2.00 to gain FFB feature.
https://support.thrustmaster.com/en/product/t248-ps-en/
PC MODE only.
=> add t248 steering wheel

package/batocera/utils/ledspicer/ledspicer.mk
=> Bump LEDSpicer to 0.6.3.1, with dependency update

board/batocera/fsoverlay/etc/init.d/S12populateshare
Fixes bug documented on wiki:
https://wiki.batocera.org/remapping_controls_per_emulator#libretro_cores:~:text=cannot%20save%20remap%20file
=> Create retroarch directories at boot time

package/batocera/emulationstation/batocera-emulationstation/wayland/sway/config, package/batocera/emulationstation/batocera-emulationstation/wayland/sway/sway-launch
Write sway display configuration to an include config file instead of rewriting the main config.  Prevents duplicate/incorrect entries from previous configurations if "batocera-save-overlay" is used or if sway-launch is rerun.
=> Simplify sway display config logic

package/batocera/core/batocera-configgen/configgen/configgen/utils/squashfs.py
Currently, if an exception happens in the `with` block of a linked rom, the mount point will be yielded (line 64). This change ensures only one path is ever yielded and limits the exceptions caught to those that are documented to be raised (so things like `KeyboardInterrupt` aren't caught).
=> fix configgen squashfs exception handling

package/batocera/core/batocera-configgen/configgen/configgen/generators/hatari/hatariGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml
atarist: improve hatarib libretro core
- add support for .hd image && .gemos directory roms
- add ide|scsi|asci hdd controller
- use emutos 1024 by default (it's embedded inside the core).
Currently, the default tos.img  don't work with all models, and don't support hard drives.
emutos 1024k is embedded inside the core, so just use it. (and increase the min memory to 1MB)
- add language support (need emutos)
- systems: remove .vhd .gem .ide extensions, they are used internally by hatarib to detect the
disk controller type. simply use the .hd extension + controller option if needed
atarist: harati : add TT & Falcon models and Emutos support
Default tos don't have hard drive support on ST.
use alternative emutos instead (opensource GPL)
I'm using 256k emutos for ST,STE,MEGASTE , and 512k …
=> improve atarist launchers

package/batocera/core/batocera-configgen/configgen/configgen/generators/hatari/hatariGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
this is ACSI,  not ASCI.  Hatari is not starting currently with --asci.
=> hatari: fix ACSI hdd controller type

batocera-Changelog.md
Jaguar CD not Jaguard CD
Remove duplicate about crosshair and duckstation.
=> typo in changelog

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Previously my steam deck right stick would just rotate the camera on its own.  Tested this with `sdl2-jstest --test 0` command and saw that this would fix the proper defaults.  I only changed the config on this deviceGUID (wasn't sure if this was mine or the other one), but this worked for me.
I'm running Batocera v39 on the 256 GB Steam Deck LCD (first iteration).
=> fix: fix right stick on steam deck

package/batocera/core/batocera-scripts/scripts/batocera-info
Replace space-like UTF-8 character (0xC2, 0xA0) with a space (0x20).
This fixes the "command not found" error on line 159 of `batocera-info` on systems with DRM display.
=> Fix batocera-info

package/batocera/core/batocera-system/batocera.conf
This pull request aims to improve the consistency and clarity of how video settings are documented in `batocera.conf`.
---
In the **Main Menu -> System Settings**, there are two related options:  
- **Video Output**  
- **Video Mode**
In `batocera.conf`, the **Video Output** is already well-documented with a dedicated section:  
```plaintext
global.videooutput=
```
However, the **Video Mode** setting (resolution and refresh rate) is saved at the end of the file without any clear documentation or explanation:  
```plaintext
es.resolution=XXXXxXXXX XXHZ
```
---
The **Video Mode** setting should have a dedicated, clearly marked section in `batocera.conf`, similar to **Video Output**. This section would include an explanation and reference to the appropriate command for listing available …
=> Proposal for Consistency in batocera.conf Formatting

Config.in, package/batocera/network/wpa_supplicant_k44/0001-2019-7-AP-Silently-ignore-management-frame-from-unexpected-.patch, package/batocera/network/wpa_supplicant_k44/0001-AP-Silently-ignore-management-frame-from-unexpected-.patch, package/batocera/network/wpa_supplicant_k44/0002-ASN.1-Validate-DigestAlgorithmIdentifier-parameters.patch, package/batocera/network/wpa_supplicant_k44/0003-Include-stdbool.h-to-allow-C99-bool-to-be-used.patch, package/batocera/network/wpa_supplicant_k44/0004-ASN.1-Add-helper-functions-for-recognizing-tag-value.patch, package/batocera/network/wpa_supplicant_k44/0005-2020-1-WPS-UPnP-Do-not-allow-event-subscriptions-with-URLs-.patch, package/batocera/network/wpa_supplicant_k44/0006-2020-1-WPS-UPnP-Fix-event-message-generation-using-a-long-U.patch, package/batocera/network/wpa_supplicant_k44/0007-2020-1-WPS-UPnP-Handle-HTTP-initiation-failures-for-events-.patch, package/batocera/network/wpa_supplicant_k44/0008-2020-2-P2P-Fix-copying-of-secondary-device-types-for-P2P-gr.patch, package/batocera/network/wpa_supplicant_k44/0009-2021-1-P2P-Fix-a-corner-case-in-peer-addition-based-on-PD-R.patch, package/batocera/network/wpa_supplicant_k44/0010-2022-1-crypto-Add-more-bignum-EC-helper-functions.patch, package/batocera/network/wpa_supplicant_k44/0011-2022-1-dragonfly-Add-sqrt-helper-function.patch, package/batocera/network/wpa_supplicant_k44/0012-2022-1-SAE-Derive-the-y-coordinate-for-PWE-with-own-impleme.patch, package/batocera/network/wpa_supplicant_k44/0013-2022-1-EAP-pwd-Derive-the-y-coordinate-for-PWE-with-own-imp.patch, package/batocera/network/wpa_supplicant_k44/50-wpa_supplicant.preset, package/batocera/network/wpa_supplicant_k44/Config.in, package/batocera/network/wpa_supplicant_k44/wpa_supplicant.conf, package/batocera/network/wpa_supplicant_k44/wpa_supplicant_44.mk, package/batocera/network/wpa_supplicant_k44/wpa_supplicant_k44.hash
Looks like when updating buildroot to the stable 2023.11.2 base the WPA_SUPPLICANT_K44 package was removed.
Very likely this is the reason why wifi doesn't work on RK3326 (and RK3128) boards.
This PR re-adds WPA_SUPPLICANT_K44 package inside batocera.linux repo (and a small modification in buildroot repo).
This PR requires: https://github.com/batocera-linux/buildroot/pull/922
This PR supersedes: https://github.com/batocera-linux/buildroot/pull/919
=> Fix Wi-Fi for Kernel 4.4 boards

batocera-Changelog.md, board/batocera/fsoverlay/etc/init.d/S04populate, board/batocera/fsoverlay/etc/init.d/rcS, package/batocera/core/batocera-system/Config.in
Fix multicast DNS name resolution, fixes #13028
- Buildroot packages `nss-mdns` and `avahi` are currently misaligned in their default configuration regarding where the avahi socket belongs.  Make `/var/run` a symlink to `/run`, to conform with Filesystem Hierarchy Standard 3.0, and re-aligning these packages with each other.  https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html
- Add package `nss-mdns` on all boards instead of only boards using Wine
=> Fix multicast DNS name resolution, fixes #13028

package/batocera/core/batocera-configgen/configgen/configgen/generators/fpinball/fpinballGenerator.py
Three issues found while adding unit tests:
- If `fpinball` exists in `wineprefix`, copying newer files from `/usr/fpinball` fails
- Setting the `rom` variable to a string with the `Z:` prefix makes it so the comparison to `'config'` never happens
- The player controller loop doesn't increase `nplayer`, so it adds all of the controllers every time (which the comments say we don't want to do)
=> fix bugs with fpinball generator

package/batocera/emulationstation/batocera-es-system/es_features.yml
My mistake, it was at the wrong place. Was placed in flycast standalone instead of flycast core.
=> fix off-screen reload button for libretro-flycast

board/batocera/fsoverlay/etc/init.d/S03urandom
This is a small security fix/improvement. I think it should wait for v42.
Currently the random seed is saved only on clean shutdown. This leads to no entropy being accumulated and the same seed reused if the device is not shut down properly.
Saving random seed on startup (immediately after using the previously saved seed) is the behavior of most distros.
=> Save random seed on startup [v42]

board/batocera/fsoverlay/etc/init.d/S18governor
Just updating to make it a bit easier to read and follow.
=> Update S18governor [V42]

board/batocera/fsoverlay/etc/init.d/S12populateshare
Reload udev rules when user persistent rules are available, fixes #10564 when used with the following rule in /userdata/system/udev/rules.d/52-dolphin.rules :
```
ACTION=="add", ENV{PRODUCT}=="57e/305/100", RUN+="/bin/sh -c 'echo -n $kernel > /sys/bus/usb/drivers/btusb/unbind'"
```
=> Reload udev rules when user persistent rules are available, fixes #10564

package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py
Read settings with latin1 codec instead of utf_8_sig, fixes #10650
=> Read settings with latin1 codec instead of utf_8_sig, fixes #10650

package/batocera/core/batocera-configgen/configgen/configgen/generators/drastic/drasticGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Modifies drastic binary to use either bilinear or nearest-neighbor image scaling.
The specific binary data that's being searched for and changed was retrieved via projects that modify drastic for various linux based os's.
Tested working on a number of my handhelds.
=> add image scaling to drastic [V42]

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
- Use cheevos token from ES instead of password in config generators for retroarch and pcsx2.  Avoid parsing issues related to special characters in the password.  Fixes #13111
- Bump ES, for cheevos token refresh at startup
=> Use cheevos token from ES instead of password, fixes #13111

package/batocera/core/batocera-configgen/configgen/configgen/generators/gsplus/gsplusGenerator.py
* Hardcode a ROM file path. GSplus config needs a file path, not a folder path. A folder path only works when the ROM files are in the same path as the binary.
* If the disc file format is of Apple II, then default the speed to Apple II's speed.
=> fix gsplus rom config and speed

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml
In the following PR squashfs was added for MSU-MD: https://github.com/batocera-linux/batocera.linux/pull/12390
In this PR I have added SGB-MSU1 as a new system with squashfs extension support. 
You can use Super GameBoy games with this which have msu1 sound, it will check for GameBoy and GameBoy Color file extensions.
I have tested both sgb msu1 with a normal folder structure and as a squashfs file both seem to work.
=> Added SGB-MSU1 with squashfs

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
This PR fixes the following problems, which were discovered when trying to use libretro MAME for apple2+/e/ee.
1. For apple2+/e/ee, only add the SD/IDE card when a hard drive image is provided.
2. Many paths are not quoted; when there are special characters or spaces in the path/filenames, the produced CMD file will cause parsing problem.
3. Some path variables were set within `if` statements and unbound outside.
4. (see comment below) ~~Adding `pluginpath`, `homepath`, `samplepath` causes parsing problems as well. Not sure whether this is retroarch or MAME's parsing problem, but as a workaround, these are omit for now.~~
=> Fix MAME config for apple2p, apple2e, apple2ee

board/batocera/fsoverlay/etc/init.d/S08connman, package/batocera/core/batocera-scripts/scripts/batocera-wifi
Refactor some code involved in batocera-wifi and S08connman
S08connman - splits the disable/enable into seperate functions instead of using "wifi_enable" to disable wifi. Refactor/optimize the wait loop. Reduce sleep time between stop and start in restart case(the only thing that is dependent on this is batocera-wifi setting wifi data before calling S08connman reload. There needs to be a brief wait period for batocera-settings-set to be applied, 0.5 is more than enough)
batocera-wifi - adds wait_for_ip function and optimizes the loop. wait_for_ip up is for when es wifi toggle is enabled, down is for when toggle is disabled, so wait time does not have to be the same.
=> wifi-update [V42]

package/batocera/controllers/guns/retroshooter-guns/99-retroshooter-guns.rules, package/batocera/controllers/guns/retroshooter-guns/retroshooter-guns-add
Disabling joystick mode.
Do makers even test their product? Stop enabling both keyboard/mouse and joystick simultaneously!
To do:
1) Update calibration script (this gun doesn't trigger the calibration for some reason, HIDRAW maybe?)
2) Add missing button (the stick click which triggers `Q`)
3) Enable LEDs (only two LEDs are on, stuck to green)
=> Add support for RS3 Reaper (new retro shooter light gun model)

package/batocera/core/batocera-udev-rules/batocera-udev-rules.mk, package/batocera/core/batocera-udev-rules/rules/99-wheels.rules
Adding mandatory usb_modeswitch to trigger PC mode on the device (G923) 
Deleting wrong line about G920
=> Cleaning up G920/G923 wheel rules

package/batocera/controllers/guns/retroshooter-guns/retroshooter-guns-add
Issue with calibration was that when holding `SELECT` for few secs, it triggers `BTN_1` but also `ESC` key which cancels calibration.
=> Fix RS3 Reaper calibration (part 2)

package/batocera/ports/sonic3-air/004-disable-enforcedebugmode.patch
Fix sonic3air, game is not playable with current default setting of EnforceDebugMode
=> Fix sonic3air, game is not playable with current default setting

package/batocera/core/batocera-udev-rules/rules/99-atariclassic.rules
Fix Atari classic controller spinner process blocks udev and is killed in 120 seconds
=> fix classic controller spinner process blocks udev and is killed

package/batocera/core/batocera-udev-rules/rules/99-atariclassic.rules
In wired mode, the controller identifies with the name "Atari Classic Controller" In bluetooth mode, it identifies with the name "Classic Controller"
=> Match the Classic Controller in BT mode

package/batocera/utils/batocera-wine/batocera-wine
Currently, we when upgrade the wine version between different batocera release, sometime the prefix need to be recreated because of incompatibility between differents wine version,proton,... That mean than save present in the botte is lost too.
This patch add support to declare specific directory && (optionaly) files where saves are located in the prefix and to create symlinks to /userdata/saves/windows/<game>
example 1 with specific directory save:
```
autorun.cmd:
SAVEDIR=drive_c/users/root/documents/localappdata/game/
DIR=drive_c/game
CMD="game.exe"
```
example 2 with saves files in the game directory:
```
autorun.cmd:
SAVEDIR=drive_c/game
SAVEFILES=savefile1.sav;savefile2.save
DIR=drive_c/game
CMD="game.exe"
```
if SAVEDIR && SAVESFILES are defined, we only symlink theses files in …
=> batocera-wine: autorun.cmd : add saves directory && save files options

package/batocera/utils/batocera-wine/batocera-wine
Seem that sandboxing is missing for play_wine && play_winetgz,
I have seen some games with .wine extension writing to /userdata/system/ because of this
```
[root@BATOCERA /userdata/roms/windows/test.wine/drive_c/users/root]# ls -lah
total 24K
drwxr-xr-x 1 root root 192 Jan  4 08:58  .
drwxr-xr-x 1 root root  20 Jan  4 08:58  ..
drwxr-xr-x 1 root root  40 Jan  4 08:58  AppData
drwxr-xr-x 1 root root   0 Jan  4 08:58  Contacts
lrwxrwxrwx 1 root root  16 Jan  4 08:58  Desktop -> /userdata/system
lrwxrwxrwx 1 root root  16 Jan  4 08:58  Documents -> /userdata/system
lrwxrwxrwx 1 root root  16 Jan  4 08:58  Downloads -> /userdata/system
drwxr-xr-x 1 root root   0 Jan  4 08:58  Favorites
drwxr-xr-x 1 root root   0 Jan  4 08:58  Links
lrwxrwxrwx 1 root root  16 Jan  4 08:58  Music -> …
```
=> batocera-wine: add sandboxing for play_wine && play_winetgz

package/batocera/core/batocera-udev-rules/rules/99-pedals.rules
After fixing the Atari Classic Controller in #13198 I looked for similar buggy usage of udev RUN and found this.  Untested, but it's clearly not working properly as written.
=> fix footpedal blocking udev

package/batocera/core/batocera-udev-rules/rules/99-atariclassic.rules, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Remap the Atari Classic Controller
- Remap the values sent by the controller using evsieve to avoid unfortunate behaviors of the original keys chosen by Atari
- Remove the ES mapping for "Atari Classic Controller" as it is currently unused
- Update the ES mapping for "virtual spinner" to reflect the new events sent by the remapped device, and adjusting the layout
=> Remap the Atari Classic Controller

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Some games are missing from the MAME database, but other do exist. Since many games rely on our gamesdb.xml to be detected as light gun or wheel games, I wanted to be futureproof by adding more information in the document.
I've added the missing games in gamesdb.xml here: https://github.com/batocera-linux/batocera-emulationstation/pull/1851
With this, the working ROMset will properly be detected in ES, in gamesdb.xml and in scrapers.
=> add game id for lindbergh

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> add VF5C to lindbergh list

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
MAME supports many different systems with variations in parameter logic. Currently libretroMAMEConfig captures common cases but there are still too many exceptions.
(edit: now incorporating @dmanlfc's suggestion)
This PR adds the possibility to let user provide custom raw parameters to pass to libretroMAME in a custom .cmd file.For example, the file `/userdata/roms/apple2/Where in the World is Carmen Sandiego (1985)/Where in the World is Carmen Sandiego (disc 1).dsk.cmd` has the following contents:
```
apple2ee -gameio joy -flop1 "/userdata/roms/apple2/Where in the World is Carmen Sandiego (1985)/Where in the World is Carmen Sandiego (disc 1).dsk" -flop2 "/userdata/roms/apple2/Where in the World is Carmen Sandiego (1985)/Where in the World is Carmen Sandiego (disc 2).dsk" -rompath …
```
=> add an option for user-provided .cmd file for libretroMAME

board/batocera/amlogic/a3gen2/patches/vulkan-loader/001-revert-vulkan-loader-remove-unused-vkicdsurface-struct-members.patch
Vulkan loader versions since 1.3.296 has introduced a change that is crashing libMali. Revert the change introduced in vulkan loader
The issue is tracked here
https://github.com/KhronosGroup/Vulkan-Loader/issues/1637
=> vim4: Fix vulkan crash

board/batocera/amlogic/s905/patches/uboot/u-boot-0016-TESTING-test-uart_ao_a_pins-bias-disable-on-Odroid-C.patch
Add partial u-boot patch from LibreELEC repo.
I've only added the odroid c2 part of the patch.
https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Amlogic/patches/u-boot/u-boot-0002-TESTING-test-uart_ao_a_pins-bias-disable-on-Odroid-C.patch
=> Fix Odroid C2 boot issues

package/batocera/core/batocera-configgen/configgen/configgen/generators/scummvm/scummvmGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
since https://github.com/batocera-linux/batocera.linux/pull/9630/commits/8cc8b2790a118a56786fff9ef112044aaa3b59de, default stretch mode is broken.
The default stretch_mode of scummvm (if not defined in command line) is "fit", not "center". (Center don't scale at all, so if you have a 4k screen with a 320x200 games, it'll be displayed too small)
This patch simply don't force it command line
also, es_features.yml is buggy, as "center" value is currently defined in french "centre".   (and scummvm is fallbacking to "fit" if a wrong value is defined)
=> scummvm: fix stretch_mode

package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/utils/batocera-wine/batocera-wine
since version 8.X, wine have enable hidraw by default, and this is breaking xinput for lot of gamepads.
(I have tested dualshock4, dualsense controllers, and sinden lightgun)
https://selfmadepenguin.wordpress.com/2024/02/14/how-i-solved-my-gamecontroller-problems/
https://social.treehouse.systems/@mgorny/112146040904035612
https://bugs.winehq.org/show_bug.cgi?id=56306
wine-ge have patches to disable hidraw by default
https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton8-7
This patch add the registry key to disablehidraw=1 by default, and allow to revert to hidraw with a new "enable_hidraw" option
=> batocera-wine: disable hidraw by default

package/batocera/core/batocera-configgen/configgen/configgen/controller.py
Fix #8568 (and replaces #12194)
=> Fix controllers with a comma in their names for SDL

batocera-Changelog.md, package/batocera/controllers/guns/xgunner-lightguns/99-xgunner-lightguns.rules, package/batocera/controllers/guns/xgunner-lightguns/Config.in, package/batocera/controllers/guns/xgunner-lightguns/xgunner-lightguns-add, package/batocera/controllers/guns/xgunner-lightguns/xgunner-lightguns.mk
All 4 players light gun supported. Button mapping was a bit tricky.
- ESC key has been disabled to avoid mispressing and exiting game by accident.
- Analog stick is arrow keys and only work for calibration. Use dpad for navigation.
- Start and Space enables the calibration mode. Use fake analog stick on the back to adjust calibration.
- For PCSX2 calibration, use the sub1 location on the key distribution image below:
Sub2 and Sub3 are mostly unused in most emulators.
=> Add initial support for XGunner light gun

package/batocera/emulators/retroarch/libretro/libretro-holani/libretro-holani.mk
rust's ffi bindgen can't find `stddef.h` from the buildroot host clang for some reason, making `libretro-holani` to FTBFS using the provided Dockerfile.
Temporary fix for
> include/libretro.h:27:10: fatal error: 'stddef.h' file not found
Until proper fix is found.
#13393
=> libretro-holani: include host clang header dir for rust-ffi. #13393

package/batocera/fonts/nanum-font/nanum_font.mk, package/batocera/utils/od-commander/Config.in
Replace default Korean font: NanumMyeongjo → NanumSquare_acB
The current default Korean font is NanumMyeongjo. However, similar to Times New Roman, it is often considered dull and outdated in Korea. Many Korean gamers even suggest changing the font as a first step after installing Batocera.
I propose replacing it with NanumSquare_acB, a much more popular and widely preferred font.
Since it shares the same license as NanumMyeongjo, this change should not cause any licensing issues.
=> Changed default Korean font

package/batocera/core/batocera-udev-rules/Config.in
BR2_PACKAGE_USB_MODESWITCH is already selected by batocera-system.  For udev rules we need BR2_PACKAGE_USB_MODESWITCH_DATA.
=> Enable BR2_PACKAGE_USB_MODESWITCH_DATA for modeswitch data and udev rules

package/batocera/core/batocera-udev-rules/rules/99-mt76x2u.rules
Load driver for Comfast 785 AC WiFi, blacklisted because of conflict with xone
=> Load driver for Comfast 785 AC WiFi, blacklisted because of conflict with xone

package/batocera/utils/batocera-steam/batocera-steam-update
This is a small improvement to the script "batocera-steam-update"
This script was tested and working (by changing code directly in "/usr/bin/batocera-steam-update")
What changed in this version : 
1. A BLACKLIST array is defined with words commonly found in non-game applications.
2. The function contains_blacklisted_word():
- Checks if any blacklist word appears in the game name.
- If found, the game is skipped.
3. Before adding a game, it checks:
- If the game is categorized as a game (Categories=*Game*).
- If the game contains any blacklisted word.
- If the game has already been added to /userdata/roms/steam/.
4. Skipping Blacklisted Entries:
- If the game name contains a blacklisted word, it logs the exclusion and moves to the next entry.
- Otherwise, it proceeds with adding the game. …
=> Enhancement to batocera-steam-update

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinSYSCONF.py
Given the operations we're doing, both `b` and `B` do the same thing. However, when I was parsing a SYSCONF file in the python REPL, some larger numbers would be read as negative numbers.
=> treat bytes as unsigned in dolphin SYSCONF

package/batocera/core/batocera-configgen/batocera-configgen.mk
There's no need to copy hidden files, byte code, or any wheels or sdists into the buildroot build directory
=> use rsync to copy files for configgen build

board/batocera/fsoverlay/etc/pam.d/system-auth
Warehouse, which is being considered as a replacement for bauh, uses /usr/bin/pkexec to launch subprocesses.  On Batocera, this always fails, since pkexec requires PAM configuration in
/etc/pam.d/system-auth to run.  Add this file to allow the Warehouse flatpak to run, which is desirable even if it doesn't become the default flatpak manager.
=> Provide /etc/pam.d/system-auth for pkexec

package/batocera/emulators/mame/mame.mk, package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
- Limit load average for parallel build of memory-hungry packages
- buildroot: Add install-images dependency on install-target
=> improve parallel build

package/batocera/core/batocera-configgen/configgen/configgen/utils/evmapy.py
if we have duplicate defition of an action in different files, we need to keep the one declared on the top key file on the list.
for example,
if we have the default system exit key configured to alt-f4, and the game have a specific pad2key exit to "esc",
we need to keep only the "esc" mapping.
It was the default behaviour on v40 before this commit: https://github.com/batocera-linux/batocera.linux/commit/a65da815b998a392f91bec5f26d8b1f89e1ad368
(on v41, on same example, the actions are duplicated in the json, and the last one (from the system alt-f4) is used by evmapy instead "esc")
=> evmapy: don't merge duplicate actions from different files

package/batocera/utils/batocera-wine/batocera-wine, package/batocera/utils/batocera-wine/batocera-wine.mk, package/batocera/utils/batocera-wine/mugen.keys, package/batocera/utils/batocera-wine/windows.keys, package/batocera/utils/evmapy-system-config/evmapy-system-config.mk
This cleanly stop wineserver with "wineserver -k" option, and after 10s, if winserver is still running, kill the process using the specific wineprefix.
From my tests, wineserver is shutting down in 2s, so 10s should be far enough.
The next step is to replace the evmapy alt-f4 with executing batocera-wine stop.
=> batocera-wine: add stop action

package/batocera/controllers/pads/xpad-noone/007-allow-to-use-triggers_to_button-to-any-model.patch
some cheap chineses clone gamepad (datafrog S80 for example), are re-using microsoft usb vendor|modelid, and have bad implementation of triggers sending digital values.
the module have a triggers_to_button option, but it's only work for unknown vendor|modelid
Retropie have same patch to allow it on any devices too https://github.com/RetroPie/RetroPie-Setup/blob/381020245f9be6a82be13bd81c0da04b971522b0/scriptmodules/supplementary/xpad/01_enable_leds_and_trigmapping.diff
=> xpad-noone: allow to use triggers_to_button to any model

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> scrape windows from "PC Windows" instead of "PC DOS" on screenscraper

package/batocera/controllers/guns/blamcon/99-blamcon.rules
New firmware removed the space between "Props" and "3D" in the light gun name.
=> update blamcon light gun rules

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
The batocera dosbox doc https://wiki.batocera.org/systems:dos say that we can defined a dosbox.conf inside the game directory
"Adding a custom dosbox.cfg in your game folder alongside dosbox.bat will allow you to specify custom DOSBOX configuration for the game."
This is not working with dosbox pure libretro core without this option
=> libretro: dosbox: allow to read dosbox.conf in game directory

package/batocera/core/batocera-configgen/configgen/configgen/generators/gsplus/gsplusGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
The previous PR https://github.com/batocera-linux/batocera.linux/pull/13067 fixed the config file path for GSPlus by hard-coding the bios filename to the most popular choice.
This PR adds an option `gsplus_bios_filename` for users to choose which bios file to use (the default is still the most popular choice):
* ROM.03 (default)
* ROM1
* ROM.00
* APPLE2GS.ROM
* APPLE2GS-BIOS.ROM
p.s. The commonly used filenames represent various BIOS versions.
p.p.s. : GSPlus calls the bios file a `ROM file`. To avoid confusion with Batcoera's ROM definition, the option name uses "bios".
=> allow user to choose GSplus bios filename

board/batocera/patches/sdl2/sdl2_input_add_invert_trigger_support.patch, package/batocera/core/batocera-configgen/configgen/configgen/controller.py
Logitech g25,g29 wheel pedals are sending the values reversed, this is breaking
games mapped to gamepad (or wine xinput), where calibration is not possible,
as sdl gamepad is expecting 0 for unpressed and max for pressed
This patch allow to revert trigger axis with ~,
it's using value="-1" from es_input.cfg, as it's mostly setup only on logitech && thrustmaster wheels devices triggers axis.
Here the list of devices from es_input.cfg:
```
DEvice SFR Controller
GameForce ACE Gamepad
Thrustmaster F430 Force Feedback
Thrustmaster Thrustmaster Advance Racer
Thrustmaster Thrustmaster T300RS Racing wheel
Thrustmaster Thrustmaster T150RS
Thrustmaster Thrustmaster Racing Wheel FFB
Driving Force GT
G25 Racing Wheel
G25 Racing Wheel
Logitech G29 Driving Force Racing Wheel
Logitech Logitech MOMO …
```
=> sdl: add an option to revert triggers z-axis values

package/batocera/utils/batocera-wine/batocera-wine
- Small fix for generating `autorun.cmd`
- Introduces new switch `autorun` so setup from SSH makes autogeneration from autorun files much more easy 
- The autofind depends heavily on more reg input from the community, I tested with maybe 5 installers
....and:
If we install msi and exe packages the chance is high to autogenerate the autorun file.
See is kind of community process: In Line 770+ we can add regex for specfic games/installers ...
----
The idea is to use a small script to wrap around
```
#!/bin/bash
readarray -t array < <(find /userdata/roms/windows -mindepth 1 -maxdepth 1 -name "*" -type d)
for i in "${array[@]}"; do
batocera-wine windows autorun "$i" .
done
```
=> batocera-wine fixes + autorun.cmd generator

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/utils/wheelsUtils.py
some wheel drivers like logitech, thrusmaster or fanatic have a sysfs knob to change the rotation. (and physically lock the wheel to not go further).
Better to use this than create a virtualwheel if we only need to change rotation. (virtualwheel is still needed for deadzone change)
=> wheels: set rotation through sysfs range if available

package/batocera/emulationstation/batocera-es-system/es_features.yml
Adds NeGcon with rumble feedback as controller entries for Beetle PSX and SwanStation.
=> Add NeGcon (Rumble) controller entries to Beetle PSX and SwanStation

package/batocera/utils/batocera-wine/batocera-wine
@nadenislamarre @dmanlfc @lbrpdx 
- Backup of  existing `autorun.cmd` is made
- If <GAME_DIR> does not exists user will get informed
- Optimized built-in reg expressions
- Users can add own reg expressions `/userdata/roms/windows_installers/autorun-regex.txt` or `/userdata/saves/windows_installers/autorun-regex.txt` can be used. The roms-dir is the prefered location
- RegEx file can be extended, use # as line comments and can comment out regexpressions with # 
Example file:
```
^.*/.*[sS]etup\.exe$
^.*/*.[Ee]ditor.*$
^.*/.*[-_\ ][Uu]ninstall\.exe$
^.*/[Rr]emove\.exe$
^.*/[Uu]nwise[[:digit:]]{0,2}\.exe$
^.*/[Uu]ninstall[-_\ ].*\.exe$
^.*/.*[Ii]nstall(..)?\.exe$
^.*/Adobe AIR/.*$
^.*/[Uu]install[ers]{0,3}/.*$
^.*/InstallShield Installation Information/.*$
^.*/dpinst\.exe$ …
```
=> batocera-wine - users can add regular expressions

package/batocera/core/batocera-configgen/configgen/configgen/utils/evmapy.py
Since we already skip the axis based on its `input.code` earlier in the loop, we don't need to skip adding the axis to the `axes` list. How we are skipping now prevents the axis being set up if "up" comes after "down" or "left" comes after "right" in the `<inputConfig>` in `es_input.cfg`.
=> fix base axis mapping in evmapy context manager

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Configuration for the _Batocera/Retroach Optimized_ firmware for the ultra low latency 4dapter Retro Controller adapter
Product link is here -> https://www.tindie.com/products/timville/4dapter-switch-mister-retro-controller-adapter/
Mapping is automatic for NES, SNES and Genesis controllers. Nintendo 64 controllers require mapping according this diagram below
=> 4dapter retro controller adapter configuration

package/batocera/core/batocera-configgen/configgen/configgen/utils/wheelsUtils.py
the sdl mapping is not working with virtual wheel, because we copy mapping from original wheel without changing the guid.
This fix virtual wheel on wine/model2 where xinput can't work without sdl mapping, also also make pedals works in correct order for wheels like logitech g29 (on model3)
=> virtual wheel: use correct guid for mapping

package/batocera/utils/batocera-wine/batocera-wine
- Fixed: WINE refused to start if regs, fonts, exe or msi directory could ne be removed (bad reg-keys for example)
- Heavily improved the detection of these files
- Simplified case selection for the redistributable files
- Some smaller corrections
- user-regex is now converted to unix-file before use
- Logfile for adding redistributables and a more clearer backup strategy for those files
https://github.com/batocera-linux/batocera.linux/pull/13603 Something usefull there - autogenerating of files
https://github.com/batocera-linux/batocera.linux/pull/13542 This was hard stuff..... oh man...
https://github.com/batocera-linux/batocera.linux/pull/13445 It started with this - thanks @aderumier
=> batocera-wine - some fixes

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
Port #13216 from libretroMAME to MAME.
For ease of parsing (quotes, escapes, spaces, etc.), the custom .cmd file for MAME will uses newlines as delimiters. This will be written into wiki once merged.
=> port custom cmd file to mame

package/batocera/utils/batocera-wine/batocera-wine
- Renamed save_install() -> saveFileToUserdata()
- fixed mv and symlinking to SAVES_WINDIR, would return 1 and therefore WINE did refuse to work
- Added remarks for better mantaining the script
Thanks @aderumier for the WINE-Save idea
@nadenislamarre please review
old PR -> https://github.com/batocera-linux/batocera.linux/pull/13656
=> batocera-wine: fix save_install() - Wine refused to work then

package/batocera/utils/batocera-steam/batocera-steam
Hey folks, I was having an issue where exiting steam games through their in-game menus would leave them in a stuck state because steam was still running.
Digging into it, I found that steam was just not outputting anything to stdout/stderr. As of the latest Steam version, it seems like it won't output if it isn't connected to a tty (see https://github.com/ValveSoftware/steam-for-linux/issues/11793). This means that the code in `batocera-steam` that detects when the games exit no longer works.
As per the response there, it seems like monitoring the log file might be a decent approach. I implemented that in this PR through a subshell that looks for the previous `Game process removed` / `Exiting app` outputs. If it encounters those, it requests steam to shutdown as before.
The format of the …
=> Fix watching for steam game exits

package/batocera/boot/batocera-initramfs/init
Allow specifying additional mount options via a colon (:) after each mount
One usecase of this change is to allow (advanced) users who wants to put boot_root on a btrfs subvolume
for example, one could use `dev=/dev/test123:subvol=/test123`
=> init script improvements: allow specifying additional mount options

batocera-Changelog.md, package/batocera/core/batocera-udev-rules/rules/99-wheels.rules, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Must be on DP mode:
And 270 degrees mode:
`-` is SELECT
`+` is START
`HOME` is Hotkey
=> add support for HORI mario kart racing pro deluxe

package/batocera/utils/batocera-wine/batocera-wine
Overwrite autorun.cmd if called from SSH. There must be a defintion from where the function was called - DONE
=> batocera-wine - small errors resolved

Makefile
- .ba-docker-image-available: Remove _check_docker prerequisite as this always forces a docker pull.
- batocera-docker-image: Fix specification of .ba-docker-image-available prerequisite.
- update-docker-image: Suppress sub-make entering/leaving directory messages.
=> Makefile: Fix docker-image targets.

package/batocera/core/batocera-system/Config.in
This enables using arrow keys in the REPL. This could possibly go in `BR2_PACKAGE_BATOCERA_DEV`.
=> enable readline in python

package/batocera/core/batocera-scripts/scripts/getLocalXDisplay
bash offers array for $PIPESTATUS to catch error in pipe-chain
find command is the critical one here, so we observe `${PIPESTATUS[0]}`
Attention: you still need to check if obtained variable is empty because if /tmp/.X11-unix-dir is present then there is no error. @nadenislamarre Are you okay with this?
=> errorcode for getLocalXDisplay

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/core/batocera-configgen/configs/configgen-defaults-bcm2835.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
=> Renamed `segacd` to `megacd` (consistency with `megadrive` not `genesis`

package/batocera/utils/rpigpioswitch/rpi-retroflag-AdvancedSafeShutdown.py
Regarding to: PR https://github.com/batocera-linux/batocera.linux/pull/13789 
Retroflag NESPi4 and Pi4 need `reboot` command to proper shutdown (means power cut)
For Pi3 it does not matter it works with `poweroff` and `reboot` command.
RETROGLAG as manufactorer also uses the `reboot` command in their scripts.
=> Updated: rpi-retroflag-AdvancedSafeShutdown.py

package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
This fixes the broken RenderingMode option in Batocera as PPSSPP changed it to SkipBufferEffects a couple of years ago (https://github.com/hrydgard/ppsspp/commit/519db766b6a251d8d8032236c401babf29e82553).
=> configgen: createPPSSPPConfig: Change RenderingMode to SkipBufferEffects.

package/batocera/core/batocera-audio/alsa/batocera-audio, package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
https://github.com/user-attachments/assets/f7bb8b1e-780b-4722-ab0d-5ce2bb14d06c
0–7s: Audio is playing through the built-in speaker.
3s: A Bluetooth audio device connects.
7s: The system detects the Bluetooth audio sink.
8–12s: Audio is now playing on the Bluetooth device (automatically switched).
12–15s: The Bluetooth device is disconnected, and audio automatically switches back to the built-in speaker.
*Short Summary*
When a Bluetooth audio device is connected, the audio output automatically switches from the built-in speakers to the Bluetooth audio device.
When the Bluetooth audio connection is lost, it automatically switches back to the built-in speakers.
(This only applies if the AUDIO OUTPUT setting is set to “AUTO”)
*Detailed Description*
1. batocera-bluetooth-agent Modifications
- …
=> Automatic Bluetooth audio output switching

package/batocera/utils/batocera-wine/batocera-wine
indeed waitWineServer function can now be improved with timeouts so imho it would be better to use: `waitWineServer 10 || { echo "WinServer reached timeout of 10s with errorcode ($?)"; stopWineServer; }` instead of `waitWineServer 0`
Why?
Commands like
```
WINEPREFIX=${WINEPOINT} eval "${WINE_ENV}" "${WINE} ${VDESKTOP} ${WINE_CMD}"
```
already call a full WINE Instance and the scripts stop at this points.... So the waitWineServer function is called very late (exactly if you quit the game) and is a kind of **"security"** function? I did not introduce this function but I think it's an important one....
Edit: Just for testing purposes I forced a call to stopWineServer with
```
waitWineServer 0.1 || stopWineServer
```
This will turn in a timeout with EC 124 and then call the stop function - …
=> batocera-wine: stop function with better control, some small fixes

package/batocera/core/batocera-configgen/configgen/configgen/generators/mugen/mugenGenerator.py, package/batocera/utils/batocera-wine/mugen.keys
- KEY_LEFTBRACE for P1 is wrong, it's L    (in the same raw of the keyboard)
- invert X Y R1 <-> A B R2  raw. (this the the standard in arcade sticks)
also fix the L key from my previous patch for old mugen engine.
=> mugen: fix evmapy mapping

board/batocera/fsoverlay/etc/pm/sleep.d/99trigger_userscripts
This pull request adds support for two new EmulationStation script hooks: `suspend` and `resume`. 
These are triggered when the system enters suspend mode (e.g., via `pm-suspend` command from SSH/terminal or the suspend options in the EmulationStation GUI) and when it resumes from 
Suspend event scripts will be triggered from:
`/userdata/system/configs/emulationstation/scripts/suspend`
Resume event scripts will be triggered from:
`/userdata/system/configs/emulationstation/scripts/resume`
If this is approved and merged, the [EmulationStation scripting documentation](https://wiki.batocera.org/launch_a_script#emulationstation_scripting) should be updated accordingly.
This addresses: https://github.com/batocera-linux/batocera.linux/issues/13894
=> Trigger userscripts upon suspend and resume events

package/batocera/utils/rpigpioswitch/S72gpioinput
I updated the shell script "S72gpioinput" in order to make gpio pins fully usable with the case Retroflag 64Pi.
Once the OS has been compiled. You have to run this command in the ssh shell : "/etc/init.d/S92switch setup" (according to this [documentation ] (https://wiki.batocera.org/add_powerdevices_rpi_only)). After a reboot, the safe shutdown should work with the case.
However, when you plug the power supply for the first time. The RPi5 is powered on automatically. I will try to find a solution for this issue.
=> Retroflag 64Pi CASE support

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/scummvm/scummvmGenerator.py
Tested with several games
Monkey 1-3
Goblins 1-3
Full Throttle
Indiana Jones 3+4
Broken Sword 1+2
Sam n Max
DotT
All working - you can create savesgames from libretro and load them from the standalone and vice versa
Only issue with **The Curse of Monkey Island** aka Monkey Island 3, from there games created with newer libretro core can't be loaded to older standalone core - vice versa worked.
I think it is a negligible problem and can also be caused by simply updating the cores to a newer version.
=> scummVM all cores use same savegame location

package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
since convertion to pathlib https://github.com/batocera-linux/batocera.linux/commit/43f3f9b4dbc9fb807e8adeaafdc80c58f79ef9ed
```
xblaFullPath = pathLead / firstLine
if xblaFullPath.exists():
```
if a playlist have a leading / , it's not working anymore because
```
xblaFullPath = Path("/userdata/roms/xbox360") / "/bar"
xblaFullPath ---> /bar
```
simply trip the leading / to fix it.
=> xenia: fix regression with leading / in rompath .xbox360 playlists

package/batocera/emulators/vpinball/vpinball.mk, package/batocera/libraries/libdmdutil/libdmdutil.mk, package/batocera/libraries/libpinmame/libpinmame.mk, package/batocera/libraries/libserum/libserum.mk
libpinmame now has an install, libdmdutil uses libserum-concentrate a friend fork with major memory optimizations.
=> vpinball: bump libpinmame to 3.7, libdmdutil, and vpinball

package/batocera/gpu/img-mesa3d/img-mesa3d.mk
I was trying to build batocera for the `jh7110`, and I noticed the fetch of the `mesa-22.1.3.tar.xz` file failed.
Looking at the contents of https://archive.mesa3d.org, it seems that only versions 23.x and onwards are directly available there, and older ones are within the `older-versions/` folder.
Rather than hardcoding the series (`22.x`) for the URL, I used Make's `$(basename ...)` function to extract it from the `$(IMG_MESA3D_VERSION)`.
Thanks for developing this cool project!
=> Update path of mesa-22.1.3.tar.xz.

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Fixes an issue where the RetroArch OSD font would break when the LANGUAGE setting is changed to CJK.
This update adjusts the configuration accordingly.
Also, https://github.com/batocera-linux/batocera.linux/issues/9001 in the last comment might also be resolved. 
I have confirmed that this issue has been resolved in Batocera 41 (Python 3.11),
but I haven't tested it in the latest dev, which uses Python 3.12.
Depends on: https://github.com/batocera-linux/batocera.linux/pull/14074
=> Set RetroArch OSD CJK fonts based on user_language or system locale

package/batocera/emulators/retroarch/retroarch/025-fix-glslang-linking.patch, package/batocera/emulators/retroarch/retroarch/retroarch.mk
Unless explicitly told to, RA will build zlib, flac, and glslang while linking against the system libraries as well. Disabling the builtin glslang requires RA to stop checking for library files that our newer glslang release has combined into the main glslang library file.
=> fix retroarch system library linking

package/batocera/core/batocera-configgen/configgen/configgen/generators/lindbergh/lindberghGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
At default/auto, it keeps the formula for minimum frequency. If the user changes the slider in ES, then it takes the value chosen between 2.0 to 4.0 (moving 0.1 each). Idea is to select base frequency. I have 3600MHz processor, I need to go with 3.6 for perfect speed accuracy on this game.
=> add cpu slider for hotd4 (lindbergh)

batocera-Changelog.md, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
The name of the CD System BRAM option in the Genesis Plus GX libretro core has been changed to genesis_plus_gx_system_bram, so the core options generator needed to be updated to work correctly.
=> Fix Genesis Plus GX core option for CD System BRAM

package/batocera/emulationstation/batocera-emulationstation/S31emulationstation
removed while loop and sleep-watchdog in favour of timeout. It wait's 20s for ES-process to finish, after 25s in total it uses ~~SIGTERM~~ SIGKILL. If we use `killall -w` it could happen that the process is stuck and a shutdown will never happen.
=> S31emulationstation - declutter

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
- only use enhanced mode for Sony DS controllers
=> pcsx2 controller fix

board/batocera/x86/fsoverlay/etc/init.d/S30checkprime, package/batocera/core/batocera-resolution/scripts/resolution/batocera-resolution.xorg, package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone
- reset display.log on each boot
- use es.resolution when we init xorg
- don't allow for dodgy 4096x2160 resolutions
- remove fake standby check until a better solution is sought
=> tidy & fix some scripts

package/batocera/utils/rpigpioswitch/S92switch
If you edit `/etc/init.d/rcS` then you see that no process is sent to background. Some scripts start rpi_gpio and use `wait` command. So Batocera will stop at init.d S92 position so I assume S92+ script like S99service will never start
=> S92switch: Send scripts to background - merge for v42 please

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/wine/wineGenerator.py
Reverts batocera-linux/batocera.linux#14518
as per @bryanforbes this is going to break everything down. Let's check that back in v43.
=> Revert "enable mouse in wine by default"

package/batocera/core/batocera-configgen/scripts/tdp_hooks.sh, package/batocera/core/batocera-scripts/scripts/batocera-amd-tdp, package/batocera/emulationstation/batocera-es-system/es_features.yml
Lets try this again.
1. Changed tdp slider to sliderauto, so auto = no entry in batocera.conf
2. Adjusted hooks script to account for no global tdp value, if no global tdp or system/game requested tdp change it does nothing. If there is a requested change, it creates a changed flag to then be used on gamestop so it knows a change was made and will revert back to system default tdp if no global defined tdp.
3. Not sure the point of the firmware helper in batocera-amd-tdp, it just gets the current fast limit, which could be anything, I think it's better to just get the default system/reported max tdp and use that since it’s determined at boot and unlikely to change during runtime.
4. Probably most importantly, sets all stapm, fast limit, and slow limits to the actual target tdp requested. …
=> fix-amd-tdp-2[v42]
