board/recalbox/c2/genimage.cfg, board/recalbox/grub2/genimage.cfg, board/recalbox/rpi/genimage.cfg, board/recalbox/xu4/genimage.cfg
=> Prevents building image from Ubuntu 17.04 when executing genimage

board/recalbox/fsoverlay/recalbox/scripts/rpi-pin356-power.py
First release !
Kill emulators : RetroArch, PPSSPP, Reicast, Mupen64Plus, LineApple & Vice x64
Other emulators soon and other features
-Genetik57
=> Fix kill button

board/recalbox/fsoverlay/recalbox/share_init/roms/wii/_info.txt
<extension>.iso .ISO .wbfs .WBFS .elf .ELF .dol .DOL .gcm .GCM .ciso .CISO .gcz .GCZ .wad .WAD</extension>
=> Updating wii/_info.txt with all extensions allowed

board/recalbox/fsoverlay/recalbox/scripts/kodilauncher.sh
added command line parameter to kodi launch command to direct kodi to working lirc node (device).
=> launch kodi with explicit lirc device.

scripts/linux/checkPackagesUpdates.sh
=> amiga: add amiberry and fsuae

board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg
*Adding several extensions
*Rectification of some extensions
*Deleting some useless extensions
-Genetik57
=> General revision

board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg
=> Several changes

package/batocera/recalbox-themes/extras/pcfx/custom.xml, package/batocera/recalbox-themes/extras/pcfx/theme.xml
=> PC-FX theme

board/recalbox/fsoverlay/recalbox/scripts/recalbox-systems.py, board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg, package/batocera/freeintv/Config.in, package/batocera/freeintv/libretro-freeintv.mk
I will try to add a new core, I'll warn when it's over
=> FreeIntv: New Core (Mattel Intellivision)

package/batocera/libretro-picodrive/libretro-picodrive.mk
=> libretro-picodrive update

package/batocera/libretro-snes9x-next/libretro-snes9x-next.mk, package/batocera/libretro-snes9x/libretro-snes9x.mk
=> snes9x and snes9x-next update

package/batocera/libretro-genesisplusgx/libretro-genesisplusgx.mk
=> genesisplusgx update

package/batocera/libretro-yabause/libretro-yabause.mk
=> libretro-yabause update

board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg
=> Intellivision: .itv extension added

board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg
=> Deleted space

package/batocera/libretro-mame2010/001-Makefile.patch, package/batocera/libretro-mame2010/libretro-mame2010.mk, package/batocera/retroarch/retroarch.mk
=> mame2010 update

board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg
=> CDTV: .bin & .cue added

package/batocera/retroarch/retroarch-002-hotkey-select-fix.patch, package/batocera/retroarch/retroarch-005-avoid_x11utf8.patch, package/batocera/retroarch/retroarch-007-fix-configure.patch, package/batocera/retroarch/retroarch.hash, package/batocera/retroarch/retroarch.mk
=> retroarch update to 1.7.1

package/batocera/libretro-stella/0000-stella-makefile.patch, package/batocera/libretro-stella/libretro-stella.mk
=> libretro-stella update

package/batocera/virtualgamepads/virtualgamepads.mk
=> virtualgamepads update

package/batocera/libretro-fmsx/0000-makefile.patch
An error occurred during compilation for the RPI platform.
https://pastebin.com/XM6cjf2K
=> libretro-fmsx - rpi: fix

package/batocera/wxwidgets/wxwidgets.mk
=> wxwidgets: fix for other plateforms

package/batocera/recalbox-initramfs/init
because when i debug, 128MB is regularly not often.
=> rootfs: make it a bit bigger for debug

package/batocera/libretro-reicast/001-save.patch
Files were being saved inside the BIOS folder were redirected to /recalbos/saves/dreamcast/
=> libretro-reicast: save

board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg, board/recalbox/legacyxu4/fsoverlay/etc/init.d/S02fan, board/recalbox/xu4/fsoverlay/etc/init.d/S02fan
=> XU4 fan noise + Intellivision extensions

package/batocera/recalbox-system/c2/recalbox.conf, package/batocera/recalbox-system/rpi1/recalbox.conf, package/batocera/recalbox-system/rpi2/recalbox.conf, package/batocera/recalbox-system/rpi3/recalbox.conf, package/batocera/recalbox-system/s905/recalbox.conf, package/batocera/recalbox-system/s912/recalbox.conf, package/batocera/recalbox-system/x86/recalbox.conf, package/batocera/recalbox-system/x86_64/recalbox.conf
https://github.com/batocera-linux/batocera-emulationstation/pull/19
=> retroachievements: update

package/batocera/libretro-o2em/libretro-o2em.mk
https://github.com/libretro/libretro-o2em/commit/f36b52fb729ff347b901df03639ef5bf56de2b3b
=> libretro-o2em: fix Need to use the keyboard to start the game

package/batocera/libretro-fba/libretro-fba.mk
https://github.com/libretro/fbalpha/releases
=> libretro-fbalpha: Latest release v0.2.97.42

package/batocera/batocera-es-system/es_systems.yml, package/batocera/libretro-mame2003-plus/libretro-mame2003-plus.mk
=> mame2003-plus: Update + little correction

package/batocera/batocera-system/Config.in
=> python dbus

package/batocera/qtsixa/qtsixa.mk
=> sixpair-kbd: binary added

package/mesa3d-headers/mesa3d-headers.mk, package/mesa3d/mesa3d.hash, package/mesa3d/mesa3d.mk
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
=> package/{mesa3d, mesa3d-headers}: bump version to 18.1.4

package/batocera/core/batocera-retrogame/Config.in, package/batocera/core/batocera-retrogame/RetroGame/Makefile, package/batocera/core/batocera-retrogame/RetroGame/README.md, package/batocera/core/batocera-retrogame/RetroGame/gamera.c, package/batocera/core/batocera-retrogame/RetroGame/retrogame.c, package/batocera/core/batocera-retrogame/batocera-retrogame.mk
Commits on Aug 1, 2015 - 8d3e90ed179146d717201b6f4337290100f9ca26
=> package: batocera-retrogame

package/batocera/emulators/retroarch/libretro/libretro-beetle-psx/000.makefile.patch, package/batocera/emulators/retroarch/libretro/libretro-beetle-psx/libretro-beetle-psx.mk
Added the option to choose between rendering by software or hardware in libretro-beetle-psx
=> libretro-beetle-psx with hw

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Added ppsspp15 to generate the es_system
=> add: ppsspp 1.5.4

board/batocera/fsoverlay/recalbox/scripts/recalbox-systems.py
=> add bios check for naomi

board/batocera/fsoverlay/recalbox/share_init/bios/ProSystem.dat
*Finally the support of the Light Gun!
*General update
*Many improvements
=> [Atari 7800] Light Gun Support + Update + Improvements

package/batocera/Config.in
=> fix ds4drv

board/batocera/fsoverlay/etc/init.d/S11share
=> fix sharedevice comments

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> 3do extensions list update

package/batocera/Config.in, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/citra/Config.in, package/batocera/emulators/citra/citra.mk
=> add: Citra

board/batocera/rpi/config.txt, package/rpi-firmware/config.txt
*CPU and GPU memory adjustment for better performance with the PPSSPP emulator
This commit only concerns rpi architectures
-Thanks to mrfixit2001 for his help
=> PPSSPP: Adjusting the CPU and GPU memory

batocera-Changelog, package/batocera/emulators/retroarch/libretro/libretro-snes9x/libretro-snes9x.mk
=> libretro-snes9x: update to Snes9x 1.58

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> mgba supports gb and gbc

board/batocera/rpi/config.txt
=> fix rpi composite sound

board/batocera/fsoverlay/etc/init.d/S02splash
=> rockpro64: respect sound disabled option

board/batocera/busybox.custom.config
=> command timeout

package/batocera/emulators/retroarch/retroarch/retroarch.mk, package/batocera/gpu/mali-rk450/egl.pc, package/batocera/gpu/mali-rk450/mali-rk450.mk
=> rockpro64: fix retroarch gpu

board/batocera/rockpro64/kernel_patches/linux-usb-hid-atari-retrobit.patch, board/batocera/rockpro64/kernel_patches/linux-usb-hid-input.xinmo.patch, board/batocera/rockpro64/kernel_patches/linux-usb-hid-quirks.xinmo.patch, board/batocera/rockpro64/kernel_patches/linux-usbhid-quircks.patch, board/batocera/rockpro64/kernel_patches/linux-wiimote-abs-not-hat.patch
=> rockpro64-pads

board/batocera/rockpro64/extlinux.conf
=> rockpro64-resolution

package/batocera/emulators/retroarch/libretro/libretro-mame2016/libretro-mame2016.mk
=> libretromame2016-compilefix

package/batocera/emulators/retroarch/libretro/libretro-mame2016/libretro-mame2016.mk
=> mame2016: yet another dir that fails sometimes at compilation step

package/batocera/libraries/sfml/Config.in
Missing dependency on SFML for LibVorbis Library in order to build
=> Update SFML Config.in for missing dep

package/batocera/emulators/retroarch/libretro/libretro-desmume/Config.in, package/batocera/emulators/retroarch/libretro/libretro-desmume/libretro-desmume.mk, package/libpcap/0001-pcap-usb-linux.c-add-missing-limits.h-for-musl-systems.patch, package/libpcap/libpcap.hash, package/libpcap/libpcap.mk
It was necessary to update libpcap for version 1.9.0 the previous one with bug.
=> update: libretro-desmume

board/batocera/doPcsx2package.sh, board/batocera/fsoverlay/etc/init.d/S12populateshare, board/batocera/fsoverlay/recalbox/scripts/recalbox-config.sh, board/batocera/fsoverlay/recalbox/scripts/recalbox-info.sh, board/batocera/fsoverlay/recalbox/scripts/recalbox-install.sh, board/batocera/fsoverlay/recalbox/scripts/recalbox-overclock.sh, board/batocera/fsoverlay/recalbox/scripts/recalbox-upgrade.sh, package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/core/batocera-desktopapps/scripts/recalbox-config-pcsx2.sh
=> fix: arch filename

package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py
=> configgen: citra

board/batocera/fsoverlay/recalbox/scripts/recalbox-systems.py
=> Bios Checker: Reorganization + Cleaning

board/batocera/fsoverlay/recalbox/scripts/recalbox-systems.py
=> Bios Checker: N64 bios added

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py
=> mupen: fix config dir creation

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> libretro: add fs by default (required for x86* and n2)

board/batocera/fsoverlay/usr/share/batocera/datainit/system/.emulationstation/es_input.cfg
=> 8bitdo: axes

board/batocera/busybox.custom.config
=> nc: users file sharing

package/batocera/core/batocera-system/Config.in
=> choices-comment

package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py
=> amiberry: fix pad have slashes in their name

board/batocera/fsoverlay/usr/share/batocera/datainit/system/.emulationstation/es_input.cfg
=> pad: update database

board/batocera/network_hotplug/S02hotplug, board/batocera/network_hotplug/checketh.sh
=> remove unused files

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py
=> pcsx2: fix configgen ini

board/batocera/patches/mesa3d/001-intelgl2114.patch
=> fix some intel gpu

board/batocera/fsoverlay/etc/init.d/S12populateshare, board/batocera/fsoverlay/usr/share/batocera/datainit/decorations/readme.txt
=> bezel custom directory

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-system/x86_64/recalbox.conf
=> ps2: enable full boot by default

board/batocera/legacyxu4/kernel-odroid-3.10-defconfig-fragment.config
=> fix xu4 linux compilation (remove rtl8812au)

package/batocera/emulationstation/recalbox-themes/recalbox-themes.mk
=> theme version

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
=> bezel: option to force no bezel over the user configuration

package/batocera/controllers/retrogame/retrogame.mk
=> retrogame bin name

package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
=> bezel: bump

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> fix: bezel for games and including spaces

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> separate naomi and atomiswave

batocera-Changelog, package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
=> wii: use pads as gc pads

package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
=> bezel: updated by fery65

board/batocera/grub2/genimage.cfg
=> x86: increase the img partition size to 3G

package/batocera/core/batocera-system/Config.in
=> s905: remove mupen64plusnext not compiling

package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
=> fix bezels : gamegear

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> desmume: pad ; mame2003: remove warning

board/batocera/fsoverlay/etc/init.d/S12populateshare
=> fix decoration initialisation

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> mame2003: remove warnings

package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
=> bezel: fix gamegear

board/batocera/fsoverlay/usr/share/batocera/datainit/system/.emulationstation/es_input.cfg
=> new joystick

package/batocera/core/batocera-splash/S02splash-image
=> splash: customizable image

board/batocera/fsoverlay/usr/share/batocera/datainit/system/.kodi/userdata/guisettings.xml
=> change airplay service name

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> fix fba shaders

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-system/Config.in, package/batocera/emulationstation/batocera-es-system/es_systems.yml
libretro-mame2003 replaced by libretro-mame2003-plus
=> removed: libretro-mame2003

package/batocera/libraries/sfml/sfml.mk
=> fix sfml compilation

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
a 4/3 resolution stretch the image on 16/9 tv
=> reicast: change default resolution on rpi

board/batocera/fsoverlay/recalbox/scripts/bluetooth/pair-device, board/batocera/patches/bluez5_utils/0005-no-link-key.patch
https://cs.stanford.edu/people/eroberts/courses/soco/projects/2003-04/wireless-computing/sec_bluetooth.shtml
=> better bt association

board/batocera/patches/sdl2/sdl2-devices-blacklist.patch
=> sdl2: blacklist the ps4 in bt

package/batocera/core/batocera-configgen/configgen/configgen/generators/fba2x/fba2xControllers.py
=> fba2x: fix controllers

board/batocera/odroidn2/patches/batocera-emulationstation/001-fixtty.patch
=> odroidn2: fix tty

board/batocera/fsoverlay/usr/share/batocera/datainit/system/.emulationstation/es_input.cfg
=> 3 new pads configurations

package/batocera/emulators/retroarch/libretro/libretro-fba/libretro-fba.mk
version with better compatibility with roms
=> neogeocd: bump libretro-fba

linux/linux.mk
=> fix dts test

package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidn2.yml
=> ppsspp: no frameskip on odroidn2

scripts/linux/batoceraBuild
=> batoceraBuild: the script used to handle the batocera compiler machine

board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc, board/batocera/x86/fsoverlay/usr/bin/batocera-resolution, package/batocera/core/batocera-system/x86/recalbox.conf
=> Option to set X11 dpi and default resolution

package/batocera/emulators/pcsx2-x86/pcsx2-x86.mk
=> align pcsx2-x86 and batocera version

board/batocera/fsoverlay/usr/share/batocera/datainit/system/configs/mupen64/input.xml, package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py
=> allow n64.analogpeak and analogdeadzone in recalbox.conf

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-system/Config.in, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/retroarch/libretro/libretro-mame2003/libretro-mame2003.mk
=> lr-mame2003: updated and enabled

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
=> mupen64: fixed wide screen mode

board/batocera/fsoverlay/etc/init.d/S11share, package/batocera/boot/batocera-initramfs/init
=> fix renamings

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> fix shaders (2)

package/batocera/emulators/ppsspp/ppsspp.mk
=> fix: ppsspp for odroid xu4

board/batocera/post-build-script.sh
=> fix: path recalbox-system.py

package/batocera/core/batocera-system/batocera-system.mk
=> fix: date and time in version

package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info
That is the script that actually parses and format the data from
https://retroachievements.org -- see the previous PR for the
corresponding Batocera-ES code.
=> Added a RetroAchievements menu in ES.

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix: compatibility with Retropie themes

batocera-Changelog, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/retroarch/libretro/libretro-cap32/libretro-cap32.mk
=> add: amstrad GX4000

board/batocera/fsoverlay/etc/init.d/S31emulationstation
=> disable splash on board other than x86 for the video

board/batocera/fsoverlay/usr/share/batocera/datainit/system/configs/emulationstation/es_input.cfg
=> some pads configurations

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py
=> fix mupen when the userfile is not complete

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
=> fix: remove gc pads configuration on emulated wiimotes

package/batocera/core/batocera-system/Config.in
=> add: ffmpeg_gpl

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> gx4000: added extension cpr and zip

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py
=> configgen: fix support for gamepads with unicode char in their names.

package/batocera/emulationstation/es-theme-carbon/es-theme-carbon.mk
=> bump: es-theme-carbon

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/emulators/retroarch/libretro/libretro-hatari/001-pathconfig.patch
=> fix: path hatari.cfg

package/batocera/emulators/retroarch/libretro/libretro-mrboom/Config.in, package/batocera/emulators/retroarch/libretro/libretro-mrboom/libretro-mrboom.mk
=> Mr. Boom Core

package/batocera/emulators/retroarch/libretro/libretro-pcsx/libretro-pcsx.mk
=> bump: libretro-pcsx_rearmed

package/batocera/emulators/ppsspp/ppsspp.mk, package/batocera/emulators/retroarch/libretro/libretro-neocd/libretro-neocd.mk, package/batocera/emulators/retroarch/libretro/libretro-picodrive/libretro-picodrive.mk, package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> fix some aarch64 issues

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix: gameandwatch

package/batocera/core/batocera-system/Config.in
=> feat: dialog for scripts

package/batocera/emulators/retroarch/libretro/libretro-atari800/001-config.patch
=> fix: path .atari800.cfg

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> fix: d-pad does not work in lr-mame2003-plus

package/batocera/emulators/retroarch/retroarch/retroarch-008-pathconfig.patch
=> fix: path retroarch-core-options.cfg

board/batocera/fsoverlay/etc/init.d/S12populateshare
=> fix a mistake that caused some initialization bugs

board/batocera/fsoverlay/etc/init.d/S12populateshare
=> fix missing directories at init

package/batocera/core/batocera-scripts/scripts/batocera-es-theme
Required by the ES pull request that will arrive in a few seconds...
=> Updated so that ES can now show install progress

package/batocera/emulators/retroarch/libretro/libretro-kronos/libretro-kronos.mk
https://www.libretro.com/index.php/kronos-1-7-0-new-renderer/
=> bump: libretro-kronos to v1.7.0

package/batocera/core/batocera-configgen/configgen/configgen/generators/reicast/reicastGenerator.py
=> fix reicast in case of corrupted / file with bad values

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> fix: libretroOptions

package/batocera/emulators/retroarch/retroarch/retroarch-008-msgfastforward.patch, package/batocera/emulators/retroarch/retroarch/retroarch.hash, package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> fix: fast forward message

package/batocera/emulators/retroarch/shaders/batocera-shaders/Config.in, package/batocera/emulators/retroarch/shaders/batocera-shaders/batocera-shaders.mk
=> shaders: removing unused dependencies

batocera-Changelog, package/batocera/emulators/moonlight-embedded/moonlight-embedded.mk
=> moonlight: bump to v2.4.10

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> lr-3do: added 4do_dsp_threaded

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix: name of the consoles

package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> fix: retroarch

board/batocera/fsoverlay/etc/init.d/S31emulationstation, package/batocera/core/batocera-system/rpi1/batocera.conf, package/batocera/core/batocera-system/rpi2/batocera.conf, package/batocera/core/batocera-system/rpi3/batocera.conf, package/batocera/utils/rpigpioswitch/S92switch, package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
This is powerswitch device from Pimoroni:
https://shop.pimoroni.de/products/onoff-shim
Added settings to batocera.conf for RPi series
@nadenislamarre Is this PR okay now? I removed the changes done to S31emulationstation
=> RPi: added ONOFFSHIM to rpi_gpioswitch (start/stop function)

package/batocera/emulators/retroarch/libretro/libretro-fbneo/libretro-fbneo.mk
=> lr-fbneo: fix demon front

package/batocera/Config.in, package/batocera/core/batocera-system/Config.in, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/retroarch/libretro/libretro-handy/Config.in, package/batocera/emulators/retroarch/libretro/libretro-handy/libretro-handy.mk
=> add: libretro-handy for Atari Lynx

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml
=> removing fba2x as default for rpi1

package/batocera/core/batocera-configgen/configs/configgen-defaults-c2.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi2.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
=> change: default core

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix: extension

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi2.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
=> default core

batocera-Changelog, package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
you can now put your scripts in /userdata/system/scripts (in any subfolder) to react to start and stop of games
=> Eventsscripts

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> jaguar: enable fast blitter

package/batocera/emulators/scummvm/scummvm.mk
=> scummvm: bump to 2.1.0

package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/enhanced/rendering-defaults.yml
After discussions with several team members on Discord.
=> Changed the "Enhanced" shaders for GB, GBA and GBC

package/batocera/emulators/citra/citra.mk
=> bump: citra (3DS)

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi2.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
=> change in the default cores

package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/rendering-defaults.yml
=> enable default color in gambatte

package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info
As well as cosmetic fixes, and the code to retrieve retroachievments' user avatar (for future use, maybe...)
=> Added a timeout for accessing RetroAchievements.org

package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/rendering-defaults.yml
=> colors for gb at 2

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> bezel: defaults values on .info

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> clean: remove the old favorite system

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix: batocera-es-system

board/batocera/rpi1/fsoverlay/etc/init.d/S31emulationstation
=> 5s is enough with preloading removed

package/batocera/emulators/linapple-pie/linapple-pie.mk
=> bump: linapple-pie

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
=> fix colorization

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> fix: cap32_model

package/batocera/emulators/retroarch/libretro/libretro-cap32/000-virtualkeyboard.patch
=> patch: virtual keyboard

package/batocera/emulators/ppsspp/Config.in, package/batocera/emulators/ppsspp/ppsspp.mk, package/batocera/emulators/ppsspp15/Config.in, package/batocera/emulators/ppsspp15/ppsspp15.mk
=> ppsspp: organizing dependency

package/batocera/emulators/retroarch/libretro/libretro-cap32/000-virtualkeyboard.patch
=> fix: patch virtual keyboard

package/batocera/core/batocera-system/Config.in
=> linapple-pie: enabled for all platforms

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> es_system: pc engine and supergrafx

board/batocera/legacyodroidxu4/patches/libretro-neocd/cmakelistArch.patch, board/batocera/odroidc2/patches/libretro-neocd/cmakelistArch.patch, board/batocera/odroidn2/patches/libretro-neocd/cmakelistArch.patch, board/batocera/odroidxu4/patches/libretro-neocd/cmakelistArch.patch, board/batocera/rockpro64/patches/libretro-neocd/cmakelistArch.patch, board/batocera/rpi/patches/libretro-neocd/cmakelistArch.patch, board/batocera/s905/patches/libretro-neocd/cmakelistArch.patch, board/batocera/s912/patches/libretro-neocd/cmakelistArch.patch, board/batocera/tinkerboard/patches/libretro-neocd/cmakelistArch.patch
=> fix: patch lr-neocd

package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml
=> psp: change default internal resolution on x86

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> rewind enabled causes Atomiswave performance loss

package/batocera/core/batocera-scripts/scripts/batocera-systems
=> amiga: change in BIOS structure

package/batocera/emulators/retroarch/libretro/libretro-mame2003-plus/libretro-mame2003-plus.mk
=> bump: libretro-mame2003-plus

package/batocera/core/batocera-system/Config.in
=> system entropy

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix system/core name

package/batocera/emulators/citra/citra.mk
=> bump: citra-emu

package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml
=> default: sega saturn x86

package/batocera/emulators/retroarch/retroarch-assets/retroarch-assets.mk
=> fix retroarch assets

package/batocera/emulators/retroarch/libretro/libretro-flycast-wince/libretro-flycast-wince.mk, package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
=> bump: libretro-flycast

board/batocera/fsoverlay/etc/udev/rules.d/99-joysticks-exotics.rules, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject
There is a GUI menu in ES that goes with this script - look for the associated PR in batocera-emulationstation. The idea is to add per-system and per-game bezels from theBezelProject into Batocera.
Similarly to the `themes.txt` for listing themes, we need to host a file on `https://batocera-linux.xorhub.com/upgrades/bezels.txt` that lists the git repositories of the Bezel Project. If you want to override the online bezels.txt, you can host your own on  `/userdata/system/bezels.txt`.
Here is the current file:
> fba	https://github.com/thebezelproject/bezelproject-MAME
> mame	https://github.com/thebezelproject/bezelproject-MAME
> neogeo	https://github.com/thebezelproject/bezelproject-MAME	
> gbc	https://github.com/thebezelproject/bezelproject-GBC
> gb …
=> theBezelProject integration, for per-game bezels

package/batocera/device-trees/device-trees-aml-s9xx/001-fix-gxl_p231_1g.patch, package/batocera/device-trees/device-trees-aml-s9xx/002-fix-gxl_p231_c300.patch, package/batocera/device-trees/device-trees-aml-s9xx/device-trees-aml-s9xx.mk
=> fix device-trees-aml-s9xx

package/batocera/emulators/retroarch/libretro/libretro-kronos/Config.in, package/batocera/emulators/retroarch/libretro/libretro-kronos/libretro-kronos.mk
=> bump: libretro-kronos

package/batocera/emulators/retroarch/libretro/libretro-cheats/libretro-cheats.mk, package/batocera/emulators/retroarch/libretro/libretro-fbneo/libretro-fbneo.mk, package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk, package/batocera/emulators/retroarch/libretro/libretro-gambatte/libretro-gambatte.mk, package/batocera/emulators/retroarch/libretro/libretro-kronos/libretro-kronos.mk, package/batocera/emulators/retroarch/libretro/libretro-mupen64plus-next/libretro-mupen64plus-next.mk, package/batocera/emulators/retroarch/libretro/libretro-pcsx/libretro-pcsx.mk, package/batocera/emulators/retroarch/libretro/libretro-px68k/libretro-px68k.mk, package/batocera/emulators/retroarch/libretro/libretro-snes9x/libretro-snes9x.mk, package/batocera/emulators/retroarch/libretro/libretro-virtualjaguar/libretro-virtualjaguar.mk, package/batocera/emulators/retroarch/libretro/libretro-yabause/libretro-yabause.mk
pcsx/px68k/virtualjaguar/yabause cores
=> Libretro: Bump Cheats/fbneo/flycast/gambatte/kronos/mupen64plus-next

package/batocera/emulationstation/es-theme-carbon/es-theme-carbon.mk
=> update to es-carbon caruso

batocera-Changelog, package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> dolphin: add internal res and auto load custom textures

board/batocera/post-build-script.sh, package/batocera/core/batocera-scripts/scripts/batocera-config, package/batocera/core/batocera-splash/S02splash
=> share path fixing

package/batocera/core/batocera-configgen/batocera-configgen.mk, package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
=> fix configgen paths

package/batocera/emulators/mupen64plus/mupen64plus-gliden64/mupen64plus-gliden64.mk, package/batocera/emulators/mupen64plus/mupen64plus-v20-gliden64/mupen64plus-v20-gliden64.mk
@jdorigao it seems these lines were added by you, but it seems that there are not used.
can you confirm we can remove them ?
=> remove unused mupen ini files

package/batocera/emulationstation/batocera-emulationstation/S31emulationstation_xorg
=> fix xorg on fat32

batocera-Changelog
With my updates (as well as a few others that I'm aware of)
=> Updated Changelog

configs/batocera-x86_64-dev_defconfig
=> defconfig-dev: fix kernel headers

package/nvidia-driver/nvidia-driver.mk
=> fix: version libnvidia-egl-wayland.so.1.1.3

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix gamecube platform for scraping

package/batocera/emulationstation/batocera-emulationstation/S31emulationstation_xorg
=> fix: Xauthority

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> retroarch: disable quit twice

board/batocera/fsoverlay/etc/triggerhappy/triggers.d/multimedia_keys.conf
=> f1 for battery, f5 for es reload

package/batocera/core/batocera-scripts/batocera-scripts.mk
=> fix: batocera-scripts (scraper)

package/batocera/core/batocera-scripts/scripts/batocera-es-theme
Made the script compatible with progressbar in ES:
```
$ batocera-es-theme install Zoid 
Need to download 92MB from https://github.com/RetroPie/es-theme-zoid
>>> 0%
>>> 11%
>>> 34%
>>> 54%
>>> 100%
Unzipping es-theme-zoid theme files...
Theme Zoid is now installed
```
=> Update theme installer for % and progressbar display

package/batocera/emulators/ppsspp/ppsspp.mk
=> bump: ppsspp to v1.9.1

package/batocera/emulators/reicast/Config.in
=> fix: reicast depends on

package/batocera/emulators/retroarch/libretro/libretro-flycast/Config.in, package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
=> lr-flycast: add openmp dependency

package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
=> lr-mame: add openmp dependency

board/batocera/fsoverlay/etc/init.d/S12populateshare, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> clean some retroarch opts

package/batocera/core/batocera-scripts/scripts/batocera-bezels
=> script batocera-bezels

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/reicast/reicastControllers.py
=> revert: reicast configgen

package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidn2.yml
=> odroidn2: crashes with genesisgxplus

package/unzip/unzip.mk
=> fix: false positive zip bomb

package/batocera/emulationstation/batocera-es-system/systems-explanations.yml
=> some explanations

batocera-Changelog
* add: new "splash screen" Batocera intro video. (special thanks to Christo Snakerville).
=> Splash screen

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
=> fix: call script for kodi

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> sg1000 es platform

package/batocera/emulators/retroarch/retroarch/retroarch-002-hotkey-select-fix.patch
=> fix retroarch hotkey

board/batocera/odroidxu4/patches/reicast/004-fix-sound.patch
=> fix reicast on xu4 kernel 4

board/batocera/odroidn2/linux_patches/linux-cvbs.patch
=> odroidn2 composite tv out

package/batocera/core/batocera-splash/S02splash, package/batocera/core/batocera-splash/S02splash-ffplay, package/batocera/core/batocera-splash/S02splash-omx
=> allow more time for video splash

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> allow the user to override the configgen values for retroarch.cfg

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
=> custom game configs now includes the system

package/batocera/emulationstation/batocera-es-system/systems-explanations.yml
=> genesis and picodrive explanations

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix psx iso files

package/batocera/emulationstation/batocera-es-system/batocera-report-system.py
Works with python2 and python3.
=> remove yaml deprecation warning

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> retroarch cache folder

package/batocera/core/batocera-scripts/scripts/batocera-config, package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject, package/batocera/core/batocera-scripts/scripts/batocera-es-theme, package/batocera/core/batocera-scripts/scripts/batocera-install, package/batocera/core/batocera-scripts/scripts/batocera-upgrade, package/batocera/core/batocera-system/rpi1/batocera.conf, package/batocera/core/batocera-system/rpi2/batocera.conf, package/batocera/core/batocera-system/rpi3/batocera.conf, package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk, package/batocera/emulationstation/batocera-es-system/batocera_systemsReport.html, package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk
=> update web urls

scripts/linux/theBezelProject-md5gen
This script is intended to run on a build machine (or the Batocera web server). It generates the files listed on http://batocera.org/upgrades/thebezelproject/ and tracks changes in the bezels so that you can run incremental updates (much) faster. Kudos to @Evoflash for this!
=> Generate MD5 for theBezelProject files.

package/batocera/utils/rpigpioswitch/S92switch, package/batocera/utils/rpigpioswitch/rpi-retroflag-GPiCase.py, package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh, package/batocera/utils/rpigpioswitch/rpigpioswitch.mk
This will make GPi case from Retroflag work to use safe shutdown feature.
@genetik57 tested the former patch from my resp
It works fine
=> Prepare Retroflag GPi case

package/batocera/gpu/gpu-aml/gpu-aml.mk
Change source to https://github.com/openwetek/gpu-aml.git
=> Change source.

package/batocera/core/batocera-scripts/scripts/batocera-systems
source: 
https://github.com/libretro/libretro-super/blob/aae46d3f13be5fe70a6082d8d2cca8b5fef7abb0/dist/info/flycast_libretro.info#L39
=> batocera-systems: correct naomi.zip md5

package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bt-pair-device
=> bt: increase timeout and add options

package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bt-pair-device, package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-btDaemon
=> bt better pairing

package/batocera/emulators/retroarch/retroarch/Config.in, package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> retroarch : flac dep

package/batocera/emulators/retroarch/libretro/libretro-handy/libretro-handy.mk
=> bump: libretro-handy

package/batocera/utils/gpicase/batocera-gpicase-install
=> write force_gpi_defaults only 1 time!

board/batocera/patches/sdl2/sdl2_input_evdev_at_first_unrelease_button.patch
=> fix: sdl2 initial state

package/batocera/emulators/retroarch/retroarch/retroarch_input_p006_sort_devices.patch
=> revert retroarch non sorting pads

package/batocera/core/batocera-configgen/configgen/configgen/generators/reicast/reicastControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/reicast/reicastGenerator.py
=> reicast : unconfigure unrequired pads while reicast doesn't like them

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
=> net options on configgen command line

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
=> options required for net

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
- it doenst work
- the mapping is strange : Main Stick/Up assigned 2 times
- _any function hardcode gamecube check
- checks are done for each button (this is why it fails)
=> fix: revert buggy patch

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> nicer image on retroarch on low resolutions

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
=> gc for pads without axes

package/batocera/emulators/retroarch/libretro/libretro-bsnes/000-GNUmakefile.patch, package/batocera/emulators/retroarch/libretro/libretro-bsnes/libretro-bsnes.mk
=> update: libretro-bsnes

package/batocera/emulators/retroarch/libretro/libretro-beetle-wswan/libretro-beetle-wswan.mk
=> update: libretro-beetle-wswan

package/batocera/emulators/retroarch/libretro/libretro-parallel-n64/000-rockpro64.patch, package/batocera/emulators/retroarch/libretro/libretro-parallel-n64/001-arm_fix.patch, package/batocera/emulators/retroarch/libretro/libretro-parallel-n64/libretro-parallel-n64.mk
=> update: libretro-parallel-n64

package/batocera/emulators/vice/vice.mk
=> update: vice

package/batocera/emulators/scummvm/scummvm.mk
=> update: scummvm

package/batocera/emulators/amiberry/000-amiberry-path.patch, package/batocera/emulators/amiberry/002-amiberry-core.patch, package/batocera/emulators/amiberry/amiberry.mk
=> bump: amiberry

package/batocera/emulators/retroarch/libretro/libretro-daphne/libretro-daphne.mk
=> add: folder structure required for libretro-daphne

package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
=> bump: batocera-emulationstation

package/batocera/emulators/fsuae/fsuae.mk
=> bump: fs-uae 3.0.0

package/batocera/emulators/retroarch/retroarch-assets/retroarch-assets.mk, package/batocera/emulators/retroarch/retroarch/retroarch-000-disable-search-menu.patch, package/batocera/emulators/retroarch/retroarch/retroarch-007-fix-configure.patch, package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> bump: retroarch v1.8.2

package/batocera/Config.in, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-system/Config.in, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/daphne/000-buildfix.patch, package/batocera/emulators/daphne/Config.in, package/batocera/emulators/daphne/daphne.mk
Package is ready configgen is missing.
=> add: package hypseus

package/batocera/emulators/retroarch/libretro/libretro-atari800/libretro-atari800.mk, package/batocera/emulators/retroarch/libretro/libretro-beetle-pce/libretro-beetle-pce.mk, package/batocera/emulators/retroarch/libretro/libretro-bluemsx/libretro-bluemsx.mk, package/batocera/emulators/retroarch/libretro/libretro-fbneo/libretro-fbneo.mk, package/batocera/emulators/retroarch/libretro/libretro-gw/libretro-gw.mk, package/batocera/emulators/retroarch/libretro/libretro-kronos/libretro-kronos.mk, package/batocera/emulators/retroarch/libretro/libretro-mame2003-plus/libretro-mame2003-plus.mk
https://www.libretro.com/index.php/libretro-core-progress-report-december-31-2019/
=> bump: libretro

package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
=> psp rewind

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> lr-theodore: enable auto run game

package/batocera/emulators/ppsspp/005-fastforward.patch
=> ppsspp : fast forward

package/batocera/core/batocera-system/Config.in
=> fix: libretro-yabasanshiro

package/batocera/emulators/dolphin-emu/000-cmake.patch, package/batocera/emulators/dolphin-emu/dolphin-emu.mk
=> bump: dolphin-emu to 5.0-11422

package/batocera/emulators/amiberry/000-amiberry-path.patch, package/batocera/emulators/amiberry/amiberry.mk
=> bump: amiberry v3.0.11

package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
=> update: batocera-emulationstation

package/batocera/emulators/retroarch/libretro/libretro-px68k/libretro-px68k.mk
=> bump: libretro-px68k

package/batocera/core/batocera-system/Config.in, package/batocera/emulators/retroarch/libretro/libretro-theodore/libretro-theodore.mk
=> bump: libretro-theodore

package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> bump: retroarch to v1.8.3

batocera-Changelog
=> changelog: retroarch v1.8.3

package/batocera/emulators/daphne/000-buildfix.patch, package/batocera/emulators/daphne/001-bugfix.patch
=> hypseus: patch

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> daphne: extension used .daphne

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix: es_system PC98

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
=> fix: configgen-defaults PC98

package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
=> daphne: fullscreen

package/batocera/emulators/ppsspp/ppsspp.mk
=> bump: ppsspp

board/batocera/fsoverlay/etc/init.d/S12populateshare, package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-system/Config.in, package/batocera/emulators/daphne/003-install.patch, package/batocera/emulators/daphne/daphne.mk
=> add: daphne (hypseus)

batocera-Changelog, package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> bump: retroarch to v1.8.4

package/batocera/emulators/retroarch/libretro/libretro-bluemsx/libretro-bluemsx.mk
=> lr-bluemsx: folders Databases and Machines

package/batocera/emulators/reicast/Config.in
=> reicast: depends openmp

package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppControllers.py
=> fix psp when playing with the pad not number 1 in sdl

package/batocera/core/batocera-desktopapps/scripts/filemanagerlauncher
=> fix f1 on exfat

package/batocera/emulators/retroarch/libretro/libretro-neocd/libretro-neocd.mk
=> lr-neocd: added makefile

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceGenerator.py, package/batocera/emulators/vice/vice.mk
=> vice: controllers

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-system/Config.in
=> fix: load the game

batocera-Changelog
=> batocera-changelog

package/batocera/core/batocera-system/Config.in
=> disable: libretro-scummvm

package/batocera/emulators/retroarch/libretro/libretro-dosbox/Config.in, package/batocera/emulators/retroarch/libretro/libretro-dosbox/libretro-dosbox.mk
=> replacing lr-dosbox with lr-dosbox-svn

package/batocera/core/batocera-scripts/Config.in, package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-hybrid-nvidia
=> script: batocera-hybrid-nvidia

package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-cores, package/batocera/emulators/retroarch/retroarch/retroarch-009-coreinfos.patch
=> batocera-cores script

package/batocera/core/batocera-scripts/scripts/batocera-hybrid-nvidia
=> fix: batocera-hybrid-nvidia

package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-hybrid-nvidia
=> hybrid: save-overlay removed

board/batocera/fsoverlay/etc/init.d/S02resize
Nothing special @nadenislamarre
=> S02resize - minimal code cleanup

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/emulators/fsuae/004-plugin-dir.patch, package/batocera/libraries/capsimg/capsimg.mk
=> bump: capsimg

package/batocera/core/batocera-scripts/batocera-scripts.mk
=> fix batocera-scripts install

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
@jdorigao i was not able to reproduce https://pastebin.com/raw/KXVtxn9i for an unknown reason (i should investigate). but if you can check that this fix is ok for you, i let you merge and that's ok.
=> fix: dolphin pads

package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-wifi
=> batocera-wifi list

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceGenerator.py, package/batocera/emulators/vice/vice.mk
=> vice: correction and improvement the configgen

package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info
Requirement to display RetroAchievements badges in https://github.com/batocera-linux/batocera-emulationstation/pull/342
=> Display retroachievements badges

board/batocera/fsoverlay/usr/share/batocera/datainit/system/configs/retroarch/retroarchcustom.cfg, package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> retroarch: enable ffmpeg

package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py
=> fix: citra-emu control

batocera-Changelog, package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/core/batocera-system/Config.in
=> enable: libretro-puae

package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
=> daphne: fastboot

package/batocera/emulators/retroarch/libretro/libretro-bsnes/libretro-bsnes.mk
=> lr-bsnes: repository DerKoun

package/batocera/emulators/retroarch/libretro/libretro-4do/000-makefile.patch
=> patch: libretro-4do

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
Update to allow individual rom based controller configuration overrides.
=> Update dolphinControllers.py to support rom based configuration

package/batocera/core/batocera-scripts/scripts/batocera-systems
=> bios: atomiswave

package/batocera/emulators/mupen64plus/mupen64plus-core/mupen64plus-core.mk, package/batocera/emulators/mupen64plus/mupen64plus-gliden64/mupen64plus-gliden64.mk, package/batocera/emulators/mupen64plus/mupen64plus-rsphle/mupen64plus-rsphle.mk
=> bump: mupen64plus

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/hooks/bluetooth-discovery-hook, package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
=> disable discovering while playing (input lag for some pads)

package/batocera/emulators/retroarch/retroarch/retroarch-010-netplay.patch
=> netplay: @BATOCERA

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py
=> fix n64 pads

board/batocera/patches/sdl2/sdl2_input_evdev_at_first_unrelease_button.patch
=> fix axis when back from es

batocera-Changelog, package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
=> bump: lr-mame to 0.218

board/batocera/patches/sdl2/sdl2_input_p003_extra_functions.patch
=> fix sdl2 codes

batocera-Changelog, package/batocera/emulators/dolphin-emu/dolphin-emu.mk
=> bump: dolphin to 5.0-11632

package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml
=> fix 905 yaml for n64

package/batocera/emulators/reicast/reicast.mk
=> reicast: extra arguments

package/batocera/emulators/retroarch/libretro/libretro-bsnes/libretro-bsnes.mk
=> replaced by libretro-bsnes

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py
=> retroarchcustom

board/batocera/fsoverlay/etc/profile.d/terminal_setup.sh, board/batocera/post-build-script.sh
I think this is the best way to do and it looks tidy!
sourcing is done by default /etc/profile
```
for i in /etc/profile.d/*.sh ; do
if [ -r "$i" ]; then
. $i
fi
done
unset i
```
=> Created /etc/profile.d/terminal_setup.sh

package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
=> daphne: widescreen only on 16/9

package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation-joysticks-indexes.patch
=> fix pad indexes according to system numeration

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/kodi/kodiConfig.py
don't merge.
i've to do the correspondant pr in es.
=> fix kodi axis number

package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml
=> retroarch: default rgui menu for odroid-go

package/batocera/emulators/daphne/004-hotkey.patch
=> daphne: hotkey + start for exit

board/batocera/fsoverlay/usr/share/batocera/datainit/system/configs/emulationstation/es_input.cfg
CSL uses same GUID as ELCOM
(maybe annother revision?)
=> Added CSL gamepad

board/batocera/rockpro64/fsoverlay/etc/asound.conf, package/batocera/core/batocera-scripts/scripts/batocera-config
=> fix sound on rockpro64

package/bluez5_utils/bluez5_utils.mk
=> add tool btmgmt

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> adding the msx1 and msx2 folders

board/batocera/odroidgoa/patches/daphne/board-rotation.patch
=> daphne: rotation

batocera-Changelog, board/batocera/odroidgoa/patches/amiberry/board-rotation.patch, package/batocera/emulators/amiberry/amiberry.mk
=> bump: amiberry v3.1.2

package/batocera/emulators/retroarch/retroarch/retroarch-001-extend-udev-buttons.patch
=> fix ra pads with key

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/core/batocera-configgen/configs/configgen-defaults-miqi.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc2.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidn2.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rock960.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rockpro64.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi2.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-tinkerboard.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> group: Amiga and MSX

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> netplay: spectator mode

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
=> netplay spectator args

package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml
=> default dreamcast on ogoa

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> adding megadrive to retroachievements

board/batocera/fsoverlay/usr/share/batocera/datainit/system/configs/emulationstation/es_input.cfg
Thanks to @Darknior for some mapping
=> Controllers: 8BitDo mapping update

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
=> add: neogeo to retroachievements

board/batocera/fsoverlay/etc/init.d/S12populateshare, package/batocera/core/batocera-system/Config.in
=> Fix a couple of boot error messages

package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceGenerator.py
=> fix: vice controller

board/batocera/odroidxu4/fsoverlay/etc/init.d/S02fan
https://wiki.odroid.com/odroid-xu4/application_note/manually_control_the_fan#fully_manual_way_to_control_the_fan_speed
=> Update S02fan for XU4 kernel 4.14

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
=> wii: better fps

board/batocera/fsoverlay/recalbox/share, board/batocera/fsoverlay/recalbox/share_init
=> clean share links

package/batocera/core/batocera-scripts/scripts/batocera-moonlight, package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info
That happens with https://retroachievements.org/game/12649 for example. Thanks @Darknior for testing weird games and finding out bugs!
=> Fixed a bug in rare cases where a RA game has no success icons

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> experimental: c20 and c128

package/batocera/controllers/mk_arcade_joystick_rpi/mk_arcade_joystick_rpi.mk
Signed-off-by: Jérémy Del Grosso <genetik57@batocera.org>
and
=> GPIO: Update to 1.6.0

board/batocera/fsoverlay/usr/share/batocera/datainit/system/configs/emulationstation/es_input.cfg
Thanks to @darknior for the 8BitDo FC30 Pro mapping
Signed-off-by: Jérémy Del Grosso <genetik57@batocera.org>
=> Controllers: New GPIO mapping + 8BitDo FC30 Pro mapping added

package/batocera/core/batocera-system/Config.in
Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis@soprasteria.com>
=> fix: BR2_PACKAGE_XKEYBOARD_CONFIG

package/batocera/emulators/retroarch/retroarch/retroarch.mk
https://github.com/libretro/RetroArch/pull/10262/commits/a4a8048a17f960fcf6a849184a8c03114667e1af
=> bump: retroarch for drm_go2 test

package/batocera/emulationstation/batocera-es-system/es_systems.yml
Removed BIN
- PC-Engine CD
- SegaSaturn
- 3DO Interactive Multiplayer
Adde CUE
- SEGA Dreamcast/Flycast
=> fix: Removed BIN extensions, added CUE

package/batocera/core/batocera-scripts/scripts/batocera-upgrade
Like https://github.com/batocera-linux/batocera.linux/pull/1394
=> batocera-upgrade: Nicer output in terminal

package/batocera/core/batocera-scripts/scripts/batocera-config, package/batocera/core/batocera-scripts/scripts/batocera-install, package/batocera/core/batocera-scripts/scripts/batocera-kodilauncher, package/batocera/core/batocera-scripts/scripts/batocera-upgrade, package/batocera/core/batocera-scripts/scripts/batocera-wifi
```
./package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fbegl_nosplash
./package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_xorg
./package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_splash
./package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_1cpu
./package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_nosplash
```
=> drop: BatoceraSettings.py -> batocera-settings

package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> fix retroarch for some boards

package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
https://github.com/batocera-linux/batocera.linux/pull/1419
Correction du précédent push
=> PSX patch to fix sound issue on Odroid XU4

board/batocera/fsoverlay/etc/init.d/S02resize
=> S02resize progress output!

board/batocera/fsoverlay/etc/init.d/S02resize
There is no chance (afaik) to see percentage output so this is pseudo percentage output
@nadenislamarre @genetik57
=> S02resize: dialog output of resize

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Happened to me with a GBA bezel from TBP.
=> Fixed a crash when using malformed bezels.

board/batocera/fsoverlay/etc/init.d/S02resize, board/batocera/fsoverlay/etc/init.d/S11share
=> fix fs for /userdata

package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-format
=> batocera-format

board/batocera/x86/linux_x86-defconfig.config, board/batocera/x86/linux_x86_64-defconfig.config
HDaudio on Intel Atom platforms
=> enabled: CONFIG_HDMI_LPE_AUDIO

package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth, package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth-agent
let the bt daemon to write it's last status in /var/run/bt_status
and bluetooth trust command display it
it is not the nicest, but i have not really a better way.
=> bt messages

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
=> default dolphin internal resolution to 0

board/batocera/patches/sdl2/sdl2_input_evdev_at_first_unrelease_button.patch
=> save sdl2 axis caches on /userdata

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix gb2players name

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Patch that was wrongly removed from 5.25 :( 
Original patch and discussion: https://github.com/batocera-linux/batocera.linux/pull/1045/files
=> Fix for run_ahead (latency reduction)

board/batocera/post-image-script.sh
Create MD5SUMS with all checksums for built files
=> md5: filecheck to use "md5sum --check MD5SUMS"

package/batocera/core/batocera-configgen/batocera-configgen.mk, package/batocera/emulationstation/batocera-es-system/Config.in, package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk, package/batocera/emulationstation/batocera-es-system/batocera-es-system.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
=> es_features.cfg

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> feature colorization

package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
=> add the video mode required for es

package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
clean while es_features is now used.
=> clean netplay commands

package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject
Thanks to Evoflash for the fix/update.
=> theBezelProject: support for Daphne and other fixes

package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife
/user/bin/batocera-es-swissknife
--overlay: this will backup the overlay file found in /boot/boot/overlay
--remount: will use remount command and toogle rw/ro command default dir is /boot .... I always forget this command ;)
it will make work a bit more comfortable behind the scenes
=> add: --remount and --overlay switch

package/batocera/alllinuxfirmwares/alllinuxfirmwares.mk
There are numerous updates for amdgpu and intel gpu. Eg. firmware 19.50 for amdgpu.
=> bump alllinuxfirmwares

package/batocera/core/batocera-splash/S03splash-image
fbv supports jpeg files so it's convenient to use it
=> jpeg files support in in S03splash-image

board/batocera/odroidgoa/patches/sdl2/board-SDL2-rotation.patch
credits .: Daniel Mehrwald
https://github.com/AreaScout/SDL/commit/54675d1edc8b8d5919ae665f7d12be3b254b0df7
=> update patch rotation odroid-go

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> configgen up to 8 players

package/batocera/core/batocera-scripts/scripts/batocera-info
=> batocera-info: rpi rev

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> clean old netplay tag

board/batocera/post-image-script.sh
=> fix btrfs tool localtion

board/batocera/rpi4/patches/mupen64plus-gliden64/002-gl-buffer-size.patch
=> rpi4 fix gl

package/batocera/core/batocera-scripts/scripts/batocera-overclock
=> rpi4: overclock

package/batocera/emulators/rpcs3/005-fix-libusb.patch, package/batocera/emulators/rpcs3/rpcs3.mk
=> rpcs3: fix libusb

package/batocera/core/batocera-scripts/scripts/batocera-es-theme
Download Progress
Unzip Progress
Done with this one - finally!
=> add: es-theme unzip progress bar

board/batocera/rpi4/linux_patches/linux-fix-libyaml.patch
=> fix rpi4 libyaml

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> pcsx: enable multitap only when forced

package/batocera/core/batocera-scripts/scripts/batocera-format
=> fix formatting command

package/batocera/core/batocera-scripts/scripts/batocera-support
=> remove some batocera-support warnings

package/batocera/core/batocera-scripts/scripts/batocera-info
=> batocera-info: available memory

package/batocera/core/batocera-scripts/batocera-scripts.mk
=> Fixed batocera-create-collection install script

board/batocera/fsoverlay/etc/init.d/S02resize, package/batocera/core/batocera-scripts/scripts/batocera-format
=> format internal

board/batocera/fsoverlay/etc/init.d/S02resize, package/batocera/core/batocera-scripts/scripts/batocera-format
=> exfat: let the user choose while it's in dev

board/batocera/patches/mesa3d/002-disable-iris.patch, board/batocera/patches/sdl2/sdl2_fix_pad_name.patch
=> fix iris and sdl2

package/batocera/core/batocera-scripts/scripts/batocera-upgrade
=> Fix very old "expr" only

package/batocera/core/batocera-system/Config.in, package/batocera/emulators/openbor/openbor/003-arm.patch, package/batocera/emulators/openbor/openbor/004-warnings.patch
=> openbor arm

package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py
- Fix CD32 isos/cues launching
- Fix multi adf floppies loading for main (Disc 1 of x) format
- Add hdf compatibility
=> Fix hdf, cd32 and adf in (Disc 1 of x) format

package/batocera/emulators/openbor/openbor4432/003-arm.patch, package/batocera/emulators/openbor/openbor4432/005-sdl2gfx.patch
=> fix openbor 4432 on arm

package/batocera/utils/winbtrfs/winbtrfs.mk
=> bump winbtrfs

package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborGenerator.py
=> fix ob 4432

board/batocera/miqi/patches/uboot/0001-include-configs-Increase-CONFIG_SYS_BOOTM_LEN-to-16M.patch, board/batocera/tinkerboard/patches/uboot/0001-include-configs-Increase-CONFIG_SYS_BOOTM_LEN-to-16M.patch, package/batocera/gpu/mali-T760/mali-T760.mk
- Fixes header issues with rk(ppsspp fails to build)
=> Mali-T760:Switch to forked libmali

package/batocera/core/batocera-scripts/scripts/batocera-format
=> format message

package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/batocera-es-system.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
=> ob features

package/batocera/core/batocera-configgen/configs/configgen-defaults-miqi.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-tinkerboard.yml
=> fix defaults emulators for miqi tinkerboard

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
=> mupen vsync

package/batocera/emulators/retroarch/libretro/libretro-flycast/000-makefile.patch, package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
Bump to latest revision.
A handful of good crash fixes and emulation improvements.
=> Bump lr-flycast

package/batocera/controllers/mk_arcade_joystick_rpi/mk_arcade_joystick_rpi.mk
Signed-off-by: Jérémy Del Grosso <genetik57@batocera.org>
=> GPIO: Update to 1.7.0

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/dosbox/dosboxGenerator.py
=> fix dosbox-x

package/batocera/core/batocera-system/rpi1/batocera.conf, package/batocera/core/batocera-system/rpi2/batocera.conf, package/batocera/core/batocera-system/rpi3/batocera.conf, package/batocera/utils/rpigpioswitch/S92switch, package/batocera/utils/rpigpioswitch/rpi-kintaro-SafeShutdown.py, package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh, package/batocera/utils/rpigpioswitch/rpigpioswitch.mk
Tested by user 20goto10
* LED works
* Power works
* Reset works
* Fan untested
There is a script available from the same author for annother distro.
=> Add: ROSHAMBO/KINTARO Super Kuma System case for rpi1,rpi2,rpi3

package/batocera/core/batocera-scripts/scripts/batocera-wifi
As in https://github.com/batocera-linux/batocera.linux/pull/1712/
=> fix: WiFi list support for whitepsace in SSID

package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborControllers.py
SNES Layout
Jump: Button A
Attack1: Button B
Special: Button Y
SEGA Style like Streets of Rage MegaDrive series
We can access all keys now with a simple SNES controller
@darknior
Any suggestions to the layout?
=> fix: OpenBOR Sega Control Style

package/batocera/core/batocera-system/c2/batocera.conf, package/batocera/core/batocera-system/libretech_h5/batocera.conf, package/batocera/core/batocera-system/miqi/batocera.conf, package/batocera/core/batocera-system/odroidgoa/batocera.conf, package/batocera/core/batocera-system/odroidn2/batocera.conf, package/batocera/core/batocera-system/rock960/batocera.conf, package/batocera/core/batocera-system/rockpro64/batocera.conf, package/batocera/core/batocera-system/rpi1/batocera.conf, package/batocera/core/batocera-system/rpi2/batocera.conf, package/batocera/core/batocera-system/rpi3/batocera.conf, package/batocera/core/batocera-system/rpi4/batocera.conf, package/batocera/core/batocera-system/s905/batocera.conf, package/batocera/core/batocera-system/s912/batocera.conf, package/batocera/core/batocera-system/tinkerboard/batocera.conf, package/batocera/core/batocera-system/vim3/batocera.conf, package/batocera/core/batocera-system/x86/batocera.conf, package/batocera/core/batocera-system/x86_64/batocera.conf, package/batocera/core/batocera-system/xu4/batocera.conf
=> Cleaning the batocera.conf file again

board/batocera/odroidgoa/fsoverlay/etc/triggerhappy/triggers.d/multimedia_keys.conf
=> toogle headphones on odroidgoa

board/batocera/fsoverlay/usr/share/batocera/configgen/scripts/governor.sh
=> odroidgoa perf in game

package/batocera/libraries/libcapsimage/libcapsimage-003-gcc9.patch
My mistake, previous patch was not tested on GCC 8.
=> Fix previous GCC9 patch (was breaking GCC < 9 build)

package/batocera/emulators/supermodel3/supermodel3.mk
Forked on my own repo until I get my fixes upstreamed
=> Fix Supermodel shaders

package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> Fix windows and windows_installers missing info in es_systems.yml

package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
LTCG is disabled.
LTCG enabled causing segmentation fault
=> Fix libretro flycast crash

package/batocera/emulationstation/batocera-emulationstation/Config.in
=> es (will) needs poppler

package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
Fix synthaxe and fix bash error !
=> Broken Script Fix

batocera-Changelog, package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-record, package/batocera/core/batocera-system/Config.in
=> batocera-record

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Playstation and Playstation 2 key legend
provided by X-arcade manual here https://ibb.co/yVfsdyb
=> Update Xin-Mo Dual Arcade config based on

package/batocera/emulationstation/batocera-es-system/batocera-es-system.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Correcting issues with features not being added to system properly.
=> batocera-es-system update

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py
=> forces some ra paths

package/batocera/emulators/retroarch/libretro/libretro-stella/libretro-stella.mk
https://github.com/stella-emu/stella/releases/tag/6.2
=> bump: libretro-stella to v6.2

package/batocera/utils/pacman/002-ignoreincludedmissing.patch, package/batocera/utils/pacman/003-mkdirsondb.patch, package/batocera/utils/pacman/pacman.conf, package/batocera/utils/pacman/pacman.mk
=> pacman minor improvements

package/batocera/core/batocera-system/Config.in, package/batocera/utils/xow/99-xow.rules
=> xow: add 2nd forgotten device

package/batocera/core/batocera-scripts/batocera-scripts.mk, package/batocera/core/batocera-scripts/scripts/batocera-store, package/batocera/utils/pacman/004-xmloutput.patch
=> pacman xml output

package/batocera/utils/pacman/004-xmloutput.patch
=> fix: remove extra parents in xml

board/batocera/post-image-script.sh
=> update img cmd cause to new kernel

package/batocera/alllinuxfirmwares/alllinuxfirmwares.mk
=> bump firmwares

package/batocera/emulators/retroarch/libretro/libretro-picodrive/libretro-picodrive.mk
=> pico parallel

package/batocera/emulationstation/batocera-es-system/es_systems.yml
this will make Dynamic Collections recognise daphne as arcade
=> add platform descriptors to daphne

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
https://www.ign.com/articles/2002/04/18/gamester-reflex-arcade-stick-review
Signed-off-by: Ntemis <ierokipides.dem@gmail.com>
=> Add support for Radica Gamester Arcade Stick

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
=> fix n64 ra pad issues

package/batocera/emulators/retroarch/libretro/libretro-stella/libretro-stella.mk
https://github.com/stella-emu/stella/releases/tag/6.2.1
=> bump: libretro-stella to v6.2.1

board/batocera/fsoverlay/etc/profile.d/terminal_setup.sh
```
Using username "root".
____    __   ____  _____  ___  ____  ____    __
(  _ \  /__\ (_  _)(  _  )/ __)( ___)(  _ \  /__\
) _ < /(__)\  )(   )(_)(( (__  )__)  )   / /(__)\
(____/(__)(__)(__) (_____)\___)(____)(_)\_)(__)(__)
ONLY CORES THAT MATTER
-- type 'batocera-check-updates' to check for stable branch --
-- add 'beta' switch to check for latest arch developments  --
Temperature: 43°
Architecture: rpi3
Model: Raspberry Pi 3 Model A Plus Rev 1.0
Revision: 9020e0
System: Linux 4.19.97-v7
Available memory: 161/240 MB
Cpu model: ARMv7 Processor rev 4 (v7l)
Cpu number: 4
OS version: 5.26 2020/05/31 20:46
```
=> update: board/software/batocera stats in terminal

board/batocera/fsoverlay/etc/init.d/S50triggerhappy, board/batocera/fsoverlay/etc/triggerhappy/triggers.d/multimedia_keys_disabled.conf, board/batocera/rockchip/odroidgoa/linux_patches/linux-999-odroidgo2_joypad_v11.patch, package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
=> odroidgoa keys

package/batocera/alllinuxfirmwares/alllinuxfirmwares.mk, package/batocera/core/batocera-bluetooth/S32bluetooth.template
=> fix rpi bt wifi

package/batocera/core/batocera-scripts/scripts/batocera-info
Added support for Odroid N2, and removed an ugly message with libGL polluting the output on x86_64.
=> Support for Odroid N2 + fix libGL msg on x86

batocera-Changelog, board/batocera/fsoverlay/etc/init.d/S11share
=> btrfs compression

board/batocera/rockchip/odroidgoa/fsoverlay/etc/triggerhappy/triggers.d/multimedia_keys.conf, package/batocera/core/batocera-audio/soundconfig
=> fix pa audio odroidgoa

package/batocera/emulators/ppsspp/ppsspp.mk
=> Update PPSSPP to 1.10.0

board/batocera/rockchip/odroidgoa/patches/ppsspp/board-maxwindow.patch
=> fix ogoa psp patch

Config.in, board/batocera/patches/sdl2/001-drm-resolution.patch, board/batocera/rpi4/fsoverlay/usr/bin/batocera-resolution, package/batocera/core/batocera-drminfo/Config.in, package/batocera/core/batocera-drminfo/batocera-drminfo.c, package/batocera/core/batocera-drminfo/batocera-drminfo.mk, package/batocera/core/batocera-system/Config.in, package/batocera/emulators/retroarch/retroarch/009-drm-resolution.patch
=> drm resolution

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenControllers.py
=> fixn64axis

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_features.yml
Add options for Fast Disc, MMU
Standardize options for CPUThread/GPUSync
Controller configgen logic updates to support future expansion (possible ES options)
=> Dolphin updates - New Options and Fixing Configgen Defaults

board/batocera/odroidn2/boot/extlinux.conf
=> fix n2 res

board/batocera/patches/mesa3d/002-disable-iris.patch
=> re-disable iris

package/batocera/core/batocera-scripts/batocera-scripts.mk
=> fix drm ogoa resolution

package/batocera/core/batocera-scripts/scripts/batocera-store
=> store list when not initialized

package/batocera/core/batocera-system/c2/batocera.conf, package/batocera/core/batocera-system/libretech_h5/batocera.conf, package/batocera/core/batocera-system/miqi/batocera.conf, package/batocera/core/batocera-system/odroidgoa/batocera.conf, package/batocera/core/batocera-system/odroidn2/batocera.conf, package/batocera/core/batocera-system/rock960/batocera.conf, package/batocera/core/batocera-system/rockpro64/batocera.conf, package/batocera/core/batocera-system/rpi1/batocera.conf, package/batocera/core/batocera-system/rpi2/batocera.conf, package/batocera/core/batocera-system/rpi3/batocera.conf, package/batocera/core/batocera-system/rpi4/batocera.conf, package/batocera/core/batocera-system/s905/batocera.conf, package/batocera/core/batocera-system/s912/batocera.conf, package/batocera/core/batocera-system/tinkerboard/batocera.conf, package/batocera/core/batocera-system/vim3/batocera.conf, package/batocera/core/batocera-system/x86/batocera.conf, package/batocera/core/batocera-system/x86_64/batocera.conf, package/batocera/core/batocera-system/xu4/batocera.conf
=> document fs compression in batocera.conf

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
-internal resolution: 1x(native)/2x/4x/8x/16x
-texture filtering: nearest/sabr/xbr/bilinear/3point/jinc2
-widescreen hack: disabled/enabled
=> Mednafen psx:

batocera-Changelog, package/batocera/core/batocera-scripts/scripts/batocera-es-theme
Added the ability to remove themes, for consistency with bezels and content downloader.
While I was on it, I added a lot of missing enhancements on the changelog.
=> Added "batocera-es-theme remove", update changelog

package/batocera/emulators/retroarch/libretro/libretro-mame2003-plus/libretro-mame2003-plus.mk
This reverts commit 143b9457015aae14f30e2cd24dbc6b2a72c47a30.
=> Revert "bump: libretro-mame2003-plus"

package/batocera/core/batocera-scripts/scripts/batocera-info
=> cpu max freq

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
Configgen Support for Vulkan in Dolphin - Do not merge until Vulkan support is official in Dolphin
=> Configgen Support for Vulkan in Dolphin

package/batocera/emulators/retroarch/libretro/libretro-picodrive/libretro-picodrive.mk
Could someone review and test this ?
=> Rebase lr-picodrive to irixxx repository (compiles on oga, n2, x86, x86_64)

package/batocera/core/batocera-system/c2/batocera.conf, package/batocera/core/batocera-system/libretech_h5/batocera.conf, package/batocera/core/batocera-system/miqi/batocera.conf, package/batocera/core/batocera-system/odroidgoa/batocera.conf, package/batocera/core/batocera-system/odroidn2/batocera.conf, package/batocera/core/batocera-system/rock960/batocera.conf, package/batocera/core/batocera-system/rockpro64/batocera.conf, package/batocera/core/batocera-system/rpi1/batocera.conf, package/batocera/core/batocera-system/rpi2/batocera.conf, package/batocera/core/batocera-system/rpi3/batocera.conf, package/batocera/core/batocera-system/rpi4/batocera.conf, package/batocera/core/batocera-system/s905/batocera.conf, package/batocera/core/batocera-system/s912/batocera.conf, package/batocera/core/batocera-system/tinkerboard/batocera.conf, package/batocera/core/batocera-system/vim3/batocera.conf, package/batocera/core/batocera-system/x86/batocera.conf, package/batocera/core/batocera-system/x86_64/batocera.conf, package/batocera/core/batocera-system/xu4/batocera.conf
Added values to batocera.conf for all archs
1. Access to hidden APs --> https://github.com/batocera-linux/batocera.linux/pull/1994
2. Preparement for Splash Screens --> https://github.com/batocera-linux/batocera.linux/pull/2014
=> Preparement: BATOCERA.CONF (Splash update regarding PR2014)

board/batocera/fsoverlay/etc/init.d/S12populateshare, board/batocera/fsoverlay/usr/share/batocera/datainit/splash/readme.txt
Preparement for https://github.com/batocera-linux/batocera.linux/pull/2014
Added dir `splash` and it's readme to datainit
=> Preparement: DATAINIT (Splash update regarding PR2014)

board/batocera/fsoverlay/etc/init.d/S08connman
sleep 1 # not nice, but until a delay, unable to execute connmanctl commands (thus S10wifi fails)
... if somebody has a better solution ?
=> fix wifi at boot

package/batocera/core/batocera-scripts/scripts/batocera-store
=> update store on first listing

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
=> fix bigben pad

board/batocera/odroidn2/genimage.cfg
=> fix dts name

package/batocera/network/rtl8821ce/rtl8821ce.mk
=> fix rtl8821ce download

board/batocera/rpi4/patches/cannonball/001-gles.patch
=> mesa 20.1.3

board/batocera/rockchip/odroidgoa/fsoverlay/etc/triggerhappy/triggers.d/multimedia_keys.conf
This reverts commit ed2f1a436afe8c9262f80302803045b1e2a56fbc.
=> Revert "fix pa audio odroidgoa"

package/batocera/emulators/dolphin-emu/003-drm-resolution.patch
=> dolphin drm resolution

board/batocera/rpi4/boot/config.txt
=> rpi4 config.txt gpu

package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_xorg
=> MESA_LOADER_DRIVER_OVERRIDE=i965

board/batocera/patches/sdl2/sdl2_accelerometers_are_not_joysticks.patch
=> accelerometers are not joysticks

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
=> fix lr citra

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/cannonball/cannonballControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/cannonball/cannonballGenerator.py, package/batocera/emulators/cannonball/0003-hotkey.patch, package/batocera/emulators/cannonball/cannonball.mk
=> cannonball config

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py, package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/core/batocera-configgen/configs/configgen-defaults.yml, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulationstation/batocera-es-system/es_systems.yml
Initial commit for rpcs configgen
Still needs
- default rpcs3 configuration (yml parsing)
- controller configuration (yml parsing)
=> Rpcs3 configgen

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix ps3 ext

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py, package/batocera/emulators/dolphin-emu/003-drm-hotkeys.patch
=> dolphin drm hotkeys

package/batocera/core/batocera-system/batocera-boot.conf, package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_xorg
=> option for iris

package/batocera/core/batocera-system/batocera-boot.conf, package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_xorg
=> change i965 mode

package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Controllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/reicast/reicastControllers.py
Updates configgen for controllers for flycast/reicast to enable d-pad
configgen for libretro to disable analog to digital on citra
=> Configgen controllers

package/batocera/core/batocera-bluetooth/S32bluetooth.template
=> fix bt on rpi4

board/batocera/rpi4/boot/config.txt
=> fix flick rpi

Makefile
Corrects errors of permission denied in the dl folder during compilation.
=> Fix dl folder permission

package/batocera/core/batocera-system/Config.in
=> rpi4: disable saturn

package/batocera/core/batocera-system/Config.in, package/batocera/emulators/retroarch/retroarch/retroarch.mk
=> Build RetroArch with vulkan support if present + slang shaders

package/batocera/emulators/retroarch/libretro/libretro-81/001-slowerkeyboard.patch
=> fix zx81 keyboard too fast

board/batocera/patches/alsa-lib/001-read-asoundrc-boot.patch
Fixed build error in patch for alsa-lib
=> Fix patch alsa-lib

package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/linapple/linappleConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/moonlight/moonlightConfig.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/moonlight/moonlightControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborGenerator.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py, package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py
=> perf on unix file saves

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> saturn zip

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> add .elf and .dol to Dolphin extensions

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
To be cherry picked (or not) for 5.27, depending on how hard we want to fix bezels and lying TVs vs how fast we want to release a fix.
=> Fix cached bezels upon resolution change from ES

package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceControllers.py
=> fix vic variable

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
Fix wrong `aspect_ratio_index` for 4K resized bezels with no `.info` (like theBezelProject) + added a faster PNG size computation, that saves about 1.5 second vs PIL image loading.
=> Fix tBP 4K bezel resize

package/batocera/core/batocera-scripts/scripts/batocera-info
=> min max cpu

package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
=> bump flycast

package/batocera/emulators/wine-x86/wine-x86.mk
=> fix wine-86

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Im adding new controllers not supported by default by batocera
=> Add News Controllers

board/batocera/doWinepackage.sh
=> wine dynamic so

package/batocera/core/batocera-configgen/configgen/configgen/generators/wine/wineGenerator.py, package/batocera/utils/batocera-wine/batocera-wine
=> wine fixes

package/batocera/libraries/libglvnd/libglvnd.hash, package/batocera/libraries/libglvnd/libglvnd.mk
=> bump libglvnd

package/batocera/utils/batocera-wine/batocera-wine
=> win32 fixes

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
=> Change Switch Controller

board/batocera/patches/dropbear/001-allow-generating-keys-on-fat.patch
=> fix dropbear

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
=> Add New Controllers

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
That fix the controller for hotkey
=> Add Dragon Rise

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
=> Add New Controller

board/batocera/post-image-script.sh
=> fix post img

package/batocera/core/batocera-configgen/configs/configgen-defaults-libretech-h5.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc4.yml, package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml
=> fix boards default

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
=> fix_default_gc

package/batocera/emulators/scummvm/000-configure.patch, package/batocera/emulators/scummvm/Config.in, package/batocera/emulators/scummvm/scummvm.mk
=> fix scummvm on rpi

package/batocera/emulationstation/batocera-es-system/es_systems.yml
To group together the systems concerned in the arcade auto collection (FNBeo, MAME, Daphne, Atomiswave and Naomi)
=> Group arcade collection systems

board/batocera/x86/linux_patches/fsync.patch
Now wine is better stable on batocera 29 that would be great to try fsync.
Have no issue in compilation.
=> Add fsync.patch

package/batocera/gpu/batocera-nvidia-driver/nvidia-driver.mk
This commit is for fix Nvidia + Vulkan.
@nadenislamarre
=> Bump nvidia-driver with Fixe

board/batocera/rockchip/odroidgoa/genimage.cfg
=> fix missing dts in the goa image

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
DO NOT MERGE yet - I'd like @cyperghost to do some testing on this first, as he owns a 5:3 screen.
=> Enable bezels for new aspect ratios (5:3, 16:10 in particular)

package/batocera/emulators/rpcs3/009-install-firmware.patch
Use with
rpcs3 --installfw /path/to/PS3UPDAT.PUP
=> RPCS3 install firmware command line option patch

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> Fix Missing RPX

package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk, package/batocera/emulators/wine/wine-lutris/wine-lutris.mk
=> winegcrypt

package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk
=> fix wow64 gcrypt

package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> fix wine theme

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py, package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py, package/batocera/core/batocera-splash/S29splashscreencontrol, package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk, package/batocera/emulationstation/es-theme-carbon/es-theme-carbon.mk
=> Evmapy as class

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
=> fix evmapy configs dir

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py, package/batocera/emulationstation/batocera-es-system/es_features.yml, package/batocera/emulators/cemu/cemu.mk, package/batocera/emulators/cemu/wiiu.keys
Cemu controllers commit to use SDL2_GameControllers in WINE.
Includes wiiu.keys file for evmapy
=> cemu_controllers

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py, package/batocera/utils/batocera-pygame/evmapy.keys, package/batocera/utils/batocera-pygame/snake.pygame
=> evmapy axis

package/batocera/emulationstation/batocera-es-system/batocera-es-system.py, package/batocera/emulationstation/batocera-es-system/es_systems.yml
=> extension limit by core

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> joystick2pad feature

package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py
=> ppsspp low resolution menu

package/batocera/gpu/batocera-nvidia-driver/nvidia-driver.mk
=> nvidia json vulkan

package/batocera/utils/batocera-wine/batocera-wine
=> fix dxvk install

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
=> some es options

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
=> evmapy rom as dir

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> dxvk cfeatures

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py, package/batocera/utils/batocera-pygame/evmapy.keys, package/batocera/utils/evmapy/004-mouse.patch
=> evmapymouse

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py, package/batocera/utils/batocera-pygame/evmapy.keys
=> simpler mouse mapping for es

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py, package/batocera/utils/evmapy/004-mouse.patch
=> fix evmapy

package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/utils/batocera-wine/batocera-wine
=> Add New Option for Wine

Config.in, package/batocera/core/batocera-system/Config.in, package/batocera/utils/evmapy-system-config/Config.in, package/batocera/utils/evmapy-system-config/evmapy-system-config.mk, package/batocera/utils/evmapy-system-config/mouse.keys
=> evmapy system configs

package/batocera/emulationstation/batocera-es-system/es_systems.yml, package/batocera/utils/batocera-wine/batocera-wine
=> rename .wine.squashfs to .wsquashfs

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> add some pad2keys features

board/batocera/doWineWow64-32package.sh, package/batocera/utils/batocera-wine/Config.in, package/batocera/utils/batocera-wine/batocera-wine
=> some wine fixes

package/batocera/core/batocera-scripts/scripts/batocera-store
=> store: list-repositories

package/batocera/emulators/wine/vkd3d-proton/Config.in, package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.mk, package/batocera/utils/batocera-wine/batocera-wine
Add Support of more games when use DX12
=> Add VKD3D-PROTON

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
=> fix when axes are for buttons

package/batocera/emulators/wine/wine-lutris/wine-lutris.mk
=> cross check between wine and mono

package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk, package/batocera/emulationstation/batocera-es-system/batocera-es-system.py, package/batocera/emulationstation/batocera-es-system/es_features.yml
=> limit options by arch

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
it seems like button mappings are off by one starting from 11. this patch fixes it. tested with 2 DS4 and 1 DS2 (total 3) controllers.
=> an attempt to fix cemu mappings for additional controllers

package/batocera/core/batocera-desktopapps/scripts/batocera-config-rpcs3
=> fix config rpcs3 dirs

package/batocera/core/batocera-scripts/scripts/batocera-settings
=> batocera-settings: add game/system

package/batocera/utils/pacman/004-xmloutput.patch
=> fix store licence

package/batocera/emulators/rpcs3/010-padsevdev.patch
=> ps3mapping

package/batocera/core/batocera-scripts/scripts/batocera-settings
=> Fix Spaces

package/batocera/core/batocera-scripts/scripts/batocera-hybrid-nvidia
=> fix hybrid nvidia multiple monitors

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py, package/batocera/emulators/rpcs3/evmapy.keys, package/batocera/emulators/rpcs3/rpcs3.mk
=> new rpcs3 configgen options

package/batocera/utils/xow/xow-daemon
=> fix xow-daemon not finishing

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py, package/batocera/core/batocera-desktopapps/scripts/batocera-config-cemu
=> fix cemu config

board/batocera/post-build-script.sh
=> remove xorg start file

package/batocera/core/batocera-scripts/scripts/batocera-systems
Rather than the Japanese one (which is hard to use if you can't read Japanese)
=> Satellaview: switched to the English default bios check

package/batocera/core/batocera-scripts/scripts/batocera-settings
read out of values with special chars fixed
system["GAME"].value readout fixed
added simple possibility to write values (extended and basic mode)
added possibility to add new key (only basic mode)
=> batocera-settings - some fixes

package/batocera/utils/batocera-wine/batocera-wine
That help for adding better performance in games.
=> Add Esync and Fsync option

package/batocera/utils/batocera-wine/batocera-wine
Fix for first run crash.
Please don't merge now
=> Fix batocera-wine

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
=> evmapy absbase

package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py, package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Controllers.py, package/batocera/emulators/dolphin-emu/003-drm-hotkeys.patch
=> dolphin+rpcs3+evmapy fixes

package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
=> Bump lr-mame to 0.226

package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
Will fix RPi1 only
No more stuck to S31emulationstation + added sleep timer
=> fix: RPi1 build + faster loading of ES

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> Add Virtual Desktop for wine on ES (29+master)

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py
Values above 5.0 leave lr-atari800 muted.
=> audio_volume = 2.0

package/batocera/utils/batocera-wine/bsod.py
=> Wine: red warning when /userdata FS is not ext4 or btrfs (29+master)

package/batocera/utils/batocera-wine/batocera-wine
Addition of the possibility of having a virtual desktop on wine.
Added automatic detection of resolution if nothing is set.
Tested & Work on last beta build 
For Beta 29
=> Add Virtual Desktop + Fixe (29+master)

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> Fix on ES (29 + Master)

package/batocera/emulators/cemu/cemu.hash, package/batocera/emulators/cemu/cemu.mk
=> Bump Cemu (29 + Master)

package/batocera/utils/batocera-wine/batocera-wine
The .exe is only format no support VDESKTOP
Better to remove for this format.
=> Fix .exe issue (29+Master)

board/batocera/rockchip/odroidgoa/linux_patches/0001-scripts-dtc-Remove-redundant-YYLOC-global-declaratio.patch, board/batocera/rockchip/odroidgoa/patches/uboot-odroid-goa/0001-Kbuild-fix-escaping-in-.cmd-files-for-future-Make.patch, board/batocera/rockchip/odroidgoa/patches/uboot-odroid-goa/0001-kbuild-fix-escaping-in-appending-U-Boot-own-DT.patch, board/batocera/rockchip/odroidgoa/patches/uboot-odroid-goa/0001-scripts-dtc-Remove-redundant-YYLOC-global-declaratio.patch
Build fixes for odroidgoA
Also sent upstream:
* https://github.com/hardkernel/u-boot/pull/66
* https://github.com/hardkernel/u-boot/pull/65
* https://github.com/hardkernel/linux/pull/404
=> odroidgoA build fixes

package/batocera/gpu/vulkan/spirv-headers/spirv-headers.hash, package/batocera/gpu/vulkan/vulkan-headers/vulkan-headers.hash, package/batocera/gpu/vulkan/vulkan-headers/vulkan-headers.mk, package/batocera/gpu/vulkan/vulkan-loader/vulkan-loader.hash, package/batocera/gpu/vulkan/vulkan-loader/vulkan-loader.mk, package/batocera/gpu/vulkan/vulkan-tools/vulkan-tools.hash, package/batocera/gpu/vulkan/vulkan-tools/vulkan-tools.mk
=> Bump Vulkan

board/batocera/scripts/post-build-script.sh, package/batocera/emulationstation/batocera-es-system/es_systems.yml
At least on x86_64, as discussed with @tcamargo
=> Fixed console login [Alt][F3] - (29+master)

package/batocera/core/batocera-scripts/scripts/batocera-es-theme, package/batocera/core/batocera-scripts/scripts/batocera-install, package/batocera/core/batocera-scripts/scripts/batocera-upgrade
=> fix redirection

package/batocera/utils/batocera-wine/batocera-wine
Have tested and validated on game.
=>  Detected keyboard (29+Master)

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
Removes SDL config adding a ~ to non-joystick axis items.
=> Update SDL controller config

package/batocera/utils/batocera-wine/batocera-wine
Have been tested & confirm to work.
=> Add DXVK for .wine (29 + Master)

package/batocera/emulationstation/batocera-es-system/es_features.yml
=> fix cemu gui option

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
=> fix ppsspp pads

package/batocera/core/batocera-scripts/scripts/batocera-settings
According https://github.com/batocera-linux/batocera.linux/pull/2555
Can be merged for bato 30
Just residues from the past, speed win is round about 30%
=> batocera-settings: removed classic mode (30)

package/batocera/core/batocera-drminfo/batocera-drminfo.c, package/batocera/core/batocera-scripts/batocera-scripts.mk
=> fix batocera-drminfo

package/batocera/core/batocera-system/Config.in
=> fix missing libnss for some plugins (netflix)

package/batocera/utils/evmapy/006-root-user.patch
Fails when you compile as non-root under Docker.
=> Fix when compiling as a non-root user

package/batocera/core/batocera-scripts/scripts/batocera-settings
Added -c to check status of key and shows exit code!
Added full write support `-w`
Works also for `-e` parameter
-w --> key
-e -w --> global.key
-e -w -s --> system.key
-e- -w -s -g --> system["game"].key
=> batocera-settings: optimiziations + write

package/batocera/arch/firmware_nonfree_rpi/firmware_nonfree_rpi.mk
File is correctly copied but in /lib/firmware :(
=> Fix Pi 400

package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.hash, package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk, package/batocera/emulators/wine/wine-proton/wine-proton.hash, package/batocera/emulators/wine/wine-proton/wine-proton.mk
@rtissera now you have good source link you can build now ^^
=> Fix Source of Proton
