batocera-linux/batocera.linux

board/recalbox/fsoverlay/recalbox/share_init/cheats/cht/Super Nintendo/Pro Action Replay/Aero the AcroBat.cht
board/recalbox/fsoverlay/recalbox/share_init/cheats/cht/Super Nintendo/Pro Action Replay/Al Unser Jrs Road to the Top.cht

These two files have duplicates with the same file names (except letter case). This clashes when pulling the sources in Windows.

Removes duplicate files from Super Nintendo cheats.

---

package/kodi/0004-CMAKE-Add-armv7l-to-script.patch

Compiling on RPI3, is not possible due to missing armv7l ???
Or missing cortex-a8 in kodi https://github.com/xbmc/xbmc/blob/Krypton/project/cmake/scripts/rbpi/ArchSetup.cmake#L13
FIxed by patching this script.
diff -Naur kodi-17.3-Krypton/project/cmake/scripts/rbpi/ArchSetup.cmake kodi-17.3-Krypton.patch/project/cmake/scripts/rbpi/ArchSetup.cmake
--- kodi-17.3-Krypton/project/cmake/scripts/rbpi/ArchSetup.cmake	2017-09-18 18:55:19.710539708 +0200
+++ kodi-17.3-Krypton.patch/project/cmake/scripts/rbpi/ArchSetup.cmake	2017-09-18 18:54:57.230689124 +0200
@@ -14,7 +14,7 @@
set(ARCH arm)
set(NEON False)
set(NEON_FLAGS "-mcpu=arm1176jzf-s -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp")
-  elseif(CPU MATCHES "cortex-a7" OR CPU MATCHES "cortex-a53")
+  elseif(CPU MATCHES "cortex-a7" OR CPU …

Fix compiling kodi on raspberry pi

---

board/recalbox/fsoverlay/etc/init.d/S02splash

Force output over both the 3.5mm jack and HDMI 
-Genetik57

Splash Screen sound fixed for 3.5mm jack output

---

board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_input.cfg

The default configuration for the R2 button is missing for the Microsoft X-Box 360 pad

Added missing R2, (RT),  button for Microsoft X-Box 360 pad

---

package/batocera/libretro-pcsx/libretro-pcsx.mk

Update from (Feb 11, 2017) to (Jan 28, 2018), tested on x86_64 and RPI3 platforms.

libretro-pscx update

---

package/batocera/libretro-atari800/0001-libretro-core.patch

Changing the sequence and option "5200" will be the default choice.

libretro-atari800: fix Atari System

---

package/mesa3d-headers/mesa3d-headers.mk
package/mesa3d/mesa3d.hash
package/mesa3d/mesa3d.mk

This is until 18.1.1 or > is out. 
18.1.0 is out but defined as development release so not for public usage.

Update mesa3d to 18.0.4

---

board/batocera/fsoverlay/etc/fstab

on the xu4, there is no overlayfs, thus, no tmpfs over the squashfs.
so, at the end, /media is read only, preventing any device to be mounted.
so, to fix it, /media should be rw in any case. tmpfs is mounted on it.

fix xu4 /media

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/fsuae/fsuaeControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/fsuae/fsuaeGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Controllers.py

playersConfigurations in configgen is a dict of strings "1", "2", ...
it is a choice that makes it not easy to manipulate : a dict in python is unsorted
and finally, pad order can be false in emulators.
Ideally, this structure should be replaced by a classical tabular

fix pad orders

---

board/batocera/fsoverlay/recalbox/scripts/recalbox-systems.py

*scph10000.bin removed because this bios should not be used as it may cause problems with emulation of the memory card and other sections.
*.NVM and .MEC files added for SCPH30004R.bin and scph39001.bin.
*EROM.BIN, rom1.bin and ROM2.BIN files added.
Note: To replace the file scph10000.bin (JAP) I advise you to use the file scph39001.bin (US)

BIOS: Some adjustments for the PS2 section

---

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml

fba2x: available only for RPI
zx81: required '81' if it does not recognize int

fix: configgen-defaults

---

linux/linux.mk

When compiling 64bit for 32bit userland, the package needs to point to the arm64 folder for the dtb

Include the 64-bit kernel in 32-bit userland DTS

---

board/batocera/fsoverlay/recalbox/scripts/recalbox-systems.py

Libretro has removed three bios, I do not know why so I remove them too

PSX: Update bios hash

---

package/batocera/emulators/citra/citra.mk

Necessary change not to conflict with the version of buildroot and the one used by libretro-citra, the latest versions of citra are using fmt-5.3.0

citra: downgrade to the version that uses fmt 5.1.0.

---

board/batocera/rockpro64/kernel_patches/linux-2000-rockpro64-wifi-bt.patch

Please note that in my own builds I have a very custom kernel with a very different device tree and a huge amount of commits back-ported to 4.4 from mainline. Many of those are changes to the wifi, sdio, bluetooth, and uart drivers. So I have specifically written this patch based off the kernel commit you're linked to and I believe it should be all that's required to enable these features. You'll want to test their functionality and stability without all of my other customizations.

Fixup rockpro wifi and bluetooth

---

board/batocera/fsoverlay/etc/init.d/S26recalboxsystem

X seems to search for the hostname at boot and can't ping it
if it's not in /etc/hosts

fix hostname

---

package/rpi-firmware/config.txt

batocera uses config.txt in board/batocera/rpi/

rpi-firmware: go back to default values

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
package/batocera/core/batocera-system/x86_64/recalbox.conf

Disables fast booting (does not skip PS2 BIOS when booting an ISO, this may require by some games relying on BIOS to get start-up parameters)

ps2: add fullboot option

---

package/batocera/core/batocera-scripts/scripts/batocera-es-theme

A Bash script to install Batocera themes, listed in a either the hostedhttps://batocera-linux.xorhub.com/upgrades/themes.txt file, or a local /userdata/system/themes.txt.

batocera-es-theme: a CLI tool to list and install Batocera themes.

---

package/gdb/8.1.1/0007-gdb-Fix-ia64-defining-TRAP_HWBKPT-before-including-gdb_wait-h.patch

Between glibc 2.28 and glibc 2.29, commit
89983cb37c9319806a551e8fe9f3a11ff8f973e1 ("Update siginfo constants
from Linux kernel (bug 21286)") was merged. This commit moved the
TRAP_HWBKPT definition from an IA64-specific header to an
architecture-agnostic header.
This change exhibited a build issue that until then was only visible
on IA64 (which Buildroot does not support). This Buildroot commit
backports a patch from gdb upstream (which is in gdb since 8.2) which
mentions IA64 because it was originally meant to fix only the
IA64-related issue. But the glibc change, this change has become
visible on all architectures.
Fixes:
- http://autobuild.buildroot.org/results/a81eb395bd95306fcbb07c1443c9134fd63fa379
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Thomas: extend commit …

package/gdb: fix build of 8.1.1 since the bump to glibc 2.29

---

board/batocera/fsoverlay/etc/init.d/S11share

it seems to cause issues to some people.
one reason is that es doesn't decode it
but it may come from the key that may change depending on something.

disable wifi password encoding

---

package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/retro/rendering-defaults.yml
package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/scanlines/rendering-defaults.yml

shaders paths fixed
- for retro
- for scanlines
retro shader for gb changed to match more the real gb. same for gba.

fix: shader paths

---

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py

Disney's Aladdin.smc.bezel=ambiance_01
Disney's Aladdin.smc.showFPS=true
Sonic and Knuckles & Sonic 3 (W) [!].bin.bezel=ambiance_03
- non alphanumeric and . chars are ignored at comparison
- in batocera.conf, now, case is essential. i hope there is no impact
@poke, please read and give your mind
initially i wanted a [game name].bezel = xxx syntax, but while it uses ini format, it didn't work and finally, the current syntax seems ok while it is more consistent with the rest.

settings by game

---

package/batocera/core/batocera-scripts/batocera-scripts.mk
package/batocera/core/batocera-scripts/scripts/batocera-settings

This is a config parser written in pure bash, it is much faster then it's python pendant. Goal is to give the user and future developers an easy method to read, change and save values.
If you serve a filename at first argument then these file will be processed.
Currently you can't add new, keys ... I think a bash statement like `[[ $? -eq 12 ]] && echo "new.key=" >> /my/config/file.conf` will solve this
[Read more about it's usage here](https://github.com/crcerror/BATOCERA-Shares/blob/master/conf-parser/README.md)
Talking about speed:
```
1. Original script
2019-06-24 19:34:17 DEBUG (unixSettings.py:21):__init__(): Creating parser for /userdata/system/batocera.conf
2019-06-24 19:34:17 DEBUG (unixSettings.py:43):load(): Looking for wifi.key in /userdata/system/batocera.conf
new key
real …
```

Add: batocera-settings a conf parser tool

---

package/batocera/core/batocera-scripts/scripts/batocera-settings

Added impoved handling of dashes
* one dash for mimic the old python script
* two dashes for common posix style
* short form of arguments <cmd> <key> <value>
* mix possible of long and short style `--comand <cmd> <key> --value <value>
* Added error 10 output for excisiting but empty keys `wifi.key=`
* So you can analyze bash exit code
* code 0 - everything okay
* code 1 - general error
* code 2 - file error
* code 10 - key is available but empty
* code 11 - key is remarked
* code 12 - key is not available
* Improved text output
* removed some typos ...
* A script to far??

batocera-settings: improved coding and error handling

---

package/batocera/core/batocera-scripts/scripts/batocera-settings

++++ LAST COMMIT ON THIS ++++
* finds # and ; as comment char -- set # as default 
* ; is old RB form (deprecated)
* improved loop to setup dashes - we are faster now ;)
++++ OLD COMMITS ++++
https://github.com/batocera-linux/batocera.linux/pull/792
https://github.com/batocera-linux/batocera.linux/pull/791

batocera-settings: finds several comment chars - default is #

---

package/batocera/core/batocera-scripts/scripts/batocera-settings

removed some typos
Tweaked some comments for future purposese
fixed: grep command could not find keys with "# key.name=value"! Fixed!
fixed: lower/uppercase of commands fixed
fixed: better error recognition if key.value is empty

fix: batocera-settings, better grep recognition, command strings

---

board/batocera/fsoverlay/etc/udev/rules.d/99-joysticks-exotics.rules

XArcade Tankstick was not recognized any more after update to the last kernel version.

Fix for Xarcade Tankstick

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

*Atari 7800
*Atari Lynx
*ColecoVision
*MAME
*FBA
*LightGun
*Apple II
*Playstation 1
Source: https://retroachievements.org/viewtopic.php?t=9302
Note: There are not many games supported yet but this is only the beginning to date

Retroachievements: Add several new platforms

---

package/batocera/core/batocera-system/rpi1/batocera.conf
package/batocera/core/batocera-system/rpi2/batocera.conf
package/batocera/core/batocera-system/rpi3/batocera.conf

Added page
https://batocera-linux.xorhub.com/wiki/doku.php?id=en:add_powerdevices_rpi_only
Original state before activating a switch
```
#system.power.switch=ATX_RASPI_R2_6
#system.power.switch=MAUSBERRY
#system.power.switch=REMOTEPIBOARD_2003
#system.power.switch=REMOTEPIBOARD_2005
#system.power.switch=WITTYPI
#system.power.switch=PIN56ONOFF
#system.power.switch=PIN56PUSH
#system.power.switch=PIN356ONOFFRESET
#system.power.switch=RETROFLAG
#system.power.switch=ONOFFSHIM
```
After activating one switch
the write command gets mad ... this is an old behaviour since RB times
```
system.power.switch=ONOFFSHIM
system.power.switch=ONOFFSHIM
system.power.switch=ONOFFSHIM
system.power.switch=ONOFFSHIM
system.power.switch=ONOFFSHIM
system.power.switch=ONOFFSHIM
system.power.switch=ONOFFSHIM …
```

RPi: Cleanup power.switch section batocera.conf

---

package/batocera/core/batocera-scripts/batocera-scripts.mk
package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife

This script offers additional information about running instances of emulators
1. Reports back if ES is running (through the real binary PID)
2. Reports back if an EMULATOR is running (by displaying PID of emulatorlaunch.py)
3. Proper Shutdown from command line are possible now (even in active emulator session)
4. You can terminate ANY emulator and you'll be kicked back to ES main menu
5. You can properly start KODI by CLI now
It's usefull if you want to control BATOCERA by GPIO buttons or if you simply want to do some tests by command line ;) I will step into the button scripts later. They do not work as expected ... cya
@jdorigao @nadenislamarre remeber to make batocera-es-swissknife executeable
would a `install -m 0755 path/from path/to` not be better?

Add script: Batocera ES Swissknife

---

package/batocera/core/batocera-scripts/scripts/batocera-systems

SyntaxError: Non-ASCII character '\xc3'

fix: batocera-systems

---

package/batocera/utils/rpigpioswitch/S92switch
package/batocera/utils/rpigpioswitch/rpi-pin356-power.py
package/batocera/utils/rpigpioswitch/rpi-pin56-power.py
package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh

- made rpi356 script work again (power, reset, LED)
- hide error output in rpi56 script
- S92switch parses button config now to rpi_gpioswitches
- start rpi_gpioswitches from terminal will show you a nice dialog window
- removed read out of batocera.conf within rpi_gpioswitches (why should this script do the work from S92switch again)
- cleanup of scripts ....
- ....

GPIO SWITCH: Some small improvements made

---

package/batocera/utils/rpigpioswitch/rpi-pin356-power.py
package/batocera/utils/rpigpioswitch/rpi-pin56-power.py

This is (hopefully) my last commit in this task
I wanted to avoid to use annother packages (like threading)
So I just used shell built-in to send shutdown process to background for get a kind of "multithreading" to let LED blink.
Furthermore the signal package can be used to send the process in deep sleep mode. So I think this is a perfect solution in our usecase.

GPIO SWITCH: Added blinking LED, signal thread for 0% CPU usage

---

board/batocera/fsoverlay/etc/udev/rules.d/99-joysticks-exotics.rules

The line removed prevents the Xarcade Tankstick to work with Batocera 5.24. The two joysticks on the Tankstick are regonized twice (once by "Xarcade-to-Gamepad Device x" and once by "XGaming X-Arcade").
With that extra line, you can see 4 joysticks instead of 2 in EmulationStation -- even though they seem to work well in ES, it's wrong. And it's now fully broken in RetroArch 1.7.8, where no Xarcade joystick is seen at all with that extra line. That's another change of behavior compared to 1.7.7.

Fix Xarcade joypad config for 5.24.

---

package/batocera/core/batocera-scripts/scripts/batocera-config

Discussed with @fabricecaruso, who needs a new command `batocera-config overscan L R T B`  that enables overscan and sets 
>  overscan_left=L 
>  overscan_right=R 
>  overscan_top=T
>  overscan_bottom=B
in `/boot/config.txt`.
Also simplified the script a bit, as I wrote a new function for this part.

New "batocera-config overscan set" command.

---

package/batocera/core/batocera-configgen/configgen/configgen/settings/batoceraSettings.py

Removed python config for just reading config files
It's 100% backwards compatible to old version
In near future scripts can migrate from python calls to `batocera-settings`
This will slighlty boost the speed of bootup

py: batoceraSettings - pipe to bash script - small speed boost

---

package/batocera/emulationstation/batocera-emulationstation/S31emulationstation_fb_1cpu
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation_fb_nosplash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation_fb_splash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation_fbegl_nosplash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation_xorg

I take referenct to
https://github.com/batocera-linux/batocera.linux/pull/1017
Moved code to S31emulationstation
```
This will secure metadata issues (favourites, scrapes ....)
if you press a button for shutdown
The timeout is set to 20 seconds (as an alternative ways for counting watchdogs)
``

S31emulationstation - always save metadata

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

So, long story short: with the new `--set-shader` CLI on RetroArch 1.7.8, you still need to have `video_shader_enable=true` in your RetroArch config options. If you upgrade from Batocera 5.23 or earlier, this setting was kept, if you have a brand new install, it needs to be added. That's what this fix does (and put the right `video_shader_dir` otherwise it takes the `datainit` by default, which is wrong).

Fixed shaders for RetroArch 1.7.8 (for real!)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
package/batocera/core/batocera-system/c2/batocera.conf
package/batocera/core/batocera-system/miqi/batocera.conf
package/batocera/core/batocera-system/odroidn2/batocera.conf
package/batocera/core/batocera-system/rockpro64/batocera.conf
package/batocera/core/batocera-system/rpi1/batocera.conf
package/batocera/core/batocera-system/rpi2/batocera.conf
package/batocera/core/batocera-system/rpi3/batocera.conf
package/batocera/core/batocera-system/s905/batocera.conf
package/batocera/core/batocera-system/s912/batocera.conf
package/batocera/core/batocera-system/tinkerboard/batocera.conf
package/batocera/core/batocera-system/x86/batocera.conf
package/batocera/core/batocera-system/x86_64/batocera.conf
package/batocera/core/batocera-system/xu4/batocera.conf

This PR enables AI-assisted game translations for RetroArch/libretro-based emulators.
Three new fields have been added in `batocera.conf`:
```
global.ai_service_enabled=1  # Is the service enabled?
global.ai_service_url=       # URL of the translation service to use
global.ai_target_lang=Fr     # Language to translate into (2-char language code)
```
I talked to **Beaker**, who manages https://ztranslate.net and he agreed to give a generic `api_key` for Batocera users so that they don't need to register individually and put their personal API key as a new parameter. If people want to do it, they can edit the `ai_service_url` with their own api_key, but by default we can use `http://ztranslate.net/service?api_key=BATOCERA`
I also pushed a PR on batocera-emulationstation to take those …

Libretro AI service for game translations

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

In case `global.ai_service_url=` exists but is empty in `batocera.conf`

fixed a crash on 5.24RC1

---

.gitignore
configs/batocera-x86_64-dev_defconfig
package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk

Bump to consider my last changes to lr-mame.
libretro-mame-tiny is a development package I use to quick build (<5min) mame. I don't want to commit it, so I add it to gitignore.

New lr-mame

---

package/batocera/utils/rpigpioswitch/rpi-retroflag-SafeShutdown.py

Fixed ` GPIO.cleanup() `
Removed useless line `start = time.time()`
The GPIO.cleanup code-line cutted down the whole power and then metadata was lost, because the shutdown process can't reach S31emulationstation and other processes. Usually I use annother powerdevice so I was not able to track down these errors so quick.
So we have two possible solutions here
1. change python script (done here)
2. change rpi_gpioswitch script to **not** kill python process
For code style equality I decided to take the first route!
regards

py: Fixed rpi-retroflag-SafeShutdown script

---

package/batocera/utils-host/xa/xa.mk

xa 2.3.9 is now unsupported and gives a 404 while compiling
Bump to latest stable 2.3.10

xa: version bump (2.3.10)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

This is the configgen code to enable the libretro `runahead` option (https://docs.libretro.com/guides/runahead/) - it basically enables faster response time than actual real hardware consoles. 
It's a follow up to @shantigilbert's PR on Batocera-ES https://github.com/batocera-linux/batocera-emulationstation/pull/245 
**THIS FEATURE IS CPU INTENSIVE:** while it can run on a reasonable x86_64 PC, but I am not sure about all the SBCs we support. A Raspberry Pi3 might be too slow to enable this, even on "old" machines. I am curious about feedback on this from other users.  Because it's quite experimental, the early 5.25 cycle is probably a good timing for testing this out. :)

Added configgen code for "runahead" option

---

package/batocera/core/batocera-scripts/scripts/batocera-systems

Compressed files have different md5sum depending on the program used and the compression ratio. In these files md5sum cannot be used.

fix-md5sum-bios-bios

---

package/batocera/utils/rpigpioswitch/S92switch
package/batocera/utils/rpigpioswitch/rpi-retroflag-AdvancedSafeShutdown.py
package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
package/batocera/utils/rpigpioswitch/rpigpioswitch.mk

Like @darknior wished....
This is an advanced version of the Retroflag scripts. The RESET-trigger button is now more versatile and is able to terminate a running emulator by just pressing the RESET button.
As result you'll be kicked back to ES main screen. This will not work for KODI!
It's a "state of the art" method well known in RetroPie
I understand the deep user wish to add this as default.
I do not want to let this be shown in the `rpi_gpioswitch` so it needs to be setted up manually by editing batocera.conf and add `RETROFLAG_ADV` to `system.power.switch` key
The alternate method is to use the installer like done before, this is the method available for RetroPie users, Recalbox ones and BATOCERAs
```
wget -O - "https://raw.githubusercontent.com/crcerror/retroflag-picase/master/instal …
```

Added RETROFLAG_ADV - please discuss BEFORE merge!

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py

**Now automatic version** for bartop/arcade cabinets where only a d-pad stick is available, this patch forces it as the analog control stick on Gamecube.

NGC use D-pad when no analog stick is available

---

package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info

**DON'T MERGE** Until ES is adapted for this (I don't have rights to add a tag)...
Discussed with @fabricecaruso, here is a new format for better RetroAchievements integration (more information can be displayed in EmulationStation).
The output format is the following, with up to 5 `<game>` (in case of success):
```
<?xml version="1.0" encoding="UTF-8"?>
<retroachievements>
<lastrefresh>1574634367</lastrefresh>
<username>lbrpdx</username>
<totalpoints>4743</totalpoints>
<rank>4184 / 61129 ranked users (Top 8%)</rank>
<averagecompletion>29.08%</averagecompletion>
<userpic>https://retroachievements.org/UserPic/lbrpdx.png</userpic>
<registered>29 Aug 2018, 03:00</registered>
<lastactivity>24 Nov 2019, 22:17</lastactivity>
<game>
<name>Awesome Game (GameBoy)</name>
<achievements>7 of …
```

RetroAchievements v2 in XML format

---

batocera-Changelog
package/batocera/utils/gpicase/batocera-gpicase-install

Some small improvements made
1. you can alter data in /boot/config.txt now
2. you can force the data writing to /boot/config.txt like it was done before (disabled for default)
3. you can change this behaviour by activating `force_gpi_defaults` in config.txt
4. set `RETROFLAG_GPI` as default value now
5. some speed improvements because the whole checking of the config is obsolet now.
```
CONFIG="$(batocera-settings "$CONFIGFILE" --command load --key force_gpi_defaults)"
CONFIGERR=$?
[[ $CONFIGERR -eq  12 || $CONFIG -eq 1 ]] || exit 0
```
This section is intersting
* Errorcode 12 means "VALUE NOT FOUND!" so we force a initial install of the GPi-case values
* CONFIG=1 means the user toggled the force_gpi_defaults in `/boot/config.txt` in this case the script behaves like the old one.

Gpicase install automatic setup

---

package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject
scripts/linux/theBezelProject-md5gen

Updates in the repository structure from theBezelProject (`batocera-es-thebezelproject`) + update on the script that generates the MD5 sums for re-downloading only the necessary bezel files (`theBezelProject-md5gen` that runs on the server that generates the Batocera images, not intended to be part of the distribution).

theBezelProject update (kudos to Evoflash)

---

package/batocera/utils/gpicase/99-gpicase.rules
package/batocera/utils/gpicase/batocera-gpicase-install
package/batocera/utils/rpigpioswitch/S92switch

~~Using subshell during 2nd boot~~
~~Switch becames active then....~~
1. The installation script **DOES NOT** modify the batocera.conf file anymore, because this file contains only user setted configuration.
2. The udev rule sets a file in : /var/run/powerswitch-detected with the content RETROFLAG_GPI (at each boot) now
3. ~~in the powerswitch script in /etc, if powerswitch is enabled on batocera.conf, choose this value, else, if /var/run/powerswitch-detected exists, choose this value~~
3. ~~**Modfied** The S92switch service in /etc/init.d enables the powerswitch (forced!) if /var/run/powerswitch-detected is available, if not then allow user settings.~~
3. User settings done in batocera.conf will be used in first instance. If no value is setted here then a value setted by udev-rule will …

gpicase: Automatic activation of shutdown scripts

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi2.yml

rpi2 snes defaults to snes9x_next

---

package/batocera/core/batocera-scripts/scripts/batocera-settings
package/batocera/core/batocera-system/x86/batocera.conf
package/batocera/core/batocera-system/x86_64/batocera.conf

Improvements made:
1. Finds values uncommented in first case
2. Finds commented values in second loop
Result: First uncommented value is used as proper value
Fixed layout in batocera.conf for x86 systems

optimized parsing of conf files

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

@nadenislamarre 
2017/06/04 - batocera.linux 5.7 - release
* psx: remove the .bin extension. please use .cue.
Was never done? Any reasons why?

psx: removed BIN extension

---

package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info

Fix required to display the RetroAchievements menu again (to match the update on `https://retroachievements.org/user/...`)

RetroAchievements HTML output update

---

package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife

`--version` or `--architecture` 
why output "0-UNKNOWN"
You can use script like this for example to extract pure numbers
```
version=$(batocera-es-swissknife --version)
version=${version%% *}
if [[ ${version//[^[:digit:]]/} -lt 524 ]]; then
echo "Error!"
echo "Your current version of Batocera is '$version'"
echo "You need at least 5.24 ...."
exit
fi  
```

Added --version and --architecture parameters

---

package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/curvature/rendering-defaults.yml

The previous shader for `curvature` set did not work on Odroid N2. This new `fakelottes` has been tested on PC (with Intel GPU), RPi3 and Odroids.

Switched "curvature" to fakelottes (for Odroids)

---

package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info

Updated `batocera-retroachievements-info` script to scrape the right information from the https://retroachievements.org website (again).

Yet another retroachievements.org HTML update

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py

As reported on the forum, and reproduced on my PC with integrated Intel GPU, a default value of "0" lets Dolphin choose what it believes is the best supported resolution, but it never works. Setting the default to "1" (i.e. Gamecube/Wii native resolution) works much better.

Fixed default resolution for Dolphin emu

---

package/batocera/emulators/retroarch/libretro/libretro-bsnes/libretro-bsnes.mk

By default, bsnes compiles by enabling optimizations for the local processor (native) and does not work on different processors.

Bsnes architecture correction

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

RetroArch used to always pause after AI translation, now it's controlled by a specific setting in `retroarch.cfg` (by default: unpaused).
Look for the corresponding ES PR.

Added an option to pause after screen translation

---

package/batocera/core/batocera-system/Config.in

s905 : remove parallel n64 as for c2

---

board/batocera/fsoverlay/etc/init.d/S99custom

Part 1: @nadenislamarre nothing special - will finish init.d service if a custom.sh is present
Part 2: Since fat32 does not have an executable bit we have two possibilites (First: mount the fat partition with umask 0000. Second: In this (single) case we call the correspondening shell file with the bash interpreter)

S99custom minor fix - fixed execution on FAT32 file systems

---

package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation-config-event-codes.patch

fix the main sdl2 pad issues.
an other once remaining to fix line 68 of the same patch (to handle cases when you unplug/plug pads)

sdl2: fix pads 1/2

---

package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife

very basic but usefull for shell lovers
if you use info elements (--version, --architecture or --update)
then exitcode can be catched for your scripts!
Output can be:
```
Webstatus:   5.24 2019/11/06 01:11
Update URL:  https://batocera.org/upgrades/rpi3/stable/last/index.html
Used on:     rpi3
Installed:   5.25-dev 2020/02/08 05:09
Status:      No Update found!
1
#
```

Added --update param for batocera-es-swissknife

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

Mame and NeoGeo having the arcade core but each maintaining its default core.

arcade: core

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py

Corrects the bug with controls that have names with unicode characters.
Example:
"Sony Interactive Entertainment DUALSHOCK®️4 USB Wireless Adapter"

fix: Configgen unicode joy for Dolphin

---

batocera-Changelog
package/batocera/emulationstation/batocera-es-system/es_systems.yml

Problems with emulators will be analyzed and corrected for version 5.26 of Batocera. 

disable: commodore C20 and C128

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml

it's not perfect.
it is because 4/3 don't count rotation

default odroidgoa to 3/4 ratio

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py

In certain cases, Dolphin configurations would be generated with white space in the device names for controllers, causing the devices not to be recognized.

Fixing config generation for controllers which may result in whitespace in the config unintentionally.

---

package/batocera/core/batocera-scripts/scripts/batocera-moonlight

Fixed `batocera-moonlight` to make Moonlight work again, with scraping from theGamesDB. 
We still had an outdated XML-based implementation that is not supported anymore (ported it to the new JSON API).
Wrote a how-to on the wiki for Moonlight to go with that PR.

Moonlight: fixed script, ported it to new theGamesDB JSON API

---

package/batocera/core/batocera-system/Config.in

required to access folders via sftp and should be replaced by openssh

BR2_PACKAGE_GESFTPSERVER

---

package/batocera/core/batocera-scripts/scripts/batocera-es-theme

This was a minimal invasive code change
thanks to @lbrpdx
Output in terminal is now
```
es-theme-minimal.zi 100%[===================>]   6.15M  2.16MB/s    in 2.8s
Unzipping es-theme-minimal to:          /userdata/themes
Theme Minimal installed to:             /userdata/themes/es-theme-minimal
#
```

es-themes: Niced Terminal output

---

batocera-Changelog
board/batocera/fsoverlay/etc/asound.conf
board/batocera/fsoverlay/etc/init.d/S26system

Tested on x86_64, probably needs testing on other architectures. It fixes the problem when video snaps play, but without sound -- which is even more noticeable when you use the option to fade the ES background down when playing video snaps.

Fixed audio for video snaps

---

board/batocera/fsoverlay/etc/init.d/S11share
board/batocera/fsoverlay/etc/init.d/S26system
board/batocera/fsoverlay/etc/init.d/S31sixad
board/batocera/fsoverlay/etc/init.d/S32bluetooth
board/batocera/fsoverlay/etc/init.d/S35securepasswd
board/batocera/fsoverlay/etc/init.d/S91smb
board/batocera/odroidgoa/fsoverlay/etc/init.d/S31emulationstation
board/batocera/rock960/fsoverlay/etc/init.d/S32bluetooth
board/batocera/rockpro64/fsoverlay/etc/init.d/S32bluetooth
board/batocera/rpi/fsoverlay/etc/init.d/S32bluetooth
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_1cpu
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_nosplash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_splash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fbegl_nosplash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_xorg

```
./board/batocera/fsoverlay/etc/init.d/S31sixad
./board/batocera/fsoverlay/etc/init.d/S91smb
./board/batocera/fsoverlay/etc/init.d/S11share
./board/batocera/fsoverlay/etc/init.d/S26system
./board/batocera/fsoverlay/etc/init.d/S32bluetooth
./board/batocera/fsoverlay/etc/init.d/S35securepasswd
./board/batocera/odroidgoa/fsoverlay/etc/init.d/S31emulationstation
./board/batocera/rock960/fsoverlay/etc/init.d/S32bluetooth
./board/batocera/rockpro64/fsoverlay/etc/init.d/S32bluetooth
./board/batocera/rpi/fsoverlay/etc/init.d/S32bluetooth
./package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fbegl_nosplash
./package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_xorg …
```

drop: batoceraSettings.py -> batocera-settings

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

In the case of a fresh install, with AI translation activated with no target language selected, or manual edits in `batocera.conf`.

Fixed crash when no target lang for AI translation

---

board/batocera/fsoverlay/etc/init.d/S12antivirus
package/batocera/core/batocera-system/Config.in

- at each boot, /userdata is scanned against virus/trojan added by the user having copied new roms
- zip are unzipped to check inside
- in a following pr, i will add an encrypted partition to store updated signatures and a cache to try to reduce
the impact on the boot time
- i think to add a way to provide any way to disable it, including via batocera-saveoverlay to prevent the user security

clamcav integration VT

---

board/batocera/patches/xapp_xinit/001-disable-xauth.patch
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_xorg

should we do that or keep XAUTHORITY and just replace the default serverauth.$$ file path in /usr/bin/startx ?
was required because of fat:
export XAUTHORITY=/var/lib/.Xauthority # needed because $HOME/.Xauthority can't be used on fat
and files:
$HOME/serverauth.$$ where created and kept when you shutdown badly
and xauth is not required as far as i understand (i understand it is to protect against users having already a local access while X is not open on network (xauth+))

disable xauth

---

board/batocera/post-image-script.sh
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py

Our previous `.md5` format was wrong. Now you can use
```
$ md5sum --check batocera-5.26-x86_64-20200402.img.gz.md5 
batocera-5.26-x86_64-20200402.img.gz: OK
```

Fix .md5 files to use "md5sum --check"

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py

Previous change in 5.25 prevented to set resolution in ES. Should be fixed for good now.

Fixed Dolphin resolution setting (from ES)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroRetroarchCustom.py

While using Batocera, it seems to me that volume is "unbalanced" between games and the user UI.
Every time i play, i have to increase TV volume for better audio in-game. Replicating what other retrogaming [solutions](https://gitlab.com/recalbox/recalbox/-/commit/cc16ae92dba6fa6a9dc5ae3112fafae397044878) did by implementing some dB gain inside `retroarchcustom.cfg`, i suggest this little fix here.
Tested with Diablo(Playstation), Sunsetriders(SNES), Contra(NES) and Altered Beast(Genesis). Now sound seems better equalized :)

Better volume balance between Retroarch and EmulationStation

---

package/batocera/core/batocera-scripts/scripts/batocera-es-theme

This gives correct output to theme installer inside ES
If this method fails we can still use the old method...
```
Downloading es-epicnoir.zip (17MB) >>> 0%
Downloading es-epicnoir.zip (17MB) >>> 5%
Downloading es-epicnoir.zip (17MB) >>> 35%
Downloading es-epicnoir.zip (17MB) >>> 64%
Downloading es-epicnoir.zip (17MB) >>> 100%
```

fix: es-theme percentage progress for ES

---

package/batocera/core/batocera-scripts/scripts/batocera-create-collection

A Bash script to manage/add easily new custom collections. If someone is motivated to do a nice GUI for ES, feel free (@fabricecaruso ?).
```
batocera-create-collection [ -c collection_name ] [ -g genre ] search_terms 
-c foobar  : The resulting collection will be stored
as "custom-foobar.cfg" in the collection directory
-g Shooter : Only games matching "Shooter" <genre> in your gamelist.xml 
files will be added to the collection
-h         : Display this help file
Note that existing game collections with the same name will have newly
found games added to the list.
Examples:
"batocera-create-collection zelda" creates a custom collection
of all your roms matching "Zelda" in their names.
You can use it with "final fantasy", and it creates a collection file
named "custom-final.fantasy.cfg". …
```

Added 'batocera-create-collection'

---

board/batocera/x86/fsoverlay/usr/bin/batocera-resolution

Nvidia Optimus causes the OS to see two screens - one on the Intel adapter which is used for display output and one on the Nvidia adapter which is used for rendering the frames. So we have two lines returned from xrandr --currentResolution and one must be discarded. ES will not launch otherwise.

Avoid duplicate resolution lines when using optimus

---

package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info

Yet another HTML change on https://retroachievements.org that breaks the display of our RetroAchievements screen (ranking disappeared).

Updated for HTML changes on retroachievements.org

---

package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

emulated wiimote is for wii, not for gamecube

es features for systems

---

package/batocera/core/batocera-system/Config.in

None of RPI systems if powerful to run mesen-s. For instance on my rpi3 Alladin games is running with ~30FPS (it should be running with 60FPS). Thus building mesen-s for RPI is pointless.

Disable building mesen-s for rpi architecture

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py

Title pretty much self-explaining. If someone has a rom with `.side.` on its name, no shake function is available. 
With this little hack, L2 is the main "shake" button while using this controller orientation (side wiimote) and it solves the problem that now i can play "New Super Mario - Wii" with my wife without losing too much time creating custom mappings :)
In some cases `Shake/X` should be enough but, i'm thinking on other games that want the shake on other directions. Maybe, split shake into `l2` and `r2` in a future when more games are tested.

Default map L2 for shaking controller on Dolphin

---

board/batocera/fsoverlay/etc/init.d/S61cec
package/batocera/core/batocera-system/Config.in
package/batocera/core/batocera-system/c2/batocera.conf
package/batocera/core/batocera-system/miqi/batocera.conf
package/batocera/core/batocera-system/odroidgoa/batocera.conf
package/batocera/core/batocera-system/odroidn2/batocera.conf
package/batocera/core/batocera-system/rock960/batocera.conf
package/batocera/core/batocera-system/rockpro64/batocera.conf
package/batocera/core/batocera-system/rpi1/batocera.conf
package/batocera/core/batocera-system/rpi2/batocera.conf
package/batocera/core/batocera-system/rpi3/batocera.conf
package/batocera/core/batocera-system/s905/batocera.conf
package/batocera/core/batocera-system/s912/batocera.conf
package/batocera/core/batocera-system/tinkerboard/batocera.conf
package/batocera/core/batocera-system/x86/batocera.conf
package/batocera/core/batocera-system/x86_64/batocera.conf
package/batocera/core/batocera-system/xu4/batocera.conf

Adding the script with stop action and `batocera.conf`for RPI3. Other boards will need test.
`cec-client -l` and `echo 'scan' | cec-client -s -d 1` should be enough to probe the hdmi connector and the Television/monitor your board is plugged

Auto turn-off monitor during poweroff

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

[start] + [select] to pop-up a virtual keyboard (was [hotkey] + [start] = quit).

Virtual keyboard for Amstrad CPC

---

package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk

Typo in the install script, messing up ES (reported by @fabricecaruso).

es_features.cfg was not correctly installed

---

package/batocera/core/batocera-scripts/scripts/batocera-es-theme

It could fail if themes got a huge download size (+100MB -- fixed now!)
This needs to be fixed in ES, too because in this cases there is now progress bar displayed (idk if this depends on the filesize only)
Code logic is more maintable now

fix: filesize theme download

---

package/batocera/libraries/libcapsimage/libcapsimage.mk

With the full GIT version for this new repo, I got an error at build time:
```
>>> libcapsimage 549b1955d52a70b9f7egie88a419f6ecfb6ee61142 Downloading
Reinitialized existing Git repository in /build/buildroot/dl/libcapsimage/git/.git/
Fetching all references
Could not fetch special ref '549b1955d52a70b9f7egie88a419f6ecfb6ee61142'; assuming it is not special.
Commit '549b1955d52a70b9f7egie88a419f6ecfb6ee61142' does not exist in this repository.
(...)
HTTP request sent, awaiting response... 404 Not Found
2020-04-20 01:44:54 ERROR 404: Not Found.
```
See https://github.com/batocera-linux/batocera.linux/commit/251e908eee347e66070f62ef004578d1df9f1380#commitcomment-38603517

Fixed capsimage git download

---

package/batocera/core/batocera-scripts/scripts/batocera-es-theme

1. github friendly (10 attempts, 5 secods per attempt)
2. We see download size now
3. We see progress bar in ES now
4. ES Badgelayout changed to [sizeMB] - Themename
5. Addes status messages
Special thanks to @lbrpdx and @fabricecaruso

fix: theme download

---

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py

Removed the warning message we systematically get at the beginning of `es_launch_srderr.log`:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details
```

Removed ugly warning in es_launch_stderr.log

---

package/batocera/emulators/dolphin-emu/001-padorder.patch

fix the pad order of dolphin in some rare cases (same pad names)
but basically, read the pad in the same order as other emulators (order by /dev/inputX)

fix dolphin pad order in case of same pad names

---

package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
package/batocera/emulationstation/batocera-es-system/es_systems.yml

In order to add Linux games and apps that can be run from a .sh script. There is a whole community of Batocera users who are using these, and the result is a new section in `es_systems.cfg`: 
```
<system>
<fullname>Ports</fullname>
<name>ports</name>
<path>/userdata/roms/ports</path>
<extension>.sh .SH</extension>
<command>%ROM%</command>
<platform>ports</platform>
<theme>ports</theme>
<group>ports</group>
</system>
```
Might be useful for Wine games too -- I'm not sure we want to get into the full `emulatorlauncher.py` for Wine either.

Add ".sh" into Ports (for 3rd party games/apps)

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

We can use libretro cores now and call them via shell file
example for 
"QUAKE called by shell file.sh"
```
#!/bin/bash
controller=$@
python /usr/lib/python2.7/site-packages/configgen/emulatorlauncher.py $controller -system tyrquake -rom /userdata/roms/tyrquake/id1/PAK0.PAK
```

Add ".sh" into Ports - added %CONTROLLERSCONFIG% argument

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

If video_driver = ' ', Retroarch's ozone theme does not work.

ozone: video_driver

---

package/batocera/utils-host/xa/xa.mk

xa-2.3.10.tar.gz moved to https://www.floodgap.com/retrotech/xa/dists/unsupported/, so download fails. Should we bump the version or point to the unsupported one?

xa: version bump (2.3.11)

---

package/batocera/emulators/retroarch/retroarch/retroarch.mk

With 1.8.6 retroarch I encountered problem with run-ahead and eg. snes9x -- emulation is very slow (30fps).
This version is 4 days ahead and works fine.

bump retroarch

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

This needs testing to make sure we cover all cases, but this patch basically:
- adds checks for caching bezels in /tmp/ that will not change (default.png...) and updates only if new bezels are added more recently than those generated in the cache
- doesn't fill /tmp/ with individual per-game bezels
- supports palette-alpha PNG resizing, like those provided by theBezelProject and adds a default viewport (when not provided for theBP bezels)
- fixes resizing when bezels are not centered for horizontal/vertical offsets

Palette-alpha PNG bezel resizing (theBezelProject)

---

package/batocera/core/batocera-scripts/scripts/batocera-hybrid-nvidia

Fix when the Nvidia PCI id is > 09, as it needs to be in decimal, not hex in the config file.

Fix for some NVidia hybrid laptops

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py

Fix for the bug reported at https://forum.batocera.org/d/3790-batoceralinux-526-rc1/20

Fix for 5.26: X68000 drives boot order

---

package/batocera/core/batocera-scripts/scripts/batocera-wifi

This finally works.
1. SSID can contain Whitespaces
2. SSID can be maximazed (32 chars!)
3. Support of special signs like !?=
4. wifi_xyz support and variants like (name-wifi_5, name_wifi_5....)
If everything fails the script checks number of colums (=only a single seperator is used). If the colums are not 2 then there is not print of SSID.
Combo fail: `guest wifi_5_super_super` 
Combo works: `guest_wifi_5_super_super`
But to be hones ... the combo `whitespace+wifi_foo_` should not be very common ;)

fix: WiFi SSID list whitespace and wifi_

---

package/batocera/libraries/libcapsimage/libcapsimage-003-gcc9.patch

This patch fixes some trivial scope errors to get libcapsimage 4.2 compiling with GCC 9.x
libcapsimage is the only package on batocera.linux master not compiling fine with GCC 9.x

Fix libcapsimage4.2 compilation for GCC 9.x series

---

package/batocera/emulators/supermodel3/supermodel3.mk

Illegal instruction at startup because of -march=native in Makefile.inc
Patched -march=native with -msse since it uses -mfpmath=sse

Fix supermodel / model3 emulator 

---

board/batocera/doWinepackage.sh
package/batocera/emulators/wine-x86/wine-x86.mk

Notes :
It's still unclear if wine-mono requires a native Linux Mono runtime, so we might be able to strip need at a later stage to save space and useless package.
GStreamer is a hit or miss depending of formats since it relies on libav which is compiled in GPL mode so without most MS codecs like ASF, WMV and so on....

Wine improvements

---

package/batocera/utils/rpigpioswitch/S92switch

Might be good to port back to 5.26 if we ever need to rebuild a RPi4 image.
Batocera-ES sets up `/tmp/shutdown.please`, not poweroff.please. As currently written the "stop" command is never invoked, preventing the Argon One case for RPi4 to stop correctly.

Fix for Rpi4/ArgonOne shutdown

---

package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh

Added fix to ArgonCase `/etc/init.d/S92switch status` gives now proper message

rpi_gpio: Revert back clean 5.26

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

- Remove all non used options from es_sytems in ES.
Like for example REWIND or AUTOSAVE when emulators not use them.
- Add 3 news WII options in ES
* vsync
* anisotropic_filtering
* antialiasing

es_sytems clean and Wii new options

---

package/batocera/utils/pacman/batocera-makepkg
package/batocera/utils/pacman/batocera-pacman-batoexec

Now that ES can manage <game> additions/removals in gamelist.xml files, we won't manage them externally from the python batoexec hook. It's cleaner as ES will be the only process accessing the gamelist.xml files, and now automatically updates the screens with game additions/removals.

Switched <game> management to ES new web service

---

package/batocera/emulators/retroarch/libretro/libretro-parallel-n64/001-gldouble-no-double-declaration-with-mesa.patch

Use same types as mesa and new headers shipped with gpu blobs.

libretro-parallel-n64: correct GLdouble patch (3rd try)

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

- better sorting & presentation in ES.
Related to SystemView Manufacturer bar ( when systems are sorted by manufacturers ) #515 :
https://github.com/batocera-linux/batocera-emulationstation/pull/515

es_systems : rename manufacturer: Misc. Arcade & Misc. Port to Arcade & Ports

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

`rom` is wrongly typed `om` for msx2 and msx2++ preventing some games to appear

Fix typo in msx2 and msx2+ extensions

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

Remove zip extensions for cd based systems : they are not compatible and this generate users feedback trying to use them and not managing to launch games

Remove incompatible zip extensions for cd based systems

---

board/batocera/fsoverlay/etc/init.d/S10wifi
board/batocera/fsoverlay/etc/init.d/S11share
board/batocera/fsoverlay/etc/init.d/S65values4boot
package/batocera/core/batocera-system/batocera-boot.conf

CREATED S10wifi
* WIFI key is now directly stored into cat-EOF-construct
* Removed residues from WiFi credentials encryption
Modified S11share
* Setted proper idents
* Changed test commands to more modernd bash statements
* splitted network connection out off S11 and transfered to S10
Add S65values for boot
* This services copies settings to batocera-boot.conf
* wifi services does not need to rely on mounted userdata anymore
Add batocera-boot.conf
* setup section
* description
@nadenislamarre This should be a better PR

Splitout of S11share -> S10wifi is independent from /userdata now

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/emulators/dolphin-emu/dolphin-emu.mk

Dolphin bump for most recent and configgen fix to pass QT variables as a system variable instead of on Dolphin command line.  This corrects issues with versions of Dolphin beyond Mar 22 version

Bump Dolphin and Fix configgen

---

package/batocera/core/batocera-scripts/scripts/batocera-systems

Hey Batocera devs!
This PR adds a --filter flag to the batocera-systems script and makes is compatible with Python 3 (it should still be compatible with Python 2.6 and up). If wanted, I can split this up in 2 commits or revert the Python 3 compatibility completely.
The reason for the PR is as follows:
I recently created https://github.com/EmuELEC/EmuELEC/pull/218 to display an alert when there were missing files for Cave Story. I later discovered an option called "Missing BIOS" in the settings and noticed it listed all missing bioses. Upon further inspection, I found out that this script exists and lists all missing BIOS files.
I wanted to use this script, but also have to keep in mind it will run in a fairly constrained environment on a SD card, which could cause a fair amount of …

Add --filter flag to batocera-systems

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Only the most used options, and by default with minimal value.
Flycast:
-widescreen hack: on/off
-anisotropic filtering: off/2x/4x/8x/16x
-texture upscaling (xBRZ): off/2x/4x/6x
-render to texture upscaling: off/2x/3x/4x/8x
Desmune:
-texture upscaling (xbrz) : off/2x/4x
-texture smoothing: on/off
-multisampling AA: off/2x/4x/8x/16x/32x

Update Dreamcast emulators options

---

package/batocera/emulators/citra/citra.mk
package/batocera/emulators/retroarch/libretro/libretro-citra/libretro-citra.mk

Advantages :
- We do not depend on buildroot fmt or other lib
- We use whatever is provided in the package
- We do not copy/clutter core/emulator-specific into /usr/lib
Builds fine on x86_64.

Statically build citra and lr-citra

---

board/batocera/fsoverlay/etc/init.d/S10wifi
board/batocera/fsoverlay/etc/init.d/S65values4boot

This one works best and offers the best of two worlds. The average user won't mind this extra config because it is completly independent from ES and batocera-wifi. The advanced user can manually add the needed keyvalues.
We just need to add keyvalues to batocera.conf
```
#wifi.hidden.ssid=hidden SSID
#wifi.hidden.key=new key
```
EDIT: we need to add the code block from above to all batocera.conf SBC.
This is also the more straight and less user confusing approach, if you compare this [PR1991](https://github.com/batocera-linux/batocera.linux/pull/1991) then it should be clear what I ment

WIFI connect to hidden APs

---

package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py

PSX Mednafen writes `beetle_psx_hw_cpu_freq_scale = "100%(native)"`, but Python ConfigParser 2.7 takes "%(" as an error, and they won't fix as it's now EOL. There is a new %-safe parser when we move to Python 3.
When this happens, a message is now logged in `es_launch_stderr.log`.

Fixed a bug with PSX Mednafen options and configgen

---

package/batocera/emulators/ppsspp/ppsspp.mk

This will be important later as I am planning to add Vulkan support and we might have conflicts with system Vulkan libs (glslang, SPIRV and so on).
Also this is tidyier but that's just my personal opinion :)

Link PPSSPP statically with dependencies (do not clutter /usr/lib)

---

Dockerfile
package/batocera/emulators/rpcs3/006-llvm-crosscompile.patch
package/batocera/emulators/rpcs3/007-fix-wolfssl.patch
package/batocera/emulators/rpcs3/008-llvm-no-ccache.patch
package/batocera/emulators/rpcs3/Config.in
package/batocera/emulators/rpcs3/rpcs3.mk

Warning !
I had to change the Dockerfile to bump to Ubuntu 20.04 base image and ncurses6 to workaround some tedious LLVM cross-compile bug.
I managed to build successfully master tree for x86, x86_64, odroidn2, odroidga, rpi3 and rpi4 with this new Docker image but some other archs are untested.
RPCS3 is indeed working as experimental with this PR and PS3 games can be "played".
The whole thing is a bit rough but its' a good starting point from the previous non-compiling one.

RPCS with working LLVM submodule

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dosboxx/dosboxxGenerator.py
package/batocera/core/batocera-system/Config.in

After further testing on N2, there are still a lot of problem with dos emulation through dosbox-x and lr-dosbox :
- `lr-dosbox` doesn't take into account custom `dosbox.cfg` nor `dosbox.conf` for a specific a game, it should according to documentation but it does n't, and I don't know why. This breaks emulation for games needing more than standard configuration, like windows 3.1 games
- on N2 `dosbox-x` is completely broken, when it manages to launch it displays a completely broken screen 
Displaying the internal menu of dosbox-x is ok though but something doesn't work with display (I tried all possible display configurations (`output=` values of `surface, overlay, opengl, openglnb, openglhq or ddraw`) it simply doesn't work
And after a while it simply ceases to work with a lot of …

Reactivate dosbox + fix for dosbox-x configgen

---

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml

Fixes the stuttering we experience with standalone version on OGA, and provides features more consistent features with the rest of the emulators ([hotkey]+[start] to exit, shaders, bezels, AI translations...)

ScummVM defaults to Libretro version

---

package/batocera/emulators/retroarch/libretro/libretro-fbneo/libretro-fbneo.mk

Safe for 5.27, tested building ok on x86_64, n2, oga

Bump fbneo

---

package/batocera/emulators/retroarch/libretro/libretro-gambatte/libretro-gambatte.mk

Safe for 5.27, tested building ok on n2, oga, x86_64

Bump lr-gambatte

---

package/batocera/core/batocera-system/Config.in

We have to remove it and find an alternative GPIO library

WiringPi is deprecated (git source tree removed).

---

package/batocera/utils/pacman/004-xmloutput.patch

Package sizes in ES were off by 1024. Needs to be merged for 5.27.

5.27: Fixed a warning + display packages in kB

---

package/batocera/core/batocera-system/Config.in

disable linapple when kmsdrm is in use (because of sdl1)

---

board/batocera/rpi4/boot/config.txt

remove rpi4 cma-size while rpi4 1G crashes randomly

---

board/batocera/fsoverlay/etc/init.d/S65values4boot
package/batocera/core/batocera-splash/S03splash-ffplay
package/batocera/core/batocera-splash/S03splash-image
package/batocera/core/batocera-splash/S03splash-mpv
package/batocera/core/batocera-splash/S03splash-omx
package/batocera/core/batocera-system/batocera-boot.conf
package/batocera/core/batocera-system/c2/batocera.conf
package/batocera/core/batocera-system/libretech_h5/batocera.conf
package/batocera/core/batocera-system/miqi/batocera.conf
package/batocera/core/batocera-system/odroidgoa/batocera.conf
package/batocera/core/batocera-system/odroidn2/batocera.conf
package/batocera/core/batocera-system/rock960/batocera.conf
package/batocera/core/batocera-system/rockpro64/batocera.conf
package/batocera/core/batocera-system/rpi1/batocera.conf
package/batocera/core/batocera-system/rpi2/batocera.conf
package/batocera/core/batocera-system/rpi3/batocera.conf
package/batocera/core/batocera-system/rpi4/batocera.conf
package/batocera/core/batocera-system/s905/batocera.conf
package/batocera/core/batocera-system/s912/batocera.conf
package/batocera/core/batocera-system/tinkerboard/batocera.conf
package/batocera/core/batocera-system/vim3/batocera.conf
package/batocera/core/batocera-system/x86/batocera.conf
package/batocera/core/batocera-system/x86_64/batocera.conf
package/batocera/core/batocera-system/xu4/batocera.conf

Added possibility to disable splash at all
Added possibilty to disable splash.sound inside batocera.conf
@tcamargo
For 5.28 you can add a switch `splash.screen.es` to enable/disable S31emulationstation loading bar

Moved splash-screen sound option to batocera.conf

---

board/batocera/x86/fsoverlay/etc/drirc

Same thing as the "old" C patch, but through configuration file, so we can run vanilla Mesa code.
@jdorigao can you test it fixes your issue on Intel HD 5500 ?

Try to workaround Mesa/Intel OpenGL 1.4 vs 2.1 bug with /etc/drirc 

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

Before, viewports were recalculated only when a new adapted bezel was generated.

Fix viewport on cached resized bezels.

---

Dockerfile

In current `master` the Docker build environment image fails to successfully build due to an APT error within the post-install stage. I've traced this issue back to relatively recent changes in 20.04 which meant that i386 packages are configured out-of-order, failing the build. As far as I can gather, this is an upstream problem but I'm not seeing any signs of it being fixed any time soon.
Testing was completed by following the wiki Docker installation instructions to the letter.
Setting the Immediate-Configure APT flag to false works well and seems to have no ill effects, so submitting this PR to resolve the problem.

Set Immediate-Configure APT flag to boolean false within Dockerfile

---

package/batocera/core/batocera-scripts/scripts/batocera-info

Otherwise, if an emulator hangs on forever without properly de-initiating OpenGL/Vulkan, you can't log into the system any more, neither from SSH or the console. X11 is stale, the commands for displaying OpenGL and Vulkan stay stuck and you just can't move forward.
Previous behavior is still there, but you need to call it with `batocera-info --full`

Removed OpenGL/Vulkan info on login

---

package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife

Update is only dependent from build-year and build-date
As long as these are the last two entries in **data.version**
So in future:
Batocera-5000 "Gran Tourino" 2020-12-31 12:55
will be detected because string comparement is only --> **202012311255**

Update: SSH batocera-check-update

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

Fix to get vertical 3:4 games back when using 1080p bezels, and made the font readable for retroarch menus when forcing a game to vertical 3:4.

Bezel for vertical 3:4 games and OGA menus

---

package/batocera/utils/rpigpioswitch/S92switch

Discussed with @crcerror : when you have a power switch on GPIO, the joypad initialization prevents it from loading. 
We still have an issue if a user would use GPIO for both joypad + power switch on RPi4... but that would need some lower level investigation and it's clearly a corner case.

Fix when using GPIO powerswitch on RPi4

---

package/batocera/utils/pacman/pacman.mk

For `repo-add` the path to Bash was wrong on BuildRoot.

pacman repo-add: default Bash path on BuildRoot

---

batocera-Changelog
package/batocera/core/batocera-splash/batocera-splash.mk

Trim 300 horizontal pixels from full-size logo, resize to native OGA resolution, adjust font size, and text position.
This makes a cleaner looking splash screen for the OGA and version text that can be read.

oga: fix splash screen

---

board/batocera/rockchip/odroidgoa/fsoverlay/etc/init.d/S31emulationstation
package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py
package/batocera/core/batocera-scripts/scripts/batocera-resolution.basic
package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm
package/batocera/core/batocera-scripts/scripts/batocera-resolution.tvservice
package/batocera/core/batocera-scripts/scripts/batocera-resolution.xorg
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_1cpu
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_nosplash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fb_splash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fbegl_nosplash
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation/S31emulationstation_fbgl_nosplash

reintegrate minmax resolution to minimize resolution of game to 1K in case your tv is 4K;
implement minmax and minmax-secure : es is in minmax-secure : it means that no risk it taken for a black screen (so, on drm, no resolution change, while on tvservice and xorg, it is ok)

min max resolution

---

package/batocera/core/batocera-scripts/scripts/batocera-store
package/batocera/utils/pacman/004-xmloutput.patch
package/batocera/utils/pacman/batocera-makepkg

Fix pacman when using multiple repositories (corresponding patch in ES to come).
Fix XML output (&, ", ' characters).
Add more pacman "groups" for no warning when creating packages.
Speed up the console CLI for batocera-store, and made it suitable for multi-repositories.

Pacman : use with multiple repositories + XML fix

---

board/batocera/amlogic/odroidc2/post-image-script-odroidc2.sh
board/batocera/amlogic/odroidc4/post-image-script-odroidc4.sh
board/batocera/amlogic/odroidn2/post-image-script-odroidn2.sh
board/batocera/amlogic/s905/post-image-script-s905.sh
board/batocera/amlogic/s912/post-image-script-s912.sh
board/batocera/amlogic/vim3/post-image-script-vim3.sh
board/batocera/libretech-h5/post-image-script-libretech-h5.sh
board/batocera/odroidxu4/post-image-script-odroidxu4.sh
board/batocera/post-image-script.sh
board/batocera/rockchip/odroidgoa/post-image-script-odroidgoa.sh
board/batocera/rockchip/rk3288/miqi/post-image-script-miqi.sh
board/batocera/rockchip/rk3288/tinkerboard/post-image-script-tinkerboard.sh
board/batocera/rockchip/rk3399/rock960/post-image-script-rock960.sh
board/batocera/rockchip/rk3399/rockpro64/post-image-script-rockpro64.sh
board/batocera/rpi/post-image-script-rpi012.sh
board/batocera/rpi/post-image-script-rpi3.sh
board/batocera/rpi4/post-image-script-rpi4.sh
board/batocera/x86/post-image-script-x86.sh

Should limit conflicts on this "big" script file and allow building variants per SoC later.

Rework big post-image-script.sh and call per-image scripts.

---

package/batocera/core/batocera-scripts/scripts/batocera-systems

is last bios available 4.86 md5 : cf9cb4ba53a83ad557501417837c8de9

Add PS3 Bios Detection

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Liste des ajouts.
(valeur la plus basse par défaut à chaque parametres).Tous testés et fonctionnel.
Flycast:
-reicast mipmapping: sur off par défaut (incompatible avec texture upscalling xbrz "texture noire" si activé)
-widescreen hack: on/off
-anisotropic filtering: off/2x/4x/8x/16x
-texture upscaling (xBRZ): off/2x/4x/6x
-render to texture upscaling: off/2x/3x/4x/8x
Desmune:
-texture upscaling (xbrz) : off/2x/4x
-texture smoothing: on/off
-multisampling AA: off/2x/4x/8x/16x/32x
Mednafen psx:
-internal resolution: 1x(native)/2x/4x/8x/16x
-texture filtering: nearest/sabr/xbr/bilinear/3point/jinc2
-widescreen hack: disabled/enabled
Genesisplus gx:
-no sprite limit : enabled, par défaut
Nestopia:
-no sprite limit: enabled, par défaut
-mask overscan h: enabled, par défaut
-mask overscan v: …

Update emulators options in ES

---

package/batocera/core/batocera-scripts/scripts/batocera-store

Otherwise errors were not caught, ES always displayed as "PACKAGE INSTALLED SUCCESSFULLY" (even for a wrong paceman arch, that was not installed).

Display correctly error cases in content downloader

---

package/batocera/core/batocera-scripts/scripts/batocera-settings
package/batocera/utils/batocera-wine/batocera-wine

```
Basic usage: batocera-settings -f [file] -r [key] -w [key] -v [value]
Extended usage: batocera-settings -e -g [game] -s [system] -r [key]
-f   Loads any config file, default '/userdata/system/batocera.conf'
-r   Read 'key' and returns value from config file
-w   Write 'key' to config file, mandatory parameter -v
-v   Set value to selected 'key', any alphanumeric value
-e   Activate extended mode, needed for parsing game/system specific keys
-g   Any alphanumeric string for game, set quotes to avoid globbing
-s   Any alphanumeric string for system
This will loop through 'system.["GAME"].key', 'system.key' or 'gloabal.key'
If -e is not set -g and -s are ignored!  
Classic: batocera-settings [file] -command [cmd] -key [key] -value [value]
Classic short: batocera-settings [file] [cmd] …
```

batocera-settings NG

---

package/batocera/core/batocera-scripts/scripts/batocera-store

Corresponding PR in ES coming as well. Without this patch, every time you "refresh" the content downloader, you also upgrade all packages to their latest versions... and we now have several packages that are 200MB+ so it takes a lot of time staring at "PLEASE WAIT". 
A new button in ES has been added for this "UPDATE ALL" feature.

Don't upgrade all pacman packages unless requested.

---

package/batocera/core/batocera-scripts/scripts/batocera-upgrade

It's for testing and developing
Sometimes you enter wrong url or switch to wrong channel and have to check used version manually.
Now you get a hint --- if there is an upgrade then you download the new version suddenly
If you do a DOWNGRADE you've 10s to press N or CTRL-C
If you download same version or version is not detected then you've 15s to avoid download
This affects only SSH upgrades, ES upgrades are uneffected

add: timer for upgrades (only in SSH)

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

Requires https://github.com/batocera-linux/batocera-emulationstation/pull/688 as a fix for ES

Mark .pbp incompatible with Duckstation (29+master)

---

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/moonlight/moonlightGenerator.py

1. Fixes axis inversion on some controllers (where axis `value > 0`)
2. Fixes D-Pad hat on some controllers (where hat `id != 0`)
3. Replaces ad-hoc SDL2 GameController config generation in CEMU with the one from `controllersConfig`.

Fix SDL2 GameController mappings

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/devilutionx/devilutionxGenerator.py
package/batocera/emulators/devilutionx/devilutionx.mk

Starts DevilutionX with a generated SDL2 game controller config.
Follow-up to #2510, made possible by #2552.
DevilutionX version bumped to get fixes for the following controller issues on the DevilutionX side:
* https://github.com/diasurgical/devilutionX/issues/930
* https://github.com/diasurgical/devilutionX/issues/931

DevilutionX: Controller support

---

board/batocera/fsoverlay/etc/init.d/S10wifi
board/batocera/fsoverlay/etc/init.d/S11share
board/batocera/fsoverlay/etc/init.d/S26system
board/batocera/fsoverlay/etc/init.d/S31sixad
board/batocera/fsoverlay/etc/init.d/S35securepasswd
board/batocera/fsoverlay/etc/init.d/S50triggerhappy
board/batocera/fsoverlay/etc/init.d/S61cec
board/batocera/fsoverlay/etc/init.d/S91smb
board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc
package/batocera/core/batocera-audio/alsa/batocera-audio
package/batocera/core/batocera-audio/alsa/batocera-audio-odroidga
package/batocera/core/batocera-audio/alsa/batocera-audio-rockpro64
package/batocera/core/batocera-audio/alsa/batocera-audio-rpi
package/batocera/core/batocera-audio/alsa/batocera-audio-vim3
package/batocera/core/batocera-bluetooth/S32bluetooth.template
package/batocera/core/batocera-scripts/scripts/batocera-config
package/batocera/core/batocera-scripts/scripts/batocera-hybrid-nvidia
package/batocera/core/batocera-scripts/scripts/batocera-install
package/batocera/core/batocera-scripts/scripts/batocera-kodilauncher
package/batocera/core/batocera-scripts/scripts/batocera-upgrade
package/batocera/core/batocera-scripts/scripts/batocera-wifi
package/batocera/core/batocera-splash/S29splashscreencontrol
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation
package/batocera/utils/gpicase/batocera-gpicase-install
package/batocera/utils/roshambo-case/S14roshambo
package/batocera/utils/rpigpioswitch/S92switch
package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh

So that we don't have to support "classic" style args anymore

batocera-settings: Migrate callers to new-style args

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py

Moves the GC triggers to L2/R2 (l1/r1 if l2/r2 don't exist), and sets analog settings if l2/r2 are analog buttons.

Update dolphin controls for analog support

---

board/batocera/patches/sdl2/sdl2_input_p006_sort_devices.patch
package/batocera/emulators/dolphin-emu/001-padorder.patch
package/batocera/emulators/retroarch/retroarch/000-input_sort_devices.patch

yes, but event9 must be after event2 and before event event10
(actual sort was alpha sort event10 < event2 < event9) causing troubles for xinmo or some
special cases

sort devices by name

---

package/batocera/core/batocera-scripts/scripts/batocera-upgrade
package/batocera/utils/rpigpioswitch/S92switch
package/batocera/utils/rpigpioswitch/rpi_gpioswitch.sh
package/batocera/utils/rpigpioswitch/rpigpioswitch.mk

Some more fixed:
- Better error handling with batocera-upgrade (ONLY SSH!)
- Some cleanups to batocera-upgrade (3 times creation of /userdata/system/upgrade)
- S92 is free from bash statements
- Some cleanups to rpi_gpioswitch

Some more cleanups for BATO30

---

package/batocera/utils/batocera-wine/batocera-wine

No more saves with pc or exe in /userdata/saves/windows but in /userdata/saves/windows/proton or lutris
For don't break prefix
Proton & lutris don't have the same prefix.

Little change

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

> /libretroConfig.py
- Send ROM options to libretroOptions for Neogeo with help from @lbrpdx
- Fix some core controllers settings with help from @lbrpdx
- Remove "systemNoRewind" limitation because working fine onN2 and PC. These settings must be applied by boards.
> /libretroOptions.py
> /es_features.yml
- Add all the usefull options to ES for the libretro emulators
- All already tested on N2
**Miss:**
- Some "only PC core" options to add
- The new "Commodore family core" options to add too for v30
@susan
- Add LABEL to YML parser
- Understand sub systems with sub options in YML parser (ex: genesisplusgx)
- Don't change the YML options order
@f.caruso
- Add LABEL to ES

Updates all LIBRETRO emulators CORE options

---

package/batocera/core/batocera-settings/batocera-settings.hash
package/batocera/core/batocera-settings/batocera-settings.mk

1. Fixes a bug in `batocera-settings-set`.
2. `batocera-settings-set` now creates a file if it does not exist

batocera-settings: Bump to 0.0.2

---

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py

Some gamepads had their stick(s) inverted.
This was initially fixed in
https://github.com/batocera-linux/batocera.linux/commit/cb5a790555a10a9d44cb6ff2be88c2b4cd5f79dc#diff-4c0044629d1097ced8ac69f82b01596e034fe8a8a6860a78db24abb62c44509b,
then broken again in a commit that fixed another issue:
https://github.com/batocera-linux/batocera.linux/commit/5a212a28534d4e9504eb4d9ace0d3c191d1dc1d2#diff-4c0044629d1097ced8ac69f82b01596e034fe8a8a6860a78db24abb62c44509b
This fixes it again.
Signed-off-by: Gleb Mazovetskiy <glex.spb@gmail.com>

Fix SDL2 stick inversion

---

package/batocera/emulators/retroarch/retroarch/retroarch.mk

Replaces the hack with a proper check

retroarch.mk: Fix OpenGL check

---

board/batocera/raspberrypi/rpi3/boot/cmdline.txt
board/batocera/raspberrypi/rpi4/boot/cmdline.txt

Thanks to @emclinux - the same cmdline.txt can boot off SDcard or USB for RPi3 and RPi4

Enable boot on USB for RPi3/RPi4

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

This is a "noob trap" as Fishou calls it: this option messes everything up if ever clicked inside the RetroArch menu.

Remove "restart RetroArch" option from the menu

---

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg

Previous ID 6 was the same as "select" ID
ID 8 matches SDL2 value for the guide button:
https://github.com/gabomdq/SDL_GameControllerDB/blob/d3f1cea1197b1b5aabf554c2d27e767148cbb955/gamecontrollerdb.txt#L834

es_input.cfg: Fix hotkey for X-Box 360 pad

---

board/batocera/fsoverlay/etc/init.d/S11share

Problem: shutdown hangs if mount /userdata with Samba/NFS mounts due to device or resource busy.
Fix: add a lazy umount flag -l in existing stop function and everything works.

Fix shutdown hang on network mounts

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py

This PR fix this issue : 
```
libGL error: MESA-LOADER: failed to open radeonsi: /lib32/dri/radeonsi_dri.so: wrong ELF class: ELFCLASS32 (search paths /lib32/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /lib32/dri/radeonsi_dri.so: wrong ELF class: ELFCLASS32 (search paths /lib32/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /lib32/dri/swrast_dri.so: wrong ELF class: ELFCLASS32 (search paths /lib32/dri)
libGL error: failed to load driver: swrast
```
and this issue : 
```
Unknown long option 'pad'
Unknown long option 'usb'
Unknown long option 'cdvd'
```
in beta have only gs plugins available : 
```
ls /usr/PCSX_AVX2/bin/plugins/
libGSdx.so    libGSnull.so
```
Tested in v30 now PS2 …

Fix PS2 in v30

---

package/batocera/core/batocera-audio/alsa/batocera-audio
package/batocera/core/batocera-audio/alsa/batocera-audio-odroidga
package/batocera/core/batocera-audio/alsa/batocera-audio-rockpro64
package/batocera/core/batocera-audio/alsa/batocera-audio-vim3

1. Migrate to POSIX Shell.
2. Remove obsolete unlock-audio.
3. Clean up formatting / minor style fixes.
Signed-off-by: Gleb Mazovetskiy <glex.spb@gmail.com>

batocera-audio: Clean up scripts

---

package/batocera/core/batocera-scripts/scripts/batocera-resolution.basic
package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm
package/batocera/core/batocera-scripts/scripts/batocera-resolution.tvservice
package/batocera/core/batocera-scripts/scripts/batocera-resolution.xorg
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation

Now you can set the maximum resolution for ES in `batocera.conf` with a syntax like:
system.es.maxresolution=1280x720
(not always 1920x1080 any more, like it was in v29)

Ported back (and enhanced) system.es.maxresolution from v29

---

package/batocera/emulationstation/es-theme-carbon/es-theme-carbon.mk

For new systems (X1, Channel F, DivolutionX...) + all .png have been quantized, saving 6MB on the overall theme.

Bump es-theme-carbon

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/xash3d_fwgs/xash3dFwgsGenerator.py

Do not try to create symlinks if they already exist.
This can happen if the config file or the save directory does not exist
but a symlink already exists in the rom directory.
Signed-off-by: Gleb Mazovetskiy <glex.spb@gmail.com>

xash3d: More robust launcher

---

board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc
package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation
package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk

xrandr is not used to work on all boards (and for when xorg will be removed)
works only for retroarch (could be done for other emulators if wanted)

batocera.conf display.rotate=0,1,2,3 option to rotate the screen

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/easyrpg/easyrpgGenerator.py

The current command used to launch the standalone EasyRPG-player from ES wasn't working, as the path to the rom needs to be included with the "--project-path" option.

fix for the standalone EasyRPG-player launch command

---

board/batocera/raspberrypi/rpi3/boot/config.txt
board/batocera/raspberrypi/rpi3/fsoverlay/etc/init.d/S03checkbootconfig

With the use of vc4-fkms-v3d for rpi3 we have no problem with the audio.

rpi3: vc4-fkms-v3d

---

board/batocera/scripts/post-build-script.sh

This way we no longer require a clean build to set home directory and shell correctly.

post-build-script: Relax /etc/passwd rewrite

---

package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.hash
package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk
package/batocera/emulators/wine/wine-lutris/wine-lutris.hash
package/batocera/emulators/wine/wine-lutris/wine-lutris.mk
package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.hash
package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
package/batocera/emulators/wine/wine-proton/wine-proton.hash
package/batocera/emulators/wine/wine-proton/wine-proton.mk

x86_64 Compilation OK with CCache
x86_wow64 OK no CCache
With this PR : 
now use Stable Lutris 6.0 Final
now use Stable Proton 5.13 with fix in stable branch

Switch Proton + Lutris to Git Stable

---

package/batocera/core/batocera-scripts/scripts/batocera-store

shift with empty argument isn't allowed in dash
it's possible that other scripts are also broken then

dash: batocera-store fix(e)

---

board/batocera/scripts/doWineWow64-32package.sh

```
/lib32/libgbm.so KO
ln -s /lib32/libgbm.so.1 /lib32/libgbm.so
/lib32/libglapi.so KO
ln -s /lib32/libglapi.so.0 /lib32/libglapi.so
/lib32/libfreetype.so KO
ln -s /lib32/libfreetype.so.6.17.4 /lib32/libfreetype.so
/lib32/libFAudio.so KO
ln -s /lib32/libFAudio.so.0 /lib32/libFAudio.so
```
```
/lib32/libxatracker.so KO
Missing
/lib32/libXrandr.so KO
Missing
/lib32/libXft.so KO
Missing
/lib32/libXinerama.so KO
Missing
/lib32/libXi.so KO
Missing
```

Fix other Missing Libs

---

package/batocera/core/batocera-scripts/scripts/batocera-install
package/batocera/core/batocera-scripts/scripts/batocera-overclock
package/batocera/core/batocera-scripts/scripts/batocera-resolution.basic
package/batocera/core/batocera-scripts/scripts/batocera-resolution.tvservice
package/batocera/core/batocera-scripts/scripts/batocera-resolution.xorg
package/batocera/core/batocera-scripts/scripts/batocera-store
package/batocera/core/batocera-scripts/scripts/batocera-wifi

In POSIX shell, `shift` errors if there are no arguments to shift.
This is unlike Bash, where `shift` is a no-op in this case.
@crcerror

batocera-scripts: Fix incorrect usage of `shift`

---

package/batocera/core/batocera-scripts/scripts/batocera-systems

We might comment out regional variants to require less files.
Also we might need to have an "optional" tag on the BIOS files added at a later stage...
I am unsure if EU/NA regional variants are needed because of PAL / NTSC issues (50 Hz / 60 Hz)

Add references to all Atari TOS images

---

board/batocera/amlogic/s905/boot/README.txt
board/batocera/amlogic/s905/boot/s905_autoscript.txt
board/batocera/amlogic/s905/boot/uEnv.txt
board/batocera/amlogic/s905/create-boot-script.sh
board/batocera/amlogic/s905/fsoverlay/etc/init.d/S03mali
board/batocera/amlogic/s905/fsoverlay/etc/modprobe.d/mali.conf
board/batocera/amlogic/s905/fsoverlay/etc/modules.conf

-remove old 3.x vendor modules from fsoverlay 
-switch to use uEnv.txt and on the kernel side to mkimage/uImage
-disable composite output (thanks Demetris!)

s905 fixes and some cleanup

---

package/batocera/core/batocera-system/Config.in

These driver packages do not build with gcc-10.
The drivers for these cards are already in the kernel anyway.

odroidgoa: Disable RTL driver packages

---

board/batocera/amlogic/odroidc2/genimage.cfg
board/batocera/amlogic/s905/genimage.cfg
board/batocera/amlogic/s912/genimage.cfg
board/batocera/libretech-h5/genimage.cfg
board/batocera/odroidxu4/genimage.cfg
board/batocera/orangepi-pc/genimage.cfg
board/batocera/orangepi-zero2/genimage.cfg
board/batocera/raspberrypi/rpi/genimage.cfg
board/batocera/raspberrypi/rpi3/genimage.cfg
board/batocera/raspberrypi/rpi4/genimage.cfg
board/batocera/rockchip/odroidgoa/genimage.cfg
board/batocera/rockchip/rk3288/miqi/genimage.cfg
board/batocera/rockchip/rk3288/tinkerboard/genimage.cfg
board/batocera/s812/genimage.cfg

The current batocera debug image for odroidgoA is over 1 GiB (1.1 GiB to
be precise), so the upgrade fails.
Increase the partition sizes for all the boards that previously used 1899.
Signed-off-by: Gleb Mazovetskiy <glex.spb@gmail.com>

Increase partition sizes (1899 -> 2515 MiB)

---

package/batocera/core/batocera-system/Config.in

aarch64 is not yet supported:
https://github.com/ricrpi/mupen64plus-video-gles2n64/issues/29

Disable MUPEN64PLUS_GLES2 on aarch64

---

board/batocera/rockchip/odroidgoa/linux_patches/0001-BACKPORT-arm64-don-t-zero-in-__copy_from_user-_inato.patch
board/batocera/rockchip/odroidgoa/linux_patches/0001-perf-cs-etm-fix-duplicate-def-of-traceid_list.patch
board/batocera/rockchip/odroidgoa/linux_patches/0002-perf-bench-Share-some-global-variables-to-fix-build-.patch
board/batocera/rockchip/odroidgoa/linux_patches/0003-perf-Make-perf-able-to-build-with-latest-libbfd.patch
board/batocera/rockchip/odroidgoa/linux_patches/0004-tools-lib-api-fs-Fix-gcc9-stringop-truncation-compil.patch
board/batocera/rockchip/odroidgoa/linux_patches/0005-Clean-the-new-GCC-9-Wmissing-attributes-warnings.patch
board/batocera/rockchip/odroidgoa/linux_patches/0006-nf_conntrack_core-Fix-gcc-10-compilation.patch
board/batocera/rockchip/odroidgoa/linux_patches/0007-wlcore-debugfs-Remove-unused-variable-res.patch
board/batocera/rockchip/odroidgoa/linux_patches/0008-usb-ehci-avoid-gcc-10-zero-length-bounds-warning.patch
board/batocera/rockchip/odroidgoa/linux_patches/0009-gcc-10-warnings-fix-low-hanging-fruit.patch
board/batocera/rockchip/odroidgoa/linux_patches/0010-Fix-joystick-analog.c-GCC-10-Wrestrict-warning.patch
board/batocera/rockchip/odroidgoa/linux_patches/0011-drivers-net-phy-mdio_bus-Fix-gcc-10-Wrestrict.patch
board/batocera/rockchip/odroidgoa/linux_patches/0012-drivers-net-wireless-Fix-gcc-10-Wrestrict.patch

Also sent upstream https://github.com/hardkernel/linux/pull/410
The kernel builds with these patches and aarch64
linux-tools perf also builds

odroidgoa kernel gcc-10 patches

---

package/batocera/gpu/mali-g31-gbm/mali-g31-gbm.mk

There is an issue with newer libmali versions that causes SDL2 to segfault https://github.com/rockchip-linux/libmali/issues/67

mali-g31-gbm: Downgrade to fix crash

---

batocera-Changelog
package/batocera/emulators/wine/wine-lutris-wow64_32/wine-lutris-wow64_32.mk
package/batocera/emulators/wine/wine-lutris/wine-lutris.mk

Stable build of Lutris wine based off Wine 6.0.
This builds fixes some issues:
Occasional graphics freeze for a couple seconds
.NET not installing properly with Winetricks
missing sounds in Cyberpunk 2077
This Wine build provides support for Media Foundation through GStreamer and should offer a working out of the box experience for many games.

bump lutris

---

package/batocera/gpu/mali-g31-gbm/mali-g31-gbm.mk

The crash described in https://github.com/rockchip-linux/libmali/issues/67 has been fixed by https://github.com/rockchip-linux/libmali/commit/6141ad6e6f2d3eb38e7e0962f61b78510b2e2d2c.

mali-g31-gbm: Bump version

---

board/batocera/rockchip/odroidgoa/linux_patches/linux-rtl8723bu.patch

Patches the Odroid kernel for the RTL driver to detect the Edimax ID

Fixes Edimax EW-7611ULB wifi not being detected

---

package/batocera/network/rtl8192eu/0001-Fix-build-with-gcc-10.patch

Fix also sent upstream: https://github.com/Mange/rtl8192eu-linux-driver/pull/222

rtl8192eu: Fix build with gcc-10 (-Wrestrict)

---

package/batocera/core/batocera-scripts/scripts/batocera-systems

Support was added to PCSX ReARMed in https://github.com/libretro/pcsx_rearmed/pull/339
This is perhaps the best BIOS for PSX, see https://forums.libretro.com/t/psx-bios-from-psp-6-60-optimised-to-play-games-more-smoothly-but-how/16976
See also: https://www.duckstation.org/wiki/BIOS.
We're still missing some bioses here, notably the one found on PS3: duckstation supports it but not PCSX ReARMed (sent https://github.com/libretro/pcsx_rearmed/pull/498)

PSX: Add hash for PSXONPSP660.BIN BIOS

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py

Allow to use "Game name.bat" instead of "dosbox.bat".
"Game name.bat" is preferred over "dosbox.bat".
Currently it is impossible to specify any per game settings for libretro-DOSBox games because name of game options file is derived from "dosbox.bat" and is "dosbox" for all games.
This commit resolves this issue by allowing to use "Game name.bat" instead of "dosbox.bat". If "Game name.bat" is used libretro recognizes game name and using game options files becomes possible.
The "Game name.bat" must not contain ".pc" folder extension.

Per-game libretro DOSBox settings

---

board/batocera/rockchip/odroidgoa/linux_patches/linux-rtl8723bu.patch

Tested compile - definitely works
I used - make odroidgoa-pkg PKG=linux
Applying linux-rtl8723bu.patch using patch: 
patching file drivers/net/wireless/rockchip_wlan/rtl8723bu/os_dep/linux/usb_intf.c
INSTALL drivers/net/wireless/rockchip_wlan/rtl8723bu/8723bu.ko
>>> linux 30aa1268194d24461299d45f35bf4f4a48c461a7 Installing to images directory
/usr/bin/install -m 0644 -D /odroidgoa/build/linux-30aa1268194d24461299d45f35bf4f4a48c461a7/arch/arm64/boot/Image /odroidgoa/images/Image
install -D /odroidgoa/build/linux-30aa1268194d24461299d45f35bf4f4a48c461a7/arch/arm64/boot/dts/rockchip/rk3326-odroidgo2-linux.dtb /odroidgoa/images/rk3326-odroidgo2-linux.dtb
install -D /odroidgoa/build/linux-30aa1268194d24461299d45f35bf4f4a48c461a7/arch/arm64/boot/dts/rockchip/rk3326-odroidgo2-linux-v11.dtb …

fixed EDIMAX USB driver for Odroid GO Advance

---

board/batocera/fsoverlay/etc/init.d/S11share

That help for improve performance too. (Old kernel 3.x is supported too)
Can only be actived by user when compression is set ON
Have check all other options is good and have try perf too on RPI4 is pretty good.

Add Autodefrag (v30)

---

package/batocera/emulators/dosbox-x/dosbox-x.mk

Compile fine on all archs (tested with GCC 10)

Bump DosBox-X to 0.83.10

---

package/batocera/emulators/wine/wine-proton-wow64_32/wine-proton-wow64_32.mk
package/batocera/emulators/wine/wine-proton/wine-proton.mk

Change log :
- Previously in Experimental: Fixed Cyberpunk 2077 world sound issues
- Previously in Experimental: Improved controller support and hotplugging in Yakuza Like a - Dragon, Subnautica, DOOM (2016), and Virginia
- Nioh 2 is now playable
- Fixed black screen on focus loss in DOOM Eternal on AMD
- Restored VR support in No Man's Sky
- Voice chat in Deep Rock Galactic is now functional
- Better support for PlayStation 5 controllers
- Sound in Dark Sector is working now
- Fixed Need for Speed (2015) hang on AMD
- More fixes for game input being active while the Steam overlay is up

Bump Proton (31)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mugen/mugenGenerator.py

For safety we can leave both video options because if a game does not have the option present then it will take the other.

Fix Mugen v30 + Master

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-libretech-h5.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-miqi.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidn2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-pc.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-zero2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rock960.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rockpro64.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s812.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s905gen3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-tinkerboard.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-vim3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults.yml

- Alphabetically order systems
- Change FSUAE by default by PUAE
- Let Amiberry for boards less powerful than PI3b+

Configuen Default Emu Update

---

batocera-Changelog
board/batocera/amlogic/odroidc2/genimage.cfg
board/batocera/amlogic/odroidc4/genimage.cfg
board/batocera/amlogic/odroidn2/genimage.cfg
board/batocera/amlogic/s905/genimage.cfg
board/batocera/amlogic/s905gen3/genimage.cfg
board/batocera/amlogic/s912/genimage.cfg
board/batocera/amlogic/vim3/genimage.cfg
board/batocera/libretech-h5/genimage.cfg
board/batocera/odroidxu4/genimage.cfg
board/batocera/orangepi-pc/genimage.cfg
board/batocera/orangepi-zero2/genimage.cfg
board/batocera/raspberrypi/rpi/genimage.cfg
board/batocera/raspberrypi/rpi3/genimage.cfg
board/batocera/raspberrypi/rpi4/genimage.cfg
board/batocera/rockchip/odroidgoa/genimage.cfg
board/batocera/rockchip/rk3288/miqi/genimage.cfg
board/batocera/rockchip/rk3288/tinkerboard/genimage.cfg
board/batocera/rockchip/rk3399/rock960/genimage.cfg
board/batocera/rockchip/rk3399/rockpro64/genimage.cfg
board/batocera/s812/genimage.cfg
board/batocera/x86/genimage.cfg

This is a cleaner way to get the 4k block size
mke2fs will now use the default profile as a result
This avoids large drive not resizing properly.
Tested on multiple drive sizes.
Please add to v30 also.

Increase the /userdata partition to 512MB

---

package/batocera/core/batocera-settings/batocera-settings.hash
package/batocera/core/batocera-settings/batocera-settings.mk

Adds support for UTF-8 byte order mark. https://github.com/batocera-linux/mini_settings/commit/4ca2be9c688b2f6a9e0c7d48c7b77ba18f1f004e
The config file should not contain them in the first place but it can happen with certain editors and is unintuitive for users to diagnose.
Reported in https://forum.batocera.org/d/5391-bluethoot-stopped/4

Bump batocera-settings to 0.0.3

---

package/batocera/emulators/supermodel/003-fix-r3dshadertriangles-mesa.patch
package/batocera/emulators/supermodel/supermodel.mk

Worth cherry-picking for 30 or if we do a 30.1 release

Fix for Supermodel shaders (no geometry) using Legacy3D or New3D without Quad

---

board/batocera/x86/fsoverlay/etc/X11/xorg.conf.d/20-amdgpu.conf

Now it won't prevent other GPU's getting to X

fix the AMD tearing fix to be GPU specific

---

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py

Too many `es_launch_stderr.log` files are shared for troubleshooting purposes without prior password editing.

Hide RetroAchievement password from es_launch_stderr.log

---

package/batocera/core/batocera-scripts/scripts/batocera-store

With `pacman -Sw` launched as a background process, `$?` was actually the return from the previous command, not what we want here.

Fix a bug when downloading large packages from ES (need to install twice)

---

board/batocera/fsoverlay/etc/init.d/S02resize
package/batocera/core/batocera-scripts/scripts/batocera-install

I tested on 2 different SDCards (64 and 128GB) and got an issue with resizing on v30, making the second partition unusable on other Linux machines (even other Batoceras!). Not sure if that is the case for **all** SD cards, but to reproduce:
1. Install a fresh Batocera
2. Boot, let the "Resizing partition" process happen
3. Everything seems to be fine, but if you mount this new resized partition into another Batocera box (for example, to copy ROMS), you have the following behavior:
3.1 By default, only the system partition is mounted (`/dev/sda1` on `/media/BATOCERA` with type `vfat`, but no `/dev/sda2` in my case)
3.2 Try to force it with: `# mount -t ext4 /dev/sda2 /tmp/oga/`
```
mount: mounting /dev/sda2 on /tmp/oga/ failed: Invalid argument
```
3.3 `# sgdisk /dev/sda`
``` Found invalid …
```

Fix resize (making the 2nd partition unusable on other OSs)

---

package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm

Issue explained in https://github.com/batocera-linux/batocera.linux/issues/3357 
The new voodoo sed command puts the progressive resolutions (1920x1080) above interlaced (1920x1080i) in the ordered list.

Fix: RPi4 favored interlaced over progressive video modes

---

board/batocera/patches/sdl2/sdl2_disable_gamepadmapping.patch

this is new in sdl2, but obviously, the temporary
open/close functions to get the BTN_GAMEPAD value erase the hwdata values.
https://www.kernel.org/doc/html/v4.15/input/gamepad.html

disable sdl2 gamepad mapping

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-libretech-h5.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-miqi.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidn2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-pc.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-zero2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rock960.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rockpro64.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s812.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s905gen3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-tinkerboard.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-vim3.yml

Tested on PI3 PI4 PC, better with option at false
Like write in LIBRETRO doc here:
https://docs.libretro.com/guides/troubleshooting-retroarch/#threaded-video
If your video driver has very bad performance, it is possible to run it on a thread to avoid almost all video driver overhead. Set video_threaded = true in config. Butter smooth VSync behavior in this case is impossible however, and latency might increase slighly. Use only if you cannot obtain full speed otherwise.

Users report problems with this option : Threaded video

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py

The commands needs to point to the RPG_RT.ldb inside the .easyrpg folder itself, currently it only pointed to the ".easyrpg" folder. Change tested on my end and working (I described it on discord, but let me say it there for reference) :
The core currently fails to launch the game (because the libretro core doesn't expect a folder, but a specific RPG_RT.ldb file inside a game folder), but due to how it works, it won't say "failed to load content", it'll just go to the main menu and display the "default folder" instead, and let you select a game (because the main menu, just like the standalone, expects a folder, I know, it's weird to explain), however that's not really optimal, doesn't support subfolders, and well, just isn't really in the spirit of Batocera, this change will make it load …

Fix the libretro command to launch the libretro-easyRPG core

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

EasyRPG (be it standalone, or libretro) doesn't support zip files as a valid path, I asked on the discord how to make it so ES wouldn't show zip files anymore, and the es_systems.yml file seems to be the way.
I also added a comment about how to use a game inside easyrpg in Batocera.
Be aware that while I asked, I don't know anything about compiling batocera, or generating the es_systems.cfg itself. So while the need to remove the zip files is there, and a description for the games is also needed (nobody distributes a .easyrpg folder, as it's a batocera thing), consider I didn't test this myself, and I only ended up doing this pull request myself because I want to practice making PRs as getting familiar with it could help writing docs down the road. (And I know not testing is frowned upon, …

Removing .zip files from the supported extensions for EasyRPG.

---

package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth

Due the removal of shift operator, remove operation now needs two arguments setted.
Just a minor fix
Caused by https://github.com/batocera-linux/batocera.linux/pull/3461

Fix: batocera-bluetooth script - remove of devices

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
package/batocera/emulationstation/batocera-es-system/es_features.yml

I tried adding a new option to ES after some discord reports mentioned the Synchronous Rendering in libretro-flycast had a performance impact for the xu4 (Actually, I asked @nadenislamarre on discord if I could try it, and he gave me instructions), testing on my own batocera PC worked, however I have a doubt regarding the change made specifically for xu4 (which is a device I don't have myself), as I'm not sure I made it correctly (the configgen-defaults files aren't making completely sense for me), if anyone can look and tell me if the changes I made are correct or not, I'd appreciate it.
As usual, consider I am not familiar with the way scripts work, and that something "obviously wrong" might not be seen by me, especially since I cannot compile batocera, so the .yml files are edited by …

Libretro-Flycast synchronous rendering option in ES

---

package/batocera/core/batocera-system/Config.in

wpa_supplicant now requires drivers to be explicitly enabled.
this change will allow connman to scan & discover wifi properly again.

Fixes wifi after latest BR bump

---

package/batocera/utils/pacman/batocera-makepkg

zstd is faster than xz and has a better compression ratio - noticeable in large packages, like the latest EasyRPG package put on the content downloader.

Switch pacman packages to zstd (+minor fixes)

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

Fix amiga and msx 'groups' wrongly added to 'System' hardware type instead of 'Computers' when using Hardware Ordering in Emulation Station
Before fix :
After fix:

Fix hardware type ordering for amiga and msx

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

Otherwise the forced "custom" keeps the aspect ratio at 4:3, not 3:4 (correctly detected by "core").

Fix vertical bezels in 720p (ex: arkanoid/lr-mame2003+ with theBP)

---

package/batocera/core/batocera-scripts/scripts/batocera-resolution.basic

Avoid an ugly:
```
/usr/bin/batocera-resolution currentMode
/usr/bin/batocera-resolution currentResolution
error: invalid command minTomaxResolution-secure
```
when invoking /etc/init.d/S31emulationstation on OGA and other archs that use the "basic" version of this script.

Cosmetic fix (error message in S31emulationstation for OGA...)

---

package/batocera/emulators/python-pygame2/Config.in

Fixes one of the issues on https://github.com/batocera-linux/batocera.linux/issues/3469 (Pygame not launching anything)

Missing dependency on pygame with Python3

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

The sentences "Test play mode" and "Game encoding" aren't very easy to understand for people that didn't use EasyRPG before.
(Once again, a minor change so I can look at the "contributing to batocera" wiki page and edit it).

Edited the ES description of the easyrpg-player standalone features.

---

package/batocera/utils/batocera-wine/batocera-wine

Add exe install support
Add exe silent install support
Fix regs import
Remove FS controle for make simple the script and improve speed.
With this pr user have possibility to install simply .exe for redist or dll on games.
Just need to put on /userdata/system/wine/exe
This is for improve and help user for non use ssh for all tweak.
Tested work on v31.

Improve batocera-wine

---

board/batocera/fsoverlay/etc/init.d/S65values4boot
package/batocera/core/batocera-splash/S03splash-mpv.template
package/batocera/core/batocera-system/batocera.conf

Tested and valitated by user RION
Option can be set to `batocera.conf`
Only values 0,1,2,3 are valid and build the multiples of 90
Other values will be ignored
Only mpv is supported so far (more to come if there is demand)

add: Splash video rotation for mpv (mainly x86)

---

Makefile

Working dir was set before. Why do you need to override it?

makefile: revert change to -shell working dir

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py

FAudio is not available now in v31.
Also OpenAL support buffering too and sound is OK
And OpenAL is recommend by RPCS3.
Tested on v31 sound is OK with rayman too.

Switch to OpenAL (Fix Sound Message in v31)

---

package/batocera/emulators/retroarch/libretro/libretro-atari800/libretro-atari800.mk

Added new system options for modern Atari XL/XE with 576 or 1088KB

bump: libretro-atari800

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/emulators/duckstation/psx.duckstation.keys

- Add the emulator options to ES
- Stop to use "fullboot" global option
- Stop to use "internal_resolution" global option

Duckstation ES options

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

- Move Zoom mode for all Amiga machines
- Add all the new Zoom mode and the AUTO one
- Put the Auto zoom by default, it fit the screen perfectly
- Add one CD32 missed Model
- Add the "Floppy Turbo" option to Amiga 500

Libretro PUAE options Update

---

package/batocera/emulators/duckstation/duckstation.mk

To permit to use fine "rumble" now we have the option in ES
https://github.com/stenzek/duckstation/commit/deeb8619182d6c935a866de0f9929dbadbbd74d3

Bump duckstation (Fix rumble)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

DOLPHIN
- Add Wii and GC rom path
- Remove "internal_resolution" old option and replace by the new es_features system with real values
PCSX2
- Remove old "fullboot" and replace by the new es_features system
- Remove "internal_resolution" old option and replace by the new es_features system with real values
- Add "games cheat" option
- Add "widescreen patches" option
- Add "automatic gamefixes" option
- Add "manual gemefixes" with "VuAddSubHack" hack for @liberodark
PPSSPP
- Remove "internal_resolution" old option and replace by the new es_features system with real values
- Add "Anisotropic filtering" option
- Add "Texture scalling level" and "type" option
- Add "Texture Deposterize" option
I have try to add "Vulkan" backend, but it not works for now
WII
- Remove "emulated_wiimotes" old …

ES Options Cleanup 2 + Updates

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-libretech-h5.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-miqi.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidgoa.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-zero2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3399.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rock960.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi1.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s812.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s905gen3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-tinkerboard.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-x86.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults.yml

Mupen64Plaus MK2 is the best video plugin used by all these boards :
libretech-H5, Miqi, OdroicC2, OdroidC4, OdroidGOA, Odroidxu4, OrangePi-Zero2, Rk3399, Rock960, Rpi4, S812, S905, S905-gen3, S912, Tinkeboard, PC86 & 64
Now we also have video options for this plugin in ES, the best choice is to put it by default.
To make sense with Discord discussion and this comit
https://github.com/batocera-linux/batocera.linux/pull/3703

Update default N64 core

---

batocera-Changelog
board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc
package/batocera/emulationstation/batocera-emulationstation/S31emulationstation

- rename es.maxresolution to es.resolution
- now instead of taking a maximum wxh value, takes a value
from batocera-resolution listModes
this can be a fixed resolution (thus more precised than the previous way)
or a max-640x480 or any value

es.resolution as mode in batocera-boot.conf

---

package/batocera/emulators/citra/citra.mk

copy command will now work for the bespoke key file used in Citra make

Fix Citra not building

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/emulators/dolphin-emu/006-nicerlaunch.patch

not sure it works while i were not able to reproduce.
but now, there is only one window to close, so it should
be ok.
moreover, hide the menubard and tool bar and empty list message at boot

fix dolphin exit 2 times

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
package/batocera/emulators/duckstation/psx.duckstation.keys

* Fix Duckstation bad filename with the first CD one of the m3u (no more tempm3u but the filename for the 1st CD)
* Also invert shortcuts for L1 and R1 (mistake between pagedown and pageup)

Duckstation-Fix m3u bad memorycard name and Shortcut Hotkeys

---

package/batocera/core/batocera-settings/batocera-settings.hash
package/batocera/core/batocera-settings/batocera-settings.mk

Allows `batocera-settings-set` to be used with `/boot/config.txt`.
Fixes #3349
https://github.com/batocera-linux/mini_settings/commit/32d05a4bfaa6110fc80b49c0e9dbf7dfeb08fcf6

Bump batocera-settings to 0.0.4

---

package/batocera/utils/pacman/004-xmloutput.patch
package/batocera/utils/pacman/005-architecture.patch

This is for Linux-native games in Ports. We can't filter them out based on sys-ports, because you'll have the same system on x86_64 and ARM boards. So, we need to differentiate them with this new tag `<arch>` that matches that pacman package architecture.
Example: the quake shareware files are independent from the arch, while the Linux-native 86_64 game super-tux-kart should be listed only for x86_64:
```
<package>
<name>ports-quake-shareware</name>
<repository>batocera</repository>
<available_version>1.0.0-4</available_version>
<description>Quake game files (shareware version)</description>
<url>https://www.dosgamesarchive.com/download/quake/</url>
<packager>lbrpdx</packager>
<download_size>15431</download_size>
<installed_size>28164</installed_size>
<arch>any</arch> …
```

Add <arch> in pacman XML to filter out arch-specific ports.

---

package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.hash
package/batocera/emulators/wine/vkd3d-proton/vkd3d-proton.mk

That only fixes :
```
Improved support for older Wine and Vulkan Loader versions.
Fix blocky shadows in Horizon Zero Dawn.
Fix the install script failing on Wine installs not built with upstream vkd3d.
Fix minor dxil translation issues.
```
Most important fix is : 
`Improved support for older Wine and Vulkan Loader versions.`

Bump VKD3D-Proton

---

package/batocera/utils/winbtrfs/winbtrfs.hash
package/batocera/utils/winbtrfs/winbtrfs.mk

Only fixes : 
```
Fixed deadlock on high load
Fixed free space issue when installing Genshin Impact
Fixed issue when copying files with wildcards in command prompt
Increased speed of directory lookups
```

Bump WinBTRFS

---

package/batocera/emulators/duckstation/004-savestate-pathandnames.patch

fixing "memcards" = 8 car not 7 !

Duckstation - fixing bad memcards patch

---

package/batocera/core/batocera-audio/alsa/asoundrc-dmix+softvol

Required for Sega Model 2 emulator to work under Wine
- Tested aroundrc fix with multiple x86 systems & RPI4
- Requires further discussion or testing

Fix asounrc causing Wine to crash with Sega Model 2

---

board/batocera/rockchip/odroidgoa/linux_patches/0013-rg315p-battery.patch

Fix the percentage of the rg351p/m battery by applying the patch from 351ELEC.
I hope this does no harm to the other odroidgoa devices.
Patch from: https://github.com/351ELEC/351ELEC/blob/d81407396baca679224c183de0b7da1ab232d9e1/projects/Rockchip/devices/RG351P/packages/linux/patches/02-rg351p-luali.patch#L5907

Fix for battery percentage on rg351p with patch from 351ELEC

---

board/batocera/raspberrypi/rpi4/boot/config.txt
board/batocera/raspberrypi/rpi4/fsoverlay/etc/init.d/S03checkbootconfig

This will help users that have panels not fully supported by the 'full' KMS driver yet
As per - https://github.com/batocera-linux/batocera.linux/issues/3717
Also sets the max_framebuffers to 1 so people with dual displays don't run into issues (not supported with ES etc)
Created [DPI] section for users with these various panel configurations.
Note: Raspberry Pi OS still uses fake KMS by default even with March 2021 release.

updated boot vc4 checks and more verbose info in the config.txt file

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppGenerator.py

Like asked here :
https://github.com/batocera-linux/batocera.linux/issues/3866
I have try it and working fine, the mouse is auto hidden in game.

Fix the mouse missing in PPSSPP config menu

---

package/batocera/core/batocera-scripts/scripts/batocera-store

This is a pre-requisite to:
- distribute retroarch cheat files as pacman packages and adress https://github.com/batocera-linux/batocera.linux/issues/3872 with all cheat files in /userdata/cheats
- remove snake.pygame currently broken and replace it with retrotrivia in v31, which is already distributed through pacman

Don't fail if pacman overwrites existing data in /userdata/

---

board/batocera/raspberrypi/rpi3/boot/config.txt

Keeping this option in the rpi3 config.txt file can confuse the user as the KMS is not enabled for rpi3 yet.

rpi3: config.txt

---

package/batocera/core/batocera-system/Config.in

rpi4: disabled libretro-swanstation

---

package/batocera/emulators/duckstation/004-savestate-pathandnames.patch

I noticed an extra character in the save memcards folder.
It actually works but it's not the right way to be written as a path

Duckstation - Fix Extra Memcards Chr Path

---

package/batocera/utils/pacman/batocera-makepkg
package/batocera/utils/pacman/batocera-pacman-batoexec

Would be nice to cherrypick to Batocera 31 to support packages that have more than one .BATOEXEC, and to make packages for the new systems in V31 that were not added yet.

Pacman: support for multiple .BATOEXEC1, .BATOEXEC2... per package

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/wine/wineGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Add option in ES for Select Mouse Yes or No for windows games.
For fix issue from forum.
By default is mouse is enable in (auto)
Tested work on by Games & Systems

Fix force Mouse in Windows Game (v31+v32)

---

package/batocera/core/batocera-settings/batocera-settings.hash
package/batocera/core/batocera-settings/batocera-settings.mk

Disables file validation by default for the `batocera-settings-get` command. This allows (limited) usage with /boot/config.txt. Refs #3349
https://github.com/batocera-linux/mini_settings/commit/b9822f8f8aaafbc46cf9123f3b3e10d9b0d523ac

batocera-settings: bump to 0.0.5

---

package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/utils/batocera-wine/batocera-wine

Issue link : https://github.com/batocera-linux/batocera.linux/issues/3993
Issue link : https://forum.batocera.org/d/5867-a-game-stopped-working-on-v31
Tested on my side OK
Tested by user OK

Improve Wine (v31+v32)

---

package/batocera/core/batocera-scripts/scripts/batocera-es-theme

Sadly the method to obtain real filesize is broken
Maybe we can add this info to theme database then.
The JSON-hack to report filesize is and was always wrong :(
@lbrpdx What do you think about adding the filesize to the theme.txt?
It can be done by cronjob automatically and this will also prevent themes from showing in the rooster if they are not available anymore.

fix: batocera-theme (faster download, but wrong filesize now)

---

package/batocera/emulators/retroarch/retroarch/014-cheevos-sounds.patch
package/batocera/emulators/retroarch/retroarch/retroarch.mk
package/batocera/emulators/retroarch/shaders/slang-shaders/slang-shaders.mk

- ALSATHREAD: Make alsathread default for all ALSA devices with threads
- ARCHIVE: Fix loading of archived content with file names containing '#' characters
- CHEEVOS: Upgrade to rcheevos 10.1
- CHEEVOS: Challenge indicators
- CHEEVOS: Group achievements by category in quick menu
- CHEEVOS: Relabel 'Start Active' with 'Encore Mode'
- D3D10: Window title should now update
- D3D11: Window title should now update
- D3D11: Allow fastforward in fullscreen
- D3D12: Window title should now update
- D3D12: Allow fastforward in fullscreen
- CRT/SWITCHRES: New implementation
- FONTS: Improve message wrapping with CJK languages
- FONTS: Fix garbled characters when converting encodings
- INPUT: Allow the 8 analog stick directions to be used as keys for core keyboard mappings
- LIBRETRO: Add API …

bump: retroarch to v1.9.5

---

board/batocera/fsoverlay/etc/profile.d/20-alias.sh

Without -c parameter mc is in black and white. At least on PuTTY with UTF-8 character set and VT100 line drawing.

modern terminal: mc in color

---

package/batocera/core/batocera-scripts/scripts/batocera-store

there is still an issue i won't handle in the py:
SigLevel is present several times by pacman-conf (fresh install)
[options]
RootDir = /
DBPath = /userdata/system/pacman/db/
CacheDir = /userdata/system/pacman/pkg/
HookDir = /etc/pacman/hooks/
GPGDir = /etc/pacman.d/gnupg/
LogFile = /userdata/system/pacman/pacman.log
Architecture = gameforce
CheckSpace
DisableDownloadTimeout
ILoveCandy
CleanMethod = KeepInstalled
SigLevel = PackageOptional
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
[batocera]
Usage = All
Server = https://store.batocera.org/

fix configparser store list

---

board/batocera/rockchip/odroidgoa/linux_patches/0013-rg351p-battery.patch

Modify RG351P battery percentage fix to affect only RG351P.
Current fix for RG351P battery percentage makes battery percentage incorrect on Odroid Go Advance.
This updates the fix to work only on RG351P.
I have tested this on Odroid Go Advance Black Edition and battery percentage is shown correctly.
@konsumschaf Can you please test this on RG351P? The battery percentage should show correctly. Because filename 0013-rg315p-battery.patch had typo I renamed it to 0013-rg351p-battery.patch before modifying.

ogoa: Fix for OGOA battery percentage

---

board/batocera/rockchip/odroidgoa/fsoverlay/usr/share/batocera/configgen/scripts/governor.sh

Set GPU and DMC governors based on system.cpu.governor setting value
Depends on ab37cb607d160b08ddf0746d831681ff86378d6d
Partially resolves #4084

ogoa: use system.cpu.governor for GPU and DMC

---

package/batocera/core/batocera-audio/alsa/batocera-audio

Work on batocera in cli
No need to restart anymore for change sound card
For ES need to disable SDL AUDIO Deinitialized (not need for pw that crash the sound)
This version is only for PW
thank for your help in this PR @lbrpdx

Improve batocera-audio

---

package/batocera/utils/batocera-wine/batocera-wine

Allows the language to be changed per game for WINE. Needed for certain older Windows Unicode games (mostly Japanese). If not used, games with Unicode filenames may fail to launch, and other games may display text incorrectly. May require additional fonts to be installed via Winetricks, depending on the game.
Add a line to the game's autorun.cmd formatted as LANG=[language code]. For example, "LANG=ja_JP.UTF-8" will set the game to use Japanese.
Tested under v31 as WINE is currently broken in v32. batocera-wine had no changes between versions.

WINE Locale

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py

Several changes to default MAME standalone default controls:
Default for Joystick will be both D-Pad & left analog
For dual stick games, Left Joystick was being set to use the right analog, corrected that to duplicate single joystick
Right Joystick was unmapped, will use right analog & face buttons in proper UDLR directions
Tested on v31 with an 8BitDo Pro controller set to xinput mode. D-pad/left analog controls worked properly in all games, Left/Right sticks & buttons worked properly in Robotron 2084.
Required modifying the input2definition function to pass the joystick code as a variable in order to get the OR functions working properly.
May require additional testing with other controller types (stickless) and multiple controllers. It's likely the detection for stickless controllers …

MAME Control Modifications

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/supermodel/supermodelGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/emulators/supermodel/supermodel.mk

Adds additional per-game/system settings to Supermodel:
Modern Pedal Controls
By default, accelerate and brake are mapped to left stick up/down. Activating this option will move those controls to L2/R2 with analog trigger support. The gearshift functions normally mapped to those are disabled, and the up/down shift (works on games with 2 & 4 position shifters) is mapped to both L/R and right stick up/down.
This creates an alternate template file at compilation that's called by the generator if the option is on.
Tested with 8BitDo Pro+ in XInput mode.
Adjust PowerPC Frequency
The default PowerPC frequency of 50MHz can cause issues with some games - ie. screen tearing in Sega Rally 2. Setting it to 100 fixes that. It can be lowered for some other games to improve performance on lower-end …

Supermodel Additional Options

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

When a "custom" system is added to EmaulationStation and it supports Retroachievements there is no simple way to enable them.
This adds` *.cheevos_force` option to `batocera.conf`.
For an example, setting this to `msu1.cheevos_force=true` enables that custom system to have Retroachievements without having to set all the options manually:
```
msu1.retroarch.cheevos_enable=true
msu1.retroarch.cheevos_hardcore_mode_enable=false
msu1.retroarch.cheevos_leaderboards_enable=false
msu1.retroarch.cheevos_verbose_enable=false
msu1.retroarch.cheevos_auto_screenshot=true
msu1.retroarch.cheevos_username=_USERNAME_
msu1.retroarch.cheevos_password=*************
msu1.retroarch.cheevos_start_active=false
```
Since I never used Python or modified Batocera before, hopefully all this makes sense.
This should …

Add an option to batocera.conf to force enable Retroachievements

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

According to RetroArch,
This option can be set to select the best colorful/appropriate value for the game.
I know it's an "auto" value, so **it's forbidden**
**BUT** this is an option that set different values to game  !
It must be possible to select it (I used it as default personnaly because I don't like the original green)
Exemple : 
Picross with this Auto value set a brown palette that is much more enjoyable 
Aladdin with this Auto set a Original green/yellow palette
Just to show you the differences : 
**Pokemon Blue**
Disabled:
<a href="https://www.imagebam.com/view/ME2M8T1" target="_blank"><img src="https://thumbs4.imagebam.com/ed/c2/7a/ME2M8T1_t.png" alt="pokdisabled.png"/></a>
Internal - GB Pocket:
<a href="https://www.imagebam.com/view/ME2M8SZ" target="_blank"><img …

Gambatte - Smart Coloring and Disabled

---

package/batocera/utils/rpigpioswitch/rpi-argonone.py

I did some looking into issue #4328 since I recently bought another argon one v2 case but decided to install batocera instead of retropie. This fix seems to address the fan issue and the power light lingering issue. Previously I was experiencing the same issues everyone else was having: fans turn on very briefly at start but then never turn on again, and power lights would not go out completely on shutdown.
I looked at the original argon shell script found [here](https://download.argon40.com/argon1.sh) to compare with rpi-argonone.py in batocera. I noticed that write calls to bus were slightly different; the official script uses `bus.write_byte` and the batocera script uses `bus.write_byte_data`.
I stopped the rpi-gpioswtich script, opened a python3 term, and tried making calls over the …

Fix issue #4328: Argon One V2/M.2 cases don't work

---

package/batocera/core/batocera-splash/Ssplash-ffplay
package/batocera/core/batocera-splash/Ssplash-image
package/batocera/core/batocera-splash/Ssplash-mpv.template
package/batocera/core/batocera-splash/Ssplash-omx
package/batocera/core/batocera-splash/Ssplashscreencontrol

add: deamon
add: extensible filemask for video and image files
removed: sync to /boot/splash
add: use /userdata/splash for user videos/images (limited by partition size now)
removed: loading in background mode (only aplayable for Pi1/0 now)

add: daemon-service for all splash services

---

board/batocera/fsoverlay/etc/udev/rules.d/99-onexplayer.rules
board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/core/batocera-scripts/scripts/batocera-resolution.xorg
package/batocera/core/batocera-splash/Ssplash-mpv.template
package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg

The OneXPlayer needs several changes to be supported properly:
- wifi6 needs last firmware (my previous PR already merged)
- controller needs a specific udev rule to be supported through xpad
- screen is rotated, so I changed the way we support screen rotation on PC (through batocera.conf only, no change in xinitrc any more as it's not resilient to Batocera upgrades)
- Also screen is natively 1600x2560 (on 8"4...) with no lower resolution available. I forced a 1920x1080:60Hz through batocera-boot.conf with a new command in batocera-resolution to support this.
I'll write a wiki article to explain how to make it work. Result: https://batocera.org/users/lbrpdx/OneXPlayer_480.mov

Support for OneXPlayer + changes tate mode on PC

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py

DOSBox Pure does not need .bat file.
It displays startup menu if more than 1 executable is in game folder.
DOSBox Pure uses name of .bat file for per-game settings.
With this commit "dosbox.bat" will be specified in command line only if it exists and "Game name.bat" does not exist.
This allows to have per-game settings when no .bat file exists in game folder.

Per-game libretro-DOSBox-pure settings by default

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/emulationstation/batocera-es-system/es_systems.yml

Adds two additional features to gb2player/gbc2player:
* Allows the use of two different ROMs (ie Pokemon games)
* Allows syncing the 2 player save files with gb/gbc single player saves.
For 2 roms:
* Create a text file named [game name].gb2 - ie Pokemon Red & Blue.gb2
* Add 2 lines to the text file. If you are using ROMs in the current gb2player/gbc2player folder, then each line should just be the file name.
* If you are using ROMs from your gb/gbc ROM folders, prefix the name with gb: or gbc:. So if you were loading Pokemon Crystal from GBC and Pokemon Yellow from GB, the two lines would be:
gbc:Pokemon Crystal.zip
gb:Pokemon Yellow.zip
For save syncing:
* By default, it will be OFF to prevent overwriting any saves that may be wanted. It can be turned on per-game or per-system.
* At …

2 player Game Boy enhancements

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

Thanks to @darknior whom keeps tracking updates, 
he discovered that according to : https://github.com/libretro/FreeIntv/pull/64
Save States are enabled.
Testing via inbuilt retroarch/download cores, the save states works 👍 
I'm just adding it to the features.
Need to be bumped for complete support now

IntTV - Updating for Save State

---

board/batocera/fsoverlay/etc/init.d/S65values4boot
package/batocera/core/batocera-splash/Ssplash-ffplay
package/batocera/core/batocera-splash/Ssplash-mpv.template
package/batocera/core/batocera-splash/Ssplash-omx
package/batocera/core/batocera-system/batocera.conf

- reuse display.rotate option for splas
- all splash options in batocera.conf only (except splash.screen.enabled in batocera-boot.conf)

splash option cleaning

---

package/batocera/emulationstation/batocera-emulationstation/emulationstation-standalone

example:
add in batocera.conf :
es.customsargs=--screenoffset 50 100

custom es options via batocera.conf

---

board/batocera/amlogic/s922x/fsoverlay/etc/init.d/S02overclock
package/batocera/core/batocera-scripts/scripts/batocera-overclock

because boot.ini is erased at each update

n2 overclocking in batocera-boot.conf

---

package/batocera/emulators/retroarch/libretro/libretro-emuscv/003-remove-io-header.patch

For fix : 
```
In file included from src/emuscv.h:25,
from src/libretro.cpp:11:
src/common.h:125:14: fatal error: sys/io.h: No such file or directory
125 |     #include <sys/io.h>
|              ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.libretro:786: src/libretro.o] Error 1
In file included from src/emuscv.h:25,
from src/emuscv.cpp:10:
src/common.h:125:14: fatal error: sys/io.h: No such file or directory
125 |     #include <sys/io.h>
|              ^~~~~~~~~~
compilation terminated.
```

Fix SCV OGA Build

---

package/batocera/emulators/ppsspp/001-batocera-path.patch

And added a new `psp-ppsspp-cheats` package in the Batocera Content Downloader to make it easier to install/manage.
Fix for #4398, thanks @wadiebs for the report!

Fix PPSSPP cheats location

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py

Sound buffer size value changed from 8192 (default value. Shows as 8 on Amiberry menu settings) to 4096 (as 4).
With this new value, it fixes the sound latency issue.
Tested and worked.

Amiberry - New sound buffer size value

---

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
package/batocera/core/batocera-configgen/configgen/configgen/Evmapy.py
package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/cannonball/cannonballGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinSYSCONF.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/fpinball/fpinballGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/fsuae/fsuaeGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/gsplus/gsplusGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/hatari/hatariGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/lexaloffle/lexaloffleGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/openbor/openborGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Controllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/solarus/solarusGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/tsugaru/tsugaruGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/settings/unixSettings.py
package/batocera/core/batocera-configgen/configgen/configgen/utils/logger.py
package/batocera/core/batocera-configgen/configgen/configgen/utils/videoMode.py

I was looking at a bug and the log files were confusing me due to stderr and stdout log files going all different directions; for example, the old configgen logger only output to stderr. This is an attempt to clean things up a little. There are still emulators with their own redirection issues (retroarch also only outputs to stderr) but at least configgen scripts are in a better place where a lot of logging happens. I tested the changes on Bato 31 on Pi4 and x64 systems. Logs look better in my eyes. There are a lot of changes so I didn't test everything but these changes are mostly just small refactors here and there. Feedback is definitely desired.
Main changes:
* Use Python3 logging with proper stdout/stderr streaming
* Refactor scripts to use module level logger, not root logger
* …

Improve configgen logging

---

package/batocera/emulators/ruffle/ruffle.mk

Reverts batocera-linux/batocera.linux#4422 as it doesn't compile

Revert "Bump Ruffle"

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

**Flycast:**
- Removed 12k internal resolution. Added 800x600, 960x720 and 1024x768. These resolutions don't affect performance on sbc like RPI3b+/RPI4 and are a good choice for a good hires image (I suggest to use max 960x720 on RPI. Higher resolutions makes graphical glitches)
**dosbox_pure:**
- Shortened controller names.
- Fixed controller type support. Now gamepad automatic mapping, pad2key and sticks type controllers works better (no analogs conflicts with own and dpad mapping that they work together)
**PUAE and Vice:**
- Forcing Digital-to-Analog to Left Analog. These cores don't support the new Digital-to-Analog mode on Retroarch. So they must be forced to value 3 (Left Analog)
**Flycast:**
- Added forcing Digital-to-Analog to Left Analog on Naomi and Atomiswave.
**Libretro …

Libretro - Fixing some stuff

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

- Removed all the TWB palettes, now unavailable with the new bumped version of gambatte, and substituted with "TWB64 Pack 1 and 2" (customizable via core options)
- Added "Special 4 (TI-83 Legacy)" palette

Libretro - Gambatte GB colorization fixed

---

package/batocera/core/batocera-system/Config.in

Of course, most 3D games won't run, but still useful to unlock retroachievements on several 2D games.

MelonDS back on RPi4 and OGS (cheevos + OK for some 2D games)

---

package/batocera/core/batocera-audio/alsa/batocera-audio
package/batocera/core/batocera-audio/alsa/batocera-audio-rk3326
package/batocera/core/batocera-audio/alsa/batocera-audio-rk3399

Fix syntax error in batocera-audio-rk3326 and batocera-audio-rk3399.
Fix formatting of setSystemVolume in 3 files.

batocera-audio: fix syntax error and formatting

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

The micro VU speedhacks can considerably improve performance, particularly MTVU. This option previously could only be toggled through the GUI via F1. This PR exposes the micro VU hacks and applies reasonable settings based on system requirements.
* Explicitly set speedhacks considered safe by the PCSX2 devs; these are already set in Batocera PCSX2 by default
* Expose all the micro VU hacks in the UI; use combinations to reduce menu entries
* On `Auto` setting, set micro VU speedhacks appropriately; 3+ cores required for MTVU, no invalid combinations, etc.
In my own tests, with MTVU enabled, ~20 FPS gain was achieved in God of War II on i5-6500 / GT 1030 and i7-6700 / GTX 960M systems. And so on `Auto`, Batocera will better configure capable systems without user involvement.
I think I have …

Enhancement: Expose PCSX2 micro VU speedhacks

---

board/batocera/scripts/doWineWow64-32package.sh
board/batocera/scripts/doWinepackage.sh
package/batocera/utils/batocera-wine/batocera-wine

With this pr batocera keep the compatibility & improve support for more modern root.
Little explain : 
The recent system is not the structure that we have now.
`/lib32`
Already in the root it is only symblinks for the lib's folders.
Arch Linux
```
/lib > /usr/lib
/lib64 > /usr/lib
```
Debian
```
lib -> usr/lib
lib32 -> usr/lib32
lib64 -> usr/lib64
libx32 -> usr/libx32
```
But don't have `/lib32`
It is less common and relevant for recent software such as wine pw or pulseaudio to look for x32 libs in `/lib32`
I think the best solution is to move `/lib32` to `/usr/lib32` where it is, this will allow us to be closer to modern structures.

Switch wow64 to /usr/lib32

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py

- Enabled "Double line mode" (No pixelated hi res images. Check Agony start screen or Team17 logo screen).
- Enabled "Remove interlace artifacts": Correct workbench and some games high-res laced screen mode flickering. Maybe it can create some conflicts with "Centering Vertical Screen" together enabled, but this happens in a very few games screen.
- Enabled "Auto Height" : Auto zoom, cutting excessive and useless vertical screen borders (like in PUAE, but only on vertical). Useful for handhelds or small screens. On 16:9 or wide aspect ratio you can see not a proper 4:3 screen with black borders, but is an normal thing. On 4:3 or 5:4 aspect ratio needed some test (unfortunately i don't have a 4:3 or 5:4 display screen)

Amiberry - Display corrections

---

package/batocera/core/batocera-triggerhappy/conf/multimedia_keys_Hardkernel_ODROID_GO3.conf

As of the latest beta/32dev version, using either the VOLUMEUP or VOLUMEDOWN key on OGS increases the volume. This should fix this (editing the file does for me at least.).
This is also a pull request meant to see if I remember how to do those.

Multimedia Keys edition for OGS

---

board/batocera/x86/fsoverlay/etc/X11/xinit/xinitrc
package/batocera/core/batocera-system/batocera-boot.conf

Add variable for AMD Dynamic Switchable Graphics to take amd-radeon gpu over intel cards when such hybrid cards are available.
I have a "HP ProBook 4740s" with Intel and AMD Radeon hybrid cards.
Now I am able to use the AMD Radeon card in Batocera.
I tested with .xinitrc in the home folder of root to overwrite /etc/X11/xinit/xinitrc and this works perfect.
If you need proof I can send screenshots.

Amd dsg for radeon

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Separate NES/FDS sprite limit and overscan settings.
Some people can like no sprite limit to be on and crop overscan to be off. Crop overscan in some games hides important info under on screen bezels. Separating settings allows better visibility without turning off bezels.

configgen: Separate NES sprite limit and overscan

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

PUAE:
- Added controller type selection.
There is a logical explanation for this: There are tons of games in whd format where there is precise mapping in case you are using a cd32 gamepad or a similar four button gamepad. Selecting the controller solves this problem. I also added other types of controllers, all explained here (taken from the libretro site):
```
RetroPad - Joypad - Standard one or two fire button joystick + customizable buttons with keyboard keys and hotkeys.
CD32 Pad - Joypad - Standard CD32 controller with unused buttons available for RetroPad extra mappings.
Analog Joystick - Joypad - Standard Analog joystick with unused buttons available for RetroPad extra mappings.
Joystick - Joypad - Standard one or two fire button joystick.
Keyboard - Keyboard - Keyboard input is …
```

Libretro - New stuff added

---

package/batocera/core/batocera-scripts/scripts/batocera-brightness

Maybe more straightforward than #4429 as this doesn't rely on `xrandr`/X11 and is suitable both for x86_64 laptops and handhelds like OGA/OGS and clones.

Fix for brightness on several laptops

---

board/batocera/fsoverlay/etc/init.d/S98xboxone
package/batocera/utils/xow/99-xow.rules
package/batocera/utils/xow/xow-daemon
package/batocera/utils/xow/xow.mk

This commit reverts the recent xbox dongle branch which breaks usb support and then adds the changes that I have been testing for the last two days.
I do not think everything is perfect given circumstances; xow is no long maintained and the behavior across systems varies a lot. It seems luck plays a part in how reliable xow is. However, I think these changes improve things and give xbox one controllers a better chance to run reliably on Batocera.
I would love if other people would test this and give feedback.
Changes:
* Update xow to latest commit
* Move modprobe conf file to proper location on build (this had the biggest impact on fixing things)
* Add ACTION to udev rule; this can help keep spurious events from happening
* Start daemon on boot if dongle detected and xow did not …

Really fix xbox one usb dongle

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Separate picodrive sprite limit and overscan settings.
Some people can like no sprite limit to be on and crop overscan to be off. Crop overscan in some games hides important info under on screen bezels. Separating settings allows better visibility without turning off bezels.
Similar PR for NES/FDS #4528

configgen: Split picodrive sprite limit, overscan

---

batocera-Changelog
package/batocera/emulators/retroarch/retroarch/retroarch.mk

Retroarch compiled on x86_64 + OGA, tested on OGA

Bump RetroArch 1.9.9 + fixes changelog

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

And back to default=64 by popular demand (@Rion and @Hew-ux actually)

Offer an option to change audio latency in ES (v32)

---

package/batocera/emulators/ecwolf/ecwolf.keys

Press START on PAD to jump back to main menu (via ESC press)
Not tested, but should work according https://github.com/crcerror/ECWolf-RPI/blob/master/ecwolf_keyboardpatch.diff
Or maybe include this patch?
Background:
On XBOX and PS3 the hotkey acts as ESC-button already and for these there is no additional key needed, 
But not all players have these controllers so it's better to keep a dedicated button to work.

fix: ecwolf back to main menu

---

package/batocera/core/batocera-splash/batocera-splash.mk

Since #4303 all devices got unmodified [logo.png](https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/logo.png) as "/usr/share/batocera/splash/boot-logo.png". On Odroid Go Advance and probably other devices with screen rotation it was displayed incorrectly.
This should fix it. On RK3326 devices [S03system-splash](https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/Ssystem-splash) will use "logo-version-wxh.png" with correct resolution. On other screen rotation devices it will use "logo-version.png" through symlink "boot-logo.png".
@crcerror @nadenislamarre

fix boot logo on devices with screen rotation

---

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py

Thanks to @iconoclusterdotexe for the analysis. It's an absolute game changer on OGA and RPi4 on many SDL-powered emulators.
If, for whatever reason, you need to disable it, you can do that in `batocera.conf`, with for example `mame.sdlvsync=0`. I did some testing on x86_64 and didn't see any regression.

Fix SDL VSync

---

package/batocera/emulators/pcsx2/pcsx2.mk
package/batocera/emulators/pcsx2_avx2/pcsx2_avx2.mk

* These missing files fix automatic game fixes and widescreen patches in standalone PCSX2
* I tested this on v.32 beta on i5-6500 with GT 1030
* I did not do testing with libretro-PCSX2 but it appears [they bundle these files in the core](https://github.com/libretro/pcsx2/pull/47)
* I am not sure why github is messing up the whitespace; looks good in `git diff` and vim

Fix pcsx2 auto game fixes and widescreen patches

---

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py

Proposition to fix issue #4130 and probably issue #3412
The joystick doesn't work on PPSSSP because of a problem in the gamecontrollerdb.txt : the dpdown value (a1) and the dpup value (a1) are the same, the two of them are positive. Idem for dpleft and dpright value (a0).
We need to respect the sign for dpad "axis" in order to have : dpdown:+a1,dpup:-a1,dpleft:-a0,dpright:+a0

fix issues #4130 and #3412

---

package/batocera/core/batocera-system/Config.in

As i said on developer channel on Batocera Discord server, it's unnecessary to have a core like beetle_psx that works good for an handful of games on RPI4. So, i want to revert its disabling.

Revert disabling beetle_psx on RPI4

---

package/batocera/core/batocera-configgen/configgen/configgen/controllersConfig.py

when a pad configuration is approximative in our database, the configName reflect the name of the pad in the database, while realName the hardware pad.

fix sdl pad : configName should not be used. Use realName instead

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/emulationstation/batocera-es-system/es_systems.yml

Expands the generator code and es_systems to accept both `.gb2` _or_ `.gbc2` file extensions for both the GB2Player and GBC2Player systems, reducing confusion and potential unnecessary future troubleshooting.

Add .gbc2 as an acceptable extension for both GB2Player and GBC2Player

---

package/batocera/utils/batocera-steam/batocera-steam

Work 
Tested on Proton Game OK (Cube World)
Tested on Linux Game OK (SOR4)
With this pr you support other languages than English. 
Step to reproduce run Steam Games from ES (not from Big Picture).
Because steam don't declare `Exiting app` but `Game process removed: AppID xxxxxx`
Actually this bug lock your screen and `batocera-es-swissknife --emukill` can't help you.
For simple user only reboot fix the issue.
For most advanced users you can run flatpak kill as batocera or just a steam -shutdown.
Im validating the fix on users
Free game for test : https://store.steampowered.com/app/1218210/Coromon/

Fix Steam Exit

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

Allows the user to use pad2key for access to these standalone programs' keyboard shortcuts which are otherwise inaccessible from controller. Suggest and tested by @Redemp (Rion on Discord).
Useful shortcuts: F9 in Citra to switch screens, ability to "Pause" in MAME (basically, set any shortcut you want).
For Citra, it might be better to implement this as a part of the config generator instead.

Add pad2key for MAME standalone custom user keyboard shortcut access

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/vice/viceConfig.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Better implementation for #4760

Option to hide borders on Vice C64 (now shown by default)

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml

Users have reported slow-down/audio cutting with default audio latency on Pi 4. Increasing audio latency slightly fixes it.
Alternative solution might be to change audio driver for RPi family, but no testing has been done. This is a sufficient workaround for now.

increase default audio_latency on Pi 4

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml
package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/emulationstation/batocera-es-system/es_systems.yml
package/batocera/emulators/mame/mame.mame.keys
package/batocera/emulators/mame/mame.mk

* Adds additional systems - Creativision, Game.com, Gamate, FM-7, Game Pocket Computer, APF M-1000, BBC Micro, Adam, Arcadia 2001, Game Master, Astrocade, Tomy Tutor, Tandy Color Computer, TI-99, & Mega Duck
* Added special controller mapping as needed for non-standard inputs (keypads on controllers etc)
* Added auto commands for computers that require loading after launch
* Also adds TV Games system for P&P TV consoles
* Adds Media Type per-game option for systems with multiple media types (cassette, disk, cartridge, etc)
* Adds toggle for UI mode for keyboard-based MESS systems
* Maps UI mode toggle to hotkey+up & scroll lock
* Adds an option for per-game config for keyboard-based systems (uses MAME's internal menu & config, creates a folder and does not overwrite existing configs in …

MESS Systems, Part 2

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml
package/batocera/emulationstation/batocera-es-system/es_features.yml

More testing with the new Ubershader settings from other users have come in, there are some situations where extremely low-end hardware (such as integrated graphics, legacy GPUs, SBCs) exhibit _more_ stuttering with Ubershaders on (this is what Ubershaders is meant to be fighting against). In light of this, I have changed the default behaviour in the config generator to not use Ubershaders and have added an exception to x86_64's defaults to use Asynchronous Ubershaders. For reference, my testing for this setting was done on both a low-end Nvidia 750Ti and a mid-range AMD Radeon RX 580 GPU, both of which displayed no more stuttering when Ubershaders were enabled. It is still possible for users of those extremely low-end hardware to manually turn off Ubershaders if they want to, but the …

Dolphin defaults adjustments

---

package/batocera/core/batocera-system/Config.in

After the update it is not compiling, disabled until it is fixed.

disabled sonic port for rk3326 and rpi

---

batocera-Changelog
package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/emulationstation/batocera-es-system/es_systems.yml

Adds the FM-77AV as an alternate model option under Fujitsu FM-7, since some games will only run on that model but it isn't emulated as accurately.

FM-77AV Support

---

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml

These values must be defined by platform, the result is not the same for everyone.

removed configgen defaults values

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

Instead of listing individual systems that support Cheevos in `systemToRetroachievements`, this lists all cores that support Cheevos in `coreToRetroachievements`.
List of supported cores was taken from https://docs.libretro.com/guides/retroachievements/#cores-compatibility
with addition of `ppsspp`, which is supported but WIKI was not yet updated.
This will avoid periodically adding systems to `systemToRetroachievements` and instead rely on which core is used to activate Cheevos. And also, if user has custom "Hack" or "Translation" systems added to ES, this will automagically activate Cheevos if supported core is used.
If this concept gets accepted, a bit more work is left to clean up `libretroConfig.py`.
This PR is just a suggestion so fell free to close it without merging.

Enable Retroachievements activation per Retroarch core

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/emulationstation/batocera-es-system/es_systems.yml

sgb supports Retroachievements
https://github.com/batocera-linux/batocera.linux/blob/c12fcaf55d06b06da5a4ba8c38c9b97049b04049/package/batocera/emulationstation/batocera-es-system/es_systems.yml#L269
satellaview
https://github.com/batocera-linux/batocera.linux/blob/c12fcaf55d06b06da5a4ba8c38c9b97049b04049/package/batocera/emulationstation/batocera-es-system/es_systems.yml#L1640
Fix bad c/p for Amiga 1200 FR comment

Add sgb and satellaview to systemToRetroachievements

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

Vulkan support on rk3326 removed because it doesn't work https://github.com/batocera-linux/batocera.linux/pull/4061

rk3326: option to vulkan removed (does not work)

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml

Alternative to the increased audio latency workaround I employed earlier: https://github.com/batocera-linux/batocera.linux/pull/4937 , iconocluster.exe has confirmed the tinyalsa audio driver performs better (no crackling) without needing the increased latency.
Fundamentally, the audio issue (crackling/distortion on default settings on RPi4) still needs to be sorted out, but this is a better workaround than what's currently employed.

RPi4 default settings: remove audio latency, replace with audio_driver: tinyalsa

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml

Alternative to https://github.com/batocera-linux/batocera.linux/pull/4662
In similar vein to https://github.com/batocera-linux/batocera.linux/pull/5009 , switching the audio driver to tinyalsa instead of increasing the audio_latency might work for RPi3 as well. But this needs testing and I don't have access to my Pi3 right now to do so. Will leave as a draft until then.

RPi3 defaults change from audio_latency to audio driver tinyalsa

---

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg

Changed hotkey for xbox360 controller from select to guide, as it is with the other xbox360 pad.
Renamed "X-Box" to "Xbox", corrected grammar on "Firmware 2015" to "2015 firmware".

Xbox360 guide button fix + rename

---

package/batocera/ports/sonic2013/sonicretro.sonic2013.keys
package/batocera/ports/soniccd/sonicretro.soniccd.keys

Update to recent keys cleanup - closes both emulators on hotkey + start (previous change killed Sonic CD exit). Modified both keys files to cover any unusual user settings.
This is a side effect of the generator auto-selecting the proper emulator, but that can't be avoided without complicating things for the end user.

Sonic Keys Fix

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

Adds `video_frame_delay_auto` from RetroArch 1.9.13: https://www.libretro.com/index.php/retroarch-1-9-13-automatic-frame-delay/
Discussion: https://discord.com/channels/357518249883205632/524321176068161554/907025124442648618
Complements https://github.com/batocera-linux/batocera-emulationstation/pull/1033
Unable to test currently as the latest RetroArch build has not been pushed to distribution. Have written the foundational code which should work when it does. Will convert to proper PR once tested.

Add auto frame delay to libretro config generator

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

This one "x" is actually a "×" character, whereas all the other entries use "x". Updating to make consistent.

es_features.yml single unicode character replacement

---

board/batocera/rockchip/rk3326/linux_patches/0011-wifi-security-fixes.patch

Fixes for FragAttacks and some other wifi security fixes.
All patch commits are from Linux kernel 4.4.
The new kernel https://github.com/shantigilbert/hardkernel-linux/tree/d167de7358c9c53d5e6592978f7cdde7674c420b and old kernel https://github.com/hardkernel/linux/tree/odroidgoA-4.4.y have the same contents in net folder (last commit hashes match). The patch file is the same that was used with old kernel.
This is tested on build with November 18 sources.

rk3326: readd kernel wifi security fixes

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

Dolphin supports playlists for multi-disc games and their automatic swapping. However, there is currently no way to manually swap a disc. This feature should still be available for the few that know how to use it, though. There is no harm is simply adding the extension to the list of accepted formats.

add "m3u" to dolphin

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinSYSCONF.py

Corrects mistake made in https://github.com/batocera-linux/batocera.linux/pull/5094 (which were kind of worked around in https://github.com/batocera-linux/batocera.linux/pull/5099 )
I hadn't realised that this setting was specific to only Wii games, not GameCube. I was testing a GameCube game to see my changes, so nothing wrong happened. This is why I have added the one comment to this function, to clarify what its intention is.
After further testing, I have uncovered an issue: sysconf fails to set the Wii's aspect ratio setting at all. No matter with the original code, my modified code, or the https://github.com/batocera-linux/batocera.linux/pull/5099 commit. Dolphin will always just use whatever was last set in its standalone config.
Being able to fix it is beyond me, but this PR will …

amend mistakes made with dolphinsysconf.py (even though it doesn't matter)

---

package/batocera/core/batocera-system/Config.in
package/batocera/utils/syncthing/syncthing.mk

Syncthing is now ported to ARM64, it probably also compile and works on ARM (32 bits) too but I have no device to test. Please let me know if it poses a problem.
Tested on OGA, with cross-sync between x86_64 and OGA. 
At the same time, I put rclone as experimental, I don't think we're ready to ship it yet. And honestly, synching is easy enough and should cover the need for saves sync up across Batocera devices.

Added syncthing to ARM64 SBCs (probably ARM 32 bits too)

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Allows the user to choose which SPU decoder they'd like to use. More info here: https://wiki.rpcs3.net/index.php?title=Help:Default_Settings All options have been tested and they work as intended.
Improvement to https://github.com/batocera-linux/batocera.linux/pull/5117

add SPU decoder selection to ES for RPCS3

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

In some circumstances auto frame delay can worsen stuttering
I think it should be off by default. Needs to be discussed. ❗ 
@Hew-ux @Redemp @iconoclusterdotexe

default auto frame delay to off

---

board/batocera/patches/sdl2/sdl2_force_modes_refresh.patch

As requested by @Redemp,. This should address https://github.com/libsdl-org/SDL/issues/4840 with CRT resolutions lower than 320x200 (patch ported from RetroLX).
Please confirm it works, I don't have any CRT screen to test.

Fix X11 crash for small CRT resolutions.

---

board/batocera/raspberrypi/boot/config_mesa3d.txt
package/batocera/core/batocera-scripts/scripts/batocera-overclock

The latest Pi4 firmware allows c0 stepping chips to be clocked at 1800MHz
- Pi400, Compute Module 4 & the latest Pi4 boards.
- The original boards using the B0 stepping will run at 1500Mhz 
Rename some of the overclock options as a result

pi4 config & overclock updates

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinSYSCONF.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

A couple of changes & explanation:
1. Dolphin doesn't support all the various aspect ratio's using the global ratio - so I have matched what's in Dolphin
2. Dolphin allows you to set a graphics ratio (as per 1) and also set the ratio for the Wii based on the TV type - so we create an option there too, thus match Dolphin's config option.
3. The Wii ratio is boolean: 0 = 4:3, 1 = 16:9, There are no other values for the SYCONF parameter
- see source code in Dolphin: const Info<bool> SYSCONF_WIDESCREEN{{System::SYSCONF, "IPL", "AR"}, true};
4. Pass the correct value to dolphinSYSCONF.py as per above
5. Fix the readString definition so it's a UTF-8 string & not a binary string - now it will write the updated value to SYSCONF correctly. i.e. 1 for 16:9 (if selected) rather than the default 0.

really fix Dolphin aspect ratio's

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/core/batocera-system/batocera.conf

Adds the option to turn off the challenge indicator icons in the bottom right of the screen when retroachievements are activated:
Complements https://github.com/batocera-linux/batocera-emulationstation/pull/1062

add option to enable/disable challenge indicators for retroachievements

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Adds the "skip draw" option to Ubershaders in Dolphin. Also renames the existing ones to match the option labels in `dolphin-emu-config`.
Since this option was added in this beta I think it's fine to rename the existing options to have them make more sense.

include "skip draw" option in ubershader + rename

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Spelling, grammar and corrections to most of the lines in the ES features YML.
Combines similar-enough lines to using the same phrase to avoid redundant translations.
Opted to use punctuation in the descriptive labels. Since most of these descriptions are full sentences, and some descriptions greatly benefit from being able to use multiple sentences, punctuation has been added to make things more consistent and easier to understand.
For MAME graphics backend change to Video Mode, the original description was not accurate in the first place. Refer to https://docs.mamedev.org/advanced/bgfx.html for what the `video` setting actually does.

es_features.yml spelling, grammar and corrections part 1

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

I think this was just a typo.
But this might also fix Mesen-S's options not appearing in the Game Boy's advanced system settings:
For reference, Mesen-S's options appear fine in the Super Game Boy system game list:

Fix mesen-s not having options in ES (probably)

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

I mean it's there we may as well use it. It's a cycle-accurate emulator that performs decently.
Already tested it and it works fine for regular SNES games.
Merge this after https://github.com/batocera-linux/batocera.linux/pull/5223

add mesen-s as a selectable emulator for SNES

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py

Avoids ps3 automatically using 4:3 ratio with bezels, cutting off the sides (ps3 games are widescreen by default).
Before this change:
After this change:

add default ratio to ps3

---

package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py

Better fix for https://github.com/batocera-linux/batocera-emulationstation/pull/1074

Fix emulatorlauncher.py for non-scraped games (empty -gameinfoxml)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py

Clean up the code from my previous fix, the two functions can be simplified into one by the presence of a simple if condition.
Change 'tattoo resize' option in ES to be a simple toggle.

tattoo code cleanup + resize functionality

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py

Default is 4:3 for Gamecube & Wii until Wii chooses 16:9 TV Mode, or the aspect ration is set other than 'auto'.
Updated the way we write the ini files too, Dolphin has removed the double quotes.

Fix Wii ratio detection for bezels

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

Set retroarch option to prevent displaying "QUICK MENU" with "No Items" after DOSBox Pure, TyrQuake or PrBoom game has exited.
A proper version of #4487, #4552, #4553 
This should not cause problems because it is setting RetroArch option and not doing code hacks.
@iconoclusterdotexe @crcerror

Exit DOSBox Pure, TyrQuake, PrBoom when games exit

---

README.md
board/batocera/README.md
package/batocera/README.md
package/batocera/core/README.md
package/batocera/core/batocera-configgen/README.md
package/batocera/core/batocera-configgen/configgen/configgen/README.md
package/batocera/emulationstation/README.md
package/batocera/emulationstation/batocera-es-system/README.md

To assist newcomer devs with navigating the source code. Descriptions have been kept brief and non-descript such that they won't need to be updated.
Folders whose labels are obvious or self-evident have been excluded.

add a bunch of directory navigation readmes

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

* Fixed CD-i config generation
* Fixed Q*Bert stick control generation
* Modified custom MAME config behavior - will now create a /custom subfolder in MAME or MESS system's config folder to maintain a separate copy.
* Moved alternate control options to MAME & Neo Geo systems only
* Corrected description for hotkey mode

MAME Config fixes & Improvements

---

package/batocera/emulators/retroarch/libretro/libretro-fceumm/libretro-fceumm.mk

Only one change in libretro-fceumm: Added A+B and Turbo A+B buttons
https://github.com/libretro/libretro-fceumm/pull/475
Tested on Batocera.

bump: libretro-fceumm

---

board/batocera/fsoverlay/etc/init.d/S08connman
package/batocera/core/batocera-system/Config.in

First, this PR fixes kernel error messages like:
> [    7.945594] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2 
> [    7.945604] cfg80211: failed to load regulatory.db 
Then, you can now add a 2-letter country code (ISO 3166-1 alpha-2) in `batocera.conf` to lookup the wifi regulatory settings for your country, like `wifi.country=US`, to fix some wifi issues.

Fix wifi regulatory database

---

package/batocera/emulators/cemu/cemu/cemu.hash
package/batocera/emulators/cemu/cemu/cemu.mk

Team Cemu has released the new version 1.26.0 on 12-24-2021. There are many bugfixes and improvements. They have also completely reworked the input system, which potentially closes [#4375](https://github.com/batocera-linux/batocera.linux/issues/4375).
For full changelog see https://cemu.info/changelog/cemu_1_26_0.txt

Bump cemu to 1.26.0d

---

board/batocera/fsoverlay/etc/init.d/S12populateshare

dropbear will automatically generate key on client connection
Key will have much more entropy because of time since boot and rngd started.

S12populateshare: remove dropbear key generation

---

package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk

Changes in 0.21:
- Remove legacy timing mode
- Variable latency mode when using the experimental timing which behaves similar to the old timing mode
- Fix 'SVGA Mode' core option not showing (https://github.com/schellingb/dosbox-pure/issues/215)
- Incorporate latest changes from vanilla DOSBox SVN
The new timing mode with better timing and video synchronization which was introduced in version 0.18 is now always active and the old behavior and all its code have been removed. If you encounter issues with it, please report them in https://github.com/schellingb/dosbox-pure/issues/184
Some new options are available in the core options under the category Emulation:
- `Force 60 FPS Output`: Enable this to force output at 60FPS.
- `Show Performance Statistics`: Shows some frame time statistics on …

Bump lr_dosbox-pure

---

batocera-Changelog
package/batocera/emulationstation/batocera-es-system/es_systems.yml
package/batocera/emulators/retroarch/libretro/libretro-vice/libretro-vice.mk

* Add `make objectclean` as suggested by @sonninnos https://github.com/batocera-linux/batocera.linux/pull/5295#issuecomment-1002243205 This should fix all the emulators.
* Re-enable all emulators (build and ES). They were disabled in https://github.com/batocera-linux/batocera.linux/commit/170d4f62d7cf921e07133783fcbae05f8fcb9f4d
@nadenislamarre Can you please test this?
@sonninnos Thank you very much for providing the solution!

lr-vice: fix and re-enable all emulators

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

By default, RetroArch will use a 4:3 aspect ratio when no aspect ratio index is provided. This is what happens in Batocera when the user leaves the "GAME ASPECT RATIO" setting on "AUTO". This is suitable for most systems.
However, systems such as the Game Boy and various vertical Arcade games that use different aspect ratios outside of 4:3, and look weird and distorted when forced to 4:3. Attached is an example of Game Boy being stretched to 4:3 (the current way Batocera treats the "AUTO" setting):
and after the fix:
Note that this change will not affect anything when decorations are turned on, as they use their own viewport settings. This is only for when decorations are set to "NONE".

use core provided as default aspect ratio for libretro

---

package/batocera/core/batocera-configgen/configgen/configgen/utils/bezels.py

Switches the resizing filters used in bezels.py from ANTIALIAS to BICUBIC, producing cleaner results.
> Right now we use the default ANTIALIAS image filter for resizing bezels and bezel elements. This uses the Lanczos filter, which is supposedly the highest quality for both upscaling and downscaling images. However, in my testing, I have found that Lanczos has a tendency to oversharpen the resulting image, creating "highlights" that weren't there in the original image.
>
> Specifically look at this example, the BICUBIC filter is used on the left, and the LANCZOS filter is used on the right. Notice how the pixels right on either side of the latter T character are slightly brighter? You might also noticed the increased (artificial) contrast on the bezel decoration in the background.
>
> …

switch from ANTIALIAS to BICUBIC in bezels.py

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

I've added `retroarchConfig['menu_widget_scale_auto'] = 'true'` because when you are using a lower resolution than 480p (width or height) and next you goes back to higher resolution, notification widget size stills big. Maybe this line was forgotten.

Libretro - Fix widget scaling

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py

Currently MAME alt controller layouts are not working for me without this fix. 
\cc @TVsIan

Ensure altlayout parameter is converted to int before using it

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py

This enables cheats for mame. You need to install cheat.7z (e.g from http://cheat.retrogames.com/) into `/userdata/cheats/mame/`

Enable cheats for mame

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Fixing controls for lr-mame:
By default, lr-mame maps lightgun buttons as secondary activators for joystick buttons. Unlike any other core (that I've found), pressing a button will register both the controller and lightgun button. Batocera's libretro generator maps the controller to the lightgun aim and buttons, the end result is that Retropad A pushes MAME buttons 1&2 together, making some games unplayable.
The fix was to create a "Map Lightgun" option for Retroarch-based emulators. If left on auto, the mame core will leave the lightgun unmapped, every other core will map as it normally does. It can be toggled manually for lightgun games or other systems where it might not need to be mapped.
This results in lr-mame controls working as expected, and no disruption to any other core.

lr-mame Control Fix

---

package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk

Changes in 0.22:
* Update automatic key mappings via Keyb2Joypad Project
* Auto start DOSBOX.BAT if it exists
* Improve audio sync
* Spelling fixes
See https://github.com/schellingb/dosbox-pure/releases/tag/0.22

Bump lr_dosbox-pure to version 0.22

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidc2.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-orangepi-pc.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3288.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3326.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi4.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s812.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s905.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-s912.yml
package/batocera/core/batocera-configgen/configs/configgen-defaults-tritium-h5.yml
package/batocera/emulationstation/batocera-es-system/es_features.yml

Being able to set this independently is critical, some people may prefer to have a frameskip that can go up to 2, 3 or even 4 frames with a base that stays as close to native as it can. This is currently not possible with Batocera. This patch fixes that.

add "auto frameskip" option to ppsspp

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Remove datasette actions from C64 controller mappings.
This fixes arrow keys.
@Kugelblitz360 has thinks arrow keys should not be mapped to datasette actions.

Fix arrow keys in C64 controller mapping & other libretro-vice settings

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Allows the user to choose between buffered rendering and skip buffer mode. This can dramatically improve the framerates at minimal fidelity loss for certain games/hardware. Also made the label for a PCSX2 setting clearer.

Rendering mode setting to ppsspp

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

I've also tested this option on non-VRR compatible displays and RetroArch handles it quite nicely; it will simply not use VRR.
If a user prefers not to use VRR, they can add `global.retroarch.vrr_runloop_enable=0` to their `batocera.conf` to disable it.

enable variable refresh rate for libretro

---

board/batocera/patches/sdl2/002-drm-conn.patch
package/batocera/core/batocera-drminfo/batocera-drminfo.c
package/batocera/core/batocera-scripts/scripts/batocera-resolution.drm
package/batocera/emulators/dolphin-emu/007-drm-conn.patch
package/batocera/emulators/duckstation/007-drm-conn.patch
package/batocera/emulators/retroarch/retroarch/008-drm-conn.patch

this fixes an issue on drm having multiple output (bad variable usage in drm-info)
and this allow to switch between multiple drm output (this is not the case of the rpi4 which has 2 cards of 1 entry).
but this fixes for rg552.

handledrmconnectors

---

package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk

This is the twenty-fourth release of DOSBox Pure intended for public testing.
Changes in 0.24:
- Fix CPU cycles in menu and command line (https://github.com/schellingb/dosbox-pure/issues/223)
- Fix "Force 60 FPS" mode when emulating display modes less than 60 Hz (https://github.com/schellingb/dosbox-pure/issues/222)

Bump Libretro Dosbox-Pure to 0.24

---

package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py
package/batocera/emulators/retroarch/shaders/batocera-shaders/batocera-shaders.mk
package/batocera/emulators/retroarch/shaders/batocera-shaders/configs/sharp-bilinear-simple/rendering-defaults.yml

Changes the default shader set from "none" to "sharp-bilinear-simple". This also turns off "smooth games" by default, although the user can still manually turn it back on.
Compared to smooth games (the standard "bilinear filter"), the performance difference is negligible. Yet despite this, the "sharp-bilinear-simple" shader produces far sharper results. The following example images were taken from the [shader's github page](https://github.com/rsn8887/sharp-bilinear-shaders/releases).
Standard "smooth games" (before this patch):
Same scene with "sharp-bilinear-simple" (after this patch):
I have tested this on both an RPi 4 and PC, however should we need to use a shader that requires even less performance (less than that of even the standard smooth games even), "sharp-bilinear-2x-prescale" …

use sharp-bilinear-simple by default

---

board/batocera/fsoverlay/etc/init.d/S65values4boot

Add system.timezone in batocera-boot.conf needed for wiki script.
And wiki script https://wiki.batocera.org/troubleshooting#changing_batocera_to_use_windows_local_time_instead needs fix
#!/bin/bash
TZ=$(/usr/bin/batocera-settings-get -f /boot/batocera-boot.conf system.timezone) hwclock --systz --localtime

Add system.timezone in batocera-boot.conf

---

package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk

Changes in 0.25:
- Fix running core without content
- Add core option to limit emulation CPU usage
- Support config changes via commandline

Bump lr_dosbox-pure 0.25

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py

- Added X=Left Alt instead of Left CTRL. Much used with games like Turrican.

Small PUAE mapping fix

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/amiberry/amiberryGenerator.py

Amiberry's generator is using Libretro's generator, and needed a fix after the lr-mame control fix.

Amiberry Fix

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py

There was an issue where the generated bezels were using the ROM name and not the system name, and were not being applied.

MESS Bezel Fix

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml

Fixes --- [poor performance](https://github.com/batocera-linux/batocera.linux/issues/5518) (is a workaround, should be disabled for the v34 beta) for emulators in RPi3.
Also increased the audio latency by 32ms to avoid audio crackling in most systems.
Alternative workaround: disable bezels. They seem to be directly causing the slowdown. Not sure why, but that would obviously be a much more intrusive and noticeable workaround.

enable threaded video by default on rpi3

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Unfortunately the 4:3 ratio in RPCS3 seems to be glitched: instead of showing the 4:3 aspect ratio at its intended resolution, it will instead stretch out the 4:3 image to 16:9 when "stretch to display" is not on (with it on, it will simply distort to whatever dimensions your display has, be it 16:9 or 4:3). Still, implementing this is better than not implementing it, as there are some users on genuine 4:3 screens who would appreciate this option.

Add a bunch of RPCS3 options to ES

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-x86_64.yml

A change in batocera's configgen caused this setting to no longer apply, this fixes it.

fix video frame delay auto setting in x86_64 defaults

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py

Note: The current beta is missing previous fixes, I recompiled from the current master to test this.
If a bezel only had a png and no info (like the Bezel Project) it was failing due to no alpha value being set. A default of 1.0 has been added for cases like this or an .info without an alpha value.

Fix for info-less PNGs (Bezel Project)

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

I have tested this option on a non-VRR display and did not notice any increased judder from usual. However, this old issue report has been brought to my attention: libretro/RetroArch#10304
It's nearly a year old, and the issue is fundamentally with RetroArch, but if even one person is reporting that having this on by default has worsened the experience I would rather have this default to off than on.
I will leave this PR as a draft for a bit to see if there are any candid reports of increased judder/stutter in the next beta.

change VRR auto setting from true to false

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

we need to change the messaging for libretro
not every core supports vulkan but we provide the option regardless
some cores will drop back to opengl, but not all
therefore we should outline this to the user

change libretro vulkan messaging to avoid confusion

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py

Reverts batocera-linux/batocera.linux#5509 as it didn't fix anything and seemingly broke other controllers

Revert "Add SDL env variable for controller" - v33

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py

as reported in the forum for v33 rc1 & rc2
For Pcsx2, MicroVuSpeedHack doesn’t works until enable speedhack is enabled inside the emulator itself (via F1 - Applications).

fixes speed hacks like MTVU not applying if enabled (v33)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

The software renderer option for Duckstation wasn't working, because the settings.yml was using True and False instead of "true" and "false", and that was throwing off the getOptBoolean function, causing it to default to Auto.
The double quotes were also missing from that section of the config writer, so they were added as well.
This should be safe for v33, but can wait until v34, with the note that the software renderer option will not work in v33 unless set manually, or set to lowercase true in batocera.conf.

Libretro duckstation/swanstation software renderer fix

---

package/batocera/emulators/retroarch/libretro/libretro-dosbox-pure/libretro-dosbox-pure.mk

Changes in 0.26:
- Fix IMGMOUNT writable raw disk images 
- Apply fix for Super Street Fighter 2 Turbo Keyboard Mapping 
- Fix restarting core with raw disk images mounted
- Fix wrong frame draw count in performance statistics while on-screen-keyboard is open
Small fixes. This can be mergeable to v33

Bump dosbox pure to 0.26

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
package/batocera/core/batocera-scripts/scripts/batocera-systems
package/batocera/emulationstation/batocera-es-system/es_features.yml

There were requests to make the default Color Computer model the CoCo3 for compatibility reasons.
The altmodel setting was not implemented in ES, but has been suggested and used as a manual option. All this pull does is change the default to coco3, add the altmodel setting to ES for coco/2/2b/3/3p, and check BIOS files for all models, making it "official."
If it doesn't make it into v33, it will still function as a manual setting.

Color Computer Alternate Models/Default Change (Safe for v33, not urgent)

---

package/batocera/emulators/retroarch/retroarch/013-cheevos-screenshot-filename.patch

This patches retroarch to add the achievement title to achievement screenshot filenames.
Right now they get output as (rom name)-cheevo-(cheevo id) without any context. It's pretty meaningless to an end user, you go through the screenshots in your library and nothing has any context. You can't even look an id up on retroachievements without making your own url.
I think ideally the achievement notification should be in the screenshot itself, but for now I think this change goes a long way to jog your memory about an old screenshot and neatens up the library view.

Make RetroArch produce better achievement screenshot filenames

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

fixes mupen64 defaulting to 16:9, no longer uses libretro's ratios (it never used them in the first place, it would just ignore them like Dolphin used to).

fix mupen64 aspect ratio settings

---

package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife

when using retroflag shutdown scripts under some circumstances.
Is an issue since B33 :(

fix: Prevent restart of ES GUI

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

As prolific as MangoHUD is, it should probably be mentioned by name here so people can realise what it actually is.
Also fixes the bezel issue with GameCube games with the widescreen hack. For instance, if the user had widescreen mode enabled while playing a GameCube game, then they *would* have gotten bezels. However, bezels were disabled in v33, so nobody even noticed this. It's satisfying squishing a bug before it could even affect anyone.
Actually I've tested this and it seems like bezels are working perfectly fine for Dolphin (on x86_64 at least). Maybe we can re-enable it?
Moved the widescreen hack to be gamecube-specific. Wii already has the ability to natively play widescreen games, the widescreen hack is only required for gamecube afaik. Let me know if that's not the case, …

relabel + fix gamecube options/bezel

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py

This is currently only for manual batocera.conf editing, though ES could be modified to allow settings there. There is no saving/changing/removing these options via Batocera directly.
To use, add a line in batocera.conf in the format:
system.folder["/full/path/"].option=value
For example, to change the shader set for a folder of Japanese NES games, I used:
nes.folder["/userdata/roms/nes/Japan/"].shaderset=Mega-Bezel-Community-JP-Night
This should work for any option - software list settings, decorations, shaders set, or emulator (ie have MAME subfolders for different versions of MAME) would be common uses.
Folder options are loaded after system options but before game options, so individual game settings will still override them.

Game Options by Folder

---

batocera-Changelog
package/batocera/core/batocera-system/Config.in
package/batocera/ports/sonic2013/sonic2013.mk
package/batocera/ports/soniccd/soniccd.mk

* Bumps Sonic Retro on x86
* Cleans up build process (author made dependencies submodules instead of separate downloads)
* Restores Sonic Retro to other boards using an older, pre-unmet dependencies version (commits are v1.1.2.1 on sonic2013 and v1.1.2 on soniccd)
Tested on x86_64 & rk3326 (Odroid Go Super)

Sonic Retro Bump & Fix

---

package/batocera/utils/unclutter/unclutter.mk

Fixe github issue : 
```
WARNING: no hash file for unclutter-v1.5-batocera.tar.gz
>>> unclutter v1.5-batocera Extracting
gzip -d -c /build/buildroot/dl/unclutter/unclutter-v1.5-batocera.tar.gz | tar --strip-components=1 -C /x86_wow64/build/unclutter-v1.5-batocera   -xf -
gzip: /build/buildroot/dl/unclutter/unclutter-v1.5-batocera.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make: *** [package/pkg-generic.mk:251: /x86_wow64/build/unclutter-v1.5-batocera/.stamp_extracted] Error 2
make: Leaving directory '/build/buildroot'
make: *** [Makefile:105 : x86_wow64-build] Erreur 2
```

Fixe unclutter

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

* `o2em_swap_gamepads`: This one probably shouldn't be an advanced option, it's pretty easy to understand what it does and why you might need to change it. There are also a lot of games that do require you to change it, so hiding it away could make things more complicated. And it's not consistent either, other platforms with similar options don't have this as an advanced option.
* `neon_enhancement`: This is the only option regarding rendering resolution that's been tagged as "advanced". Removing for consistency.
* `crosshairs`: This is pretty necessary for lightgun games, and isn't too hard to understand what it does. Also, these are the only two platforms where this was tagged as advanced, the rest don't have this. Removing for consistency, but could also go the other way just as …

remove a few options from advanced

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

es_systems.cfg contains errors in the <theme> items for a few systems. This commit fixes theme display issues for BBCMicro, Astrocade, and Creativision

Commit 3 changes to es_systems.yml to fix theme display

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/drastic/drasticGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

Adding a screen orientation option to the drastic emu. Same as what is available with the `libretro: DeSmuME`

Add screen orientation option for drastic

---

package/batocera/utils/syncthing/syncthing.mk

builds OK, fixes issue with cleanbuild not being able to remove the syncthing folder from `output/<arch>/build/syncthing-v###`. Credit to nuumio for the code/suggestion.

bump syncthing + fix permissions issue with cache

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

This bug caused user-set shaders to be ignored by default. It was impossible to set the shader to "none".
Suggestion: rename "none" to "custom", to imply that the user can indeed use RetroArch to set up their preferred shaders.

fix shader generator behaviour

---

batocera-Changelog
package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py

the commit breaks libretro on sbc.
by the way, options should be set in .yml files, not in python code (except if logic is usefull)
This reverts commit 0be74046ace340e91e4982e3a80d229253d10876.

Revert "Libretro Flycast Fix"

---

package/batocera/emulators/easyrpg/easyrpg-player/easyrpg.easyrpg.keys

The recent update of EasyRPG Player changed the screenshot key from F10 to F7, this reflects this change.
This change happened because the original test-play mode of RPG Maker 2003 had a "Abort Event" at F10, which the player now has as well, so they had to swap them out to stay faithful.
**_Please note_** that in the current state, it won't save the screenshots to the screenshot folder, but in the save folder, changing this goes beyond my abilities though, as I think this isn't something that can be set up in main branch of easyrpg itself currently (I think there was a patch on batocera's side for that, but it may not be there anymore(?)).

[easyrpg-player standalone]Changed the Screenshot key

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

A few tweaks to the system names and manufacturers:
* There were a couple of duplicate company names - Acorn Computers & Acorn, and Epoch Co & Epoch.
* A lot of systems (mostly Sony & Sega) had the company name as part of the system name. Removed this in all cases EXCEPT where it is an official part of the name (such as Nintendo 64, most Commodore systems, Sega CD).
* Also left it on the Camputers Lynx both because it seems to be used officially and to prevent duplication with the Atari Lynx.
* Added spaces/hyphens to a few names to match official names - Mega Drive, SG-1000, ZX Spectrum. Removed hyphen from Pokemon Mini.
No changes were made to folders or anything else, just the display names.

System/Company Name Consistency

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin_triforce/dolphinTriforceControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin_triforce/dolphinTriforceGenerator.py
package/batocera/core/batocera-desktopapps/scripts/batocera-config-dolphin-triforce
package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/emulators/dolphin-triforce/dolphin-triforce.mk
package/batocera/emulators/dolphin-triforce/triforce.dolphin-triforce.keys

- Rename binary to exclude ".AppImage" extension and adjusted appropriate commandArrays; fixes evmapy, now actually works (addresses one point in https://github.com/batocera-linux/batocera.linux/pull/5621#issuecomment-1039702230 )
- Adjust internal resolution scaling to only go up to 4x (this branch did not support higher resolutions) and fix the numerical values for configgen.
- Removes features that aren't actually in the triforce branch
- Categorise the appropriate features as "ADVANCED OPTIONS"

Triforce fixes

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

It looks like Retroarch has reverted back to using gl for the OpenGL driver, it was opengl in a previous build when the now-reverted Flycast fix was added.
This PR:
* Changes the option in ES to use gl instead of opengl
* Auto corrects the setting while generating, in case anyone still has opengl from selecting it manually
* Re-adds flycast to the list of non-GLCore cores
* Re-adds the "don't override a manually selected backend by core" function that was reverted with the lr-flycast change.

Retroarch OpenGL Fix

---

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg

Hi.
Adding the iNNEXT SNES-Alike USB controller(https://www.youtube.com/watch?v=v7KYR5HAQBc)

iNNEXT SNES Retro USB Controller - es_input.cfg

---

board/batocera/x86/patches/ffmpeg/001-av1-radeon.patch

fixes - https://github.com/batocera-linux/batocera.linux/issues/5745
- tested aok - didn't see any issues
used: https://github.com/SPBTV/video_av1_samples
- builds fine for x86_64 (patch only applies here)

fix av1 decoding on radeon cards

---

board/batocera/fsoverlay/etc/modprobe.d/8821ce.conf

the rtw88 drivers have been good since kernel 5.9
- therefore we now want to test using the 8821ce driver from the kernel rather than external sources
- thus disabling this blacklist for now
- if ok, i will remove the legacy driver etc.

we want to use the 8821ce driver in the kernel now

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
package/batocera/emulators/retroarch/retroarch/retroarch.mk

Finally found the true source of the lr-flycast OpenGL/GLCore issues.
Retroarch was compiling without proper OpenGLES support, which was causing Flycast (which was compiled with OpenGLES) to fail.
Added in a conditional to compile Retroarch with OpenGLES3 support if available, which fixes the issue on x86_64. My other test device, an Odroid Go Super never experienced this issue, so I can't test for it there.
There was a report lr-flycast would not load in OpenGL/GLCore on RPI4, so that would be a good test board for it.
Also removed lr-flycast from the GLCore exception list, since it works in GLCore after this fix.

Fix Retroarch OpenGLES

---

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg

fix retro-bit saturn wireless es_config mapping
Remapped Retro-Bit Sega Saturn 2.4Ghz Controller to default X-Input from Retro-Bit.
It was setup as a Xbox Fight-stick before.
Removed and fixed the D-pad that was  setup twice as the left analog. This could cause issue in Wine with controller scrolling the menus by itself.
Added
DPad to normal, press and hold Up + Start for 3 seconds
DPad to Left Analog mode, press and hold Left + Start for 3 seconds
DPad to Right Analog mode, press and hold Right + Start for 3 second
/Rion

Fix Retro-Bit Sega Saturn 2.4Ghz X-Input

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml
package/batocera/emulationstation/batocera-es-system/es_systems.yml

MAME/LR-MESS:
* Adds a RAM size option, compatible with Mac IIx and Mac LC 3.
* Installs the nuBus Image Reader virtual device on Mac IIx by default (can be disabled or moved to a different slot).
MAME:
* Adds the "disk image" media type to auto-mount to the image reader - requires the boot disk option, as it doesn't mount until after boot. Renamed "Disk" to "Floppy Disk" to differentiate.
I was currently unable to add the disk image to lr-mess, as loading a disk image plus a boot chd or floppy will cause a segfault and crash Retroarch. I've already submitted an issue to the lr-mame github, and if/when this gets fixed I can enable it.

Mac Additions

---

package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin_triforce/dolphinTriforceGenerator.py

It was making constant writes to the log about every single DVD drive access, which is a lot. A ten minute session would make a 5MB text log. This disables just the DVD access logging in dolphin_triforce, everything else is still logged.

prevent triforce log spam

---

package/batocera/emulators/retroarch/libretro/libretro-swanstation/Config.in

https://github.com/libretro/duckstation doesn't redirect to https://github.com/libretro/swanstation anymore

Update Swanstation config.in link

---

package/batocera/core/batocera-scripts/scripts/batocera-config

To stop the `system/logs/batocera.log` file from filling up infinitely.
ie. this:

Prevent eternal "---- batocera-config ----" log spam

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/moonlight/moonlightConfig.py

Changes moonlight default framerate to 30fps. This prevents issue with graphical glitches for 30 fps games when moonlight is set to 60 fps.

Update default moonlight framerate to 30 fps

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

on linux, only the udev driver for mouses allows the multiplayer guns.
xorg systems defaults on the x driver.
hope this doesn't break something about the keyboard

guns on X must use udev

---

package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg

This allows the user to access the functions behind the North and West button using only the keyboard with the default configuration. Lengthy explanation follows:
The = and - buttons are language agnostic symbols (ie. they appear in the same spots irrelevant of the language layout used) although of course there are still a few exceptions such as for specialised keyboard layouts (such as Dvorak). Still, users of such layouts would know where such keys would lie, and this binding uses the keycode not the label code, so it is positional not label-based. And at the end of the day, having these buttons bound to _something_ by default is better than the current situation of them being bound to _nothing_, being able to access these menus _sometimes_ is better than _never_ in my opinion.
An …

Bind North and West to = and - respectively on the keyboard by default

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin_triforce/dolphinTriforceControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin_triforce/dolphinTriforceGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

1 - Remap the Insert Coin button to the 'Select' button to be consistent with other Arcade emulators.
2 - Disable the 99 Credits cheat by default on MKAGP2 to allow user to insert coin as per other Arcade games and emulators. The cheat can still be enabled from dolphin-triforce-config inside Applications.
3 - Added an ES option to Disable On-Screen Display Messages.
All changes have been tested OK

Triforce Tweaks

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

Moves the threaded video option from being an advanced setting only for libretro into the latency reduction settings for all emulators.
There are other emulators with similar settings that this may benefit from in the future. Plus, it makes more sense, as it's directly tied to input latency.
Also made its logic consistent with the other similar options.

move threaded video option

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/mupen/mupenConfig.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

In testing across RPi3, regular x86_64 and Intel J4125 x86_64 (thanks xMoJo12) lowering the PRIMARY_BUFFER_SIZE to 8192 from 16384 seems to have a net increase in performance with no audio issues over what mupen itself provides as default.
I'm open to changing this of course if anyone has issues but I've yet to find a case, and the RPi3 is already on the lowest-end of what is considered "weak for N64". In fact, it seems to still be running fine even on the Low preset I made (but I don't need to push boundaries here).

add mupen64 audio buffer settings

---

package/batocera/core/batocera-system/Config.in

AV1 is missing in most recent 34 beta 
Adding this lib will enable ffmpeg av1 decoding

Add AV1 decoder to ffmpeg/kodi

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

as far as I'm aware these are working as intended, defaults to "none". Enabling for those users who want to intentionally use these.

add bezel/hud to sh ports

---

package/batocera/emulators/retroarch/batocera-bezel/batocera-bezel.mk

-f because there may be bezels in the future that are intended to overwrite other bezels (right now there isn't any)

add standalone bezel variations

---

package/batocera/controllers/umtool/umtool.mk

Initial commit was a snapshot of master.  This updates `umtool` to the latest official release, which was released shortly thereafter.

Bump to latest official umtool release

---

package/batocera/core/batocera-configgen/configs/configgen-defaults-rpi3.yml

The slowdown issue with decorations is back again and no known solution is out there. Considering this has also been an issue in the past and v33 was skipped because of it, it might be best to just leave this option on for the foreseeable future. I'll be testing this from time to time with the option off to see if anything can be done about it.
It also helps with shader slowdown, but that's a separate issue in unto itself.

redo rpi3 workaround, enable threaded video

---

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
package/batocera/emulationstation/batocera-es-system/es_systems.yml

Two fixes for es_systems.yml:
When sameduck (mega duck emulator) was added, it was added as a new system even though we already had megaduck via mame/mess. Possibly because the emulator doesn't support zip files, but the bin files are the same for both.
Removed the sameduck system, added sameduck as an alternate emulator for megaduck with zip/7z listed as incompatible. I also updated the system name to "Mega Duck / Cougar Boy" as that's what the sameduck system had. I did not change the default emulator, as changing it to sameduck from lr-mess caused errors with missing defaults on some platforms.
In addition, we have common support issues with people trying to use zipped n64 roms on the standalone emulator. They're supposed to work, but don't, and it just returns to ES.
For the time …

Merge Sameduck & Megaduck systems/Disable Zip for N64 Standalones

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

3DO doesn't support m3u files as the system didn't have a change disk option (ejecting resets the console). Opera's default for saved games is to use separate files per game, which makes multi-disc games not work without manually changing the option in Retroarch. This PR:
* Adds an NVRAM Storage option to 3DO for per system or game settings in ES
* Will normally default to Per Game if left on auto, but if the ROM name contains the word "Disc" it will assume it's a multi-disc game and enable it.

Add Shared Storage Option to 3DO (Safe for v34)

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

Consistency to option labels (we do not indicate which is the default because the default could be different on any given platform), makes it easier for translators as there are less strings to maintain, use American English spelling, use consistent tone and form.

consistency to rpcs3 es_features

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/mame/mameGenerator.py

Just a quick fix - the auto-softlist option for FM Towns was kicking in too late and not working right, and there was a second issue when using CHD-based software lists (rare, except for FM Towns), both are corrected. Verified the MAME fix on my system and with @Modhack, lr-MESS is still fussy but should work properly once that issue is corrected.

Fix MAME FM Towns & CHD Softlists (v34)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/daphne/daphneGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

New features from Hypseus Singe v2.8.2:
- Enable SDL_TEXTUREACCESS_STREAMING, can improve video performance on SBC's with SDL2 => 2.0.16 on higher resolution Singe games.
- Hide crosshair in supported games (e.g. ActionMax)
Added parameter:
- Enable scanlines. Use with Stretch aspect ratio and adjust joystick sensitivity as required.
NOTE: made -scanlines PC only as it negates the performance improvements of -texturestream on SBCs
Fixes:
- Daphne games crashed when -js_range is set for all games, now applied to Singe and ActionMax games only

Added features from Hypseus Singe v2.8.2, scanlines, excluded -js_range from Daphne games

---

package/batocera/emulationstation/batocera-es-system/es_features.yml

Fixes #6074 
Core already referenced in:https://github.com/wholee/batocera.linux/blob/6468c11086f418d7f1e86348217efc1adbff3b9e/package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py#L36
and system in:
https://github.com/wholee/batocera.linux/blob/6468c11086f418d7f1e86348217efc1adbff3b9e/package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py#L32

Add cheevos to kronos in es_features.yml

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

https://retroachievements.org/viewtopic.php?t=14469
https://docs.libretro.com/library/nestopia_ue/
While you can still earn cheevos on the core, it is officially unsupported as of 06 Dec, 2021.
es_features.yml file
https://github.com/batocera-linux/batocera.linux/blob/768aa8708f56d6f02d1ab63435db8057a021cdf0/package/batocera/emulationstation/batocera-es-system/es_features.yml#L3155
correctly lists Nestopia as not having cheevos

Nestopia is no longer officially supported for retroachievements

---

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml

From user feedback...
Cause the libreto 2.1.1 version does not support all the game engines supported on standalone 2.5.1, and cant play properly some supported games.
- Broker Sword 1 will play it cutscenes only at 2.5.1
- Grin Fradango and some Monkey Island games, will only works at 2.5.1 too.
- And many other engines are supported on 2.5.1: AGS (Adventure Game Studio), Glk (Text Adventures), SCI (Sierra's Creative Interpreter), ...

make standalone scummvm the default

---

package/batocera/emulators/mame/mame.mk

The issue that was preventing shaders from working in standalone MAME was that in v242, the DX9 shaders were set to the default, and if the files were missing (even on Linux), BGFX would fail. We've been removing the DX9 shaders since they don't work on Linux anyway. Rion found the issue reported on MAME's github.
This re-bumps to v242, and will leave the DX9 shaders in place. We went through a good part of v34 beta using v242 and the only issue was the shaders, so it should be safe if it's not too late.

MAME Re-bump & Shader Fix (v34?)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py

This adds an option to `batocera.conf` to enable players to start a gaming session with all achievements active (even the ones they already have registered as unlocked on RetroAchievements.org).
#https://github.com/libretro/RetroArch/pull/10637
#https://github.com/libretro/RetroArch/pull/12472
The option for Retroarch is `cheevos_start_active` but to avoid some confusions it was renamed to _Encore mode_ in #https://github.com/libretro/RetroArch/pull/12472
I've also created a PR for EmulationStation #https://github.com/batocera-linux/batocera-emulationstation/pull/1179 to go along with this setting.
Changes in this PR can also be used regardless if the #https://github.com/batocera-linux/batocera-emulationstation/pull/1179 PR is approved or not.
And to note, this setting can also be used …

Add cheevos Encore mode

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

* Adds options to select RDP Plugin, RSP Plugin, and CPU Core to lr-mupen64plus-next.
* Defaults are still the current/fastest - GLideN64 RDP, HLE RSP, Dynarec CPU.

Advanced N64 Options

---

package/batocera/core/batocera-configgen/configs/configgen-defaults.yml

Disable for Model2 is not need and that create issue
Disable for Flatpak is not need
Disable for Ruffle that crash Flash MongoHUD

Disable HUD Part 2

---

package/batocera/emulationstation/batocera-es-system/es_systems.yml

Even if the official docs don't have the _cmt_ extension as supported https://docs.libretro.com/library/quasi88/#extensions
the emulator itself does: https://github.com/libretro/quasi88-libretro/blob/dccf881719d793aac56944e3e6c3d5358ac2c87a/src/help.h#L38
And Retropie also has it listed as supported: https://retropie.org.uk/docs/PC-8800/

Update PC88 *.cmt

---

package/batocera/alllinuxfirmwares/alllinuxfirmwares.mk

- fixes stability with the MediaTek MT7922 chipset
- adds firmware for RTL8852C devices
- general firmware updates aligning with the 5.17 kernel

bump linux firmware to 9th May 22

---

package/batocera/core/batocera-controller-overlays/batocera-controller-overlays.hash
package/batocera/core/batocera-controller-overlays/batocera-controller-overlays.mk
package/batocera/core/batocera-scripts/scripts/batocera-systems
package/batocera/emulators/retroarch/libretro/libretro-cap32/amstradcpc.keys
package/batocera/emulators/retroarch/libretro/libretro-cap32/libretro-cap32.mk

- Fix Vectrex BIOS requirement (not required by default emulator)
- Add controller overlays/tattoos for Amstrad CPC, Amiga, Atari ST, ZX81
- Better pad2key for Amstrad CPC

Batocera 34 - additional fixes & updates

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastControllers.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/flycast/flycastGenerator.py
package/batocera/core/batocera-configgen/configgen/configgen/generators/redream/redreamGenerator.py
package/batocera/emulationstation/batocera-es-system/es_features.yml

this 'fixes' the triggers where sensitive actions were not previously available with the default button identification

allow sony controller triggers to be configured as analog (not buttons)

---

package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
package/batocera/core/batocera-scripts/scripts/batocera-systems
package/batocera/emulationstation/batocera-es-system/es_features.yml

Remove zip and move to folder to check good hash.
Same as https://github.com/libretro/neocd_libretro
Front Loader BIOS | neocd_f.rom | a5f4a7a627b3083c979f6ebe1fabc5d2df6d083b
-- | -- | --
Front Loader BIOS (SMKDAN 0.7b DEC 2010) | neocd_sf.rom | 4a94719ee5d0e3f2b981498f70efc1b8f1cef325
Top Loader BIOS | neocd_t.rom | cc92b54a18a8bff6e595aabe8e5c360ba9e62eb5
Top Loader BIOS (SMKDAN 0.7b DEC 2010) | neocd_st.rom | 19729b51bdab60c42aafef6e20ea9234c7eb8410
CDZ BIOS | neocd_z.rom | b0f1c4fa8d4492a04431805f6537138b842b549f
CDZ BIOS (SMKDAN 0.7b DEC 2010) | neocd_sz.rom | 6a947457031dd3a702a296862446d7485aa89dbb
Front Loader BIOS (MAME) | front-sp1.bin | 53bc1f283cdf00fa2efbb79f2e36d4c8038d743a
Top Loader BIOS (MAME) | top-sp1.bin | 235f4d1d74364415910f73c10ae5482d90b4274f
CDZ BIOS (MAME) | …

Fix Neo Geo

---

package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject

`batocera-es-thebezelproject install <system>` performs an almost exact text match on ROMs vs bezel filenames to determine a match. Unmatched ROMs often differ in trivial ways and without playing the game, it is otherwise hard to know when something hasn't matched. (NB: the information is in the log, but you have to dig to find it versus all the other log messages.)
This PR adds an option to `install` which is `--show-unmatched`. With this option enabled, the script will gather all the unmatched ROMs and dump them at the end of the script.
The output looks like this:
```
batocera-es-thebezelproject install psx --show-unmatched
[psx] 75 ROMs found
[psx] 72 bezels (75 ROMs) were installed/modified
[psx] Installing system bezel
[psx] Installing default bezel
[psx] Unmatched ROMS (check …
```

Add support for showing unmatched roms in batocera-es-thebezelproject
